# Copyright (c) 2026 Etienne Cimon
# SPDX-License-Identifier: MIT

[package]
name = "g6b-gr"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "SysGrInit rewrite: 16-color framebuffer (UART cells or host PPM)"

[dependencies]
g6b-spec = { workspace = true }

[lints]
workspace = true
