#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Etienne Cimon
#
# Pull diffs from the linux-dist *etcimon forks* (after you developed there)
# into g6lc_qemu/openwrt/patches/from-fork/. Compile still uses official
# openwrt/openwrt + apply-patches.sh — never the fork.
#
#   bash g6lc_qemu/openwrt/extract-patches.sh
#
# Components (folder prefix openwrt- for feeds):
#   linux-dist/openwrt              vs github.com/openwrt/openwrt @ v24.10.2
#   linux-dist/openwrt-packages     vs github.com/openwrt/packages @ pin SHA
#   linux-dist/openwrt-luci         vs github.com/openwrt/luci @ pin SHA
#   linux-dist/openwrt-routing      vs github.com/openwrt/routing @ pin SHA
#   linux-dist/openwrt-telephony    vs github.com/openwrt/telephony @ pin SHA
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
DIST="${LINUX_DIST:-$ROOT/linux-dist}"
PATCHES="${OPENWRT_PATCHES:-$HERE/patches}"
PIN_REF="${OPENWRT_REF:-v24.10.2}"
OUT="$PATCHES/from-fork"
mkdir -p "$OUT"

log() { echo "[extract-patches] $*"; }

# Official pins from OpenWrt v24.10.2 feeds.conf.default.
extract_one() {
  local name="$1" official_url="$2" pin="$3" fork_dir="$4"
  if [ ! -d "$fork_dir/.git" ] && [ ! -f "$fork_dir/.git" ]; then
    log "skip $name: no checkout at $fork_dir (init-submodules.sh first)"
    return 0
  fi
  log "extract $name  fork=$fork_dir  official=$official_url  pin=$pin"
  git -C "$fork_dir" remote get-url official >/dev/null 2>&1 \
    || git -C "$fork_dir" remote add official "$official_url"
  if ! git -C "$fork_dir" cat-file -e "$pin^{commit}" 2>/dev/null; then
    log "  fetch official $pin"
    git -C "$fork_dir" fetch --depth 1 official "$pin" || \
      git -C "$fork_dir" fetch official "$pin"
  fi
  local n
  n="$(git -C "$fork_dir" rev-list --count "$pin"..HEAD 2>/dev/null || echo 0)"
  if [ "$n" = 0 ]; then
    log "  $name: fork HEAD == pin; no extra commits"
    return 0
  fi
  local dest="$OUT/$name"
  rm -rf "$dest"
  mkdir -p "$dest"
  git -C "$fork_dir" format-patch --output-directory "$dest" \
    --zero-commit --no-signature "$pin"..HEAD
  local count
  count="$(find "$dest" -name '*.patch' | wc -l | tr -d ' ')"
  log "  wrote $count patch(es) -> $dest"
}

extract_one openwrt \
  "https://github.com/openwrt/openwrt.git" "$PIN_REF" \
  "$DIST/openwrt"

extract_one openwrt-packages \
  "https://github.com/openwrt/packages.git" \
  "c7d1a8c1ae976bd0ad94a351d82ee8fbf16a81f0" \
  "$DIST/openwrt-packages"

extract_one openwrt-luci \
  "https://github.com/openwrt/luci.git" \
  "d6b13f648339273facc07b173546ace459c1cabe" \
  "$DIST/openwrt-luci"

extract_one openwrt-routing \
  "https://github.com/openwrt/routing.git" \
  "85d040f28c21c116c905aa15a66255dde80336e7" \
  "$DIST/openwrt-routing"

extract_one openwrt-telephony \
  "https://github.com/openwrt/telephony.git" \
  "2a4541d46199ac96fac214d02c908402831c4dc6" \
  "$DIST/openwrt-telephony"

# Rebuild series: seed patches first, then from-fork/openwrt/*.patch only
# (feed patches are recorded but applied only if OPENWRT_SRC is a feed tree).
series="$PATCHES/series"
{
  echo "# Regenerated by extract-patches.sh $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "0001-kernel-defaults-olddefconfig.patch"
  echo "0002-sifiveu-g6lc-virt-and-isa-overlay.patch"
  if [ -d "$OUT/openwrt" ]; then
    find "$OUT/openwrt" -name '*.patch' | sort | while read -r p; do
      echo "from-fork/openwrt/$(basename "$p")"
    done
  fi
} > "$series"
log "updated $series"
log "compile path remains: official clone + apply-patches.sh (no etcimon fork)"
