default:
{
    switches = [ "-mtriple=wasm32-unknown-wasi", "-defaultlib=", "-d-version=CRuntime_LIBWASM", "-d-version=G6LC_G6B", "-fno-moduleinfo", "-mattr=+exception-handling", "--wasm-enable-eh", "-link-internally", "--foptimize-nothrow=false", "-L-z", "-Lstack-size=1048576", "-L--stack-first" ];
    post-switches = [ "-IE:/cva6/g6lc_bios/libwasm/runtime-v1.43.0" ];
    lib-dirs = [];
};
