// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
//
// aiOverlay.ts — pin the AI overlay as a generated `<pkg>_ai` package + DTS.
//
// The build-time overlay (`+define+G6LC_AI_OVERLAY`, build_config_pkg.sv) lets any
// core package elaborate with the canonical island plane. That is the iteration
// form; it cannot be read by the macro-blind package consumers (g6lc_qemu ingest,
// sv-timing, the docs). This module produces the shareable form: a package file
// derived textually from the base package with exactly three fields rewritten
// (`CvxifEn`, `CoproType`, `AiCfg`) and a DTS that includes the base DTS plus the
// island node, appending the `xg6lcai` extension to every cpu. Generated files
// carry a marker header and are drift-tested against this generator.
//
// Scope: LibreCore packages only (`g6lc64_*`). Upstream-shaped packages (`cv*`)
// are tier-U files; deriving a second copy of them is a licensing question the
// generator refuses rather than answers (use the overlay define on those).

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

export const AI_OVERLAY_MARKER = "GENERATED by build-platform ai-overlay pin";

export interface PinOptions {
  /** Base package name, e.g. `g6lc64_ooo_int2_l3`. */
  target: string;
  /** Integer strip (`AiCfgIslandInt`) instead of the FP island. */
  int?: boolean;
  /** Island geometry literal recorded in the DTS node (default AiIslandLatencyDefault). */
  islandCfg?: string;
}

export interface PinResult {
  packageName: string;
  packagePath: string;
  packageText: string;
  dtsName: string | null;
  dtsPath: string | null;
  dtsText: string | null;
}

/** Island geometry as published by the DTS node (mirrors g6lc_ai_island_cfg_pkg literals). */
const ISLAND_GEOMETRY: Record<string, { m: number; n: number; k: number; macs: number; queues: number; depth: number; noc: number; gbps: number; clusters: number }> = {
  AiIslandLatencyDefault: { m: 1024, n: 512, k: 512, macs: 512, queues: 2, depth: 64, noc: 64, gbps: 16, clusters: 1 },
  AiIslandV1WidePort: { m: 1024, n: 512, k: 512, macs: 512, queues: 2, depth: 64, noc: 512, gbps: 128, clusters: 1 },
  AiIslandV2ColumnArray: { m: 1024, n: 512, k: 512, macs: 4096, queues: 2, depth: 64, noc: 512, gbps: 128, clusters: 1 },
  AiIslandV3Quad: { m: 1024, n: 512, k: 512, macs: 4096, queues: 2, depth: 64, noc: 512, gbps: 400, clusters: 4 },
  AiIslandV4Octo: { m: 1024, n: 512, k: 512, macs: 4096, queues: 2, depth: 64, noc: 512, gbps: 400, clusters: 8 },
};

export function baseDtsName(target: string): string {
  // g6lc64_ooo_int2_l3 -> ariane-ooo-int2-l3.dts ; g6lc64_smt2 -> ariane-smt2.dts
  return `ariane-${target.replace(/^g6lc64_/, "").replace(/_/g, "-")}.dts`;
}

function rewriteField(text: string, field: string, value: string, label: string): string {
  const re = new RegExp(`(^\\s*${field}:\\s*)([^,\\n]+)(,?)`, "m");
  const m = re.exec(text);
  if (!m) throw new Error(`${label}: field '${field}' not found in the cva6_cfg literal`);
  return text.replace(re, `$1${value}$3`);
}

/** Derive the `_ai` package text from the base package text. */
export function pinPackageText(baseText: string, opts: PinOptions, baseRel: string, baseSha: string): string {
  const aiLiteral = opts.int ? "config_pkg::AiCfgIslandInt" : "config_pkg::AiCfgIsland";
  let text = baseText;
  text = rewriteField(text, "CvxifEn", "bit'(1)", opts.target);
  text = rewriteField(text, "CoproType", "config_pkg::COPRO_G6LC_AI", opts.target);
  text = rewriteField(text, "AiCfg", aiLiteral, opts.target);
  const header =
    `// ${AI_OVERLAY_MARKER} -- do not edit.\n` +
    `// Base: ${baseRel} (sha256 ${baseSha.slice(0, 16)}), plane: ${aiLiteral}` +
    (opts.islandCfg ? `, island geometry ${opts.islandCfg}` : "") +
    `.\n` +
    `// Regenerate: bun run src/cli/index.ts ai-overlay pin --target ${opts.target}` +
    (opts.int ? " --int" : "") +
    (opts.islandCfg ? ` --island-cfg ${opts.islandCfg}` : "") +
    `\n` +
    `// This is the pinned form of \`+define+G6LC_AI_OVERLAY\` on the base package:\n` +
    `// exactly CvxifEn, CoproType and AiCfg differ from the base. Everything the\n` +
    `// base states about the core is inherited verbatim, including its licence.\n`;
  // Insert after the leading comment block (licence header), before `package`.
  const pkgIdx = text.search(/^package\s+cva6_config_pkg;/m);
  if (pkgIdx < 0) throw new Error(`${opts.target}: 'package cva6_config_pkg;' not found`);
  return text.slice(0, pkgIdx) + header + "\n" + text.slice(pkgIdx);
}

/** Derive the `_ai` DTS: include the base DTS + island dtsi, append xg6lcai per cpu. */
export function pinDtsText(baseDts: string, baseDtsName: string, opts: PinOptions): string {
  const cpus = [...baseDts.matchAll(/^\s*(CPU\d+):\s*cpu@\d+\s*\{([\s\S]*?)^\s{4}\};/gm)];
  if (cpus.length === 0) throw new Error(`${baseDtsName}: no labelled cpu@N nodes found`);
  const geometry = ISLAND_GEOMETRY[opts.islandCfg ?? "AiIslandLatencyDefault"];
  if (!geometry) throw new Error(`unknown island geometry literal: ${opts.islandCfg}`);
  let out =
    `// ${AI_OVERLAY_MARKER} -- do not edit.\n` +
    `// ${opts.target}_ai: ${baseDtsName} plus the Xg6lcai matrix plane (g6lc-ai-matrix.dtsi)\n` +
    `// and the xg6lcai ISA token on every cpu. Regenerate with\n` +
    `// bun run src/cli/index.ts ai-overlay pin --target ${opts.target}` +
    (opts.int ? " --int" : "") + (opts.islandCfg ? ` --island-cfg ${opts.islandCfg}` : "") + "\n" +
    `/dts-v1/;\n\n/include/ "${baseDtsName}"\n/include/ "g6lc-ai-matrix.dtsi"\n\n`;
  for (const m of cpus) {
    const label = m[1] ?? "CPU?";
    const body = m[2] ?? "";
    const ext = /riscv,isa-extensions\s*=\s*([\s\S]*?);/m.exec(body);
    if (!ext || ext[1] === undefined) throw new Error(`${baseDtsName}: ${label} has no riscv,isa-extensions`);
    const list = ext[1].replace(/\s+/g, " ").trim();
    const extended = list.includes('"xg6lcai"') ? list : `${list}, "xg6lcai"`;
    out += `&${label} {\n  riscv,isa-extensions = ${extended};\n};\n\n`;
  }
  out +=
    `// Island geometry published to the driver (must track the CAP words of\n` +
    `// g6lc_ai_island_cfg_pkg::${opts.islandCfg ?? "AiIslandLatencyDefault"}).\n` +
    `&ai_matrix {\n` +
    `  g6lc,acc-tile-m = <${geometry.m}>;\n  g6lc,acc-tile-n = <${geometry.n}>;\n  g6lc,acc-tile-k = <${geometry.k}>;\n` +
    `  g6lc,macs-per-cycle = <${geometry.macs}>;\n  g6lc,queues = <${geometry.queues}>;\n  g6lc,queue-depth = <${geometry.depth}>;\n` +
    `  g6lc,noc-width = <${geometry.noc}>;\n  g6lc,dram-gbps = <${geometry.gbps}>;\n  g6lc,clusters = <${geometry.clusters}>;\n};\n`;
  return out;
}

/** Read a text file with LF line endings whatever the checkout produced (autocrlf). */
function readLf(path: string): string {
  return readFileSync(path, "utf8").replace(/\r\n/g, "\n");
}

async function sha256Hex(text: string): Promise<string> {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/** Compute the pinned artefacts for a target (pure: nothing is written). */
export async function computePin(repoRoot: string, opts: PinOptions): Promise<PinResult> {
  if (!/^g6lc64_[a-z0-9_]+$/.test(opts.target)) {
    throw new Error(`ai-overlay pin: only g6lc64_* packages are pinned (got '${opts.target}'); use +define+G6LC_AI_OVERLAY on upstream-shaped packages`);
  }
  if (opts.target.endsWith("_ai")) throw new Error(`ai-overlay pin: '${opts.target}' is already an AI package`);
  const baseRel = `core/include/${opts.target}_config_pkg.sv`;
  const basePath = join(repoRoot, baseRel);
  if (!existsSync(basePath)) throw new Error(`ai-overlay pin: base package not found: ${baseRel}`);
  // Line endings are normalised before anything is derived from the text: a
  // Windows checkout with autocrlf reads the same base as CRLF, and the base
  // sha in the marker header (and the generated bytes) must not depend on that.
  const baseText = readLf(basePath);
  if (/AiCfg:\s*config_pkg::AiCfgOff/.test(baseText) === false) {
    throw new Error(`${baseRel}: AiCfg is not AiCfgOff -- the base already carries an AI plane; nothing to pin`);
  }
  const baseSha = await sha256Hex(baseText);
  const packageName = `${opts.target}_ai`;
  const packageText = pinPackageText(baseText, opts, baseRel, baseSha);

  const dtsBase = baseDtsName(opts.target);
  const dtsBasePath = join(repoRoot, "corev_apu/bootrom", dtsBase);
  let dtsName: string | null = null;
  let dtsPath: string | null = null;
  let dtsText: string | null = null;
  if (existsSync(dtsBasePath)) {
    dtsName = dtsBase.replace(/\.dts$/, "-ai.dts");
    dtsPath = join(repoRoot, "corev_apu/bootrom", dtsName);
    dtsText = pinDtsText(readLf(dtsBasePath), dtsBase, opts);
  }
  return {
    packageName,
    packagePath: join(repoRoot, "core/include", `${packageName}_config_pkg.sv`),
    packageText,
    dtsName,
    dtsPath,
    dtsText,
  };
}

/** Drift check: the pinned files on disk equal a fresh generation. */
export async function checkPin(repoRoot: string, opts: PinOptions): Promise<{ ok: boolean; detail: string }> {
  const pin = await computePin(repoRoot, opts);
  const problems: string[] = [];
  if (!existsSync(pin.packagePath)) problems.push(`missing ${pin.packagePath}`);
  else if (readFileSync(pin.packagePath, "utf8").replace(/\r\n/g, "\n") !== pin.packageText.replace(/\r\n/g, "\n"))
    problems.push(`drift: ${pin.packagePath}`);
  if (pin.dtsPath) {
    if (!existsSync(pin.dtsPath)) problems.push(`missing ${pin.dtsPath}`);
    else if (readFileSync(pin.dtsPath, "utf8").replace(/\r\n/g, "\n") !== (pin.dtsText ?? "").replace(/\r\n/g, "\n"))
      problems.push(`drift: ${pin.dtsPath}`);
  }
  return { ok: problems.length === 0, detail: problems.join("; ") || "pinned files match the generator" };
}
