// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
//
// fo4Golden.ts — S3b FO4 golden checks for timings packages (structural only).
// Compares analyze.json path FO4 totals against a golden file; used to detect
// accidental FO4 model / fixture drift before STA lab correlation.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface Fo4GoldenPath {
  path_id?: number;
  startpoint?: string;
  endpoint?: string;
  total_fo4: number;
}

export interface Fo4Golden {
  schema: string;
  note?: string;
  package_id?: string;
  target_mhz?: number;
  budget_fo4?: number;
  /** Relative tolerance on total_fo4 (default 0.01 = 1%). */
  tolerance?: number;
  paths: Fo4GoldenPath[];
  frequency_closure?: {
    closes?: boolean;
    worst_path_fo4?: number;
    failing_paths?: number;
  };
}

export interface Fo4GoldenMismatch {
  kind: "missing_path" | "extra_path" | "fo4_delta" | "closure" | "parse";
  detail: string;
  expected?: number;
  actual?: number;
}

export interface Fo4GoldenCheckResult {
  ok: boolean;
  goldenPath: string;
  reportPath: string;
  tolerance: number;
  mismatches: Fo4GoldenMismatch[];
  compared: number;
}

function loadJson(path: string): unknown {
  return JSON.parse(readFileSync(path, "utf8"));
}

function pathKey(p: {
  path_id?: number | null;
  startpoint?: string;
  endpoint?: string;
  start?: string;
  end?: string;
}): string {
  if (p.path_id != null) return `id:${p.path_id}`;
  const s = p.startpoint ?? p.start ?? "?";
  const e = p.endpoint ?? p.end ?? "?";
  return `${s}→${e}`;
}

/** Load golden file (JSON). */
export function loadFo4Golden(path: string): Fo4Golden {
  const g = loadJson(path) as Fo4Golden;
  if (!g || !Array.isArray(g.paths)) {
    throw new Error(`invalid fo4 golden: ${path}`);
  }
  return g;
}

/** Build a golden object from an analyze-result-like report. */
export function goldenFromAnalyze(
  report: Record<string, unknown>,
  opts: { packageId?: string; tolerance?: number } = {},
): Fo4Golden {
  const paths = Array.isArray(report.paths)
    ? (report.paths as Record<string, unknown>[])
    : [];
  const fc = (report.frequency_closure ?? {}) as Record<string, unknown>;
  return {
    schema: "cva6-fo4-golden.v0",
    note: "generated by timings fo4-golden write — structural FO4 only, not STA",
    package_id: opts.packageId,
    target_mhz:
      typeof report.target_mhz === "number" ? report.target_mhz : undefined,
    budget_fo4:
      typeof report.budget_fo4 === "number"
        ? report.budget_fo4
        : typeof fc.budget_fo4 === "number"
          ? fc.budget_fo4
          : undefined,
    tolerance: opts.tolerance ?? 0.01,
    paths: paths.map((p) => ({
      path_id: typeof p.path_id === "number" ? p.path_id : undefined,
      startpoint: typeof p.startpoint === "string" ? p.startpoint : undefined,
      endpoint: typeof p.endpoint === "string" ? p.endpoint : undefined,
      total_fo4: typeof p.total_fo4 === "number" ? p.total_fo4 : 0,
    })),
    frequency_closure: {
      closes: typeof fc.closes === "boolean" ? fc.closes : undefined,
      worst_path_fo4:
        typeof fc.worst_path_fo4 === "number" ? fc.worst_path_fo4 : undefined,
      failing_paths:
        typeof fc.failing_paths === "number" ? fc.failing_paths : undefined,
    },
  };
}

/**
 * Compare package analyze.json against fo4-golden.json.
 * Default golden path: <pkgDir>/fo4-golden.json or sibling fixture path.
 */
export function checkFo4Golden(
  pkgDir: string,
  goldenPath?: string,
): Fo4GoldenCheckResult {
  const reportPath = existsSync(join(pkgDir, "analyze.json"))
    ? join(pkgDir, "analyze.json")
    : join(pkgDir, "correct.json");
  const gPath = goldenPath ?? join(pkgDir, "fo4-golden.json");
  const mismatches: Fo4GoldenMismatch[] = [];

  if (!existsSync(reportPath)) {
    return {
      ok: false,
      goldenPath: gPath,
      reportPath,
      tolerance: 0,
      mismatches: [{ kind: "parse", detail: `missing report ${reportPath}` }],
      compared: 0,
    };
  }
  if (!existsSync(gPath)) {
    return {
      ok: false,
      goldenPath: gPath,
      reportPath,
      tolerance: 0,
      mismatches: [{ kind: "parse", detail: `missing golden ${gPath}` }],
      compared: 0,
    };
  }

  let report: Record<string, unknown>;
  let golden: Fo4Golden;
  try {
    report = loadJson(reportPath) as Record<string, unknown>;
    golden = loadFo4Golden(gPath);
  } catch (e) {
    return {
      ok: false,
      goldenPath: gPath,
      reportPath,
      tolerance: 0,
      mismatches: [
        {
          kind: "parse",
          detail: e instanceof Error ? e.message : String(e),
        },
      ],
      compared: 0,
    };
  }

  const tol = golden.tolerance ?? 0.01;
  const actualPaths = Array.isArray(report.paths)
    ? (report.paths as Record<string, unknown>[])
    : [];
  const actualMap = new Map<string, number>();
  for (const p of actualPaths) {
    const key = pathKey({
      path_id: typeof p.path_id === "number" ? p.path_id : undefined,
      startpoint: typeof p.startpoint === "string" ? p.startpoint : undefined,
      endpoint: typeof p.endpoint === "string" ? p.endpoint : undefined,
    });
    actualMap.set(key, typeof p.total_fo4 === "number" ? p.total_fo4 : 0);
  }

  let compared = 0;
  for (const gp of golden.paths) {
    const key = pathKey(gp);
    const act = actualMap.get(key);
    if (act == null) {
      mismatches.push({
        kind: "missing_path",
        detail: `golden path missing in report: ${key}`,
        expected: gp.total_fo4,
      });
      continue;
    }
    compared++;
    const exp = gp.total_fo4;
    const rel = exp === 0 ? Math.abs(act) : Math.abs(act - exp) / Math.abs(exp);
    if (rel > tol) {
      mismatches.push({
        kind: "fo4_delta",
        detail: `FO4 delta for ${key}: expected ${exp}, got ${act} (tol ${tol})`,
        expected: exp,
        actual: act,
      });
    }
    actualMap.delete(key);
  }
  for (const [key, act] of actualMap) {
    mismatches.push({
      kind: "extra_path",
      detail: `report path not in golden: ${key} fo4=${act}`,
      actual: act,
    });
  }

  if (golden.frequency_closure) {
    const fc = (report.frequency_closure ?? {}) as Record<string, unknown>;
    if (
      golden.frequency_closure.closes != null &&
      fc.closes !== golden.frequency_closure.closes
    ) {
      mismatches.push({
        kind: "closure",
        detail: `frequency_closure.closes expected ${golden.frequency_closure.closes}, got ${String(fc.closes)}`,
      });
    }
    if (
      golden.frequency_closure.worst_path_fo4 != null &&
      typeof fc.worst_path_fo4 === "number"
    ) {
      const exp = golden.frequency_closure.worst_path_fo4;
      const act = fc.worst_path_fo4;
      const rel = exp === 0 ? Math.abs(act) : Math.abs(act - exp) / Math.abs(exp);
      if (rel > tol) {
        mismatches.push({
          kind: "closure",
          detail: `worst_path_fo4 expected ${exp}, got ${act}`,
          expected: exp,
          actual: act,
        });
      }
    }
  }

  return {
    ok: mismatches.length === 0,
    goldenPath: gPath,
    reportPath,
    tolerance: tol,
    mismatches,
    compared,
  };
}

export function writeFo4Golden(path: string, golden: Fo4Golden): void {
  writeFileSync(path, JSON.stringify(golden, null, 2) + "\n", "utf8");
}
