// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
//
// staHandoff.ts — Host-side OpenSTA/OpenROAD handoff from timings packages.
//
// Phase S0: review-only SDC seeds + FO4 path CSV + correlate scaffold.
// Phase S1: Yosys (+yosys-slang when available) synth smoke → synth/netlist.v
// Phase S2: OpenSTA when `sta`/`opensta` + liberty present → opensta/paths.rpt
// Soft-skip when tools/liberty missing. See architecture/build-platform-opensta-from-timing.md.
// sv-timing package remains independent — we only consume analyze JSON + portable.f.

import {
  existsSync,
  mkdirSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, isAbsolute, join } from "node:path";

import type { PlatformContext } from "../context.ts";
import { hasBinary, run, which } from "../platform/exec.ts";
import {
  resolveFromTimingDir,
  summarizeTimingsPackage,
  type TimingsSoakDashboard,
  writeTimingsDashboard,
} from "./timings.ts";
import { edaEnv, edaPaths, posixPath } from "./eda.ts";

export interface StaHandoffOptions {
  fromTiming: string;
  /** Output root; default workspace/build/sta-handoff/<tag> */
  outDir?: string;
  targetMhz?: number;
  topN?: number;
  /** Attempt S1/S2 when tools present (default false for pure S0). */
  tryTools?: boolean;
  /** Top module for synth (default: first module in analyze.json or comb_cloud). */
  top?: string;
  /** Liberty .lib for OpenSTA (else CVA6_LIBERTY / physicalDesign). */
  liberty?: string;
  /** Prefer corrected emit flist when present. */
  useEmit?: boolean;
  /**
   * Inject a synthetic OpenSTA paths.rpt for offline S3a correlate self-test
   * (true = package sibling opensta_paths.rpt or repo fixture; string = path).
   */
  injectStaFixture?: boolean | string;
}

export interface StaHandoffResult {
  ok: boolean;
  outDir: string;
  seedsSdc: string;
  fo4Csv: string;
  manifest: string;
  correlate: string;
  netlist?: string;
  dashboard?: TimingsSoakDashboard;
  stages: {
    id: string;
    status: "pass" | "skip" | "fail";
    detail: string;
  }[];
  issues: string[];
}

function tagFromPath(p: string): string {
  const parts = p.replace(/\\/g, "/").split("/").filter(Boolean);
  return parts[parts.length - 1] || "package";
}

function loadAnalyzeJson(dir: string): Record<string, unknown> | null {
  for (const name of ["analyze.json", "correct.json"]) {
    const f = join(dir, name);
    if (!existsSync(f)) continue;
    try {
      return JSON.parse(readFileSync(f, "utf8")) as Record<string, unknown>;
    } catch {
      return null;
    }
  }
  return null;
}

interface Fo4Row {
  rank: number;
  pathId: number | null;
  totalFo4: number;
  slackFo4: number | null;
  maxFreqMhz: number | null;
  kind: string;
  start: string;
  end: string;
  closes: boolean | null;
}

function extractFo4Rows(raw: Record<string, unknown>, topN: number): Fo4Row[] {
  const paths = Array.isArray(raw.paths) ? (raw.paths as Record<string, unknown>[]) : [];
  const rows: Fo4Row[] = paths.map((p, i) => ({
    rank: 0,
    pathId: typeof p.path_id === "number" ? p.path_id : null,
    totalFo4: typeof p.total_fo4 === "number" ? p.total_fo4 : 0,
    slackFo4: typeof p.slack_fo4 === "number" ? p.slack_fo4 : null,
    maxFreqMhz: typeof p.max_freq_mhz === "number" ? p.max_freq_mhz : null,
    kind: typeof p.path_kind === "string" ? p.path_kind : "?",
    start: typeof p.startpoint === "string" ? p.startpoint : "?",
    end: typeof p.endpoint === "string" ? p.endpoint : "?",
    closes: typeof p.closes === "boolean" ? p.closes : null,
  }));
  rows.sort((a, b) => b.totalFo4 - a.totalFo4);
  return rows.slice(0, topN).map((r, i) => ({ ...r, rank: i + 1 }));
}

function periodNs(mhz: number): number {
  if (!Number.isFinite(mhz) || mhz <= 0) return 1;
  return 1000 / mhz;
}

/** Build review-only SDC text from analyze JSON + target MHz. */
export function buildSeedsSdc(opts: {
  targetMhz: number;
  rows: Fo4Row[];
  staHints?: Record<string, unknown>[];
  sourceDir: string;
}): string {
  const lines: string[] = [
    "# =============================================================================",
    "# REVIEW-ONLY SDC seeds generated by build-platform timings sta-handoff",
    `# Source package: ${opts.sourceDir}`,
    "# structural FO4 is NOT STA sign-off — engineer must validate hierarchical names",
    "# Do NOT treat set_max_delay as derived from FO4 without review",
    "# =============================================================================",
    "",
    `# create_clock seed from host target_mhz=${opts.targetMhz}`,
    `# period_ns ≈ ${periodNs(opts.targetMhz).toFixed(4)}  (1000/MHz)`,
    `create_clock -name clk -period ${periodNs(opts.targetMhz).toFixed(4)} [get_ports clk_i]`,
    "# ^^^ port name clk_i is a CVA6-common default; edit for your top",
    "",
    "# --- FO4-ranked path seeds (report_timing comments only) ---",
  ];
  for (const r of opts.rows) {
    lines.push(
      `# FO4 rank=${r.rank} path_id=${r.pathId ?? "?"} total_fo4=${r.totalFo4.toFixed(2)} ` +
        `slack_fo4=${r.slackFo4 ?? "?"} kind=${r.kind}`,
    );
    lines.push(
      `# report_timing -from {${r.start}} -to {${r.end}}  ;# engineer validates names`,
    );
    lines.push("");
  }
  const hints = opts.staHints ?? [];
  if (hints.length) {
    lines.push("# --- sta_hints[] from sv-timing analyze (review-only) ---");
    for (const h of hints.slice(0, 16)) {
      const from = typeof h.from === "string" ? h.from : typeof h.start === "string" ? h.start : "?";
      const to = typeof h.to === "string" ? h.to : typeof h.end === "string" ? h.end : "?";
      const cmt =
        typeof h.sdc_comment === "string"
          ? h.sdc_comment
          : typeof h.comment === "string"
            ? h.comment
            : "";
      lines.push(`# hint: report_timing -from {${from}} -to {${to}}`);
      if (cmt) lines.push(`# ${cmt.replace(/\n/g, " ")}`);
      lines.push("");
    }
  }
  lines.push("# end of review-only seeds");
  lines.push("");
  return lines.join("\n");
}

function fo4Csv(rows: Fo4Row[]): string {
  const header =
    "rank,path_id,total_fo4,slack_fo4,max_freq_mhz,kind,startpoint,endpoint,closes\n";
  const body = rows
    .map(
      (r) =>
        `${r.rank},${r.pathId ?? ""},${r.totalFo4},${r.slackFo4 ?? ""},${r.maxFreqMhz ?? ""},` +
        `${r.kind},"${r.start.replace(/"/g, '""')}","${r.end.replace(/"/g, '""')}",${r.closes ?? ""}`,
    )
    .join("\n");
  return header + body + "\n";
}

/** Parse portable.f-style list into absolute source paths. */
export function listSourcesFromPortableF(portablePath: string): string[] {
  if (!existsSync(portablePath)) return [];
  const base = dirname(portablePath);
  const files: string[] = [];
  for (const line of readFileSync(portablePath, "utf8").split(/\r?\n/)) {
    const text = line.replace(/\/\/.*$/, "").replace(/^\s*#.*$/, "").trim();
    if (!text || text.startsWith("+") || text.startsWith("-")) continue;
    const abs =
      isAbsolute(text) || /^[A-Za-z]:[\\/]/.test(text) ? text : join(base, text);
    if (existsSync(abs)) files.push(abs);
  }
  return files;
}

function pickTopModule(
  raw: Record<string, unknown>,
  override?: string,
): string {
  if (override && override.length) return override;
  if (Array.isArray(raw.modules) && raw.modules.length) {
    const m0 = raw.modules[0] as Record<string, unknown>;
    if (typeof m0.name === "string") return m0.name;
  }
  const req = raw.modules_requested;
  if (Array.isArray(req) && typeof req[0] === "string") return req[0];
  return "top";
}

function resolveLiberty(ctx: PlatformContext, override?: string): string | null {
  if (override && existsSync(override)) return override;
  if (process.env.CVA6_LIBERTY && existsSync(process.env.CVA6_LIBERTY)) {
    return process.env.CVA6_LIBERTY;
  }
  const pdk = ctx.config.physicalDesign?.pdk as
    | { liberty?: string; name?: string }
    | undefined;
  if (pdk?.liberty) {
    const cand = isAbsolute(pdk.liberty)
      ? pdk.liberty
      : join(ctx.repoRoot, pdk.liberty);
    if (existsSync(cand)) return cand;
  }
  // Common open-PDK study drop (optional, not required)
  for (const rel of [
    "pd/pdk/core/lib/typical.lib",
    "pd/pdk/technology.example/lib/typical.lib",
    "build-platform/workspace/tooling/liberty/typical.lib",
  ]) {
    const cand = join(ctx.repoRoot, rel);
    if (existsSync(cand)) return cand;
  }
  return null;
}

function resolveOpenStaBin(): string | null {
  return which("sta") ?? which("opensta") ?? (hasBinary("sta") ? "sta" : hasBinary("opensta") ? "opensta" : null);
}

/** Best-effort parse of OpenSTA path report for start/end + slack. */
export function parseOpenStaPathReport(text: string): {
  rank: number;
  start?: string;
  end?: string;
  slack?: number;
}[] {
  const rows: { rank: number; start?: string; end?: string; slack?: number }[] = [];
  // Match lines like:  slack (VIOLATED) -0.12 or Startpoint: foo / Endpoint: bar
  let start: string | undefined;
  let end: string | undefined;
  let slack: number | undefined;
  for (const line of text.split(/\r?\n/)) {
    const s = /Startpoint:\s+(\S+)/i.exec(line);
    if (s) start = s[1];
    const e = /Endpoint:\s+(\S+)/i.exec(line);
    if (e) end = e[1];
    const sl = /slack\s*(?:\([^)]*\))?\s+(-?\d+(?:\.\d+)?)/i.exec(line);
    if (sl) {
      slack = Number(sl[1]);
      if (start || end || slack != null) {
        rows.push({
          rank: rows.length + 1,
          start,
          end,
          slack,
        });
        start = undefined;
        end = undefined;
        slack = undefined;
      }
    }
  }
  return rows.slice(0, 32);
}

function computeOverlap(
  fo4: Fo4Row[],
  sta: { start?: string; end?: string }[],
): { overlap: string[]; missing_in_sta: string[]; missing_in_fo4: string[] } {
  const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9_]/g, "");
  const fo4Keys = fo4.map((r) => ({
    key: `${norm(r.start)}→${norm(r.end)}`,
    label: `${r.start}→${r.end}`,
  }));
  const staKeys = sta.map((r) => ({
    key: `${norm(r.start ?? "")}→${norm(r.end ?? "")}`,
    label: `${r.start ?? "?"}→${r.end ?? "?"}`,
  }));
  const staSet = new Set(staKeys.map((s) => s.key));
  const fo4Set = new Set(fo4Keys.map((f) => f.key));
  const overlap = fo4Keys.filter((f) => staSet.has(f.key)).map((f) => f.label);
  const missing_in_sta = fo4Keys.filter((f) => !staSet.has(f.key)).map((f) => f.label);
  const missing_in_fo4 = staKeys.filter((s) => !fo4Set.has(s.key)).map((s) => s.label);
  return { overlap, missing_in_sta, missing_in_fo4 };
}

async function runYosysSynthSmoke(
  ctx: PlatformContext,
  opts: {
    sources: string[];
    top: string;
    synthDir: string;
    dryRun?: boolean;
  },
): Promise<{ status: "pass" | "skip" | "fail"; detail: string; netlist?: string }> {
  mkdirSync(opts.synthDir, { recursive: true });
  const netlist = join(opts.synthDir, "netlist.v");
  const logPath = join(opts.synthDir, "yosys.log");
  const flistPath = join(opts.synthDir, "sources.f");

  if (opts.sources.length === 0) {
    return { status: "skip", detail: "no source files from portable.f / emit flist" };
  }

  writeFileSync(flistPath, opts.sources.map((s) => posixPath(s)).join("\n") + "\n", "utf8");

  let yosysBin: string | null = null;
  let slangPlugin: string | null = null;
  let env: Record<string, string> | undefined;
  try {
    const paths = edaPaths(ctx);
    if (existsSync(paths.yosys)) {
      yosysBin = paths.yosys;
      if (existsSync(paths.slangPlugin)) slangPlugin = paths.slangPlugin;
      env = edaEnv(ctx, paths, ctx.config.soc.coreConfig);
    }
  } catch {
    /* no suite root */
  }
  if (!yosysBin) {
    yosysBin = which("yosys");
  }
  if (!yosysBin) {
    return { status: "skip", detail: "yosys not found (OSS CAD suite or PATH)" };
  }

  // Prefer slang frontend for .sv; fall back to read_verilog for .v-only lists.
  const hasSv = opts.sources.some((s) => /\.svh?$/i.test(s));
  let script: string;
  if (slangPlugin && hasSv) {
    script = [
      `read_slang -f ${posixPath(flistPath)} --top ${opts.top} --single-unit`,
      `hierarchy -check -top ${opts.top}`,
      "proc",
      "opt -fast",
      "check",
      "stat",
      `write_verilog -noattr ${posixPath(netlist)}`,
    ].join("; ");
  } else if (!hasSv) {
    const reads = opts.sources
      .map((s) => `read_verilog ${posixPath(s)}`)
      .join("; ");
    script = [
      reads,
      `hierarchy -check -top ${opts.top}`,
      "proc",
      "opt -fast",
      "stat",
      `write_verilog -noattr ${posixPath(netlist)}`,
    ].join("; ");
  } else {
    // SV without slang plugin — try read_verilog -sv (limited)
    const reads = opts.sources
      .map((s) => `read_verilog -sv ${posixPath(s)}`)
      .join("; ");
    script = [
      reads,
      `hierarchy -check -top ${opts.top}`,
      "proc",
      "opt -fast",
      "stat",
      `write_verilog -noattr ${posixPath(netlist)}`,
    ].join("; ");
  }

  const yosysArgs =
    slangPlugin && hasSv
      ? ["-m", slangPlugin, "-p", script]
      : ["-p", script];

  if (opts.dryRun) {
    writeFileSync(
      logPath,
      `[dry-run] ${yosysBin} ${yosysArgs.join(" ")}\n`,
      "utf8",
    );
    return {
      status: "skip",
      detail: `dry-run yosys top=${opts.top} sources=${opts.sources.length}`,
    };
  }

  const result = await run(yosysBin, yosysArgs, {
    cwd: ctx.repoRoot,
    env,
    stdio: "capture",
    allowFailure: true,
    dryRun: false,
  });
  writeFileSync(
    logPath,
    `exit=${result.code}\n${result.stdout}\n${result.stderr}\n`,
    "utf8",
  );

  if (!result.ok) {
    // Soft-fail for complex packages (full CVA6) — still a stage fail for fixtures
    return {
      status: "fail",
      detail: `yosys exit ${result.code} (see yosys.log); complex SV may need module allowlist`,
    };
  }
  if (!existsSync(netlist)) {
    return { status: "fail", detail: "yosys ok but netlist.v missing" };
  }
  return {
    status: "pass",
    detail: `netlist.v top=${opts.top} (${opts.sources.length} sources)`,
    netlist: posixPath(netlist),
  };
}

async function runOpenStaSmoke(opts: {
  netlist: string;
  sdc: string;
  liberty: string;
  openstaDir: string;
  staBin: string;
  top: string;
  dryRun?: boolean;
}): Promise<{
  status: "pass" | "skip" | "fail";
  detail: string;
  report?: string;
  staRows?: ReturnType<typeof parseOpenStaPathReport>;
}> {
  mkdirSync(opts.openstaDir, { recursive: true });
  const tclPath = join(opts.openstaDir, "run.tcl");
  const reportPath = join(opts.openstaDir, "paths.rpt");
  const wnsPath = join(opts.openstaDir, "wns.txt");
  const logPath = join(opts.openstaDir, "opensta.log");

  // Generic OpenSTA script — liberty must match netlist tech
  const tcl = [
    `# Generated by build-platform timings sta-handoff S2 — not sign-off`,
    `read_liberty ${posixPath(opts.liberty)}`,
    `read_verilog ${posixPath(opts.netlist)}`,
    `link_design ${opts.top}`,
    `read_sdc ${posixPath(opts.sdc)}`,
    `report_checks -path_delay max -fields {slew cap input_pins nets} -format full_clock_expanded -group_count 20 > ${posixPath(reportPath)}`,
    `report_wns > ${posixPath(wnsPath)}`,
    `report_tns`,
    "exit",
    "",
  ].join("\n");
  writeFileSync(tclPath, tcl, "utf8");

  if (opts.dryRun) {
    return {
      status: "skip",
      detail: `dry-run ${opts.staBin} -exit run.tcl`,
    };
  }

  const result = await run(opts.staBin, ["-exit", tclPath], {
    cwd: opts.openstaDir,
    stdio: "capture",
    allowFailure: true,
  });
  writeFileSync(
    logPath,
    `exit=${result.code}\n${result.stdout}\n${result.stderr}\n`,
    "utf8",
  );

  if (!result.ok && !existsSync(reportPath)) {
    return {
      status: "fail",
      detail: `opensta exit ${result.code} (see opensta.log); check liberty vs netlist`,
    };
  }
  const reportText = existsSync(reportPath)
    ? readFileSync(reportPath, "utf8")
    : result.stdout;
  if (!existsSync(reportPath) && result.stdout) {
    writeFileSync(reportPath, result.stdout, "utf8");
  }
  const staRows = parseOpenStaPathReport(reportText);
  return {
    status: result.ok || existsSync(reportPath) ? "pass" : "fail",
    detail: `paths.rpt (${staRows.length} parsed path blocks)`,
    report: posixPath(reportPath),
    staRows,
  };
}

/**
 * Phase S0–S2 handoff: SDC seeds + FO4 CSV + optional Yosys + optional OpenSTA.
 */
export async function runStaHandoff(
  ctx: PlatformContext,
  opts: StaHandoffOptions,
): Promise<StaHandoffResult> {
  const stages: StaHandoffResult["stages"] = [];
  const issues: string[] = [];
  const topN = opts.topN ?? 16;
  const pkgDir = resolveFromTimingDir(ctx, opts.fromTiming);
  const tag = tagFromPath(pkgDir);
  let resolvedOut: string;
  if (!opts.outDir) {
    resolvedOut = join(ctx.paths.build, "sta-handoff", tag);
  } else if (
    opts.outDir.startsWith("/") ||
    /^[A-Za-z]:[\\/]/.test(opts.outDir)
  ) {
    resolvedOut = opts.outDir;
  } else if (/^workspace[/\\]/i.test(opts.outDir)) {
    resolvedOut = join(ctx.paths.root, opts.outDir.replace(/^workspace[/\\]/i, ""));
  } else {
    resolvedOut = join(ctx.repoRoot, opts.outDir);
  }

  mkdirSync(resolvedOut, { recursive: true });

  if (!existsSync(pkgDir)) {
    return {
      ok: false,
      outDir: posixPath(resolvedOut),
      seedsSdc: "",
      fo4Csv: "",
      manifest: "",
      correlate: "",
      stages: [{ id: "s0-package", status: "fail", detail: `missing package ${pkgDir}` }],
      issues: [`package not found: ${pkgDir}`],
    };
  }

  const raw = loadAnalyzeJson(pkgDir);
  if (!raw) {
    issues.push("no parseable analyze.json/correct.json");
    stages.push({ id: "s0-analyze", status: "fail", detail: "missing report JSON" });
    return {
      ok: false,
      outDir: posixPath(resolvedOut),
      seedsSdc: "",
      fo4Csv: "",
      manifest: "",
      correlate: "",
      stages,
      issues,
    };
  }

  const targetMhz =
    opts.targetMhz ??
    (typeof raw.target_mhz === "number" ? raw.target_mhz : ctx.config.soc.targetFrequencyMHz);

  const rows = extractFo4Rows(raw, topN);
  const staHints = Array.isArray(raw.sta_hints)
    ? (raw.sta_hints as Record<string, unknown>[])
    : [];

  const sdcPath = join(resolvedOut, "seeds.sdc");
  const csvPath = join(resolvedOut, "fo4_paths.csv");
  const manifestPath = join(resolvedOut, "handoff-manifest.json");
  const correlatePath = join(resolvedOut, "correlate.json");

  writeFileSync(
    sdcPath,
    buildSeedsSdc({
      targetMhz,
      rows,
      staHints,
      sourceDir: posixPath(pkgDir),
    }),
    "utf8",
  );
  writeFileSync(csvPath, fo4Csv(rows), "utf8");

  const dashboard = summarizeTimingsPackage(ctx, pkgDir);
  writeTimingsDashboard(resolvedOut, dashboard);
  // Also refresh package-side dashboard
  try {
    writeTimingsDashboard(pkgDir, dashboard);
  } catch {
    /* ignore */
  }

  stages.push({
    id: "s0-sdc-seeds",
    status: "pass",
    detail: `${rows.length} FO4 paths, ${staHints.length} sta_hints → seeds.sdc`,
  });

  // --- S1 Yosys synth + S2 OpenSTA (optional, soft-skip) ---
  let netlistPath: string | undefined;
  let staRows: ReturnType<typeof parseOpenStaPathReport> = [];
  const top = pickTopModule(raw, opts.top);
  const synthDir = join(resolvedOut, "synth");
  const openstaDir = join(resolvedOut, "opensta");

  if (opts.tryTools) {
    // Resolve sources: emit flist preferred when useEmit
    let portable =
      existsSync(join(pkgDir, "portable.host.f"))
        ? join(pkgDir, "portable.host.f")
        : join(pkgDir, "portable.f");
    const correctedF = join(pkgDir, "corrected", "svt_corrected.f");
    if (opts.useEmit && existsSync(correctedF)) {
      portable = correctedF;
    } else if (existsSync(join(pkgDir, "svt_corrected.f"))) {
      portable = join(pkgDir, "svt_corrected.f");
    }
    const sources = listSourcesFromPortableF(portable);

    const synth = await runYosysSynthSmoke(ctx, {
      sources,
      top,
      synthDir,
      dryRun: ctx.dryRun,
    });
    stages.push({
      id: "s1-yosys-synth",
      status: synth.status,
      detail: synth.detail,
    });
    if (synth.netlist) netlistPath = synth.netlist;

    const liberty = resolveLiberty(ctx, opts.liberty);
    const staBin = resolveOpenStaBin();
    if (!netlistPath) {
      stages.push({
        id: "s2-opensta",
        status: "skip",
        detail: "no netlist from S1 — skip OpenSTA",
      });
    } else if (!liberty) {
      stages.push({
        id: "s2-opensta",
        status: "skip",
        detail:
          "no liberty (.lib): set CVA6_LIBERTY or physicalDesign.pdk.liberty / pd/pdk drop",
      });
      // Still write a stub TCL for operators
      mkdirSync(openstaDir, { recursive: true });
      writeFileSync(
        join(openstaDir, "run.tcl"),
        [
          "# Stub: provide liberty then re-run timings sta-handoff --try-tools",
          `# read_liberty <path.lib>`,
          `read_verilog ${netlistPath}`,
          `link_design ${top}`,
          `read_sdc ${posixPath(sdcPath)}`,
          "report_checks -path_delay max -group_count 10",
          "exit",
          "",
        ].join("\n"),
        "utf8",
      );
    } else if (!staBin) {
      stages.push({
        id: "s2-opensta",
        status: "skip",
        detail: "opensta/sta not on PATH (soft-skip)",
      });
    } else {
      const sta = await runOpenStaSmoke({
        netlist: netlistPath,
        sdc: sdcPath,
        liberty,
        openstaDir,
        staBin,
        top,
        dryRun: ctx.dryRun,
      });
      stages.push({
        id: "s2-opensta",
        status: sta.status,
        detail: sta.detail,
      });
      if (sta.staRows) staRows = sta.staRows;
    }

    // S4: write OpenROAD floorplan TCL when netlist exists; run only if openroad + try
    const openroadDir = join(resolvedOut, "openroad");
    if (netlistPath) {
      mkdirSync(openroadDir, { recursive: true });
      const orTcl = join(openroadDir, "floorplan.tcl");
      writeFileSync(
        orTcl,
        [
          "# OpenROAD floorplan smoke — study path only, not tape-out",
          `# netlist: ${netlistPath}`,
          "# Provide LEF/lib via lab scripts; this is a scaffold.",
          `read_verilog ${netlistPath}`,
          `link_design ${top}`,
          "initialize_floorplan -die_area {0 0 100 100} -core_area {10 10 90 90}",
          "# place_pins / global_placement require tech LEF — soft lab step",
          "exit",
          "",
        ].join("\n"),
        "utf8",
      );
      const orBin = which("openroad");
      if (orBin && !ctx.dryRun) {
        const orLog = join(openroadDir, "openroad.log");
        const orResult = await run(orBin, ["-exit", orTcl], {
          cwd: openroadDir,
          stdio: "capture",
          allowFailure: true,
        });
        writeFileSync(
          orLog,
          `exit=${orResult.code}\n${orResult.stdout}\n${orResult.stderr}\n`,
          "utf8",
        );
        stages.push({
          id: "s4-openroad",
          status: orResult.ok ? "pass" : "fail",
          detail: orResult.ok
            ? "floorplan.tcl ran (study)"
            : `openroad exit ${orResult.code} (often missing LEF — see openroad.log)`,
        });
      } else if (orBin && ctx.dryRun) {
        stages.push({
          id: "s4-openroad",
          status: "skip",
          detail: "dry-run openroad floorplan.tcl written",
        });
      } else {
        stages.push({
          id: "s4-openroad",
          status: "skip",
          detail: "floorplan.tcl written; openroad not on PATH",
        });
      }
    } else if (hasBinary("openroad")) {
      stages.push({
        id: "s4-openroad",
        status: "skip",
        detail: "openroad present — need S1 netlist first",
      });
    } else {
      stages.push({
        id: "s4-openroad",
        status: "skip",
        detail: "openroad not on PATH",
      });
    }
  } else {
    stages.push({
      id: "s1-yosys-synth",
      status: "skip",
      detail: "pass --try-tools to run Yosys/OpenSTA stages",
    });
    stages.push({
      id: "s2-opensta",
      status: "skip",
      detail: "pass --try-tools to run Yosys/OpenSTA stages",
    });
  }

  // --- Optional offline STA fixture inject (S3a self-test without OpenSTA binary) ---
  mkdirSync(openstaDir, { recursive: true });
  const staReport = join(openstaDir, "paths.rpt");
  const realStaThisRun = staRows.length > 0;
  if (opts.injectStaFixture && !realStaThisRun) {
    // Always (re)write so re-runs stay reproducible and the stage is visible.
    const fixturePath = resolveStaFixturePath(ctx, pkgDir, opts.injectStaFixture);
    if (fixturePath && existsSync(fixturePath)) {
      writeFileSync(staReport, readFileSync(fixturePath, "utf8"), "utf8");
      stages.push({
        id: "s2-opensta-fixture",
        status: "pass",
        detail: `injected synthetic paths.rpt from ${posixPath(fixturePath)} (not real STA)`,
      });
    } else {
      stages.push({
        id: "s2-opensta-fixture",
        status: "skip",
        detail: "injectStaFixture set but fixture file not found",
      });
    }
  } else if (!opts.injectStaFixture && !realStaThisRun && existsSync(staReport)) {
    // --no-sta-fixture: drop leftover synthetic inject so correlate is FO4-only.
    const head = readFileSync(staReport, "utf8").slice(0, 120);
    if (/Synthetic OpenSTA/i.test(head)) {
      try {
        unlinkSync(staReport);
      } catch {
        // best-effort; correlate will still parse if unlink fails
      }
    }
  }

  // --- S3 correlate ---
  const staPresent = existsSync(staReport) || staRows.length > 0;
  if (staPresent && staRows.length === 0 && existsSync(staReport)) {
    staRows = parseOpenStaPathReport(readFileSync(staReport, "utf8"));
  }
  const overlap = computeOverlap(rows, staRows);
  const correlate = {
    schema: "cva6-sta-correlate.v0",
    note: "structural FO4 vs STA — STA authoritative when present; FO4 is screening only",
    package: posixPath(pkgDir),
    targetMhz,
    top,
    fo4_rank: rows.map((r) => ({
      rank: r.rank,
      path_id: r.pathId,
      total_fo4: r.totalFo4,
      start: r.start,
      end: r.end,
      kind: r.kind,
    })),
    sta_rank: staRows,
    overlap: overlap.overlap,
    missing_in_sta: overlap.missing_in_sta,
    missing_in_fo4: overlap.missing_in_fo4,
    overlap_score:
      rows.length === 0
        ? null
        : Number((overlap.overlap.length / rows.length).toFixed(3)),
    sta_report: staPresent ? posixPath(staReport) : null,
    netlist: netlistPath ?? null,
    stages_pending: staPresent
      ? []
      : ["s1-yosys-synth", "s2-opensta"].filter(
          (id) => !stages.some((s) => s.id === id && s.status === "pass"),
        ),
  };

  if (staPresent && staRows.length > 0) {
    stages.push({
      id: "s3-correlate",
      status: "pass",
      detail: `overlap_score=${correlate.overlap_score} (${overlap.overlap.length}/${rows.length} FO4 tops matched)`,
    });
  } else if (staPresent) {
    stages.push({
      id: "s3-correlate",
      status: "pass",
      detail: "sta report present but no path blocks parsed — FO4 ranks only",
    });
  } else {
    stages.push({
      id: "s3-correlate",
      status: "skip",
      detail: "no opensta/paths.rpt yet — FO4-only correlate scaffold",
    });
  }
  writeFileSync(correlatePath, JSON.stringify(correlate, null, 2) + "\n", "utf8");

  const manifest = {
    schema: "cva6-sta-handoff.v1",
    package: posixPath(pkgDir),
    outDir: posixPath(resolvedOut),
    targetMhz,
    top,
    files: {
      seedsSdc: posixPath(sdcPath),
      fo4Csv: posixPath(csvPath),
      correlate: posixPath(correlatePath),
      soakDashboard: posixPath(join(resolvedOut, "soak-dashboard.json")),
      netlist: netlistPath ?? null,
      openstaReport: staPresent ? posixPath(staReport) : null,
    },
    stages,
    disclaimer: "structural FO4 is not STA sign-off",
  };
  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + "\n", "utf8");

  // S0 is success even if S1 fails on heavy packages (informational PD path)
  const s0ok = stages.some((s) => s.id === "s0-sdc-seeds" && s.status === "pass");
  return {
    ok: s0ok,
    outDir: posixPath(resolvedOut),
    seedsSdc: posixPath(sdcPath),
    fo4Csv: posixPath(csvPath),
    manifest: posixPath(manifestPath),
    correlate: posixPath(correlatePath),
    netlist: netlistPath,
    dashboard,
    stages,
    issues,
  };
}

/** Locate synthetic OpenSTA paths.rpt fixture for offline correlate. */
function resolveStaFixturePath(
  ctx: PlatformContext,
  pkgDir: string,
  inject: boolean | string,
): string | null {
  if (typeof inject === "string" && inject.length > 0) {
    if (existsSync(inject)) return inject;
    const underRepo = join(ctx.repoRoot, inject);
    if (existsSync(underRepo)) return underRepo;
    return null;
  }
  const candidates = [
    join(pkgDir, "opensta_paths.rpt"),
    join(pkgDir, "paths.rpt"),
    join(
      ctx.repoRoot,
      "verif",
      "sv-timing-tests",
      "fixtures",
      "sta_smoke",
      "opensta_paths.rpt",
    ),
  ];
  for (const c of candidates) {
    if (existsSync(c)) return c;
  }
  return null;
}

/**
 * Materialize the pure-Verilog sta_smoke package under outDir (for CI S1).
 * Copies comb_adder.v analyze.json and writes absolute portable.f.
 */
export function materializeStaSmokePackage(
  ctx: PlatformContext,
  outDir: string,
): { dir: string; portableF: string; top: string } {
  mkdirSync(outDir, { recursive: true });
  const fix = join(
    ctx.repoRoot,
    "verif",
    "sv-timing-tests",
    "fixtures",
    "sta_smoke",
  );
  const v = join(fix, "comb_adder.v");
  const a = join(fix, "analyze.json");
  if (!existsSync(v) || !existsSync(a)) {
    throw new Error(`sta_smoke fixture missing under ${fix}`);
  }
  writeFileSync(join(outDir, "comb_adder.v"), readFileSync(v));
  writeFileSync(join(outDir, "analyze.json"), readFileSync(a));
  const goldenSrc = join(fix, "fo4-golden.json");
  if (existsSync(goldenSrc)) {
    writeFileSync(join(outDir, "fo4-golden.json"), readFileSync(goldenSrc));
  }
  const staFix = join(fix, "opensta_paths.rpt");
  if (existsSync(staFix)) {
    writeFileSync(join(outDir, "opensta_paths.rpt"), readFileSync(staFix));
  }
  const portableF = join(outDir, "portable.f");
  writeFileSync(
    portableF,
    `# sta_smoke portable\n${posixPath(join(outDir, "comb_adder.v"))}\n`,
    "utf8",
  );
  writeFileSync(
    join(outDir, "stamp.json"),
    JSON.stringify(
      {
        kind: "compile",
        target: "sta_smoke",
        modules: ["comb_adder"],
        exitCode: 0,
        mtimeMs: Date.now(),
        portableF: posixPath(portableF),
        reportJson: posixPath(join(outDir, "analyze.json")),
      },
      null,
      2,
    ) + "\n",
    "utf8",
  );
  return { dir: outDir, portableF, top: "comb_adder" };
}

/** Bench correlation: merge FO4 dashboard with optional suite metrics env. */
export function buildBenchCorrelation(opts: {
  dashboard: TimingsSoakDashboard;
  benchId: string;
  /** Optional numeric metrics (DMIPS, iterations, cycles) from suite env/logs */
  metrics?: Record<string, number | string>;
}): Record<string, unknown> {
  return {
    schema: "cva6-bench-timing-correlate.v0",
    note: "side-by-side structural FO4 dashboard + software bench metrics — not STA",
    bench_id: opts.benchId,
    metrics: opts.metrics ?? {},
    timing: {
      source: opts.dashboard.source,
      target_mhz: opts.dashboard.targetMhz,
      path_count: opts.dashboard.pathCount,
      closes: opts.dashboard.closes,
      max_freq_mhz: opts.dashboard.maxFreqMhz,
      worst_path_fo4: opts.dashboard.worstPathFo4,
      hottest: opts.dashboard.hottest.slice(0, 5),
    },
    env_hints: {
      CVA6_FROM_TIMING: process.env.CVA6_FROM_TIMING ?? null,
      CVA6_TIMINGS_USE_EMIT: process.env.CVA6_TIMINGS_USE_EMIT ?? null,
    },
  };
}
