# Copyright (c) 2026 Etienne Cimon
# SPDX-License-Identifier: MIT

[package]
name = "g6b-hw"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "BIOS hardware adapters: virtio-net, SoC ethernet/wifi/hdmi (not QEMU -netdev, not OpenSSL)"

[dependencies]
g6b-spec = { workspace = true }
g6b-asm = { workspace = true }
g6b-fs = { workspace = true }

[lints]
workspace = true
