# Copyright (c) 2026 Etienne Cimon
# SPDX-License-Identifier: MIT

[package]
name = "g6b-js"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Goja-shaped ES5 AOT for BIOS DOM (innerText assignments)"

[dependencies]
g6b-dom = { workspace = true }
g6b-webidl = { workspace = true }

[lints]
workspace = true
