#!/usr/bin/env python3
# Copyright (c) 2026 Etienne Cimon
# SPDX-License-Identifier: MIT
#
# flist_expand.py — generic filelist expander.
#
# Understands the common EDA `.f` conventions: file paths, `#` / `//` comments,
# `+incdir+`, `+define+`, and nested `-f` / `-F` includes with cycle guarding.
# Variables are expanded from an EXPLICIT map supplied by the caller; no project
# variable name is baked in, which is what lets this run against any tree.
#
#   python tools/flist_expand.py --in entry.f --set ROOT=/abs/project --out portable.f
#   python tools/flist_expand.py --selftest
#
# The Rust crate `g6q-flist` implements the same grammar; this script exists so the
# expansion is usable from shell/CI without building the workspace, and as an
# executable specification the crate is tested against.

from __future__ import annotations

import argparse
import re
import sys
import tempfile
from pathlib import Path

_VAR = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}|\$([A-Za-z_][A-Za-z0-9_]*)")


class FlistError(Exception):
    pass


def expand_vars(text: str, mapping: dict[str, str], *, strict: bool) -> str:
    def repl(m: re.Match[str]) -> str:
        name = m.group(1) or m.group(2)
        if name in mapping:
            return mapping[name]
        if strict:
            raise FlistError(f"undefined variable ${{{name}}}")
        return m.group(0)

    return _VAR.sub(repl, text)


def _strip_comment(line: str) -> str:
    # `//` anywhere, `#` only at the start of a token (a path may contain '#'
    # in theory but never in practice; be conservative and only honour a leading '#').
    idx = line.find("//")
    if idx >= 0:
        line = line[:idx]
    stripped = line.strip()
    if stripped.startswith("#"):
        return ""
    return line


class Expansion:
    def __init__(self) -> None:
        self.files: list[str] = []
        self.incdirs: list[str] = []
        self.defines: list[str] = []
        self.visited: set[Path] = set()

    def as_portable(self) -> str:
        out: list[str] = ["// generated by g6lc_qemu flist_expand.py"]
        out += [f"+incdir+{d}" for d in self.incdirs]
        out += [f"+define+{d}" for d in self.defines]
        out += list(self.files)
        return "\n".join(out) + "\n"


def expand(entry: Path, mapping: dict[str, str], *, strict: bool = True,
           acc: Expansion | None = None) -> Expansion:
    acc = acc if acc is not None else Expansion()
    entry = entry.resolve()
    if entry in acc.visited:
        return acc  # cycle guard: silently skip a second visit
    if not entry.is_file():
        raise FlistError(f"filelist not found: {entry}")
    acc.visited.add(entry)
    base = entry.parent

    tokens: list[str] = []
    for raw in entry.read_text(encoding="utf-8", errors="replace").splitlines():
        line = _strip_comment(raw).strip()
        if line:
            tokens.extend(line.split())

    i = 0
    while i < len(tokens):
        tok = expand_vars(tokens[i], mapping, strict=strict)
        if tok in ("-f", "-F"):
            if i + 1 >= len(tokens):
                raise FlistError(f"{entry}: dangling {tok}")
            nested = expand_vars(tokens[i + 1], mapping, strict=strict)
            npath = Path(nested)
            if not npath.is_absolute():
                npath = base / npath
            expand(npath, mapping, strict=strict, acc=acc)
            i += 2
            continue
        if tok.startswith("+incdir+"):
            for d in tok[len("+incdir+"):].split("+"):
                if d and d not in acc.incdirs:
                    acc.incdirs.append(_abs(d, base))
        elif tok.startswith("+define+"):
            for d in tok[len("+define+"):].split("+"):
                if d and d not in acc.defines:
                    acc.defines.append(d)
        elif tok.startswith(("-", "+")):
            pass  # unknown switch: ignored, not an error
        else:
            p = _abs(tok, base)
            if p not in acc.files:
                acc.files.append(p)
        i += 1
    return acc


def _is_absolute_portable(value: str) -> bool:
    """Whether a filelist entry should be treated as absolute, on any host.

    ``Path.is_absolute()`` is host-dependent, and that is the wrong semantics here: a
    manifest written on Linux routinely contains POSIX absolute paths such as
    ``/opt/design/core/top.sv``, and on Windows ``Path.is_absolute()`` reports those as
    *relative* because they lack a drive letter. Joining them onto the manifest's own
    directory then produces a path that matches nothing, and every membership query
    silently returns false -- a failure mode that looks like a design fact.

    Kept byte-for-byte equivalent to ``is_absolute_portable`` in crates/g6q-flist.
    """
    if not value:
        return False
    if value[0] in "/\\":
        return True
    return len(value) >= 3 and value[0].isalpha() and value[1] == ":" and value[2] in "/\\"


def _abs(value: str, base: Path) -> str:
    if _is_absolute_portable(value):
        text = value.replace("\\", "/")
    else:
        text = str(base / value).replace("\\", "/")
    # canonicalize()-style verbatim prefixes must never leak into output.
    return text[4:] if text.startswith("//?/") else text


# ------------------------------------------------------------------ selftest ---

_SELFTEST_TOP = """\
// top filelist
+incdir+${ROOT}/include
+define+FEATURE_B
${ROOT}/a.sv
-f nested.f
# a full-line comment
${ROOT}/c.sv   // trailing comment
"""

_SELFTEST_NESTED = """\
${ROOT}/b.sv
-f top.f          // cycle: must be ignored
"""


def selftest() -> int:
    with tempfile.TemporaryDirectory() as td:
        d = Path(td)
        (d / "top.f").write_text(_SELFTEST_TOP, encoding="utf-8")
        (d / "nested.f").write_text(_SELFTEST_NESTED, encoding="utf-8")
        res = expand(d / "top.f", {"ROOT": "/abs/proj"})

        checks = [
            (res.files == ["/abs/proj/a.sv", "/abs/proj/b.sv", "/abs/proj/c.sv"],
             f"file order/content wrong: {res.files}"),
            (res.incdirs == ["/abs/proj/include"], f"incdirs wrong: {res.incdirs}"),
            (res.defines == ["FEATURE_B"], f"defines wrong: {res.defines}"),
        ]
        failed = [msg for ok, msg in checks if not ok]

        try:
            expand(d / "top.f", {}, strict=True)
            failed.append("strict mode did not reject an undefined variable")
        except FlistError:
            pass

        # Portable absoluteness: a POSIX path from a Linux-authored manifest must stay
        # absolute on Windows, or every later membership query silently misses.
        abs_checks = [
            ("/opt/design/top.sv", True),
            ("\\\\server\\share\\top.sv", True),
            ("C:/design/top.sv", True),
            ("core/top.sv", False),
            ("./top.sv", False),
            ("C:top.sv", False),
        ]
        for value, want in abs_checks:
            if _is_absolute_portable(value) != want:
                failed.append(f"absoluteness wrong for {value!r}")

        # A relative entry resolves against the listing file's own directory.
        (d / "rel.f").write_text("core/top.sv\n", encoding="utf-8")
        rel = expand(d / "rel.f", {})
        if len(rel.files) != 1 or not rel.files[0].endswith("core/top.sv"):
            failed.append(f"relative resolution wrong: {rel.files}")
        if any("//?/" in f for f in rel.files):
            failed.append(f"verbatim prefix leaked: {rel.files}")

    if failed:
        for msg in failed:
            print(f"[flist_expand] FAIL: {msg}", file=sys.stderr)
        return 1
    print("[flist_expand] selftest OK")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Generic filelist expander.")
    ap.add_argument("--in", dest="entry", help="entry .f file")
    ap.add_argument("--out", dest="out", help="write a portable .f here (default: stdout)")
    ap.add_argument("--set", action="append", default=[], metavar="VAR=VALUE",
                    help="variable for ${VAR} expansion (repeatable)")
    ap.add_argument("--lenient", action="store_true",
                    help="leave undefined variables in place instead of failing")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args(argv)

    if args.selftest:
        return selftest()
    if not args.entry:
        ap.error("--in is required (or use --selftest)")

    mapping: dict[str, str] = {}
    for item in args.set:
        name, sep, value = item.partition("=")
        if not sep:
            ap.error(f"--set expects VAR=VALUE, got {item!r}")
        mapping[name] = value

    try:
        res = expand(Path(args.entry), mapping, strict=not args.lenient)
    except FlistError as exc:
        print(f"[flist_expand] ERROR: {exc}", file=sys.stderr)
        return 2

    text = res.as_portable()
    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"[flist_expand] wrote {args.out} ({len(res.files)} files)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
