#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Etienne Cimon
#
# OpenSTA handoff smoke (S0–S2, optional S4):
#   1) Pure-Verilog sta_smoke fixture package (no Rust compile required)
#   2) timings sta-handoff --try-tools → seeds.sdc + optional Yosys netlist
# Soft-pass S1 if yosys missing; hard-require S0 artifacts always.
# Plan: architecture/build-platform-opensta-from-timing.md

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
# shellcheck source=../sv-timing-tests/scripts/common.sh
source "$ROOT/verif/sv-timing-tests/scripts/common.sh"

svt_need_bun
OUT="$(svt_out_base "$ROOT")/sta-handoff-smoke"
PKG="$OUT/pkg"
FIX="$ROOT/verif/sv-timing-tests/fixtures/sta_smoke"
MHZ="${SVT_TARGET_MHZ:-1250}"

svt_ensure_dir "$PKG"

if svt_maybe_from_timing "$ROOT"; then
  PKG="$SVT_FROM_TIMING_DIR"
  echo "[timings-sta-handoff] using CVA6_FROM_TIMING package $PKG"
else
  echo "[timings-sta-handoff] materialize sta_smoke package → $PKG"
  # Absolute portable.f for S1 (no env expansion needed)
  {
    echo "# sta_smoke portable — generated by timings-sta-handoff.sh"
    echo "$FIX/comb_adder.v"
  } >"$PKG/portable.f"
  cp -f "$FIX/analyze.json" "$PKG/analyze.json"
  if [[ -f "$FIX/fo4-golden.json" ]]; then
    cp -f "$FIX/fo4-golden.json" "$PKG/fo4-golden.json"
  fi
  cat >"$PKG/stamp.json" <<EOF
{
  "kind": "compile",
  "target": "sta_smoke",
  "targetMhz": $MHZ,
  "modules": ["comb_adder"],
  "allModules": false,
  "command": "fixture-materialize",
  "exitCode": 0,
  "mtimeMs": $(date +%s000 2>/dev/null || echo 0),
  "portableF": "$PKG/portable.f",
  "reportJson": "$PKG/analyze.json"
}
EOF
fi

echo "[timings-sta-handoff] sta-handoff S0–S2 (+ S4 stub)"
TOP="${SVT_STA_TOP:-comb_adder}"
EXTRA=(--top "$TOP")
if [[ -n "${CVA6_LIBERTY:-}" ]]; then EXTRA+=(--liberty "$CVA6_LIBERTY"); fi
svt_timings "$ROOT" sta-handoff --from-timing "$PKG" --output "$OUT/handoff" --try-tools "${EXTRA[@]}"

test -f "$OUT/handoff/seeds.sdc" || { echo "missing seeds.sdc"; exit 1; }
test -f "$OUT/handoff/fo4_paths.csv" || { echo "missing fo4_paths.csv"; exit 1; }
test -f "$OUT/handoff/correlate.json" || { echo "missing correlate.json"; exit 1; }
grep -q "REVIEW-ONLY" "$OUT/handoff/seeds.sdc"
grep -q "create_clock" "$OUT/handoff/seeds.sdc"
grep -q "comb_adder\|a_i\|y_o" "$OUT/handoff/seeds.sdc" || true

# S3b: FO4 golden must match fixture analyze.json
if [[ -f "$PKG/fo4-golden.json" ]]; then
  echo "[timings-sta-handoff] fo4-golden check"
  svt_timings "$ROOT" fo4-golden check --from-timing "$PKG"
else
  echo "[timings-sta-handoff] no fo4-golden.json — skip S3b"
fi

# S1: if yosys available, netlist must exist for this pure-.v fixture
if command -v yosys >/dev/null 2>&1 || [[ -x "$ROOT/build-platform/workspace/tooling/oss-cad-suite/bin/yosys" ]] \
  || [[ -x "$ROOT/build-platform/workspace/tooling/oss-cad-suite/bin/yosys.exe" ]]; then
  if [[ -f "$OUT/handoff/synth/netlist.v" ]]; then
    echo "[timings-sta-handoff] S1 PASS netlist.v"
    test -s "$OUT/handoff/synth/netlist.v"
  else
    echo "[timings-sta-handoff] yosys detected but netlist missing — check synth/yosys.log"
    if [[ -f "$OUT/handoff/synth/yosys.log" ]]; then
      tail -n 40 "$OUT/handoff/synth/yosys.log" || true
    fi
    # Soft: still pass suite so hosts without OSS CAD suite layout stay green
    echo "[timings-sta-handoff] S1 SOFT (yosys present but synth failed)"
  fi
else
  echo "[timings-sta-handoff] S1 skip (no yosys)"
fi

if [[ -f "$OUT/handoff/opensta/paths.rpt" ]]; then
  echo "[timings-sta-handoff] S2 paths.rpt present"
fi
if [[ -f "$OUT/handoff/openroad/floorplan.tcl" ]]; then
  echo "[timings-sta-handoff] S4 floorplan.tcl present"
fi

echo "[timings-sta-handoff] PASS (S0 hard; S1–S4 soft without full PD stack)"
