// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT

//! Opt-in soak against a real design tree.
//!
//! The package's own tests must pass with only this tree and its synthetic fixtures
//! (independence, KD0), so this file **skips itself** unless `G6Q_DESIGN_ROOT` points at
//! a checkout. When it is set, it parses every configuration package found there and
//! asserts the reader copes with real input rather than only with the sample.
//!
//! ```text
//! G6Q_DESIGN_ROOT=/path/to/design cargo test -p g6q-svcfg -- --nocapture
//! ```
//!
//! Fixtures are never taken from that tree ([`AGENTS-licensing.md`] §4); this test reads
//! it at run time and commits nothing from it.
//!
//! [`AGENTS-licensing.md`]: ../../../AGENTS-licensing.md

use std::path::{Path, PathBuf};

use g6q_svcfg::{read_package_file, validate};

fn design_root() -> Option<PathBuf> {
    let v = std::env::var("G6Q_DESIGN_ROOT").ok()?;
    let p = PathBuf::from(v);
    p.is_dir().then_some(p)
}

/// Configuration packages in a design tree, excluding the shared type definitions and
/// anything a build step generates.
fn config_packages(root: &Path) -> Vec<PathBuf> {
    let dir = root.join("core").join("include");
    let Ok(entries) = std::fs::read_dir(&dir) else {
        return Vec::new();
    };
    let mut out: Vec<PathBuf> = entries
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| {
            let Some(name) = p.file_name().and_then(|s| s.to_str()) else {
                return false;
            };
            name.ends_with("config_pkg.sv")
                // Shared type/derivation packages, not targets.
                && name != "config_pkg.sv"
                && name != "build_config_pkg.sv"
                && name != "cva6_config_pkg.sv"
                // Generated by a build; may not even be readable.
                && !name.starts_with("work-ver-")
                && !name.starts_with("hwconfig")
        })
        .collect();
    out.sort();
    out
}

#[test]
fn every_real_configuration_package_reads_and_validates() {
    let Some(root) = design_root() else {
        eprintln!("skipped: set G6Q_DESIGN_ROOT to a design checkout to run this soak");
        return;
    };
    let pkgs = config_packages(&root);
    assert!(
        !pkgs.is_empty(),
        "no configuration packages under {}",
        root.display()
    );

    let mut failures: Vec<String> = Vec::new();
    for path in &pkgs {
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let pkg = match read_package_file(path) {
            Ok(p) => p,
            Err(e) => {
                failures.push(format!("{name}: unreadable ({e})"));
                continue;
            }
        };

        let Some((cfg_name, members)) = pkg.main_config() else {
            failures.push(format!("{name}: no configuration struct found"));
            continue;
        };

        // A real configuration is large; anything tiny means the reader lost the body.
        if members.len() < 40 {
            failures.push(format!("{name}: only {} fields parsed", members.len()));
        }
        // The one field every target must have.
        if !matches!(pkg.int_or("XLEN", 0), 32 | 64) {
            failures.push(format!("{name}: XLEN did not resolve"));
        }

        let unresolved = pkg.unresolved_fields();
        let legality = validate(&pkg);

        println!(
            "{name:<44} cfg={cfg_name:<12} fields={:<4} unresolved={:<2} legal={} unchecked={}",
            members.len(),
            unresolved.len(),
            legality.is_legal(),
            legality.unchecked().len()
        );
        if !unresolved.is_empty() {
            println!("    unresolved: {unresolved:?}");
        }
        for v in legality.violations() {
            println!(
                "    VIOLATION {}: {}",
                v.rule,
                v.violation.as_deref().unwrap_or("")
            );
            failures.push(format!(
                "{name}: {} -- {}",
                v.rule,
                v.violation.as_deref().unwrap_or("")
            ));
        }
    }

    println!("\n{} package(s) read", pkgs.len());
    assert!(
        failures.is_empty(),
        "soak failures:\n  {}",
        failures.join("\n  ")
    );
}

#[test]
fn reading_a_real_package_is_deterministic() {
    let Some(root) = design_root() else {
        return;
    };
    for path in config_packages(&root).into_iter().take(4) {
        let a = read_package_file(&path).expect("readable");
        let b = read_package_file(&path).expect("readable");
        assert_eq!(a, b, "{} did not read identically twice", path.display());
    }
}
