// Copyright 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
//
// 3d-b RTL bridge server (apu-vulkan-engine.md §12.3 phase B):
// clocks the real g6lc_apu_sys (ApuVenus, or ApuP1Transport with
// -GVenusOff=1) one cycle at a time and bridges it to a unix-domain
// stream socket — QEMU's g6lc_apu_bridge device (or bridge_selftest.py)
// is the CPU.
//
// Wire protocol (little-endian, see §12.3/3d-b):
//   u32 len (bytes after this field), u8 type, u8 flags, u16 seq, payload
//   QEMU->RTL:  0x01 MMIO_RD {u32 off}             -> 0x81 {u32 data,u8 err}
//               0x02 MMIO_WR {u32 off,u32 data,u8 strb} -> 0x82 {u8 err}
//   RTL->QEMU:  0x11 DMA_RD {u64 addr,u32 len}     -> 0x91 {u8 err,bytes}
//               0x12 DMA_WR {u64 addr,u32 len,bytes,strb[len/8 ceil]}
//                                                   -> 0x92 {u8 err}
//               0x13 IRQ {u8 level}                (no reply)
// The DUT keeps clocking while a DMA reply is outstanding; MMIO frames
// arriving meanwhile are queued.  seq matches replies to requests.
//
// Debug overlay: MMIO_RD offsets >= VN_MMIO_LEN+0x1000 (never generated
// by QEMU's 4 KiB region) read the vgsys observability taps
// (dbg_sel_i/dbg_rdata_o in the fixture) without touching the DUT —
// the selftest's chkp equivalents (EK_LIVE/EK_PAGES/EK_FENCE/EK_EXTRA/
// EK_HEAD/EK_STATUS) go through that page.
//
// Options: --sock PATH (env G6LC_APU_RTL_SOCK, default
// /tmp/g6lc-apu-rtl.sock), --trace FILE.fst, --max-cycles N,
// --bench N (free-run N cycles, print kHz), --stats (periodic counters).

#include "Vtb_g6lc_apu_bridge.h"
#include "verilated.h"
#if VM_TRACE_FST
#include "verilated_fst_c.h"
#endif
#include <sys/socket.h>
#include <sys/un.h>
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>
#include <poll.h>
#include <signal.h>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cerrno>
#include <deque>
#include <vector>
#include <unordered_map>
#include <string>
#include <chrono>
#include "bridge_map.h"   // generated by gen_venus_map.py — never typed

// ---- frame types --------------------------------------------------------
static const uint8_t T_MMIO_RD = 0x01, T_MMIO_WR = 0x02;
static const uint8_t T_MMIO_RD_R = 0x81, T_MMIO_WR_R = 0x82;
static const uint8_t T_DMA_RD = 0x11, T_DMA_WR = 0x12, T_IRQ = 0x13;
static const uint8_t T_DMA_RD_R = 0x91, T_DMA_WR_R = 0x92;

static const uint64_t MMIO_BASE = VN_MMIO_BASE;
static const uint64_t MMIO_LEN  = VN_MMIO_LEN;
static const uint64_t DMA_BASE  = VN_DMA_BASE;
static const uint64_t DMA_BYTES = VN_DMA_BYTES;
static const uint64_t SHM_BASE  = VN_SHM_BASE;
static const uint64_t SHM_BYTES = VN_SHM_BYTES;
// debug page: past the real MMIO window (generated VN_DBG_BASE)
static const uint32_t DBG_BASE  = (uint32_t)VN_DBG_BASE;

static Vtb_g6lc_apu_bridge* top;
static VerilatedFstC* tfp = nullptr;
static uint64_t cycles = 0;
static volatile bool running = true;

// ---- stats --------------------------------------------------------------
static uint64_t st_mmio_r = 0, st_mmio_w = 0;
static uint64_t st_dma_rd = 0, st_dma_wr = 0;
static uint64_t st_dma_rd_bytes = 0, st_dma_wr_bytes = 0;
static uint64_t st_irq = 0, st_oob = 0;

// ---- socket --------------------------------------------------------------
static int lfd = -1, cfd = -1;
static std::vector<uint8_t> rxbuf;
static uint16_t req_seq = 1;

static void die(const char* m) { perror(m); exit(1); }

static void sock_listen(const char* path) {
  lfd = socket(AF_UNIX, SOCK_STREAM | SOCK_NONBLOCK, 0);
  if (lfd < 0) die("socket");
  unlink(path);
  struct sockaddr_un sa = {};
  sa.sun_family = AF_UNIX;
  snprintf(sa.sun_path, sizeof(sa.sun_path), "%s", path);
  if (bind(lfd, (struct sockaddr*)&sa, sizeof(sa)) < 0) die("bind");
  if (listen(lfd, 1) < 0) die("listen");
  fprintf(stderr, "[bridge] listening on %s\n", path);
}

static void sock_accept() {
  if (cfd >= 0 || lfd < 0) return;
  int fd = accept4(lfd, nullptr, nullptr, SOCK_NONBLOCK);
  if (fd >= 0) {
    cfd = fd;
    fprintf(stderr, "[bridge] client connected\n");
  }
}

static void sock_close_client() {
  if (cfd >= 0) {
    fprintf(stderr, "[bridge] client disconnected\n");
    close(cfd);
    cfd = -1;
    rxbuf.clear();
  }
}

static void put_u8(std::vector<uint8_t>& v, uint8_t x) { v.push_back(x); }
static void put_u16(std::vector<uint8_t>& v, uint16_t x) {
  v.push_back(x & 0xff); v.push_back(x >> 8);
}
static void put_u32(std::vector<uint8_t>& v, uint32_t x) {
  for (int i = 0; i < 4; i++) v.push_back((x >> (8 * i)) & 0xff);
}
static void put_u64(std::vector<uint8_t>& v, uint64_t x) {
  for (int i = 0; i < 8; i++) v.push_back((x >> (8 * i)) & 0xff);
}

// raw send, framing: u32 len | u8 type | u8 flags | u16 seq | payload
static bool send_frame(uint8_t type, uint16_t seq, const uint8_t* pl,
                       size_t plen) {
  if (cfd < 0) return false;
  std::vector<uint8_t> f;
  put_u32(f, 4 + (uint32_t)plen);
  put_u8(f, type); put_u8(f, 0); put_u16(f, seq);
  for (size_t i = 0; i < plen; i++) f.push_back(pl[i]);
  size_t off = 0;
  while (off < f.size()) {
    ssize_t n = send(cfd, f.data() + off, f.size() - off, MSG_NOSIGNAL);
    if (n < 0) {
      if (errno == EAGAIN || errno == EWOULDBLOCK) { usleep(100); continue; }
      if (errno == EPIPE || errno == ECONNRESET) { sock_close_client(); return false; }
      die("send");
    }
    off += (size_t)n;
  }
  return true;
}

// ---- MMIO master state (AXI-Lite, one outstanding) -----------------------
struct MmioOp { uint16_t seq; bool wr; uint32_t off, data; uint8_t strb; };
static std::deque<MmioOp> mmio_q;
static bool m_act = false, m_awok = false, m_wok = false, m_iss = false;
static MmioOp m_cur;

// ---- DMA read burst (one outstanding burst at a time) --------------------
static bool     rd_open = false, rd_reply = false;
static uint8_t  rd_id = 0, rd_size = 0;
static uint64_t rd_addr = 0, rd_base = 0;
static int      rd_beats = 0, rd_beat = 0;
static uint16_t rd_seq = 0;
static uint8_t  rd_err = 0;
static std::vector<uint8_t> rd_bytes;

// ---- DMA write txn (one outstanding: AW+beats then B) --------------------
struct WBeat { uint64_t data; uint8_t strb; bool last; };
static bool     wr_aw = false, wr_sent = false, wr_reply = false;
static uint8_t  wr_id = 0, wr_size = 0;
static uint64_t wr_addr = 0;
static int      wr_beats = 0;
static uint8_t  wr_err = 0;
static uint16_t wr_seq = 0;
static std::deque<WBeat> wq;          // beats awaiting/belonging to the open txn

// replies arriving from the guest side, by requester seq
struct DmaReply { uint8_t err; std::vector<uint8_t> bytes; };
static std::unordered_map<uint16_t, DmaReply> dma_replies;
static std::unordered_map<uint16_t, std::pair<uint64_t, uint32_t>> rd_track;
static bool dbg = false;

static int prev_irq = 0;

// ---- helpers -------------------------------------------------------------
static bool in_window(uint64_t a) {
  return (a >= DMA_BASE && a < DMA_BASE + DMA_BYTES) ||
         (a >= SHM_BASE && a < SHM_BASE + SHM_BYTES);
}

static uint64_t lane_base(uint64_t burst_addr, int beat, uint8_t size) {
  return (burst_addr + ((uint64_t)beat << size)) & ~7ull;
}

// aligned 8-byte-lane span covering the whole burst
static void burst_span(uint64_t addr, int beats, uint8_t size,
                       uint64_t& base, uint64_t& len) {
  base = addr & ~7ull;
  uint64_t end = base;
  for (int i = 0; i < beats; i++)
    end = lane_base(addr, i, size) + 8;
  len = end - base;
}

// ---- debug overlay (no DUT access) ---------------------------------------
static uint32_t dbg_read(uint32_t off) {
  uint32_t idx = (off - DBG_BASE) >> 3;
  int hi = (off >> 2) & 1;
  top->dbg_sel_i = idx & 0xff;
  top->eval();                       // pure comb mux
  uint64_t v = top->dbg_rdata_o;
  return (uint32_t)(hi ? (v >> 32) : v);
}

// ---- socket dispatch ------------------------------------------------------
static void on_frame(uint8_t type, uint8_t flags, uint16_t seq,
                     const uint8_t* pl, size_t plen) {
  (void)flags;
  switch (type) {
  case T_MMIO_RD: {
    if (plen < 4) return;
    uint32_t off = pl[0] | (pl[1] << 8) | (pl[2] << 16) | ((uint32_t)pl[3] << 24);
    if (off >= DBG_BASE) {          // debug overlay: answer at once
      uint8_t r[5];
      uint32_t d = dbg_read(off);
      for (int i = 0; i < 4; i++) r[i] = (d >> (8 * i)) & 0xff;
      r[4] = 0;
      send_frame(T_MMIO_RD_R, seq, r, 5);
      st_mmio_r++;
      return;
    }
    mmio_q.push_back({seq, false, off, 0, 0});
    break;
  }
  case T_MMIO_WR: {
    if (plen < 9) return;
    uint32_t off = pl[0] | (pl[1] << 8) | (pl[2] << 16) | ((uint32_t)pl[3] << 24);
    uint32_t d = pl[4] | (pl[5] << 8) | (pl[6] << 16) | ((uint32_t)pl[7] << 24);
    mmio_q.push_back({seq, true, off, d, pl[8]});
    break;
  }
  case T_DMA_RD_R: {
    if (plen < 1) return;
    DmaReply r; r.err = pl[0];
    r.bytes.assign(pl + 1, pl + plen);
    dma_replies[seq] = std::move(r);
    if (dbg && rd_track.count(seq)) {
      auto t = rd_track[seq];
      fprintf(stderr, "[dbg] DMA_RD %016lx+%lu:", (unsigned long)t.first,
              (unsigned long)t.second);
      for (size_t i = 1; i < plen && i <= 48; i += 4) {
        uint32_t w = 0;
        for (int b = 0; b < 4 && i + b < plen; b++) w |= (uint32_t)pl[i + b] << (8 * b);
        fprintf(stderr, " %08x", w);
      }
      fprintf(stderr, "%s\n", plen > 49 ? " ..." : "");
    }
    break;
  }
  case T_DMA_WR_R: {
    if (plen < 1) return;
    DmaReply r; r.err = pl[0];
    dma_replies[seq] = std::move(r);
    break;
  }
  default:
    fprintf(stderr, "[bridge] unknown frame type 0x%02x seq %u\n",
            type, seq);
  }
}

static void pump_socket() {
  sock_accept();
  if (cfd < 0) return;
  uint8_t buf[65536];
  for (;;) {
    ssize_t n = recv(cfd, buf, sizeof(buf), MSG_DONTWAIT);
    if (n == 0) { sock_close_client(); return; }
    if (n < 0) {
      if (errno == EAGAIN || errno == EWOULDBLOCK) break;
      if (errno == ECONNRESET) { sock_close_client(); return; }
      die("recv");
    }
    rxbuf.insert(rxbuf.end(), buf, buf + n);
  }
  size_t pos = 0;
  while (rxbuf.size() - pos >= 4) {
    uint32_t len = rxbuf[pos] | (rxbuf[pos + 1] << 8) |
                   (rxbuf[pos + 2] << 16) | ((uint32_t)rxbuf[pos + 3] << 24);
    if (rxbuf.size() - pos < 4 + len) break;
    const uint8_t* fr = rxbuf.data() + pos + 4;
    on_frame(fr[0], fr[1], fr[2] | (fr[3] << 8), fr + 4, len - 4);
    pos += 4 + len;
  }
  rxbuf.erase(rxbuf.begin(), rxbuf.begin() + pos);
}

// ---- per-cycle drive ------------------------------------------------------
static void drive_inputs() {
  // guest AXI-Lite master
  if (!m_act && !mmio_q.empty()) {
    m_cur = mmio_q.front(); mmio_q.pop_front();
    m_act = true; m_awok = m_wok = false; m_iss = false;
  }
  if (m_act && m_cur.wr) {
    top->g_awvalid_i = !m_awok;
    top->g_awaddr_i  = MMIO_BASE + m_cur.off;
    top->g_wvalid_i  = !m_wok;
    top->g_wdata_i   = m_cur.data;
    top->g_wstrb_i   = m_cur.strb & 0xf;
    top->g_bready_i  = 1;
  } else if (m_act) {
    top->g_arvalid_i = !m_iss;
    top->g_araddr_i  = MMIO_BASE + m_cur.off;
    top->g_rready_i  = 1;
  } else {
    top->g_awvalid_i = 0; top->g_wvalid_i = 0; top->g_bready_i = 0;
    top->g_arvalid_i = 0; top->g_rready_i = 0;
  }
  // AXI4 slave
  top->d_arready_i = !rd_open;
  top->d_awready_i = !wr_aw;                  // one open write
  top->d_wready_i  = !wr_sent;                // collect beats until sent
  top->d_bvalid_i  = wr_reply;                // hold until accepted
  top->d_bid_i     = wr_id;
  top->d_bresp_i   = wr_err ? 2 : 0;          // SLVERR : OKAY
  top->d_rvalid_i  = rd_open && rd_reply;
  top->d_rid_i     = rd_id;
  top->d_rresp_i   = rd_err ? 2 : 0;
  top->d_rlast_i   = rd_beat == rd_beats - 1;
  uint64_t lb = lane_base(rd_addr, rd_beat, rd_size);
  uint64_t d = 0;
  for (int b = 0; b < 8; b++) {
    uint64_t idx = lb - rd_base + b;
    uint8_t v = idx < rd_bytes.size() ? rd_bytes[idx] : 0;
    d |= (uint64_t)v << (8 * b);
  }
  top->d_rdata_i = d;
}

struct HS {
  bool g_aw, g_w, g_b, g_ar, g_r;
  bool d_aw, d_w, d_b, d_ar, d_r;
  int irq;
  // payload captured at handshake time (pre-edge); post-edge the DUT's
  // registered outputs already hold the next cycle's values
  uint32_t g_rdata; uint8_t g_rresp, g_bresp;
  uint64_t d_wdata; uint8_t d_wstrb; bool d_wlast;
  uint8_t d_awid, d_awlen, d_awsize;
  uint64_t d_awaddr;
  uint8_t d_arid, d_arlen, d_arsize;
  uint64_t d_araddr;
};

static HS sample_outputs() {
  HS h = {};
  h.g_aw = top->g_awvalid_i && top->g_awready_o;
  h.g_w  = top->g_wvalid_i && top->g_wready_o;
  h.g_b  = top->g_bvalid_o && top->g_bready_i;
  h.g_ar = top->g_arvalid_i && top->g_arready_o;
  h.g_r  = top->g_rvalid_o && top->g_rready_i;
  h.d_aw = top->d_awvalid_o && top->d_awready_i;
  h.d_w  = top->d_wvalid_o && top->d_wready_i;
  h.d_b  = top->d_bvalid_i && top->d_bready_o;
  h.d_ar = top->d_arvalid_o && top->d_arready_i;
  h.d_r  = top->d_rvalid_i && top->d_rready_o;
  h.irq = top->guest_irq_o;
  if (h.g_r) { h.g_rdata = top->g_rdata_o; h.g_rresp = top->g_rresp_o; }
  if (h.g_b) h.g_bresp = top->g_bresp_o;
  if (h.d_w) { h.d_wdata = top->d_wdata_o; h.d_wstrb = top->d_wstrb_o;
               h.d_wlast = top->d_wlast_o; }
  if (h.d_aw) { h.d_awid = top->d_awid_o; h.d_awaddr = top->d_awaddr_o;
                h.d_awlen = top->d_awlen_o; h.d_awsize = top->d_awsize_o; }
  if (h.d_ar) { h.d_arid = top->d_arid_o; h.d_araddr = top->d_araddr_o;
                h.d_arlen = top->d_arlen_o; h.d_arsize = top->d_arsize_o; }
  return h;
}

static void issue_dma_rd() {
  uint64_t base, len;
  burst_span(rd_addr, rd_beats, rd_size, base, len);
  rd_base = base;
  std::vector<uint8_t> pl;
  put_u64(pl, base); put_u32(pl, (uint32_t)len);
  rd_seq = req_seq++;
  rd_track[rd_seq] = {base, (uint32_t)len};
  send_frame(T_DMA_RD, rd_seq, pl.data(), pl.size());
  st_dma_rd++; st_dma_rd_bytes += len;
  if (dbg) fprintf(stderr, "[dbg] DMA_RD req %016lx+%lu\n",
                   (unsigned long)base, (unsigned long)len);
  if (!in_window(base) || !in_window(base + len - 1)) {
    st_oob++;
    fprintf(stderr, "[bridge] DMA_RD out of window: %016lx+%lu\n",
            (unsigned long)base, (unsigned long)len);
  }
}

static void issue_dma_wr() {
  // flatten collected beats into bytes+strb over the lane-aligned span
  uint64_t base, len;
  burst_span(wr_addr, wr_beats, wr_size, base, len);
  std::vector<uint8_t> bytes(len, 0);
  std::vector<uint8_t> strb((len + 7) / 8, 0);
  int i = 0;
  for (auto it = wq.begin(); it != wq.end() && i < wr_beats; ++it, ++i) {
    uint64_t lb = lane_base(wr_addr, i, wr_size);
    for (int b = 0; b < 8; b++) {
      if (it->strb & (1 << b)) {
        uint64_t off = lb - base + b;
        if (off < len) {
          bytes[off] = (it->data >> (8 * b)) & 0xff;
          strb[off >> 3] |= 1 << (off & 7);
        }
      }
    }
  }
  std::vector<uint8_t> pl;
  put_u64(pl, base); put_u32(pl, (uint32_t)len);
  pl.insert(pl.end(), bytes.begin(), bytes.end());
  pl.insert(pl.end(), strb.begin(), strb.end());
  wr_seq = req_seq++;
  send_frame(T_DMA_WR, wr_seq, pl.data(), pl.size());
  st_dma_wr++; st_dma_wr_bytes += len;
  wr_sent = true;
  if (dbg) {
    fprintf(stderr, "[dbg] DMA_WR %016lx+%lu:", (unsigned long)base,
            (unsigned long)len);
    for (size_t i = 0; i < len && i < 48; i += 4) {
      uint32_t w = 0;
      for (int b = 0; b < 4 && i + b < len; b++) w |= (uint32_t)bytes[i + b] << (8 * b);
      fprintf(stderr, " %08x", w);
    }
    fprintf(stderr, " |");
    for (size_t i = 0; i < len; i++)
      fprintf(stderr, "%c", (strb[i >> 3] >> (i & 7)) & 1 ? '#' : '.');
    fprintf(stderr, "%s\n", len > 48 ? " ..." : "");
  }
  if (!in_window(base) || !in_window(base + len - 1)) {
    st_oob++;
    fprintf(stderr, "[bridge] DMA_WR out of window: %016lx+%lu\n",
            (unsigned long)base, (unsigned long)len);
  }
}

static void update_state(const HS& h) {
  // guest MMIO progress
  if (m_act) {
    if (m_cur.wr) {
      if (h.g_aw) m_awok = true;
      if (h.g_w)  m_wok = true;
      if (h.g_b) {
        uint8_t r[1] = { (uint8_t)(h.g_bresp != 0 ? 1 : 0) };
        send_frame(T_MMIO_WR_R, m_cur.seq, r, 1);
        st_mmio_w++;
        m_act = false;
      }
    } else {
      if (h.g_ar) m_iss = true;
      if (h.g_r) {
        uint8_t r[5];
        uint32_t d = h.g_rdata;
        for (int i = 0; i < 4; i++) r[i] = (d >> (8 * i)) & 0xff;
        r[4] = (uint8_t)(h.g_rresp != 0 ? 1 : 0);
        send_frame(T_MMIO_RD_R, m_cur.seq, r, 5);
        st_mmio_r++;
        m_act = false;
      }
    }
  }
  // DMA read channel
  if (h.d_ar) {
    rd_open = true; rd_reply = false; rd_beat = 0;
    rd_id = h.d_arid; rd_addr = h.d_araddr;
    rd_beats = h.d_arlen + 1; rd_size = h.d_arsize;
    rd_err = 0;
    issue_dma_rd();
  }
  if (rd_open && !rd_reply) {
    auto it = dma_replies.find(rd_seq);
    if (it != dma_replies.end()) {
      rd_reply = true; rd_err = it->second.err;
      rd_bytes = std::move(it->second.bytes);
      dma_replies.erase(it);
    }
  }
  if (h.d_r) {
    rd_beat++;
    if (rd_beat == rd_beats) rd_open = false;
  }
  // DMA write channel
  if (h.d_aw) {
    wr_aw = true;
    wr_id = h.d_awid; wr_addr = h.d_awaddr;
    wr_beats = h.d_awlen + 1; wr_size = h.d_awsize;
  }
  if (h.d_w) {
    wq.push_back({h.d_wdata, h.d_wstrb, h.d_wlast});
  }
  if (wr_aw && !wr_sent && (int)wq.size() >= wr_beats) {
    issue_dma_wr();
    // keep leftover beats (a W arriving for the next txn early)
    for (int i = 0; i < wr_beats && !wq.empty(); i++) wq.pop_front();
  }
  if (wr_sent && !wr_reply) {
    auto it = dma_replies.find(wr_seq);
    if (it != dma_replies.end()) {
      wr_reply = true; wr_err = it->second.err;
      dma_replies.erase(it);
    }
  }
  if (h.d_b) {                        // B accepted: write txn closes
    wr_aw = wr_sent = wr_reply = false;
    wr_err = 0; wr_beats = 0;
    wq.clear();
  }
  // IRQ edge
  if (h.irq != prev_irq) {
    uint8_t pl[1] = { (uint8_t)h.irq };
    send_frame(T_IRQ, 0, pl, 1);
    if (h.irq) st_irq++;
    prev_irq = h.irq;
  }
}

static void stats() {
  fprintf(stderr,
    "[bridge] cycles=%lu mmio_r=%lu mmio_w=%lu dma_rd=%lu(%lu B) "
    "dma_wr=%lu(%lu B) irq=%lu oob=%lu\n",
    (unsigned long)cycles, (unsigned long)st_mmio_r,
    (unsigned long)st_mmio_w, (unsigned long)st_dma_rd,
    (unsigned long)st_dma_rd_bytes, (unsigned long)st_dma_wr,
    (unsigned long)st_dma_wr_bytes, (unsigned long)st_irq,
    (unsigned long)st_oob);
}

static void on_sig(int) { running = false; }

int main(int argc, char** argv) {
  Verilated::commandArgs(argc, argv);
  dbg = getenv("G6LC_APU_DEBUG") != nullptr;
  const char* sock = getenv("G6LC_APU_RTL_SOCK");
  if (!sock) sock = "/tmp/g6lc-apu-rtl.sock";
  const char* trace = nullptr;
  uint64_t maxcyc = 0, bench = 0;
  bool do_stats = false;
  for (int i = 1; i < argc; i++) {
    if (!strcmp(argv[i], "--sock") && i + 1 < argc) sock = argv[++i];
    else if (!strcmp(argv[i], "--trace") && i + 1 < argc) trace = argv[++i];
    else if (!strcmp(argv[i], "--max-cycles") && i + 1 < argc)
      maxcyc = strtoull(argv[++i], nullptr, 0);
    else if (!strcmp(argv[i], "--bench") && i + 1 < argc)
      bench = strtoull(argv[++i], nullptr, 0);
    else if (!strcmp(argv[i], "--stats")) do_stats = true;
  }

  top = new Vtb_g6lc_apu_bridge;
  if (trace) {
    Verilated::traceEverOn(true);
    tfp = new VerilatedFstC;
    top->trace(tfp, 99);
    tfp->open(trace);
  }
  signal(SIGINT, on_sig);
  signal(SIGTERM, on_sig);

  // reset
  top->clk_i = 0; top->rst_ni = 0;
  top->g_awvalid_i = 0; top->g_wvalid_i = 0; top->g_bready_i = 0;
  top->g_arvalid_i = 0; top->g_rready_i = 0;
  top->d_awready_i = 0; top->d_wready_i = 0; top->d_bvalid_i = 0;
  top->d_arready_i = 0; top->d_rvalid_i = 0;
  top->dbg_sel_i = 0;
  for (int i = 0; i < 32; i++) {
    top->eval();
    top->clk_i = 1; top->eval();
    top->clk_i = 0;
    if (tfp) { tfp->dump(2 * cycles); tfp->dump(2 * cycles + 1); }
    cycles++;
  }
  top->rst_ni = 1;

  if (!bench) sock_listen(sock);

  auto t0 = std::chrono::steady_clock::now();
  uint64_t bench_start = 0;
  while (running) {
    if (!bench) pump_socket();
    drive_inputs();
    top->eval();
    if (tfp) tfp->dump(2 * cycles);
    HS h = sample_outputs();
    top->clk_i = 1; top->eval();
    if (tfp) tfp->dump(2 * cycles + 1);
    cycles++;
    update_state(h);
    top->clk_i = 0;
    if (bench && cycles - bench_start >= bench) break;
    if (maxcyc && cycles >= maxcyc) break;
    if (do_stats && (cycles & 0x3fffff) == 0) stats();
  }
  double sec = std::chrono::duration<double>(
      std::chrono::steady_clock::now() - t0).count();
  stats();
  if (cycles && sec > 0)
    fprintf(stderr, "[bridge] %.1f kHz\n", cycles / sec / 1000.0);
  if (tfp) { tfp->close(); }
  delete top;
  return 0;
}
