// Copyright 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
`timescale 1ns/1ps
// Transport session test of g6lc_apu_vgtop (§6b of
// architecture/uncore/apu-vulkan-engine.md).  The TB replays the
// guest-script tape generated by
//   python corev_apu/apu/tools/vn_golden.py --transport ue_sm5_transport 1
// against the real vgtop composition (vgctl + vnpump + vnfront +
// objtab + cmdrec + cmdexec + publication FSM).
//
// Tape ops (ue_sm5_transport.hex, one 32-bit word per line):
//   0 TP_END
//   1 TP_MEMW      [n][addr_lo][addr_hi][w0..w(n-1)]  guest RAM write
//   2 TP_CHAIN     [nd][desc{alo,ahi,len,write}*nd][flags][flo][fhi]
//                  [ctx][ridx]                       submit a chain
//   3 TP_APW       [n][off_lo][off_hi][w0..]          aperture write
//   4 TP_WAIT_HEAD [ring][head_ap_addr][exp][tmo]     poll aperture
//   5 TP_WAIT_IDLE [ring][status_ap_addr][mask][want][tmo]
//   6 TP_CHECK     [what][a0][a1]                     consume exp recs
//   7 TP_DELAY     [cycles]
//
// .exp records (8 words, consumed in order, FFFFFFFF FFFFFFFF ends):
//   1 EK_RESP   {used_len, resp_type, nbody}
//   2 EK_BODY   {w0..w6}    7 body words per record
//   3 EK_HEAD   {ring, head}
//   4 EK_STATUS {ring, status}
//   5 EK_REPLY  {idx, word}
//   6 EK_LIVE   {live}
//   7 EK_EXTRA  {ring, byte_off, word}
//   8 EK_FENCE  {fence_lo, fence_hi, ring_idx}
//
// The used ring is TB-synthesized: used elems at GUSED + slot*8 and a
// single used.idx cell at GUIDX.  The TB checks every response word
// against EK_RESP/EK_BODY, the used element/idx against the expected
// used_len, publication order (response < used elem < used idx <
// ISR), ring head/status through the pump's observability ports,
// reply bytes in the aperture, and ObjTab live count after teardown.

module tb_g6lc_apu_vgtop;
  import g6lc_apu_mp_pkg::*;
  import g6lc_apu_vn_pkg::*;
  import g6lc_apu_vg_pkg::*;
  import g6lc_apu_objtab_pkg::*;
  import g6lc_apu_cmdrec_pkg::*;
  import g6lc_apu_cmdexec_pkg::*;
  import g6lc_apu_vnfront_pkg::*;

  localparam int unsigned Rings   = 4;
  localparam int unsigned GMW     = 32'h40000;   // 1 MiB guest RAM
  // §12.3 F5-c: dense model spans the whole guest window — lazy type-1
  // blobs (memsplit) can first-fit above the low MiB
  localparam int unsigned PWB     = 32'(APU_VG_GUEST_BYTES >> 2);
  localparam int unsigned APW     = PWB;
  // §12.3 F5: the device-private arena sits at APU_VG_GUEST_BYTES..top;
  // the dense model covers it in [APW, APW+PPW) of i_mem.apm
  localparam int unsigned PPW     =
      APU_VG_PRIV_PAGES * (APU_VG_PAGE_BYTES / 4);
  // first-fit allocation keeps every session in the dense range; an
  // index past it is a tape/model bug — never wrap
  function automatic int unsigned apix(input int unsigned w);
    if (w < APW) return w;
    if (w >= PWB && w < PWB + PPW) return APW + (w - PWB);
    $fatal(1, "aperture word %0d past dense model", w);
    return 0;
  endfunction
  localparam int unsigned TAPEW   = 32'h100000;
  localparam int unsigned EXPW    = 32'h8000;
  localparam int unsigned MAXCYC  = 300_000_000;

  logic clk = 0, rst_ni = 0;
  int errors = 0, checks = 0, cycles = 0, cases = 0;

  // ---- DUT ------------------------------------------------------------
  logic            ch_v = 0, ch_r;
  logic [15:0]     ch_id = '0;
  logic [3:0]      ch_n = '0;
  apu_vg_desc_t [APU_VG_MAX_DESC-1:0] ch_d;
  logic            cpl_v;
  logic            vg_mf;
  logic [31:0]     cpl_len;
  logic [2:0]      mp_rv, mp_rr, mp_rsv;
  apu_mp_req_t [2:0] mp_req;
  apu_mp_rsp_t [2:0] mp_rsp;
  logic            w_v, w_done = 0;
  logic            w_r;
  apu_cmdexec_work_t w_o;
  logic            d_done, vg_busy;
  logic            f_pulse;
  logic [63:0]     f_id;
  logic [7:0]      f_ring;
  logic [Rings-1:0]       r_active;
  logic [Rings-1:0][31:0] r_status, r_head;
  logic [Rings-1:0][APU_VG_AP_WORD_W-1:0] r_extra;
  logic [15:0]     ot_live;
  // debug ObjTab (unused; tied off)
  logic            dot_r;
  apu_objtab_req_t dot_req = '0;
  logic            dot_cv;
  apu_objtab_cpl_t dot_cpl;

  g6lc_apu_vgtop #(.Enable(1'b1), .Rings(Rings)) i_dut (
    .clk_i(clk), .rst_ni(rst_ni), .testmode_i(1'b0),
    .chain_valid_i(ch_v), .chain_ready_o(ch_r),
    .chain_id_i(ch_id), .chain_n_i(ch_n), .chain_desc_i(ch_d),
    .cpl_valid_o(cpl_v), .cpl_ready_i(1'b1),
    .cpl_len_o(cpl_len), .mem_fault_o(vg_mf),
    .mp_req_valid_o(mp_rv), .mp_req_ready_i(mp_rr),
    .mp_req_o(mp_req),
    .mp_rsp_valid_i(mp_rsv), .mp_rsp_i(mp_rsp),
    .work_valid_o(w_v), .work_ready_i(w_r), .work_o(w_o),
    .work_done_i(w_done), .work_done_pl_i('0),
    .done_o(d_done), .busy_o(vg_busy),
    .fence_pulse_o(f_pulse), .fence_id_o(f_id), .fence_ring_o(f_ring),
    .ring_active_o(r_active), .ring_status_o(r_status),
    .ring_head_o(r_head), .ring_extra_w_o(r_extra),
    .objtab_live_o(ot_live),
    .dbg_ot_valid_i(1'b0), .dbg_ot_ready_o(dot_r),
    .dbg_ot_req_i(dot_req),
    .dbg_ot_cpl_valid_o(dot_cv), .dbg_ot_cpl_ready_i(1'b0),
    .dbg_ot_cpl_o(dot_cpl),
    .xf_axi_req_o(xf_areq), .xf_axi_rsp_i(xf_arsp),
    .ap_base_i(64'(g6lc_apu_pkg::APU_SHM_BASE)),
    .xf_flush_i(1'b0), .xfer_busy_o(xf_busy));

  // shared memory model: mp ports 0..2 -> {guest, aperture} backing
  tb_apu_mp_mem #(.N(3), .GMW(GMW), .APW(APW),
                  .PWB(PWB), .PPW(PPW)) i_mem (
    .clk_i(clk), .rst_ni(rst_ni),
    .req_valid_i(mp_rv), .req_ready_o(mp_rr), .req_i(mp_req),
    .rsp_valid_o(mp_rsv), .rsp_o(mp_rsp));

  // xfer AXI aperture slave: burst-capable reads + single-beat
  // writes over i_mem.apm, window-checked
  g6lc_apu_bus_pkg::apu_dma_axi_req_t  xf_areq;
  g6lc_apu_bus_pkg::apu_dma_axi_resp_t xf_arsp;
  logic            xf_busy;
  localparam logic [63:0] XAB  = g6lc_apu_pkg::APU_SHM_BASE;
  localparam logic [63:0] XAPB = APU_VG_SHM_BYTES;
  logic               xr_act, xr_vld;
  g6lc_apu_bus_pkg::apu_dma_axi_r_chan_t  xrch;
  logic [63:0]        xr_addr;
  logic [2:0]         xr_size;
  int unsigned        xr_rem;
  logic               xaw_s, xw_s, xb_vld;
  g6lc_apu_bus_pkg::apu_dma_axi_aw_chan_t xwaw;
  g6lc_apu_bus_pkg::apu_dma_axi_w_chan_t  xww;
  int unsigned        xf_aw_n = 0, xf_w_n = 0, xf_b_n = 0;
  int unsigned        xf_ar_n = 0, xf_r_n = 0, xf_arb = 0;
  int unsigned        xf_outst = 0;
  int                 xlog = 0;
  initial xlog = $test$plusargs("xlog");

  always_comb begin
    xf_arsp = '0;
    xf_arsp.ar_ready = !xr_act && !xr_vld;
    xf_arsp.r_valid  = xr_vld;
    xf_arsp.r        = xrch;
    xf_arsp.aw_ready = !xaw_s;
    xf_arsp.w_ready  = !xw_s;
    xf_arsp.b_valid  = xb_vld;
    xf_arsp.b        = '{id: 4'd1, resp: axi_pkg::RESP_OKAY, user: '0};
  end

  always @(posedge clk or negedge rst_ni) begin
    if (!rst_ni) begin
      xr_act <= 0; xr_vld <= 0; xr_rem <= 0; xr_addr <= '0;
      xr_size <= '0; xaw_s <= 0; xw_s <= 0; xb_vld <= 0;
      xwaw <= '0; xww <= '0; xrch <= '0;
    end else begin
      if (xf_areq.ar_valid && xf_arsp.ar_ready) begin
        if (!(xf_areq.ar.addr >= XAB && xf_areq.ar.addr < XAB + XAPB))
          $fatal(1, "xfer AR %016x outside aperture", xf_areq.ar.addr);
        if (xlog && xf_ar_n < 200)
          $display("XAR cyc=%0d ar=%016x len=%0d", cycles,
                   xf_areq.ar.addr, xf_areq.ar.len);
        xr_act <= 1; xr_addr <= xf_areq.ar.addr;
        xr_size <= xf_areq.ar.size;
        xr_rem <= int'(xf_areq.ar.len) + 1;
        xf_ar_n++; xf_arb += int'(xf_areq.ar.len) + 1; xf_outst++;
        if (xf_outst > 2) $fatal(1, "xfer outstanding > 2");
      end
      if (xr_act && !xr_vld) begin
        xrch <= '0;
        xrch.id <= '0; xrch.resp <= axi_pkg::RESP_OKAY;
        xrch.last <= xr_rem == 1;
        // R beat is bus-lane aligned: lane b holds the byte at
        // (xr_addr & ~7) + b, so an unaligned AR head lands in the
        // upper lanes — dma_read's keep mask depends on it
        for (int b = 0; b < 8; b++)
          xrch.data[8*b +: 8] <=
            i_mem.apm[apix(32'(((xr_addr & ~64'h7) + 64'(b) - XAB) >> 2))]
                     [8*(((xr_addr & ~64'h7) + 64'(b)) & 64'h3) +: 8];
        xr_vld <= 1;
      end
      if (xr_vld && xf_areq.r_ready) begin
        xr_vld <= 0;
        xf_r_n++;
        xr_addr <= xr_addr + (64'd1 << xr_size);
        if (xr_rem <= 1) begin xr_act <= 0; xf_outst--; end
        else xr_rem <= xr_rem - 1;
      end
      if (xf_areq.aw_valid && xf_arsp.aw_ready) begin
        if (!(xf_areq.aw.addr >= XAB && xf_areq.aw.addr < XAB + XAPB))
          $fatal(1, "xfer AW %016x outside aperture", xf_areq.aw.addr);
        if (xf_areq.aw.len != 0)
          $fatal(1, "xfer multi-beat write");
        xaw_s <= 1; xwaw <= xf_areq.aw;
        xf_aw_n++; xf_outst++;
        if (xf_outst > 2) $fatal(1, "xfer outstanding > 2");
      end
      if (xf_areq.w_valid && xf_arsp.w_ready) begin
        if (!xf_areq.w.last) $fatal(1, "xfer write w/o last");
        xw_s <= 1; xww <= xf_areq.w;
        xf_w_n++;
      end
      if (xaw_s && xw_s && !xb_vld) begin
        // dma_write strb marks absolute lanes of aw.addr & ~7
        for (int b = 0; b < 8; b++)
          if (xww.strb[b])
            i_mem.apm[apix(32'(((xwaw.addr & ~64'h7) + 64'(b) - XAB) >> 2))]
                     [8*(((xwaw.addr & ~64'h7) + 64'(b)) & 64'h3) +: 8]
              <= xww.data[8*b +: 8];
        xb_vld <= 1;
      end
      if (xb_vld && xf_areq.b_ready) begin
        xb_vld <= 0; xaw_s <= 0; xw_s <= 0;
        xf_b_n++; xf_outst--;
        if (xlog && xf_b_n < 200)
          $display("XW cyc=%0d aw=%016x data=%016x strb=%02x",
                   cycles, xwaw.addr, xww.data, xww.strb);
      end
    end
  end

  // Enable=0 fixture: all outputs must stay quiet
  logic            o_chr, o_wv, o_dn, o_bsy, o_cpl, o_fp,
                   o_dotr, o_dotcv, o_mf, o_xbusy;
  g6lc_apu_bus_pkg::apu_dma_axi_req_t  o_xareq;
  logic [2:0]      o_mpv;
  apu_mp_req_t [2:0] o_mpreq;
  logic [31:0]     o_cplen;
  logic [63:0]     o_fid2;
  logic [7:0]      o_fring;
  apu_cmdexec_work_t o_wo;
  logic [Rings-1:0]       o_ra;
  logic [Rings-1:0][31:0] o_rs, o_rh;
  logic [Rings-1:0][APU_VG_AP_WORD_W-1:0] o_re;
  logic [15:0]     o_liv;
  apu_objtab_cpl_t o_dotcpl;
  apu_mp_rsp_t [2:0] mp_rsp0 = '{default: '0};
  apu_vg_desc_t [APU_VG_MAX_DESC-1:0] d_empty = '{default: '0};

  g6lc_apu_vgtop #(.Enable(1'b0), .Rings(Rings)) i_off (
    .clk_i(clk), .rst_ni(rst_ni), .testmode_i(1'b0),
    .chain_valid_i(1'b0), .chain_ready_o(o_chr),
    .chain_id_i('0), .chain_n_i('0), .chain_desc_i(d_empty),
    .cpl_valid_o(o_cpl), .cpl_ready_i(1'b0),
    .cpl_len_o(o_cplen), .mem_fault_o(o_mf),
    .mp_req_valid_o(o_mpv), .mp_req_ready_i(3'b000),
    .mp_req_o(o_mpreq),
    .mp_rsp_valid_i(3'b000), .mp_rsp_i(mp_rsp0),
    .work_valid_o(o_wv), .work_ready_i(1'b0), .work_o(o_wo),
    .work_done_i(1'b0), .work_done_pl_i('0),
    .done_o(o_dn), .busy_o(o_bsy),
    .fence_pulse_o(o_fp), .fence_id_o(o_fid2), .fence_ring_o(o_fring),
    .ring_active_o(o_ra), .ring_status_o(o_rs), .ring_head_o(o_rh),
    .ring_extra_w_o(o_re), .objtab_live_o(o_liv),
    .dbg_ot_valid_i(1'b0), .dbg_ot_ready_o(o_dotr),
    .dbg_ot_req_i(dot_req),
    .dbg_ot_cpl_valid_o(o_dotcv), .dbg_ot_cpl_ready_i(1'b0),
    .dbg_ot_cpl_o(o_dotcpl),
    .xf_axi_req_o(o_xareq),
    .xf_axi_rsp_i(g6lc_apu_bus_pkg::apu_dma_axi_resp_t'('0)),
    .ap_base_i('0), .xf_flush_i(1'b0), .xfer_busy_o(o_xbusy));

  // ---- tape / expected stores (the guest RAM + aperture live in the
  // mp model i_mem; this TB pokes i_mem.gmem / i_mem.apm directly) ----
  logic [31:0] tape [TAPEW];
  logic [31:0] expm [EXPW];

  // ---- work port: accept after 2 cycles, done pulse 3 later ----------------
  int unsigned w_delay = 0;
  logic      w_vq = 0;
  always @(posedge clk or negedge rst_ni) begin
    if (!rst_ni) begin
      w_delay <= 0; w_vq <= 0; w_done <= 0;
    end else begin
      w_done <= 0;
      if (w_v && w_r) begin
        w_vq <= 1'b1;
        w_delay <= 3;
      end else if (w_vq && w_delay != 0) begin
        w_delay <= w_delay - 1;
        if (w_delay == 1) begin
          w_done <= 1'b1;
          w_vq <= 0;
        end
      end
    end
  end
  assign w_r = !w_vq;

  // fence observability: NBA-only writes (no mixed blocking/
  // nonblocking on the same variable in the TB)
  int unsigned f_count = 0;
  logic [63:0] f_seen_id;
  logic [7:0]  f_seen_ring;
  always @(posedge clk or negedge rst_ni)
    if (!rst_ni) begin
      f_count <= 0; f_seen_id <= '0; f_seen_ring <= '0;
    end else if (f_pulse) begin
      f_count <= f_count + 1;
      f_seen_id <= f_id; f_seen_ring <= f_ring;
    end

  always #5 clk = ~clk;
  always @(posedge clk) cycles++;
  always @(negedge clk) begin
    if (o_wv || o_dn || o_bsy || o_cpl || o_fp || o_dotcv || o_chr ||
        o_mf || o_xbusy ||
        (|o_mpv) || (|o_mpreq) || (|o_cplen) ||
        (|o_fid2) || (|o_fring) || (|o_ra) || (|o_rs) || (|o_rh) ||
        (|o_re) || o_liv !== '0 || o_xareq !== '0)
      $fatal(1, "disabled vgtop active");
    if (cycles > MAXCYC) $fatal(1, "watchdog");
  end

  // ---- helpers ------------------------------------------------------------
  int unsigned tp, ep;            // tape / exp cursors
  int unsigned pub_id = 0;        // avail ids / used-elem slots
  int unsigned fc0;               // fence-pulse count at chain submit
  logic [31:0] cpl_snap;          // cpl_len_o at the completion pulse

  // §7a Gate-2 float compare (same rule as tb_g6lc_apu_shwave):
  // sign-aware ULP distance; ±0 equal; NaN==NaN.
  function automatic int unsigned ulpd(input logic [31:0] a,
                                       input logic [31:0] b);
    logic [31:0] d;
    begin
      if (a === b) return 0;
      if ((a & 32'h7FFF_FFFF) == 0 && (b & 32'h7FFF_FFFF) == 0)
        return 0;
      if (a[30:23] == 8'hFF && a[22:0] != 0 &&
          b[30:23] == 8'hFF && b[22:0] != 0)
        return 0;
      if (a[31] != b[31]) return 32'h7FFF_FFFF;
      d = (a > b) ? a - b : b - a;
      return int'(d);
    end
  endfunction

  int unsigned g1_n = 0, g1_bad = 0, g2_n = 0;
  int unsigned ulp1 = 0, ulp2 = 0, maxulp = 0;

  task automatic check(input bit ok, input string msg);
    checks++;
    if (!ok) begin
      errors++;
      $display("FAIL %s (t=%0d)", msg, cycles);
      if (errors > 40) $fatal(1, "too many errors");
    end
  endtask

  function automatic logic [31:0] nexp();
    nexp = expm[ep];
    ep++;
  endfunction

  function automatic logic [31:0] ntap();
    ntap = tape[tp];
    tp++;
  endfunction

  // consume an exp record kind, returns its kind word (or 0 on sentinel)
  function automatic int rec_kind();
    if (ep + 1 < EXPW && expm[ep] == 32'hFFFFFFFF &&
        expm[ep + 1] == 32'hFFFFFFFF)
      return 0;
    return expm[ep];
  endfunction

  task automatic do_chain();
    int unsigned nd, a0, a1;
    int unsigned flags, flo, fhi, cx, ridx;
    logic [63:0] raddr;
    int unsigned rwords;
    int unsigned wr0;
    int unsigned dl, dw;
    begin
      nd = ntap();
      raddr = '0; rwords = 0;
      for (int i = 0; i < APU_VG_MAX_DESC; i++) ch_d[i] = '0;
      for (int i = 0; i < nd; i++) begin
        a0 = ntap(); a1 = ntap();
        dl = ntap(); dw = ntap();
        ch_d[i].addr = {32'(a1), 32'(a0)};
        ch_d[i].len = 32'(dl);
        ch_d[i].write = dw != 0;
        if (dw != 0) begin
          raddr = {32'(a1), 32'(a0)};
          rwords = dl;
        end
      end
      flags = ntap(); flo = ntap(); fhi = ntap();
      cx = ntap(); ridx = ntap();
      ch_n = nd[3:0];
      ch_id = pub_id[15:0];
      fc0 = f_count;
      // wait for the previous chain to finish completely (done is a
      // pulse; a FENCE response spends an extra cycle in StFence)
      begin
        int unsigned t = 0;
        while (!ch_r && t < 20_000_000) begin @(posedge clk); t++; end
        check(ch_r, "vgctl not idle before chain");
      end
      // accept = chain_ready_o drops (vgctl latched the chain and
      // left StIdle); hold valid until then
      ch_v = 1;
      begin
        int unsigned t = 0;
        @(posedge clk);
        while (ch_r && t < 1000) begin @(posedge clk); t++; end
        check(!ch_r, "chain not accepted");
      end
      ch_v = 0;
      // wait for the completion pulse (cpl_valid_o = done_o) with
      // timeout; the pulse is one cycle so sample mid-cycle at negedge
      begin : wait_cpl
        int unsigned tmo = 0;
        while (!cpl_v && tmo < 20_000_000) begin
          @(negedge clk); tmo++;
        end
        check(cpl_v, "chain completion timeout");
        cpl_snap = cpl_len;
        @(posedge clk);
        @(negedge clk);    // settle
      end
      // EK_RESP {kind, used_len, resp_type, nbody, 0,0,0,0}
      check(rec_kind() == 1, "EK_RESP kind");
      begin
        int unsigned e_used, e_type, e_nbody;
          ep++;                              // kind word
          e_used  = nexp();
          e_type  = nexp();
          e_nbody = nexp();
          ep += 4;                           // pad
          // response header word0 = type, written to the WRITE desc
          check(i_mem.gmem[raddr[31:0] >> 2] == e_type,
                $sformatf("resp type got=%08x exp=%08x",
                          i_mem.gmem[raddr[31:0] >> 2], e_type));
          // response body words at raddr+24
          for (int i = 0; i < e_nbody; i++) begin
            check(rec_kind() == 2, "EK_BODY kind");
            check(i_mem.gmem[(raddr[31:0] >> 2) + 6 + i] == expm[ep + 1],
                  $sformatf("resp body[%0d] got=%08x exp=%08x", i,
                            i_mem.gmem[(raddr[31:0] >> 2) + 6 + i],
                            expm[ep + 1]));
            ep += 8;
          end
        // completion length the walker would publish as used.len
        check(cpl_snap == 32'(e_used),
              $sformatf("cpl_len got=%08x exp=%08x", cpl_snap, e_used));
        begin : idle_wait
          // the mp poll loop keeps the pump busy for a bounded backlog;
          // with mp latency jitter this takes longer than the old
          // 1-cycle port did — wait generously rather than one cycle
          int unsigned iw;
          iw = 0;
          while (vg_busy && iw < 100000) @(posedge clk) iw++;
        end
        check(!vg_busy, "vgtop idle after completion");
        // fence record if requested: {8, flo, fhi, ring_idx}
        if ((flags & 1) != 0) begin
          int unsigned t = 0;
          check(rec_kind() == 8, "EK_FENCE kind");
          check(expm[ep + 1] == flo && expm[ep + 2] == fhi &&
                expm[ep + 3] == ridx, "EK_FENCE words");
          // the pulse fires in StFence, one cycle after done_o
          while (f_count == fc0 && t < 1000) begin
            @(posedge clk); t++;
          end
          check(f_count == fc0 + 1 &&
                f_seen_id == {32'(fhi), 32'(flo)} &&
                f_seen_ring == 8'(ridx), "fence pulse seen");
          ep += 8;
        end
      end
      pub_id++;
      cases++;
    end
  endtask

  // -------------------------------------------------------------------------
  initial begin
    string vname = "ue_sm5_transport";
    if ($value$plusargs("vec=%s", vname))
      $display("compute-session tape: %s", vname);
    $readmemh({"vn_vectors/", vname, ".hex"}, tape, 0);
    $readmemh({"vn_vectors/", vname, ".exp"}, expm, 0);
    tp = 0; ep = 0;
    repeat (8) @(posedge clk);
    rst_ni = 1;
    repeat (4) @(posedge clk);

    while (1) begin
      int unsigned op = ntap();
      if (op == 0) break;
      case (op)
        1: begin // TP_MEMW
          int unsigned n = ntap();
          int unsigned al = ntap(), ah = ntap();
          for (int i = 0; i < n; i++)
            i_mem.gmem[((al >> 2) + i) % GMW] = ntap();
        end
        2: do_chain();
        3: begin // TP_APW
          int unsigned n = ntap();
          int unsigned al = ntap(), ah = ntap();
          for (int i = 0; i < n; i++)
            i_mem.apm[apix(((al >> 2) + i))] = ntap();
        end
        4: begin // TP_WAIT_HEAD [ring][ap_addr][exp][tmo]
          int unsigned rg = ntap(), ad = ntap(),
                       eh = ntap(), tmo = ntap();
          int unsigned t = 0;
          while (i_mem.apm[apix((ad >> 2))] != eh && t < tmo) begin
            @(posedge clk); t++;
          end
          if (i_mem.apm[apix((ad >> 2))] != eh)
            $display("DBG WAIT_HEAD ring%0d: ap_head=%08x r_head=%08x r_status=%08x",
                     rg, i_mem.apm[apix((ad >> 2))], r_head[rg],
                     r_status[rg]);
          check(i_mem.apm[apix((ad >> 2))] == eh,
                $sformatf("WAIT_HEAD ring%0d ap got=%08x exp=%08x",
                          rg, i_mem.apm[apix((ad >> 2))], eh));
          check(rec_kind() == 3, "EK_HEAD kind");
          check(expm[ep + 1] == rg && expm[ep + 2] == eh,
                "EK_HEAD words");
          check(r_head[rg] == eh,
                $sformatf("ring_head_o got=%08x exp=%08x",
                          r_head[rg], eh));
          ep += 8;
        end
        5: begin // TP_WAIT_IDLE [ring][ap_addr][mask][want][tmo]
          int unsigned rg = ntap(), ad = ntap(), mask = ntap(),
                       want = ntap(), tmo = ntap();
          int unsigned t = 0;
          while (((i_mem.apm[apix((ad >> 2))] & mask) != want) && t < tmo) begin
            @(posedge clk); t++;
          end
          check((i_mem.apm[apix((ad >> 2))] & mask) == want,
                $sformatf("WAIT_IDLE ring%0d status=%08x mask=%0d want=%0d",
                          rg, i_mem.apm[apix((ad >> 2))], mask, want));
          check(rec_kind() == 4, "EK_STATUS kind");
          check(r_status[rg] == expm[ep + 2],
                $sformatf("ring_status_o got=%08x exp=%08x",
                          r_status[rg], expm[ep + 2]));
          check(i_mem.apm[apix((ad >> 2))] == expm[ep + 2],
                "aperture status == exp");
          ep += 8;
        end
        6: begin // TP_CHECK
          int unsigned what = ntap(), a0 = ntap(), a1 = ntap();
          case (what)
            0: begin // CK_HEAD
              check(rec_kind() == 3, "EK_HEAD kind");
              check(r_head[a0] == expm[ep + 2],
                    $sformatf("CK_HEAD ring%0d got=%08x exp=%08x",
                              a0, r_head[a0], expm[ep + 2]));
              ep += 8;
            end
            1: begin // CK_STATUS
              check(rec_kind() == 4, "EK_STATUS kind");
              check(r_status[a0] == expm[ep + 2],
                    $sformatf("CK_STATUS ring%0d got=%08x exp=%08x",
                              a0, r_status[a0], expm[ep + 2]));
              ep += 8;
            end
            2: begin // CK_REPLY [nwords][ap byte off]
              int unsigned bad = 0;
              for (int i = 0; i < a0; i++) begin
                check(rec_kind() == 5, "EK_REPLY kind");
                if (i_mem.apm[apix((a1 >> 2) + expm[ep + 1])] !=
                    expm[ep + 2]) bad++;
                check(i_mem.apm[apix((a1 >> 2) + expm[ep + 1])] ==
                      expm[ep + 2],
                      $sformatf("CK_REPLY off=%0x idx=%0d got=%08x exp=%08x",
                                a1, expm[ep + 1],
                                i_mem.apm[apix((a1 >> 2) + expm[ep + 1])],
                                expm[ep + 2]));
                ep += 8;
              end
              if (bad != 0) begin
                $display("DBG window off=%0x n=%0d:", a1, a0);
                for (int i = 0; i < a0; i++)
                  $display("  [%0d] got=%08x", i,
                           i_mem.apm[apix(((a1 >> 2) + i))]);
              end
            end
            3: begin // CK_LIVE (+ EK_PAGES allocated aperture pages)
              check(rec_kind() == 6, "EK_LIVE kind");
              check(ot_live == 16'(expm[ep + 1]),
                    $sformatf("CK_LIVE got=%0d exp=%0d",
                              ot_live, expm[ep + 1]));
              ep += 8;
              check(rec_kind() == 11, "EK_PAGES kind");
              check(i_dut.gen_on.i_vgp.gen_on.used_q ==
                    32'(expm[ep + 1]),
                    $sformatf("CK_PAGES got=%0d exp=%0d",
                              i_dut.gen_on.i_vgp.gen_on.used_q,
                              expm[ep + 1]));
              ep += 8;
            end
            4: begin // CK_EXTRA [ring][byte off]
              check(rec_kind() == 7, "EK_EXTRA kind");
              check(i_mem.apm[apix(r_extra[a0] + (a1 >> 2))] ==
                    expm[ep + 3],
                    $sformatf("CK_EXTRA ring%0d off=%0x got=%08x exp=%08x",
                              a0, a1,
                              i_mem.apm[apix(r_extra[a0] + (a1 >> 2))],
                              expm[ep + 3]));
              ep += 8;
            end
            6: begin // CK_APR [nwords][ap byte off] — §7a gates
              // EK_APRCHK {off, model_word, oracle_word, cls}
              for (int i = 0; i < a0; i++) begin
                automatic logic [31:0] got =
                    i_mem.apm[apix(((a1 >> 2) + i))];
                automatic int unsigned u;
                check(rec_kind() == 10, "EK_APRCHK kind");
                check(expm[ep + 1] == a1 + 4 * i,
                      "EK_APRCHK offset");
                // Gate 1: bit-exact vs the spirv_model words
                g1_n++;
                if (got != expm[ep + 2]) g1_bad++;
                check(got == expm[ep + 2],
                      $sformatf("G1 off=%0x got=%08x exp=%08x",
                                a1 + 4 * i, got, expm[ep + 2]));
                // Gate 2: oracle compare — cls 0 int/bool exact,
                // cls 1 float <= 2 ULP
                g2_n++;
                if (expm[ep + 4] == 0) begin
                  check(got == expm[ep + 3],
                        $sformatf("G2i off=%0x got=%08x exp=%08x",
                                  a1 + 4 * i, got, expm[ep + 3]));
                end else begin
                  u = ulpd(got, expm[ep + 3]);
                  if (u == 1) ulp1++;
                  else if (u == 2) ulp2++;
                  if (u > maxulp && u != 32'h7FFF_FFFF) maxulp = u;
                  if (u == 32'h7FFF_FFFF) maxulp = 32'h7FFF_FFFF;
                  check(u <= 2,
                        $sformatf("G2f off=%0x got=%08x exp=%08x ulp=%0d",
                                  a1 + 4 * i, got, expm[ep + 3], u));
                end
                ep += 8;
              end
            end
            default: $fatal(1, "unknown CHECK %0d", what);
          endcase
        end
        7: begin // TP_DELAY
          int unsigned n = ntap();
          repeat (n) @(posedge clk);
        end
        default: $fatal(1, "unknown tape op %0d", op);
      endcase
    end

    // teardown: ObjTab live count and the allocated-page count are
    // checked by the last CK_LIVE; ObjPay chunks must all be freed too
    check(i_dut.gen_on.i_pay.gen_on.free_q === '0,
          "objpay chunks drained");
    if (errors == 0) begin
      if (g1_n != 0)
        $display("PASS-COMPUTE g1=%0d g2=%0d ulp1=%0d ulp2=%0d maxulp=%0d cycles=%0d",
                 g1_n, g2_n, ulp1, ulp2, maxulp, cycles);
      $display("PASS tb_g6lc_apu_vgtop cases=%0d checks=%0d cycles=%0d",
               cases, checks, cycles);
    end else
      $display("FAIL tb_g6lc_apu_vgtop cases=%0d checks=%0d errors=%0d",
               cases, checks, errors);
    $finish;
  end
endmodule
