// Copyright 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
`timescale 1ns/1ps
// Transport session test of g6lc_apu_vgtop (§6b of
// architecture/uncore/apu-vulkan-engine.md).  The TB replays the
// guest-script tape generated by
//   python corev_apu/apu/tools/vn_golden.py --transport ue_sm5_transport 1
// against the real vgtop composition (vgctl + vnpump + vnfront +
// objtab + cmdrec + cmdexec + publication FSM).
//
// Tape ops (ue_sm5_transport.hex, one 32-bit word per line):
//   0 TP_END
//   1 TP_MEMW      [n][addr_lo][addr_hi][w0..w(n-1)]  guest RAM write
//   2 TP_CHAIN     [nd][desc{alo,ahi,len,write}*nd][flags][flo][fhi]
//                  [ctx][ridx]                       submit a chain
//   3 TP_APW       [n][off_lo][off_hi][w0..]          aperture write
//   4 TP_WAIT_HEAD [ring][head_ap_addr][exp][tmo]     poll aperture
//   5 TP_WAIT_IDLE [ring][status_ap_addr][mask][want][tmo]
//   6 TP_CHECK     [what][a0][a1]                     consume exp recs
//   7 TP_DELAY     [cycles]
//
// .exp records (8 words, consumed in order, FFFFFFFF FFFFFFFF ends):
//   1 EK_RESP   {used_len, resp_type, nbody}
//   2 EK_BODY   {w0..w6}    7 body words per record
//   3 EK_HEAD   {ring, head}
//   4 EK_STATUS {ring, status}
//   5 EK_REPLY  {idx, word}
//   6 EK_LIVE   {live}
//   7 EK_EXTRA  {ring, byte_off, word}
//   8 EK_FENCE  {fence_lo, fence_hi, ring_idx}
//
// The used ring is TB-synthesized: used elems at GUSED + slot*8 and a
// single used.idx cell at GUIDX.  The TB checks every response word
// against EK_RESP/EK_BODY, the used element/idx against the expected
// used_len, publication order (response < used elem < used idx <
// ISR), ring head/status through the pump's observability ports,
// reply bytes in the aperture, and ObjTab live count after teardown.

module tb_g6lc_apu_vgtop;
  import g6lc_apu_vn_pkg::*;
  import g6lc_apu_vg_pkg::*;
  import g6lc_apu_objtab_pkg::*;
  import g6lc_apu_cmdrec_pkg::*;
  import g6lc_apu_cmdexec_pkg::*;
  import g6lc_apu_vnfront_pkg::*;

  localparam int unsigned Rings   = 4;
  localparam int unsigned GMW     = 32'h40000;   // 1 MiB guest RAM
  localparam int unsigned APW     = 32'h40000;   // 1 MiB aperture
  localparam int unsigned TAPEW   = 32'h100000;
  localparam int unsigned EXPW    = 32'h8000;
  localparam logic [63:0] GUSED   = 64'h0002_0000;
  localparam logic [63:0] GUIDX   = 64'h0002_1000;
  localparam int unsigned MAXCYC  = 300_000_000;

  logic clk = 0, rst_ni = 0;
  int errors = 0, checks = 0, cycles = 0, cases = 0;

  // ---- DUT ------------------------------------------------------------
  logic            ch_v = 0, ch_r;
  logic [15:0]     ch_id = '0;
  logic [3:0]      ch_n = '0;
  apu_vg_desc_t [APU_VG_MAX_DESC-1:0] ch_d;
  logic [63:0]     ch_uelem = '0, ch_uidx = '0;
  logic            mem_re, mem_we;
  logic [63:0]     mem_addr;
  logic [31:0]     mem_wdata, mem_rdata;
  logic            ap_re, ap_we;
  logic [17:0]     ap_raddr, ap_waddr;
  logic [31:0]     ap_wdata, ap_rdata;
  logic            w_v, w_done = 0;
  logic            w_r;
  apu_cmdexec_work_t w_o;
  // §7b/5a-ii: ShaderCore 64-bit aperture port
  logic            sh_re, sh_we;
  logic [63:0]     sh_addr, sh_wdata;
  logic [7:0]      sh_wstrb;
  logic [63:0]     sh_rdata;
  logic            d_done, irq;
  logic [31:0]     isr;
  logic            isr_ack = 0;
  logic            f_pulse;
  logic [63:0]     f_id;
  logic [7:0]      f_ring;
  logic [Rings-1:0]       r_active;
  logic [Rings-1:0][31:0] r_status, r_head;
  logic [Rings-1:0][17:0] r_extra;
  logic [15:0]     ot_live;
  // debug ObjTab (unused; tied off)
  logic            dot_r;
  apu_objtab_req_t dot_req = '0;
  logic            dot_cv;
  apu_objtab_cpl_t dot_cpl;

  g6lc_apu_vgtop #(.Enable(1'b1), .Rings(Rings)) i_dut (
    .clk_i(clk), .rst_ni(rst_ni), .testmode_i(1'b0),
    .chain_valid_i(ch_v), .chain_ready_o(ch_r),
    .chain_id_i(ch_id), .chain_n_i(ch_n), .chain_desc_i(ch_d),
    .chain_uelem_addr_i(ch_uelem), .chain_uidx_addr_i(ch_uidx),
    .mem_re_o(mem_re), .mem_we_o(mem_we),
    .mem_addr_o(mem_addr), .mem_wdata_o(mem_wdata),
    .mem_rdata_i(mem_rdata),
    .ap_re_o(ap_re), .ap_raddr_o(ap_raddr),
    .ap_we_o(ap_we), .ap_waddr_o(ap_waddr),
    .ap_wdata_o(ap_wdata), .ap_rdata_i(ap_rdata),
    .work_valid_o(w_v), .work_ready_i(w_r), .work_o(w_o),
    .work_done_i(w_done), .work_done_pl_i('0),
    .sh_mem_re_o(sh_re), .sh_mem_we_o(sh_we),
    .sh_mem_addr_o(sh_addr), .sh_mem_wdata_o(sh_wdata),
    .sh_mem_wstrb_o(sh_wstrb), .sh_mem_rdata_i(sh_rdata),
    .done_o(d_done), .irq_o(irq), .isr_o(isr), .isr_ack_i(isr_ack),
    .fence_pulse_o(f_pulse), .fence_id_o(f_id), .fence_ring_o(f_ring),
    .ring_active_o(r_active), .ring_status_o(r_status),
    .ring_head_o(r_head), .ring_extra_w_o(r_extra),
    .objtab_live_o(ot_live),
    .dbg_ot_valid_i(1'b0), .dbg_ot_ready_o(dot_r),
    .dbg_ot_req_i(dot_req),
    .dbg_ot_cpl_valid_o(dot_cv), .dbg_ot_cpl_ready_i(1'b0),
    .dbg_ot_cpl_o(dot_cpl));

  // Enable=0 fixture: all outputs must stay quiet
  logic            o_chr, o_mre, o_mwe, o_are, o_awe, o_wv, o_dn, o_iq,
                   o_fp, o_dotr, o_dotcv;
  logic            o_shre, o_shwe;
  logic [63:0]     o_shaddr, o_shwd;
  logic [7:0]      o_shws;
  logic [31:0]     o_isr;
  logic [63:0]     o_maddr, o_fid;
  logic [31:0]     o_mwd;
  logic [17:0]     o_aaddr, o_awaddr;
  logic [31:0]     o_awd;
  apu_cmdexec_work_t o_wo;
  logic [63:0]     o_fid2;
  logic [7:0]      o_fring;
  logic [Rings-1:0]       o_ra;
  logic [Rings-1:0][31:0] o_rs, o_rh;
  logic [Rings-1:0][17:0] o_re;
  logic [15:0]     o_liv;
  apu_objtab_cpl_t o_dotcpl;
  apu_vg_desc_t [APU_VG_MAX_DESC-1:0] d_empty = '{default: '0};

  g6lc_apu_vgtop #(.Enable(1'b0), .Rings(Rings)) i_off (
    .clk_i(clk), .rst_ni(rst_ni), .testmode_i(1'b0),
    .chain_valid_i(1'b0), .chain_ready_o(o_chr),
    .chain_id_i('0), .chain_n_i('0), .chain_desc_i(d_empty),
    .chain_uelem_addr_i('0), .chain_uidx_addr_i('0),
    .mem_re_o(o_mre), .mem_we_o(o_mwe), .mem_addr_o(o_maddr),
    .mem_wdata_o(o_mwd), .mem_rdata_i('0),
    .ap_re_o(o_are), .ap_raddr_o(o_aaddr),
    .ap_we_o(o_awe), .ap_waddr_o(o_awaddr),
    .ap_wdata_o(o_awd), .ap_rdata_i('0),
    .work_valid_o(o_wv), .work_ready_i(1'b0), .work_o(o_wo),
    .work_done_i(1'b0), .work_done_pl_i('0),
    .sh_mem_re_o(o_shre), .sh_mem_we_o(o_shwe),
    .sh_mem_addr_o(o_shaddr), .sh_mem_wdata_o(o_shwd),
    .sh_mem_wstrb_o(o_shws), .sh_mem_rdata_i('0),
    .done_o(o_dn), .irq_o(o_iq), .isr_o(o_isr), .isr_ack_i(1'b0),
    .fence_pulse_o(o_fp), .fence_id_o(o_fid2), .fence_ring_o(o_fring),
    .ring_active_o(o_ra), .ring_status_o(o_rs), .ring_head_o(o_rh),
    .ring_extra_w_o(o_re), .objtab_live_o(o_liv),
    .dbg_ot_valid_i(1'b0), .dbg_ot_ready_o(o_dotr),
    .dbg_ot_req_i(dot_req),
    .dbg_ot_cpl_valid_o(o_dotcv), .dbg_ot_cpl_ready_i(1'b0),
    .dbg_ot_cpl_o(o_dotcpl));

  // ---- memories ----------------------------------------------------------
  logic [31:0] gmem [GMW];
  logic [31:0] apm  [APW];
  logic [31:0] tape [TAPEW];
  logic [31:0] expm [EXPW];

  // 1-cycle guest-mem service; write log for publication order
  int unsigned wrlog_n = 0;
  logic [63:0] wrlog_a [4096];
  logic [31:0] wrlog_d [4096];
  always @(posedge clk) begin
    if (mem_re) mem_rdata <= gmem[mem_addr[31:0] >> 2];
    if (mem_we) begin
      gmem[mem_addr[31:0] >> 2] <= mem_wdata;
      if (wrlog_n < 4096) begin
        wrlog_a[wrlog_n] <= mem_addr;
        wrlog_d[wrlog_n] <= mem_wdata;
        wrlog_n <= wrlog_n + 1;
      end
    end
  end
  always @(posedge clk) begin
    if (ap_we) apm[ap_waddr] <= ap_wdata;
    if (ap_re) ap_rdata <= apm[ap_raddr];
  end

  // §7b/5a-ii: ShaderCore 64-bit aperture service — same backing
  // store as the 32-bit ap_* window (guest buffer writes must be
  // visible to the shader; unification with the ring/reply memory
  // is 3c).  Fixed 1-cycle reads, byte-strobed writes.
  always @(posedge clk) begin
    if (sh_re) begin
      for (int b = 0; b < 8; b++) begin
        automatic int unsigned a = sh_addr[20:0] + b;
        sh_rdata[b*8 +: 8] <= apm[(a >> 2) % APW][8*(a[1:0]) +: 8];
      end
    end
    if (sh_we) begin
      for (int b = 0; b < 8; b++) begin
        automatic int unsigned a = sh_addr[20:0] + b;
        if (sh_wstrb[b])
          apm[(a >> 2) % APW][8*(a[1:0]) +: 8] <= sh_wdata[b*8 +: 8];
      end
    end
  end

  // ---- work port: accept after 2 cycles, done pulse 3 later ----------------
  int unsigned w_delay = 0;
  logic      w_vq = 0;
  always @(posedge clk or negedge rst_ni) begin
    if (!rst_ni) begin
      w_delay <= 0; w_vq <= 0; w_done <= 0;
    end else begin
      w_done <= 0;
      if (w_v && w_r) begin
        w_vq <= 1'b1;
        w_delay <= 3;
      end else if (w_vq && w_delay != 0) begin
        w_delay <= w_delay - 1;
        if (w_delay == 1) begin
          w_done <= 1'b1;
          w_vq <= 0;
        end
      end
    end
  end
  assign w_r = !w_vq;

  // ISR acknowledge one cycle after the irq pulse
  always @(posedge clk or negedge rst_ni) begin
    if (!rst_ni) isr_ack <= 0;
    else         isr_ack <= irq;
  end

  // fence observability: NBA-only writes (no mixed blocking/
  // nonblocking on the same variable in the TB)
  int unsigned f_count = 0;
  logic [63:0] f_seen_id;
  logic [7:0]  f_seen_ring;
  always @(posedge clk or negedge rst_ni)
    if (!rst_ni) begin
      f_count <= 0; f_seen_id <= '0; f_seen_ring <= '0;
    end else if (f_pulse) begin
      f_count <= f_count + 1;
      f_seen_id <= f_id; f_seen_ring <= f_ring;
    end

  always #5 clk = ~clk;
  always @(posedge clk) cycles++;
  always @(negedge clk) begin
    if (o_mre || o_mwe || o_are || o_awe || o_wv || o_dn || o_iq ||
        o_fp || o_dotcv || o_chr || o_shre || o_shwe ||
        (|o_shaddr) || (|o_shwd) || (|o_shws) ||
        (|o_isr) || o_liv !== '0)
      $fatal(1, "disabled vgtop active");
    if (cycles > MAXCYC) $fatal(1, "watchdog");
  end

  // ---- helpers ------------------------------------------------------------
  int unsigned tp, ep;            // tape / exp cursors
  int unsigned pub_id = 0;        // avail ids / used-elem slots
  int unsigned fc0;               // fence-pulse count at chain submit

  // §7a Gate-2 float compare (same rule as tb_g6lc_apu_shwave):
  // sign-aware ULP distance; ±0 equal; NaN==NaN.
  function automatic int unsigned ulpd(input logic [31:0] a,
                                       input logic [31:0] b);
    logic [31:0] d;
    begin
      if (a === b) return 0;
      if ((a & 32'h7FFF_FFFF) == 0 && (b & 32'h7FFF_FFFF) == 0)
        return 0;
      if (a[30:23] == 8'hFF && a[22:0] != 0 &&
          b[30:23] == 8'hFF && b[22:0] != 0)
        return 0;
      if (a[31] != b[31]) return 32'h7FFF_FFFF;
      d = (a > b) ? a - b : b - a;
      return int'(d);
    end
  endfunction

  int unsigned g1_n = 0, g1_bad = 0, g2_n = 0;
  int unsigned ulp1 = 0, ulp2 = 0, maxulp = 0;

  task automatic check(input bit ok, input string msg);
    checks++;
    if (!ok) begin
      errors++;
      $display("FAIL %s (t=%0d)", msg, cycles);
      if (errors > 40) $fatal(1, "too many errors");
    end
  endtask

  function automatic logic [31:0] nexp();
    nexp = expm[ep];
    ep++;
  endfunction

  function automatic logic [31:0] ntap();
    ntap = tape[tp];
    tp++;
  endfunction

  // consume an exp record kind, returns its kind word (or 0 on sentinel)
  function automatic int rec_kind();
    if (ep + 1 < EXPW && expm[ep] == 32'hFFFFFFFF &&
        expm[ep + 1] == 32'hFFFFFFFF)
      return 0;
    return expm[ep];
  endfunction

  task automatic do_chain();
    int unsigned nd, a0, a1;
    int unsigned flags, flo, fhi, cx, ridx;
    logic [63:0] raddr;
    int unsigned rwords;
    int unsigned wr0;
    int unsigned dl, dw;
    begin
      nd = ntap();
      raddr = '0; rwords = 0;
      for (int i = 0; i < APU_VG_MAX_DESC; i++) ch_d[i] = '0;
      for (int i = 0; i < nd; i++) begin
        a0 = ntap(); a1 = ntap();
        dl = ntap(); dw = ntap();
        ch_d[i].addr = {32'(a1), 32'(a0)};
        ch_d[i].len = 32'(dl);
        ch_d[i].write = dw != 0;
        if (dw != 0) begin
          raddr = {32'(a1), 32'(a0)};
          rwords = dl;
        end
      end
      flags = ntap(); flo = ntap(); fhi = ntap();
      cx = ntap(); ridx = ntap();
      ch_n = nd[3:0];
      ch_id = pub_id[15:0];
      ch_uelem = GUSED + 64'(pub_id) * 64'd8;
      ch_uidx = GUIDX;
      wr0 = wrlog_n;
      fc0 = f_count;
      // wait for the previous chain to finish completely (done is a
      // pulse; a FENCE response spends an extra cycle in StFence)
      begin
        int unsigned t = 0;
        while (!ch_r && t < 20_000_000) begin @(posedge clk); t++; end
        check(ch_r, "vgctl not idle before chain");
      end
      // accept = chain_ready_o drops (vgctl latched the chain and
      // left StIdle); hold valid until then
      ch_v = 1;
      begin
        int unsigned t = 0;
        @(posedge clk);
        while (ch_r && t < 1000) begin @(posedge clk); t++; end
        check(!ch_r, "chain not accepted");
      end
      ch_v = 0;
      // wait for publication (done pulse) with timeout; done_o is a
      // one-cycle pulse so sample mid-cycle at negedge
      begin
        int unsigned tmo = 0;
        while (!d_done && tmo < 20_000_000) begin
          @(negedge clk); tmo++;
        end
        check(d_done, "chain publication done timeout");
        @(posedge clk);
        @(negedge clk);    // settle: used/ISR writes just committed
      end
      // EK_RESP {kind, used_len, resp_type, nbody, 0,0,0,0}
      check(rec_kind() == 1, "EK_RESP kind");
      begin
        int unsigned e_used, e_type, e_nbody;
        ep++;                              // kind word
        e_used  = nexp();
        e_type  = nexp();
        e_nbody = nexp();
        ep += 4;                           // pad
        // response header word0 = type, written to the WRITE desc
        check(gmem[raddr[31:0] >> 2] == e_type,
              $sformatf("resp type got=%08x exp=%08x",
                        gmem[raddr[31:0] >> 2], e_type));
        // response body words at raddr+24
        for (int i = 0; i < e_nbody; i++) begin
          check(rec_kind() == 2, "EK_BODY kind");
          check(gmem[(raddr[31:0] >> 2) + 6 + i] == expm[ep + 1],
                $sformatf("resp body[%0d] got=%08x exp=%08x", i,
                          gmem[(raddr[31:0] >> 2) + 6 + i],
                          expm[ep + 1]));
          ep += 8;
        end
        // used element {id, len} at this chain's slot + used idx
        check(gmem[(GUSED[31:0] >> 2) + pub_id * 2] == pub_id,
              $sformatf("used id got=%08x exp=%08x",
                        gmem[(GUSED[31:0] >> 2) + pub_id * 2],
                        pub_id));
        check(gmem[(GUSED[31:0] >> 2) + pub_id * 2 + 1] == e_used,
              $sformatf("used len got=%08x exp=%08x",
                        gmem[(GUSED[31:0] >> 2) + pub_id * 2 + 1],
                        e_used));
        check(gmem[GUIDX[31:0] >> 2] == pub_id,
              $sformatf("used idx got=%08x exp=%08x",
                        gmem[GUIDX[31:0] >> 2], pub_id));
        check((isr & 32'd1) != 32'h0, "ISR bit0 set");
        // order: uelem write comes after every response write, idx last
        begin
          int unsigned iu = wrlog_n, ii = wrlog_n;
          logic [63:0] uea = GUSED + 64'(pub_id) * 64'd8;
          for (int i = wr0; i < wrlog_n; i++) begin
            if (wrlog_a[i] == uea) iu = i;
            if (wrlog_a[i] == GUIDX) ii = i;
          end
          check(iu < wrlog_n, "used elem written");
          check(ii < wrlog_n, "used idx written");
          check(iu < ii, "publication order elem<idx");
          for (int i = wr0; i < wrlog_n; i++) begin
            if (wrlog_a[i] >= raddr &&
                wrlog_a[i] < raddr + 64'(rwords))
              check(i < iu, "response before used elem");
          end
        end
        // fence record if requested: {8, flo, fhi, ring_idx}
        if ((flags & 1) != 0) begin
          int unsigned t = 0;
          check(rec_kind() == 8, "EK_FENCE kind");
          check(expm[ep + 1] == flo && expm[ep + 2] == fhi &&
                expm[ep + 3] == ridx, "EK_FENCE words");
          // the pulse fires in StFence, one cycle after done_o
          while (f_count == fc0 && t < 1000) begin
            @(posedge clk); t++;
          end
          check(f_count == fc0 + 1 &&
                f_seen_id == {32'(fhi), 32'(flo)} &&
                f_seen_ring == 8'(ridx), "fence pulse seen");
          ep += 8;
        end
      end
      pub_id++;
      cases++;
    end
  endtask

  // -------------------------------------------------------------------------
  initial begin
    string vname = "ue_sm5_transport";
    if ($value$plusargs("vec=%s", vname))
      $display("compute-session tape: %s", vname);
    $readmemh({"vn_vectors/", vname, ".hex"}, tape, 0);
    $readmemh({"vn_vectors/", vname, ".exp"}, expm, 0);
    for (int i = 0; i < GMW; i++) gmem[i] = '0;
    for (int i = 0; i < APW; i++) apm[i] = '0;
    tp = 0; ep = 0;
    repeat (8) @(posedge clk);
    rst_ni = 1;
    repeat (4) @(posedge clk);

    while (1) begin
      int unsigned op = ntap();
      if (op == 0) break;
      case (op)
        1: begin // TP_MEMW
          int unsigned n = ntap();
          int unsigned al = ntap(), ah = ntap();
          for (int i = 0; i < n; i++)
            gmem[((al >> 2) + i) % GMW] = ntap();
        end
        2: do_chain();
        3: begin // TP_APW
          int unsigned n = ntap();
          int unsigned al = ntap(), ah = ntap();
          for (int i = 0; i < n; i++)
            apm[((al >> 2) + i) % APW] = ntap();
        end
        4: begin // TP_WAIT_HEAD [ring][ap_addr][exp][tmo]
          int unsigned rg = ntap(), ad = ntap(),
                       eh = ntap(), tmo = ntap();
          int unsigned t = 0;
          while (apm[(ad >> 2) % APW] != eh && t < tmo) begin
            @(posedge clk); t++;
          end
          if (apm[(ad >> 2) % APW] != eh)
            $display("DBG WAIT_HEAD ring%0d: ap_head=%08x r_head=%08x r_status=%08x",
                     rg, apm[(ad >> 2) % APW], r_head[rg],
                     r_status[rg]);
          check(apm[(ad >> 2) % APW] == eh,
                $sformatf("WAIT_HEAD ring%0d ap got=%08x exp=%08x",
                          rg, apm[(ad >> 2) % APW], eh));
          check(rec_kind() == 3, "EK_HEAD kind");
          check(expm[ep + 1] == rg && expm[ep + 2] == eh,
                "EK_HEAD words");
          check(r_head[rg] == eh,
                $sformatf("ring_head_o got=%08x exp=%08x",
                          r_head[rg], eh));
          ep += 8;
        end
        5: begin // TP_WAIT_IDLE [ring][ap_addr][mask][want][tmo]
          int unsigned rg = ntap(), ad = ntap(), mask = ntap(),
                       want = ntap(), tmo = ntap();
          int unsigned t = 0;
          while (((apm[(ad >> 2) % APW] & mask) != want) && t < tmo) begin
            @(posedge clk); t++;
          end
          check((apm[(ad >> 2) % APW] & mask) == want,
                $sformatf("WAIT_IDLE ring%0d status=%08x mask=%0d want=%0d",
                          rg, apm[(ad >> 2) % APW], mask, want));
          check(rec_kind() == 4, "EK_STATUS kind");
          check(r_status[rg] == expm[ep + 2],
                $sformatf("ring_status_o got=%08x exp=%08x",
                          r_status[rg], expm[ep + 2]));
          check(apm[(ad >> 2) % APW] == expm[ep + 2],
                "aperture status == exp");
          ep += 8;
        end
        6: begin // TP_CHECK
          int unsigned what = ntap(), a0 = ntap(), a1 = ntap();
          case (what)
            0: begin // CK_HEAD
              check(rec_kind() == 3, "EK_HEAD kind");
              check(r_head[a0] == expm[ep + 2],
                    $sformatf("CK_HEAD ring%0d got=%08x exp=%08x",
                              a0, r_head[a0], expm[ep + 2]));
              ep += 8;
            end
            1: begin // CK_STATUS
              check(rec_kind() == 4, "EK_STATUS kind");
              check(r_status[a0] == expm[ep + 2],
                    $sformatf("CK_STATUS ring%0d got=%08x exp=%08x",
                              a0, r_status[a0], expm[ep + 2]));
              ep += 8;
            end
            2: begin // CK_REPLY [nwords][ap byte off]
              int unsigned bad = 0;
              for (int i = 0; i < a0; i++) begin
                check(rec_kind() == 5, "EK_REPLY kind");
                if (apm[((a1 >> 2) + expm[ep + 1]) % APW] !=
                    expm[ep + 2]) bad++;
                check(apm[((a1 >> 2) + expm[ep + 1]) % APW] ==
                      expm[ep + 2],
                      $sformatf("CK_REPLY off=%0x idx=%0d got=%08x exp=%08x",
                                a1, expm[ep + 1],
                                apm[((a1 >> 2) + expm[ep + 1]) % APW],
                                expm[ep + 2]));
                ep += 8;
              end
              if (bad != 0) begin
                $display("DBG window off=%0x n=%0d:", a1, a0);
                for (int i = 0; i < a0; i++)
                  $display("  [%0d] got=%08x", i,
                           apm[((a1 >> 2) + i) % APW]);
              end
            end
            3: begin // CK_LIVE (+ EK_PAGES allocated aperture pages)
              check(rec_kind() == 6, "EK_LIVE kind");
              check(ot_live == 16'(expm[ep + 1]),
                    $sformatf("CK_LIVE got=%0d exp=%0d",
                              ot_live, expm[ep + 1]));
              ep += 8;
              check(rec_kind() == 11, "EK_PAGES kind");
              check($countones(i_dut.gen_on.i_vgp.gen_on.free_q) ==
                    int'(expm[ep + 1]),
                    $sformatf("CK_PAGES got=%0d exp=%0d",
                              $countones(
                                  i_dut.gen_on.i_vgp.gen_on.free_q),
                              expm[ep + 1]));
              ep += 8;
            end
            4: begin // CK_EXTRA [ring][byte off]
              check(rec_kind() == 7, "EK_EXTRA kind");
              check(apm[(r_extra[a0] + (a1 >> 2)) % APW] ==
                    expm[ep + 3],
                    $sformatf("CK_EXTRA ring%0d off=%0x got=%08x exp=%08x",
                              a0, a1,
                              apm[(r_extra[a0] + (a1 >> 2)) % APW],
                              expm[ep + 3]));
              ep += 8;
            end
            6: begin // CK_APR [nwords][ap byte off] — §7a gates
              // EK_APRCHK {off, model_word, oracle_word, cls}
              for (int i = 0; i < a0; i++) begin
                automatic logic [31:0] got =
                    apm[((a1 >> 2) + i) % APW];
                automatic int unsigned u;
                check(rec_kind() == 10, "EK_APRCHK kind");
                check(expm[ep + 1] == a1 + 4 * i,
                      "EK_APRCHK offset");
                // Gate 1: bit-exact vs the spirv_model words
                g1_n++;
                if (got != expm[ep + 2]) g1_bad++;
                check(got == expm[ep + 2],
                      $sformatf("G1 off=%0x got=%08x exp=%08x",
                                a1 + 4 * i, got, expm[ep + 2]));
                // Gate 2: oracle compare — cls 0 int/bool exact,
                // cls 1 float <= 2 ULP
                g2_n++;
                if (expm[ep + 4] == 0) begin
                  check(got == expm[ep + 3],
                        $sformatf("G2i off=%0x got=%08x exp=%08x",
                                  a1 + 4 * i, got, expm[ep + 3]));
                end else begin
                  u = ulpd(got, expm[ep + 3]);
                  if (u == 1) ulp1++;
                  else if (u == 2) ulp2++;
                  if (u > maxulp && u != 32'h7FFF_FFFF) maxulp = u;
                  if (u == 32'h7FFF_FFFF) maxulp = 32'h7FFF_FFFF;
                  check(u <= 2,
                        $sformatf("G2f off=%0x got=%08x exp=%08x ulp=%0d",
                                  a1 + 4 * i, got, expm[ep + 3], u));
                end
                ep += 8;
              end
            end
            default: $fatal(1, "unknown CHECK %0d", what);
          endcase
        end
        7: begin // TP_DELAY
          int unsigned n = ntap();
          repeat (n) @(posedge clk);
        end
        default: $fatal(1, "unknown tape op %0d", op);
      endcase
    end

    // teardown: ObjTab live count and the allocated-page count are
    // checked by the last CK_LIVE; ObjPay chunks must all be freed too
    check(i_dut.gen_on.i_pay.gen_on.free_q === '0,
          "objpay chunks drained");
    if (errors == 0) begin
      if (g1_n != 0)
        $display("PASS-COMPUTE g1=%0d g2=%0d ulp1=%0d ulp2=%0d maxulp=%0d cycles=%0d",
                 g1_n, g2_n, ulp1, ulp2, maxulp, cycles);
      $display("PASS tb_g6lc_apu_vgtop cases=%0d checks=%0d cycles=%0d",
               cases, checks, cycles);
    end else
      $display("FAIL tb_g6lc_apu_vgtop cases=%0d checks=%0d errors=%0d",
               cases, checks, errors);
    $finish;
  end
endmodule
