// Copyright 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
`timescale 1ns/1ps
// Session-level integration test of g6lc_apu_vnfront (§4c/§6 of
// architecture/uncore/apu-vulkan-engine.md).  The front is wired to the
// real g6lc_apu_objtab, g6lc_apu_cmdrec and g6lc_apu_cmdexec; the
// front's and the executor's backend ports share each engine through a
// small two-master arbiter (plus a third, TB-owned objtab master used
// for the final RESET_CTX emptiness check).  The command stream and the
// expected record are generated by
//   python corev_apu/apu/tools/vn_golden.py --session ue_sm5_session 1
//
// Layouts:
//   cs[]        : ue_sm5_session.hex (all command streams concatenated,
//                 '%%08X' words; // name lines are $readmemh comments)
//   exp[]       : ue_sm5_session.exp, RECW=386 words per command:
//     +0  cs_base        +1  cs_len
//     +2  command type   +3  flags  bit0 reply  bit1 record
//                                   bit2 work   bit3 reset-first
//                                   bit4 gate work port
//     +4  result         +5  reply words
//     +6  live count     +7  fault
//     +8..23  expected appended record (16 words, word i=[32*i +:32])
//     +24 n_work         +25..32 work ctypes
//     +33 n_rep          +34..385 reply words
//   sentinel    : FFFFFFFF FFFFFFFF
//
// The work port is modelled with a few-cycle accept + deferred
// work_done_i.  flags bit4 holds work_ready_i low so the executor
// keeps its command-buffer pins: that makes the pinned-destroy
// negative arm deterministic (the pin lands before the first work
// record is presented; the arm's vkFreeCommandBuffers probes RETIRE
// while the pin is held).  flags bit3 marks the first command of each
// negative arm: the TB resets the whole stack there, matching the
// model's per-arm reset.
//   pay[]       : ue_sm5_session.pay -- ObjPay/cmdrec-arena write
//                 checkpoints, checked after the indexed command:
//                   tag 1 {tag, rec, n, (addr, word)*n}      ObjPay
//                   tag 2 {tag, rec, cbuf, n, (idx, word)*n} arena
//                 sentinel FFFFFFFF.  ObjPay contents are read back
//                 through the TB's peek of the engine's payload SRAM.
// +ses=<name> selects a different session file set (used by the
// ObjPay-FULL arm built with -GObjPayWords=512).
module tb_g6lc_apu_vnfront;
  import g6lc_apu_vn_pkg::*;
  import g6lc_apu_cmdrec_pkg::*;
  import g6lc_apu_objtab_pkg::*;
  import g6lc_apu_objpay_pkg::*;
  import g6lc_apu_cmdexec_pkg::*;

  parameter int unsigned ObjPayWords = 16384;

  localparam int RECW  = 386;
  localparam int EXPW  = 386 * 256;
  localparam int PAYW  = 16384;
  localparam int PayPerBuf = 256;
  localparam int Fences = 16;
  localparam int Slots  = 256;
  localparam logic [15:0] REP_BASE = 16'h0800;
  localparam logic [15:0] REP_LEN  = 16'd352;

  logic clk = 0, rst_ni = 0;
  int errors = 0, checks = 0, cycles = 0, cases = 0;

  // ---- front ----------------------------------------------------------
  logic               f_start = 0, f_busy, f_done;
  logic [15:0]        f_base = '0, f_len = '0;
  logic               cs_re;
  logic [15:0]        cs_addr;
  logic [31:0]        cs_rdata = '0;
  logic               rep_we;
  logic [15:0]        rep_addr;
  logic [31:0]        rep_wdata;
  logic [31:0]        f_result;
  logic [15:0]        f_rwords;
  logic [3:0]         f_fault;
  // front backend ports
  logic               fot_v, fot_r, fot_cv;
  apu_objtab_req_t    fot_req;
  logic               fcr_v, fcr_r, fcr_cv;
  apu_cmdrec_req_t    fcr_req;
  logic               fsub_v, fsub_r;
  apu_cmdexec_submit_t fsub;
  logic [15:0]        f_dseq;
  logic [Fences-1:0]  f_fsig, f_flost, f_fclr;
  // payload stream (front -> cmdrec) + objpay port
  logic               fpay_v, fpay_r;
  logic [31:0]        fpay_d;
  logic               fop_v, fop_r, fop_cv;
  apu_objpay_req_t    fop_req;
  apu_objpay_cpl_t    fop_cpl;
  // Enable=0 fixture
  logic               o_csre, o_repwe, o_otv, o_crcv, o_subv, o_busy,
                      o_done;
  logic [15:0]        o_addr, o_raddr, o_rwords;
  logic [31:0]        o_wdata, o_result;
  logic [3:0]         o_fault;
  apu_objtab_req_t    o_otreq;
  apu_cmdrec_req_t    o_crreq;
  apu_cmdexec_submit_t o_sub;
  logic [Fences-1:0]  o_fclr;
  logic               o_payv, o_opv;
  logic [31:0]        o_payd;
  apu_objpay_req_t    o_opreq;

  g6lc_apu_vnfront #(.Enable(1'b1), .Fences(Fences), .CbBufs(16))
  i_front (
    .clk_i(clk), .rst_ni(rst_ni), .testmode_i(1'b0),
    .start_i(f_start), .cs_base_i(f_base), .cs_len_i(f_len),
    .rep_base_i(REP_BASE), .rep_len_i(REP_LEN), .ctx_i(8'h0),
    .cs_re_o(cs_re), .cs_addr_o(cs_addr), .cs_rdata_i(cs_rdata),
    .rep_we_o(rep_we), .rep_addr_o(rep_addr), .rep_wdata_o(rep_wdata),
    .ot_req_valid_o(fot_v), .ot_req_ready_i(fot_r), .ot_req_o(fot_req),
    .ot_cpl_valid_i(fot_cv), .ot_cpl_ready_o(),
    .ot_cpl_i(ot_cpl),
    .cr_req_valid_o(fcr_v), .cr_req_ready_i(fcr_r), .cr_req_o(fcr_req),
    .cr_cpl_valid_i(fcr_cv), .cr_cpl_ready_o(),
    .cr_cpl_i(cr_cpl),
    .cr_pay_valid_o(fpay_v), .cr_pay_data_o(fpay_d),
    .cr_pay_ready_i(fpay_r),
    .op_req_valid_o(fop_v), .op_req_ready_i(fop_r),
    .op_req_o(fop_req),
    .op_cpl_valid_i(fop_cv), .op_cpl_ready_o(),
    .op_cpl_i(fop_cpl),
    .ex_submit_valid_o(fsub_v), .ex_submit_ready_i(fsub_r),
    .ex_submit_o(fsub),
    .ex_done_seq_i(f_dseq), .ex_fence_signaled_i(f_fsig),
    .ex_fence_lost_i(f_flost), .ex_fence_clr_o(f_fclr),
    .busy_o(f_busy), .done_o(f_done), .result_o(f_result),
    .rep_words_o(f_rwords), .fault_o(f_fault));

  g6lc_apu_vnfront_fixture #(.Enable(1'b0), .Fences(Fences))
  i_off (
    .clk_i(clk), .rst_ni(rst_ni), .testmode_i(1'b0),
    .start_i(f_start), .cs_base_i(f_base), .cs_len_i(f_len),
    .rep_base_i(REP_BASE), .rep_len_i(REP_LEN), .ctx_i(8'h0),
    .cs_re_o(o_csre), .cs_addr_o(o_addr), .cs_rdata_i(cs_rdata),
    .rep_we_o(o_repwe), .rep_addr_o(o_raddr), .rep_wdata_o(o_wdata),
    .ot_req_valid_o(o_otv), .ot_req_ready_i(1'b0), .ot_req_o(o_otreq),
    .ot_cpl_valid_i(1'b0), .ot_cpl_ready_o(), .ot_cpl_i(ot_cpl),
    .cr_req_valid_o(o_crcv), .cr_req_ready_i(1'b0), .cr_req_o(o_crreq),
    .cr_cpl_valid_i(1'b0), .cr_cpl_ready_o(), .cr_cpl_i(cr_cpl),
    .cr_pay_valid_o(o_payv), .cr_pay_data_o(o_payd),
    .cr_pay_ready_i(1'b0),
    .op_req_valid_o(o_opv), .op_req_ready_i(1'b0),
    .op_req_o(o_opreq),
    .op_cpl_valid_i(1'b0), .op_cpl_ready_o(), .op_cpl_i('0),
    .ex_submit_valid_o(o_subv), .ex_submit_ready_i(1'b0),
    .ex_submit_o(o_sub),
    .ex_done_seq_i('0), .ex_fence_signaled_i('0), .ex_fence_lost_i('0),
    .ex_fence_clr_o(o_fclr),
    .busy_o(o_busy), .done_o(o_done), .result_o(o_result),
    .rep_words_o(o_rwords), .fault_o(o_fault));

  // ---- executor --------------------------------------------------------
  logic               xot_v, xot_r, xot_cv;
  apu_objtab_req_t    xot_req;
  logic               xcr_v, xcr_r, xcr_cv;
  apu_cmdrec_req_t    xcr_req;
  logic               w_v, w_r;
  apu_cmdexec_work_t  w_o;
  logic               w_done = 1'b0;

  g6lc_apu_cmdexec #(.Enable(1'b1), .Fences(Fences)) i_exec (
    .clk_i(clk), .rst_ni(rst_ni), .testmode_i(1'b0),
    .submit_valid_i(fsub_v), .submit_ready_o(fsub_r), .submit_i(fsub),
    .cr_req_valid_o(xcr_v), .cr_req_ready_i(xcr_r), .cr_req_o(xcr_req),
    .cr_cpl_valid_i(xcr_cv), .cr_cpl_ready_o(), .cr_cpl_i(cr_cpl),
    .ot_req_valid_o(xot_v), .ot_req_ready_i(xot_r), .ot_req_o(xot_req),
    .ot_cpl_valid_i(xot_cv), .ot_cpl_ready_o(), .ot_cpl_i(ot_cpl),
    .work_valid_o(w_v), .work_ready_i(w_r), .work_o(w_o),
    .work_done_i(w_done),
    .done_seq_o(f_dseq),
    .fence_signaled_o(f_fsig), .fence_lost_o(f_flost),
    .fence_clr_i(f_fclr));

  // ---- shared backends with 3-master arbitration -----------------------
  // objtab: 0=front, 1=exec, 2=tb(final RESET_CTX)
  logic               tb_ot = 1'b0, tot_v = 1'b0, tot_r, tot_cv;
  apu_objtab_req_t    tot_req;
  logic               ot_vld, ot_rdy, ot_cvld;
  apu_objtab_req_t    ot_req;
  apu_objtab_cpl_t    ot_cpl;
  logic               ot_busy = 1'b0;
  logic [1:0]         ot_own = '0;

  wire   ot_take = ot_vld && ot_rdy;
  wire   [1:0] ot_sel = ot_busy ? ot_own
                       : (tb_ot ? 2'd2
                          : (fot_v ? 2'd0
                             : (xot_v ? 2'd1 : 2'd3)));
  assign ot_vld = ot_sel == 2'd0 ? fot_v
                : ot_sel == 2'd1 ? xot_v
                : ot_sel == 2'd2 ? tot_v : 1'b0;
  assign ot_req = ot_sel == 2'd0 ? fot_req
                : ot_sel == 2'd1 ? xot_req : tot_req;
  assign fot_r = ot_sel == 2'd0 && ot_rdy;
  assign xot_r = ot_sel == 2'd1 && ot_rdy;
  assign tot_r = ot_sel == 2'd2 && ot_rdy;
  assign fot_cv = ot_cvld && ot_busy && ot_own == 2'd0;
  assign xot_cv = ot_cvld && ot_busy && ot_own == 2'd1;
  assign tot_cv = ot_cvld && ot_busy && ot_own == 2'd2;
  always @(posedge clk or negedge rst_ni)
    if (!rst_ni) begin ot_busy <= 1'b0; ot_own <= '0; end
    else if (ot_take) begin ot_busy <= 1'b1; ot_own <= ot_sel; end
    else if (ot_cvld) ot_busy <= 1'b0;

  // cmdrec: front + exec only
  logic               cr_vld, cr_rdy, cr_cvld;
  apu_cmdrec_req_t    cr_req;
  apu_cmdrec_cpl_t    cr_cpl;
  logic               cr_busy = 1'b0, cr_own = 1'b0;
  wire   cr_take = cr_vld && cr_rdy;
  wire   cr_sel  = cr_busy ? cr_own : ~fcr_v;
  assign cr_vld = cr_sel ? xcr_v : fcr_v;
  assign cr_req = cr_sel ? xcr_req : fcr_req;
  assign fcr_r  = !cr_sel && cr_rdy;
  assign xcr_r  =  cr_sel && cr_rdy;
  assign fcr_cv = cr_cvld && cr_busy && !cr_own;
  assign xcr_cv = cr_cvld && cr_busy &&  cr_own;
  always @(posedge clk or negedge rst_ni)
    if (!rst_ni) begin cr_busy <= 1'b0; cr_own <= 1'b0; end
    else if (cr_take) begin cr_busy <= 1'b1; cr_own <= cr_sel; end
    else if (cr_cvld) cr_busy <= 1'b0;

  g6lc_apu_objtab #(.Enable(1'b1), .Slots(Slots)) i_obj (
    .clk_i(clk), .rst_ni(rst_ni), .testmode_i(1'b0),
    .req_valid_i(ot_vld), .req_ready_o(ot_rdy), .req_i(ot_req),
    .cpl_valid_o(ot_cvld), .cpl_ready_i(1'b1), .cpl_o(ot_cpl),
    .live_o());
  g6lc_apu_cmdrec #(.Enable(1'b1), .NumBufs(16), .RecsPerBuf(64))
  i_rec (
    .clk_i(clk), .rst_ni(rst_ni), .testmode_i(1'b0),
    .req_valid_i(cr_vld), .req_ready_o(cr_rdy), .req_i(cr_req),
    .cpl_valid_o(cr_cvld), .cpl_ready_i(1'b1), .cpl_o(cr_cpl),
    .pay_valid_i(fpay_v), .pay_data_i(fpay_d),
    .pay_ready_o(fpay_r));

  // objpay: single master (the front)
  g6lc_apu_objpay #(.Enable(1'b1), .PayWords(ObjPayWords)) i_pay (
    .clk_i(clk), .rst_ni(rst_ni), .testmode_i(1'b0),
    .req_valid_i(fop_v), .req_ready_o(fop_r), .req_i(fop_req),
    .cpl_valid_o(fop_cv), .cpl_ready_i(1'b1), .cpl_o(fop_cpl));

  // ---- memories --------------------------------------------------------
  logic [31:0] cs   [65536];
  logic [31:0] expm [EXPW];
  logic [31:0] paym [PAYW];
  logic [31:0] repm [4096];
  always @(posedge clk) if (cs_re) cs_rdata <= cs[cs_addr];
  always @(posedge clk) if (rep_we) repm[rep_addr[11:0]] <= rep_wdata;

  always #5 clk = ~clk;
  always @(posedge clk) cycles++;

  // disabled-engine quiet check
  always @(negedge clk) begin
    if (o_csre || o_repwe || o_otv || o_crcv || o_subv || o_busy ||
        o_done || o_fclr !== '0 || o_result !== '0 ||
        o_payv || o_opv || o_payd !== '0 || o_opreq !== '0 ||
        o_rwords !== '0 || o_fault !== '0)
      $fatal(1, "disabled vnfront active");
  end

  // ---- work port --------------------------------------------------------
  logic        work_gate = 1'b0;
  logic [31:0] ew_q [256];
  int          ew_head = 0, ew_tail = 0;
  int          pend = 0, dtimer = 0;
  assign w_r = !work_gate && (cycles % 5) != 4;

  always @(posedge clk) begin
    if (!rst_ni) begin
      pend   <= 0;
      dtimer <= 0;
      w_done <= 1'b0;
    end else begin
    if (w_v && w_r) begin
      checks++;
      if (ew_head == ew_tail) begin
        errors++;
        $display("FAIL: unanticipated work ctype=%08x", w_o.ctype);
      end else if (w_o.ctype !== ew_q[ew_head]) begin
        errors++;
        $display("FAIL: work ctype %08x expected %08x",
                 w_o.ctype, ew_q[ew_head]);
      end
      ew_head = ew_head + 1;
      pend   <= pend + 1;
    end
    w_done <= 1'b0;
    if (dtimer != 0) begin
      dtimer <= dtimer - 1;
      if (dtimer == 1) begin
        w_done <= 1'b1;
        pend   <= pend - 1 + (w_v && w_r ? 1 : 0);
      end
    end else if (pend != 0) begin
      dtimer <= 3;
    end
    end
  end

  // ---- record-append monitor (front cmdrec port) -----------------------
  apu_cmdrec_rec_t last_rec;
  int              appends = 0;
  always @(posedge clk)
    if (fcr_v && fcr_r && fcr_req.op == APU_CMDREC_OP_APPEND) begin
      last_rec <= fcr_req.rec;
      appends   = appends + 1;
    end

  function automatic logic [31:0] ev(input int rec, input int w);
    return expm[rec * RECW + w];
  endfunction

  // ---- debug: backend transaction trace (OT_TRACE=1) -------------------
  always @(posedge clk) begin
    if (ot_take)
      $display("OT req own=%0d op=%0d id=%x kind=%0d pid=%x",
               ot_sel, ot_req.op, ot_req.id, ot_req.kind,
               ot_req.parent_id);
    if (ot_cvld)
      $display("OT cpl own=%0d st=%0d h=%x", ot_own, ot_cpl.status,
               ot_cpl.handle);
    if (cr_take)
      $display("CR req own=%0d op=%0d buf=%0d", cr_sel, cr_req.op,
               cr_req.cbuf);
    if (cr_cvld)
      $display("CR cpl own=%0d st=%0d cnt=%0d", cr_own, cr_cpl.status,
               cr_cpl.count);
  end

  task automatic check(input string name, input logic ok);
    checks++;
    if (ok !== 1'b1) begin
      errors++;
      $display("FAIL rec %0d: %s", cases, name);
      if (errors > 16) $fatal(1, "too many errors");
    end
  endtask

  // ---- final RESET_CTX through the TB objtab master --------------------
  task automatic reset_ctx();
    @(negedge clk);
    tb_ot = 1'b1;
    tot_v = 1'b1;
    tot_req = '{op: APU_OBJTAB_OP_RESET_CTX, ctx: 8'h0, default: '0};
    @(posedge clk);
    while (!tot_r) @(posedge clk);
    @(negedge clk); tot_v = 1'b0;
    while (!tot_cv) @(negedge clk);
    @(negedge clk);
    tb_ot = 1'b0;
  endtask

  int rec, tmo, payp, npw;
  logic [31:0] fl, pw_addr, pw_cbuf;
  logic [511:0] exp_rec;
  int app0, nwork, nrep;
  string ses;

  initial begin
    if (!$value$plusargs("ses=%s", ses)) ses = "ue_sm5_session";
    for (int i = 0; i < $size(cs); i++) cs[i] = '0;
    for (int i = 0; i < $size(expm); i++) expm[i] = '0;
    for (int i = 0; i < $size(paym); i++) paym[i] = '0;
    for (int i = 0; i < $size(repm); i++) repm[i] = '0;
    $readmemh($sformatf("vn_vectors/%s.hex", ses), cs, 0);
    $readmemh($sformatf("vn_vectors/%s.exp", ses), expm, 0);
    $readmemh($sformatf("vn_vectors/%s.pay", ses), paym, 0);
    @(negedge clk); rst_ni = 1'b0;
    repeat (3) @(negedge clk); rst_ni = 1'b1;
    repeat (2) @(negedge clk);

    rec = 0;
    payp = 0;
    while (ev(rec, 0) !== 32'hFFFFFFFF) begin
      fl = ev(rec, 3);
      if ((fl & 32'd8) != 0) begin
        // negative arm: reset the whole stack, then let it settle
        @(negedge clk); rst_ni = 1'b0;
        repeat (3) @(negedge clk); rst_ni = 1'b1;
        repeat (2) @(negedge clk);
        ew_head = 0; ew_tail = 0; appends = 0;
        work_gate = 1'b0;
      end
      // push the expected work sequence up front so an eager executor
      // cannot issue before the expectation exists
      nwork = int'(ev(rec, 24));
      for (int i = 0; i < nwork; i++) begin
        ew_q[ew_tail] = ev(rec, 25 + i);
        ew_tail++;
      end
      work_gate = (fl & 32'd16) != 32'd0;
      app0 = appends;

      @(negedge clk);
      f_base = 16'(ev(rec, 0));
      f_len  = 16'(ev(rec, 1));
      f_start = 1'b1;
      @(posedge clk);
      @(negedge clk); f_start = 1'b0;
      tmo = 0;
      while (!f_done) begin
        @(negedge clk);
        tmo++;
        if (tmo > 20000) $fatal(1, "timeout rec %0d", rec);
      end
      cases++;

      check($sformatf("result %08x exp %08x", f_result, ev(rec, 4)),
            f_result === ev(rec, 4));
      check("fault", f_fault === 4'(ev(rec, 7)));
      if ((fl & 32'd1) != 0) begin
        check("rep_words", f_rwords === 16'(ev(rec, 5)));
        nrep = int'(ev(rec, 33));
        for (int i = 0; i < nrep; i++)
          check($sformatf("rep[%0d]", i),
                repm[12'(REP_BASE + 16'(i))] === ev(rec, 34 + i));
      end else begin
        check("norep", f_rwords === 16'h0);
      end
      check($sformatf("live %0d exp %0d",
                      $countones(i_obj.gen_on.live_q), ev(rec, 6)),
            $countones(i_obj.gen_on.live_q) === int'(ev(rec, 6)));
      if ((fl & 32'd2) != 0) begin
        for (int i = 0; i < 16; i++)
          exp_rec[32 * i +: 32] = ev(rec, 8 + i);
        check("append seen", appends > app0);
        check("record", last_rec === exp_rec);
      end
      // §7b payload checkpoints written by this command
      while (paym[payp] !== 32'hFFFFFFFF &&
             paym[payp + 1] === 32'(rec)) begin
        if (paym[payp] == 32'd1) begin
          npw = int'(paym[payp + 2]);
          payp += 3;
          for (int i = 0; i < npw; i++) begin
            pw_addr = paym[payp];
            check($sformatf("objpay[%0d]", pw_addr),
                  i_pay.gen_on.i_pay.sram[pw_addr] === paym[payp + 1]);
            payp += 2;
          end
        end else if (paym[payp] == 32'd2) begin
          pw_cbuf = paym[payp + 2];
          npw = int'(paym[payp + 3]);
          payp += 4;
          for (int i = 0; i < npw; i++) begin
            pw_addr = paym[payp];
            check($sformatf("arena[%0d:%0d]", pw_cbuf, pw_addr),
                  i_rec.gen_on.i_pay.sram[
                    int'(pw_cbuf) * PayPerBuf + int'(pw_addr)]
                  === paym[payp + 1]);
            payp += 2;
          end
        end else begin
          $fatal(1, "bad .pay tag %08x at %0d", paym[payp], payp);
        end
      end
      rec++;
    end

    // ---- final: ObjTab must empty under RESET_CTX -----------------------
    reset_ctx();
    check("reset_ctx status", ot_cpl.status == APU_OBJTAB_OK);
    check("reset_ctx pinned==0", ot_cpl.handle[15:0] === 16'h0);
    repeat (4) @(negedge clk);
    check("objtab empty", $countones(i_obj.gen_on.live_q) === 0);
    check("all work consumed", ew_head == ew_tail);
    check("objpay chunks drained",
          i_pay.gen_on.free_q === '0);

    if (errors == 0)
      $display("PASS tb_g6lc_apu_vnfront cases=%0d checks=%0d cycles=%0d",
               cases, checks, cycles);
    else
      $display({"FAIL tb_g6lc_apu_vnfront cases=%0d errors=%0d ",
                "checks=%0d cycles=%0d"}, cases, errors, checks, cycles);
    $finish;
  end
endmodule
