// Generated by browser-ui compiler from src/App.svelte
//# svelte-d-ir orig=src/App.svelte kind=file parse=first-party
module app;
import libwasm;

nothrow:
@safe:

struct App
{
nothrow:
  @trusted:
  mixin NodeDef!"main";
  void construct() @trusted { }
  void onMount() { }
  enum g6bStaticDom = true;
  void ready() {
    auto root = this.getNamedNode.node;
    Handle menu_main_body = 0;
    Handle menu_cpu_body = 0;
    Handle menu_memory_body = 0;
    Handle menu_uncore_body = 0;
    Handle menu_devices_body = 0;
    Handle menu_boot_body = 0;
    Handle menu_settings_body = 0;
    try {
      setProperty(root, "id", "bios-ui");
      setProperty(root, "data-start-menu", "main");
      setProperty(root, "data-worker-url", "WORKER_URL_PLACEHOLDER");
      setProperty(root, "data-worker-limit", "WORKER_LIMIT_PLACEHOLDER");
      setProperty(root, "data-wasm-url", "WASM_URL_PLACEHOLDER");
      auto banner = createElement(NodeType.h1);
      setProperty(banner, "id", "banner");
      setProperty(banner, "innerText", "G6LC-BIOS | GSys LibreCore");
      appendChild(root, banner);
      auto bios_mark = createElement(NodeType.img);
      setProperty(bios_mark, "id", "bios-mark");
      setProperty(bios_mark, "src", "/ui/g6lc.svg");
      setProperty(bios_mark, "width", "48");
      setProperty(bios_mark, "height", "24");
      setProperty(bios_mark, "alt", "G6LC");
      appendChild(root, bios_mark);
      auto profile = createElement(NodeType.p);
      setProperty(profile, "id", "profile");
      appendChild(root, profile);
      auto bios_menu = createElement(NodeType.nav);
      setProperty(bios_menu, "id", "bios-menu");
      setProperty(bios_menu, "role", "tablist");
      setProperty(bios_menu, "aria-label", "Setup menus");
      auto menu_title = createElement(NodeType.span);
      setProperty(menu_title, "id", "menu-title");
      setProperty(menu_title, "innerText", "SETUP");
      appendChild(bios_menu, menu_title);
      auto tab_main = createElement(NodeType.a);
      setProperty(tab_main, "id", "tab-main");
      setProperty(tab_main, "class", "bios-tab");
      setProperty(tab_main, "href", "#menu-main");
      setProperty(tab_main, "data-menu-link", "main");
      setProperty(tab_main, "role", "tab");
      setProperty(tab_main, "tabindex", "-1");
      setProperty(tab_main, "aria-selected", "false");
      setProperty(tab_main, "innerText", "Main");
      appendChild(bios_menu, tab_main);
      g6b_listen("tab-main", "click");
      auto tab_cpu = createElement(NodeType.a);
      setProperty(tab_cpu, "id", "tab-cpu");
      setProperty(tab_cpu, "class", "bios-tab");
      setProperty(tab_cpu, "href", "#menu-cpu");
      setProperty(tab_cpu, "data-menu-link", "cpu");
      setProperty(tab_cpu, "role", "tab");
      setProperty(tab_cpu, "tabindex", "-1");
      setProperty(tab_cpu, "aria-selected", "false");
      setProperty(tab_cpu, "innerText", "CPU");
      appendChild(bios_menu, tab_cpu);
      g6b_listen("tab-cpu", "click");
      auto tab_memory = createElement(NodeType.a);
      setProperty(tab_memory, "id", "tab-memory");
      setProperty(tab_memory, "class", "bios-tab");
      setProperty(tab_memory, "href", "#menu-memory");
      setProperty(tab_memory, "data-menu-link", "memory");
      setProperty(tab_memory, "role", "tab");
      setProperty(tab_memory, "tabindex", "-1");
      setProperty(tab_memory, "aria-selected", "false");
      setProperty(tab_memory, "innerText", "Memory");
      appendChild(bios_menu, tab_memory);
      g6b_listen("tab-memory", "click");
      auto tab_uncore = createElement(NodeType.a);
      setProperty(tab_uncore, "id", "tab-uncore");
      setProperty(tab_uncore, "class", "bios-tab");
      setProperty(tab_uncore, "href", "#menu-uncore");
      setProperty(tab_uncore, "data-menu-link", "uncore");
      setProperty(tab_uncore, "role", "tab");
      setProperty(tab_uncore, "tabindex", "-1");
      setProperty(tab_uncore, "aria-selected", "false");
      setProperty(tab_uncore, "innerText", "Uncore");
      appendChild(bios_menu, tab_uncore);
      g6b_listen("tab-uncore", "click");
      auto tab_devices = createElement(NodeType.a);
      setProperty(tab_devices, "id", "tab-devices");
      setProperty(tab_devices, "class", "bios-tab");
      setProperty(tab_devices, "href", "#menu-devices");
      setProperty(tab_devices, "data-menu-link", "devices");
      setProperty(tab_devices, "role", "tab");
      setProperty(tab_devices, "tabindex", "-1");
      setProperty(tab_devices, "aria-selected", "false");
      setProperty(tab_devices, "innerText", "Devices");
      appendChild(bios_menu, tab_devices);
      g6b_listen("tab-devices", "click");
      auto tab_boot = createElement(NodeType.a);
      setProperty(tab_boot, "id", "tab-boot");
      setProperty(tab_boot, "class", "bios-tab");
      setProperty(tab_boot, "href", "#menu-boot");
      setProperty(tab_boot, "data-menu-link", "boot");
      setProperty(tab_boot, "role", "tab");
      setProperty(tab_boot, "tabindex", "-1");
      setProperty(tab_boot, "aria-selected", "false");
      setProperty(tab_boot, "innerText", "Boot");
      appendChild(bios_menu, tab_boot);
      g6b_listen("tab-boot", "click");
      auto tab_settings = createElement(NodeType.a);
      setProperty(tab_settings, "id", "tab-settings");
      setProperty(tab_settings, "class", "bios-tab");
      setProperty(tab_settings, "href", "#menu-settings");
      setProperty(tab_settings, "data-menu-link", "settings");
      setProperty(tab_settings, "role", "tab");
      setProperty(tab_settings, "tabindex", "-1");
      setProperty(tab_settings, "aria-selected", "false");
      setProperty(tab_settings, "innerText", "Settings");
      appendChild(bios_menu, tab_settings);
      g6b_listen("tab-settings", "click");
      appendChild(root, bios_menu);
      auto status = createElement(NodeType.p);
      setProperty(status, "id", "status");
      setProperty(status, "role", "status");
      setProperty(status, "innerText", "UI-BOOT");
      appendChild(root, status);
      auto bios_nav = createElement(NodeType.p);
      setProperty(bios_nav, "id", "bios-nav");
      setProperty(bios_nav, "innerText", "Main CPU Memory Uncore Devices Boot Settings");
      appendChild(root, bios_nav);
      auto read_only_note = createElement(NodeType.p);
      setProperty(read_only_note, "id", "read-only-note");
      setProperty(read_only_note, "innerText", "Read-only BoardSpec view. Editing, settings import, and flashing are unavailable here.");
      appendChild(root, read_only_note);
      auto refresh = createElement(NodeType.button);
      setProperty(refresh, "id", "refresh");
      setProperty(refresh, "type", "button");
      setProperty(refresh, "innerText", "Refresh values");
      appendChild(root, refresh);
      g6b_listen("refresh", "click");
      auto menu_main = createElement(NodeType.section);
      setProperty(menu_main, "id", "menu-main");
      setProperty(menu_main, "data-menu", "main");
      setProperty(menu_main, "aria-labelledby", "main-title");
      auto main_title = createElement(NodeType.h2);
      setProperty(main_title, "id", "main-title");
      setProperty(main_title, "innerText", "Main");
      appendChild(menu_main, main_title);
      auto n0 = createElement(NodeType.table);
      auto n1 = createElement(NodeType.thead);
      auto n2 = createElement(NodeType.tr);
      auto n3 = createElement(NodeType.th);
      setProperty(n3, "class", "col-head");
      setProperty(n3, "innerText", "Setting");
      appendChild(n2, n3);
      auto n4 = createElement(NodeType.th);
      setProperty(n4, "class", "col-head");
      setProperty(n4, "innerText", "Value");
      appendChild(n2, n4);
      auto n5 = createElement(NodeType.th);
      setProperty(n5, "class", "col-head");
      setProperty(n5, "innerText", "Access");
      appendChild(n2, n5);
      appendChild(n1, n2);
      appendChild(n0, n1);
      menu_main_body = createElement(NodeType.tbody);
      setProperty(menu_main_body, "id", "menu-main-body");
      appendChild(n0, menu_main_body);
      appendChild(menu_main, n0);
      appendChild(root, menu_main);
      auto menu_cpu = createElement(NodeType.section);
      setProperty(menu_cpu, "id", "menu-cpu");
      setProperty(menu_cpu, "data-menu", "cpu");
      setProperty(menu_cpu, "aria-labelledby", "cpu-title");
      auto cpu_title = createElement(NodeType.h2);
      setProperty(cpu_title, "id", "cpu-title");
      setProperty(cpu_title, "innerText", "CPU");
      appendChild(menu_cpu, cpu_title);
      auto n6 = createElement(NodeType.table);
      auto n7 = createElement(NodeType.thead);
      auto n8 = createElement(NodeType.tr);
      auto n9 = createElement(NodeType.th);
      setProperty(n9, "class", "col-head");
      setProperty(n9, "innerText", "Setting");
      appendChild(n8, n9);
      auto n10 = createElement(NodeType.th);
      setProperty(n10, "class", "col-head");
      setProperty(n10, "innerText", "Value");
      appendChild(n8, n10);
      auto n11 = createElement(NodeType.th);
      setProperty(n11, "class", "col-head");
      setProperty(n11, "innerText", "Access");
      appendChild(n8, n11);
      appendChild(n7, n8);
      appendChild(n6, n7);
      menu_cpu_body = createElement(NodeType.tbody);
      setProperty(menu_cpu_body, "id", "menu-cpu-body");
      appendChild(n6, menu_cpu_body);
      appendChild(menu_cpu, n6);
      appendChild(root, menu_cpu);
      auto menu_memory = createElement(NodeType.section);
      setProperty(menu_memory, "id", "menu-memory");
      setProperty(menu_memory, "data-menu", "memory");
      setProperty(menu_memory, "aria-labelledby", "memory-title");
      auto memory_title = createElement(NodeType.h2);
      setProperty(memory_title, "id", "memory-title");
      setProperty(memory_title, "innerText", "Memory");
      appendChild(menu_memory, memory_title);
      auto n12 = createElement(NodeType.table);
      auto n13 = createElement(NodeType.thead);
      auto n14 = createElement(NodeType.tr);
      auto n15 = createElement(NodeType.th);
      setProperty(n15, "class", "col-head");
      setProperty(n15, "innerText", "Setting");
      appendChild(n14, n15);
      auto n16 = createElement(NodeType.th);
      setProperty(n16, "class", "col-head");
      setProperty(n16, "innerText", "Value");
      appendChild(n14, n16);
      auto n17 = createElement(NodeType.th);
      setProperty(n17, "class", "col-head");
      setProperty(n17, "innerText", "Access");
      appendChild(n14, n17);
      appendChild(n13, n14);
      appendChild(n12, n13);
      menu_memory_body = createElement(NodeType.tbody);
      setProperty(menu_memory_body, "id", "menu-memory-body");
      appendChild(n12, menu_memory_body);
      appendChild(menu_memory, n12);
      appendChild(root, menu_memory);
      auto menu_uncore = createElement(NodeType.section);
      setProperty(menu_uncore, "id", "menu-uncore");
      setProperty(menu_uncore, "data-menu", "uncore");
      setProperty(menu_uncore, "aria-labelledby", "uncore-title");
      auto uncore_title = createElement(NodeType.h2);
      setProperty(uncore_title, "id", "uncore-title");
      setProperty(uncore_title, "innerText", "Uncore");
      appendChild(menu_uncore, uncore_title);
      auto n18 = createElement(NodeType.table);
      auto n19 = createElement(NodeType.thead);
      auto n20 = createElement(NodeType.tr);
      auto n21 = createElement(NodeType.th);
      setProperty(n21, "class", "col-head");
      setProperty(n21, "innerText", "Setting");
      appendChild(n20, n21);
      auto n22 = createElement(NodeType.th);
      setProperty(n22, "class", "col-head");
      setProperty(n22, "innerText", "Value");
      appendChild(n20, n22);
      auto n23 = createElement(NodeType.th);
      setProperty(n23, "class", "col-head");
      setProperty(n23, "innerText", "Access");
      appendChild(n20, n23);
      appendChild(n19, n20);
      appendChild(n18, n19);
      menu_uncore_body = createElement(NodeType.tbody);
      setProperty(menu_uncore_body, "id", "menu-uncore-body");
      appendChild(n18, menu_uncore_body);
      appendChild(menu_uncore, n18);
      appendChild(root, menu_uncore);
      auto menu_devices = createElement(NodeType.section);
      setProperty(menu_devices, "id", "menu-devices");
      setProperty(menu_devices, "data-menu", "devices");
      setProperty(menu_devices, "aria-labelledby", "devices-title");
      auto devices_title = createElement(NodeType.h2);
      setProperty(devices_title, "id", "devices-title");
      setProperty(devices_title, "innerText", "Devices");
      appendChild(menu_devices, devices_title);
      auto n24 = createElement(NodeType.table);
      auto n25 = createElement(NodeType.thead);
      auto n26 = createElement(NodeType.tr);
      auto n27 = createElement(NodeType.th);
      setProperty(n27, "class", "col-head");
      setProperty(n27, "innerText", "Setting");
      appendChild(n26, n27);
      auto n28 = createElement(NodeType.th);
      setProperty(n28, "class", "col-head");
      setProperty(n28, "innerText", "Value");
      appendChild(n26, n28);
      auto n29 = createElement(NodeType.th);
      setProperty(n29, "class", "col-head");
      setProperty(n29, "innerText", "Access");
      appendChild(n26, n29);
      appendChild(n25, n26);
      appendChild(n24, n25);
      menu_devices_body = createElement(NodeType.tbody);
      setProperty(menu_devices_body, "id", "menu-devices-body");
      appendChild(n24, menu_devices_body);
      appendChild(menu_devices, n24);
      appendChild(root, menu_devices);
      auto menu_boot = createElement(NodeType.section);
      setProperty(menu_boot, "id", "menu-boot");
      setProperty(menu_boot, "data-menu", "boot");
      setProperty(menu_boot, "aria-labelledby", "boot-title");
      auto boot_title = createElement(NodeType.h2);
      setProperty(boot_title, "id", "boot-title");
      setProperty(boot_title, "innerText", "Boot");
      appendChild(menu_boot, boot_title);
      auto n30 = createElement(NodeType.table);
      auto n31 = createElement(NodeType.thead);
      auto n32 = createElement(NodeType.tr);
      auto n33 = createElement(NodeType.th);
      setProperty(n33, "class", "col-head");
      setProperty(n33, "innerText", "Setting");
      appendChild(n32, n33);
      auto n34 = createElement(NodeType.th);
      setProperty(n34, "class", "col-head");
      setProperty(n34, "innerText", "Value");
      appendChild(n32, n34);
      auto n35 = createElement(NodeType.th);
      setProperty(n35, "class", "col-head");
      setProperty(n35, "innerText", "Access");
      appendChild(n32, n35);
      appendChild(n31, n32);
      appendChild(n30, n31);
      menu_boot_body = createElement(NodeType.tbody);
      setProperty(menu_boot_body, "id", "menu-boot-body");
      appendChild(n30, menu_boot_body);
      appendChild(menu_boot, n30);
      appendChild(root, menu_boot);
      auto menu_settings = createElement(NodeType.section);
      setProperty(menu_settings, "id", "menu-settings");
      setProperty(menu_settings, "data-menu", "settings");
      setProperty(menu_settings, "aria-labelledby", "settings-title");
      auto settings_title = createElement(NodeType.h2);
      setProperty(settings_title, "id", "settings-title");
      setProperty(settings_title, "innerText", "Settings");
      appendChild(menu_settings, settings_title);
      auto n36 = createElement(NodeType.table);
      auto n37 = createElement(NodeType.thead);
      auto n38 = createElement(NodeType.tr);
      auto n39 = createElement(NodeType.th);
      setProperty(n39, "class", "col-head");
      setProperty(n39, "innerText", "Setting");
      appendChild(n38, n39);
      auto n40 = createElement(NodeType.th);
      setProperty(n40, "class", "col-head");
      setProperty(n40, "innerText", "Value");
      appendChild(n38, n40);
      auto n41 = createElement(NodeType.th);
      setProperty(n41, "class", "col-head");
      setProperty(n41, "innerText", "Access");
      appendChild(n38, n41);
      appendChild(n37, n38);
      appendChild(n36, n37);
      menu_settings_body = createElement(NodeType.tbody);
      setProperty(menu_settings_body, "id", "menu-settings-body");
      appendChild(n36, menu_settings_body);
      appendChild(menu_settings, n36);
      appendChild(root, menu_settings);
      auto g6b_ui_conditional = createElement(NodeType.div);
      setProperty(g6b_ui_conditional, "id", "g6b-ui-conditional");
      appendChild(root, g6b_ui_conditional);
      auto n42 = createElement(NodeType.footer);
      auto bios_hint = createElement(NodeType.p);
      setProperty(bios_hint, "id", "bios-hint");
      setProperty(bios_hint, "innerText", "ArrowLeft/ArrowRight Select tab Home/End First/Last F10 Refresh (not save) Read-only BoardSpec view");
      appendChild(n42, bios_hint);
      appendChild(root, n42);
      auto store = createElement(NodeType.section);
      setProperty(store, "id", "store");
      setProperty(store, "aria-labelledby", "store-title");
      auto store_title = createElement(NodeType.h2);
      setProperty(store_title, "id", "store-title");
      setProperty(store_title, "innerText", "Store");
      appendChild(store, store_title);
      auto store_status = createElement(NodeType.p);
      setProperty(store_status, "id", "store-status");
      appendChild(store, store_status);
      appendChild(root, store);
    } catch (Exception e) {
      // bounded catch: DOM construct
    }
    auto p0 = g6b_fetch("/bios/menu");
    auto p1 = g6b_fetch("/bios/menu/main");
    auto p2 = g6b_fetch("/bios/menu/cpu");
    auto p3 = g6b_fetch("/bios/menu/memory");
    auto p4 = g6b_fetch("/bios/menu/uncore");
    auto p5 = g6b_fetch("/bios/menu/devices");
    auto p6 = g6b_fetch("/bios/menu/boot");
    auto p7 = g6b_fetch("/bios/menu/settings");
    auto p8 = g6b_fetch("/bios/clocks");
    auto p9 = g6b_fetch("/bios/bootloader");
    auto p10 = g6b_fetch("/bios/display");
    auto p11 = g6b_fetch("/bios/settings");
    auto p12 = g6b_fetch("/bios/settings/usb");
    auto p13 = g6b_fetch("/bios/usb/ls");
    auto p14 = g6b_fetch("/bios/files");
    auto p15 = g6b_fetch("/bios/files/fat32");
    auto p16 = g6b_fetch("/bios/files/ntfs");
    auto p17 = g6b_fetch("/bios/files/ext4");
    g6b_holyc("Menu(\"main\")");
    g6b_register("/bios/custom", "POST");
    auto p18 = g6b_fetch("/bios/store");
    if (libwasm_await_supported()) {
      libwasm_await__void(p1);
      try {
        auto json_p1 = libwasm_await_value();
        auto j1 = parseJSON!ThreadMemAllocator(json_p1);
        foreach (_; j1) {
          string id = "", label = "", value = "";
          bool writable = false;
          foreach (key; j1.byKey) {
            if (key == "id") id = j1.read!string;
            else if (key == "label") label = j1.read!string;
            else if (key == "value") value = j1.read!string;
            else if (key == "writable") writable = j1.read!bool;
            else j1.skipValue();
          }
          auto tr = createElement(NodeType.tr);
          auto td0 = createElement(NodeType.td);
          setProperty(td0, "innerText", label);
          appendChild(tr, td0);
          auto td1 = createElement(NodeType.td);
          setProperty(td1, "innerText", value);
          appendChild(tr, td1);
          auto td2 = createElement(NodeType.td);
          setProperty(td2, "innerText", writable ? "RW" : "R");
          appendChild(tr, td2);
          appendChild(menu_main_body, tr);
        }
      } catch (Exception e) {}
      libwasm_await__void(p2);
      try {
        auto json_p2 = libwasm_await_value();
        auto j2 = parseJSON!ThreadMemAllocator(json_p2);
        foreach (_; j2) {
          string id = "", label = "", value = "";
          bool writable = false;
          foreach (key; j2.byKey) {
            if (key == "id") id = j2.read!string;
            else if (key == "label") label = j2.read!string;
            else if (key == "value") value = j2.read!string;
            else if (key == "writable") writable = j2.read!bool;
            else j2.skipValue();
          }
          auto tr = createElement(NodeType.tr);
          auto td0 = createElement(NodeType.td);
          setProperty(td0, "innerText", label);
          appendChild(tr, td0);
          auto td1 = createElement(NodeType.td);
          setProperty(td1, "innerText", value);
          appendChild(tr, td1);
          auto td2 = createElement(NodeType.td);
          setProperty(td2, "innerText", writable ? "RW" : "R");
          appendChild(tr, td2);
          appendChild(menu_cpu_body, tr);
        }
      } catch (Exception e) {}
      libwasm_await__void(p3);
      try {
        auto json_p3 = libwasm_await_value();
        auto j3 = parseJSON!ThreadMemAllocator(json_p3);
        foreach (_; j3) {
          string id = "", label = "", value = "";
          bool writable = false;
          foreach (key; j3.byKey) {
            if (key == "id") id = j3.read!string;
            else if (key == "label") label = j3.read!string;
            else if (key == "value") value = j3.read!string;
            else if (key == "writable") writable = j3.read!bool;
            else j3.skipValue();
          }
          auto tr = createElement(NodeType.tr);
          auto td0 = createElement(NodeType.td);
          setProperty(td0, "innerText", label);
          appendChild(tr, td0);
          auto td1 = createElement(NodeType.td);
          setProperty(td1, "innerText", value);
          appendChild(tr, td1);
          auto td2 = createElement(NodeType.td);
          setProperty(td2, "innerText", writable ? "RW" : "R");
          appendChild(tr, td2);
          appendChild(menu_memory_body, tr);
        }
      } catch (Exception e) {}
      libwasm_await__void(p4);
      try {
        auto json_p4 = libwasm_await_value();
        auto j4 = parseJSON!ThreadMemAllocator(json_p4);
        foreach (_; j4) {
          string id = "", label = "", value = "";
          bool writable = false;
          foreach (key; j4.byKey) {
            if (key == "id") id = j4.read!string;
            else if (key == "label") label = j4.read!string;
            else if (key == "value") value = j4.read!string;
            else if (key == "writable") writable = j4.read!bool;
            else j4.skipValue();
          }
          auto tr = createElement(NodeType.tr);
          auto td0 = createElement(NodeType.td);
          setProperty(td0, "innerText", label);
          appendChild(tr, td0);
          auto td1 = createElement(NodeType.td);
          setProperty(td1, "innerText", value);
          appendChild(tr, td1);
          auto td2 = createElement(NodeType.td);
          setProperty(td2, "innerText", writable ? "RW" : "R");
          appendChild(tr, td2);
          appendChild(menu_uncore_body, tr);
        }
      } catch (Exception e) {}
      libwasm_await__void(p5);
      try {
        auto json_p5 = libwasm_await_value();
        auto j5 = parseJSON!ThreadMemAllocator(json_p5);
        foreach (_; j5) {
          string id = "", label = "", value = "";
          bool writable = false;
          foreach (key; j5.byKey) {
            if (key == "id") id = j5.read!string;
            else if (key == "label") label = j5.read!string;
            else if (key == "value") value = j5.read!string;
            else if (key == "writable") writable = j5.read!bool;
            else j5.skipValue();
          }
          auto tr = createElement(NodeType.tr);
          auto td0 = createElement(NodeType.td);
          setProperty(td0, "innerText", label);
          appendChild(tr, td0);
          auto td1 = createElement(NodeType.td);
          setProperty(td1, "innerText", value);
          appendChild(tr, td1);
          auto td2 = createElement(NodeType.td);
          setProperty(td2, "innerText", writable ? "RW" : "R");
          appendChild(tr, td2);
          appendChild(menu_devices_body, tr);
        }
      } catch (Exception e) {}
      libwasm_await__void(p6);
      try {
        auto json_p6 = libwasm_await_value();
        auto j6 = parseJSON!ThreadMemAllocator(json_p6);
        foreach (_; j6) {
          string id = "", label = "", value = "";
          bool writable = false;
          foreach (key; j6.byKey) {
            if (key == "id") id = j6.read!string;
            else if (key == "label") label = j6.read!string;
            else if (key == "value") value = j6.read!string;
            else if (key == "writable") writable = j6.read!bool;
            else j6.skipValue();
          }
          auto tr = createElement(NodeType.tr);
          auto td0 = createElement(NodeType.td);
          setProperty(td0, "innerText", label);
          appendChild(tr, td0);
          auto td1 = createElement(NodeType.td);
          setProperty(td1, "innerText", value);
          appendChild(tr, td1);
          auto td2 = createElement(NodeType.td);
          setProperty(td2, "innerText", writable ? "RW" : "R");
          appendChild(tr, td2);
          appendChild(menu_boot_body, tr);
        }
      } catch (Exception e) {}
      libwasm_await__void(p7);
      try {
        auto json_p7 = libwasm_await_value();
        auto j7 = parseJSON!ThreadMemAllocator(json_p7);
        foreach (_; j7) {
          string id = "", label = "", value = "";
          bool writable = false;
          foreach (key; j7.byKey) {
            if (key == "id") id = j7.read!string;
            else if (key == "label") label = j7.read!string;
            else if (key == "value") value = j7.read!string;
            else if (key == "writable") writable = j7.read!bool;
            else j7.skipValue();
          }
          auto tr = createElement(NodeType.tr);
          auto td0 = createElement(NodeType.td);
          setProperty(td0, "innerText", label);
          appendChild(tr, td0);
          auto td1 = createElement(NodeType.td);
          setProperty(td1, "innerText", value);
          appendChild(tr, td1);
          auto td2 = createElement(NodeType.td);
          setProperty(td2, "innerText", writable ? "RW" : "R");
          appendChild(tr, td2);
          appendChild(menu_settings_body, tr);
        }
      } catch (Exception e) {}
    }
    auto db = PgLite("memory://registry");
    db.waitReady();
    db.exec("CREATE TABLE IF NOT EXISTS bios_ui (k TEXT PRIMARY KEY, v TEXT)");
    auto rows = db.queryAsync("SELECT k, v FROM bios_ui", "[]");
    setProperty(store_status, "innerText", JSON.stringify(rows));
  }
  void onUnmount() { }
}
mixin Spa!App;

private struct G6bFxParticle { float x, y, intensity, size; }
static assert(G6bFxParticle.sizeof == 16);
private __gshared G6bFxParticle[256] g6bFxParticles;
private __gshared float[512] g6bFxVelocity;
private __gshared float[2] g6bFxLogo;
private __gshared float[2] g6bFxLogoVelocity = [0.17f, 0.12f];
private __gshared uint g6bFxSeed = 0x6C696272;
private __gshared bool g6bFxReady;

private float g6bFxRandom() @trusted @nogc
{
    g6bFxSeed ^= g6bFxSeed << 13;
    g6bFxSeed ^= g6bFxSeed >> 17;
    g6bFxSeed ^= g6bFxSeed << 5;
    return cast(float)(g6bFxSeed & 0xFFFFFF) / 16777216.0f;
}

private float g6bFxClamp(float value, float low, float high) @safe @nogc
{
    return value < low ? low : (value > high ? high : value);
}

extern(C) export uint g6b_fx_data() @trusted @nogc
{
    return cast(uint)g6bFxParticles.ptr;
}

extern(C) export uint g6b_fx_count() @safe @nogc
{
    return 256;
}

extern(C) export uint g6b_fx_logo() @trusted @nogc
{
    return cast(uint)g6bFxLogo.ptr;
}

extern(C) export void g6b_fx_step(float dt) @trusted @nogc
{
    if (!g6bFxReady)
    {
        foreach (i; 0 .. 256)
        {
            g6bFxParticles[i] = G6bFxParticle(g6bFxRandom() * 2.0f - 1.0f,
                g6bFxRandom() * 2.0f - 1.0f, 0.35f + 0.65f * g6bFxRandom(),
                2.0f + 8.0f * g6bFxRandom());
            g6bFxVelocity[i * 2] = (g6bFxRandom() - 0.5f) * 0.2f;
            g6bFxVelocity[i * 2 + 1] = (g6bFxRandom() - 0.5f) * 0.2f;
        }
        g6bFxLogo[] = 0.0f;
        g6bFxReady = true;
    }
    if (!(dt > 0.0f)) return;
    if (dt > 0.05f) dt = 0.05f;
    foreach (axis; 0 .. 2)
    {
        const limit = axis == 0 ? 0.76f : 0.78f;
        g6bFxLogo[axis] += g6bFxLogoVelocity[axis] * dt;
        if (g6bFxLogo[axis] > limit || g6bFxLogo[axis] < -limit)
        {
            g6bFxLogo[axis] = g6bFxClamp(g6bFxLogo[axis], -limit, limit);
            g6bFxLogoVelocity[axis] = -g6bFxLogoVelocity[axis];
        }
    }
    foreach (i; 0 .. 256)
    {
        auto p = &g6bFxParticles[i];
        const dx = g6bFxLogo[0] - p.x;
        const dy = g6bFxLogo[1] - p.y;
        const force = 0.12f / (0.08f + dx * dx + dy * dy);
        float vx = g6bFxVelocity[i * 2];
        float vy = g6bFxVelocity[i * 2 + 1];
        vx = (vx + (dx * 0.30f - dy * 0.80f) * force * dt) * (1.0f - 0.18f * dt);
        vy = (vy + ((dy * 0.30f + dx * 0.80f) * force - 0.10f) * dt) * (1.0f - 0.18f * dt);
        vx = g6bFxClamp(vx, -1.5f, 1.5f);
        vy = g6bFxClamp(vy, -1.5f, 1.5f);
        p.x += vx * dt;
        p.y += vy * dt;
        p.intensity -= 0.18f * dt;
        if (p.x < -1.0f || p.x > 1.0f || p.y < -1.0f || p.y > 1.0f || p.intensity < 0.1f)
        {
            p.x = g6bFxLogo[0] + (g6bFxRandom() - 0.5f) * 0.05f;
            p.y = g6bFxLogo[1] + (g6bFxRandom() - 0.5f) * 0.05f;
            p.intensity = 0.55f + 0.45f * g6bFxRandom();
            p.size = 2.0f + 8.0f * g6bFxRandom();
            vx = (g6bFxRandom() - 0.5f) * 1.4f;
            vy = 0.2f + 0.8f * g6bFxRandom();
        }
        g6bFxVelocity[i * 2] = vx;
        g6bFxVelocity[i * 2 + 1] = vy;
    }
}
