// Generated by browser-ui compiler from src/App.svelte
//# svelte-d-ir orig=src/App.svelte kind=file parse=first-party
module app;
import libwasm;
import boot;
import cpu;
import devices;
import filemgr;
import flash;
import main;
import memory;
import menu;
import settings;
import uncore;

nothrow:
@safe:

struct App
{
nothrow:
  @trusted:
  mixin NodeDef!"section";
  @prop!"id" enum id = "status";
  @prop!"innerText" string status = "UI-BOOT";
  @child Boot boot;
  @child Cpu cpu;
  @child Devices devices;
  @child FileMgr filemgr;
  @child Flash flash;
  @child Main main;
  @child Memory memory;
  @child Menu menu;
  @child Settings settings;
  @child Uncore uncore;
  void construct() @trusted { }
  void onMount() { }
  void onUnmount() { }
}
mixin Spa!App;
