// Generated by browser-ui compiler from src/App.svelte
//# svelte-d-ir orig=src/App.svelte kind=file parse=first-party
module app;
import libwasm;

nothrow:
@safe:

struct App
{
nothrow:
  @trusted:
  mixin NodeDef!"main";
  void construct() @trusted { }
  void onMount() { }
  enum g6bStaticDom = true;
  void ready() {
    auto root = this.getNamedNode.node;
    Handle menu_main_body = 0;
    Handle menu_cpu_body = 0;
    Handle menu_memory_body = 0;
    Handle menu_uncore_body = 0;
    Handle menu_devices_body = 0;
    Handle menu_boot_body = 0;
    Handle menu_settings_body = 0;
    Handle store_status = 0;
    try {
      setProperty(root, "id", "bios-ui");
      setProperty(root, "data-start-menu", "main");
      setProperty(root, "data-worker-url", "WORKER_URL_PLACEHOLDER");
      setProperty(root, "data-worker-limit", "WORKER_LIMIT_PLACEHOLDER");
      setProperty(root, "data-wasm-url", "WASM_URL_PLACEHOLDER");
      auto bios_header = createElement(NodeType.header);
      setProperty(bios_header, "id", "bios-header");
      auto banner = createElement(NodeType.h1);
      setProperty(banner, "id", "banner");
      setProperty(banner, "innerText", "G6LC-BIOS | GSys LibreCore");
      appendChild(bios_header, banner);
      auto bios_eyebrow = createElement(NodeType.p);
      setProperty(bios_eyebrow, "id", "bios-eyebrow");
      setProperty(bios_eyebrow, "innerText", "SYSTEM SETUP");
      appendChild(bios_header, bios_eyebrow);
      auto profile = createElement(NodeType.p);
      setProperty(profile, "id", "profile");
      appendChild(bios_header, profile);
      appendChild(root, bios_header);
      auto bios_menu = createElement(NodeType.nav);
      setProperty(bios_menu, "id", "bios-menu");
      setProperty(bios_menu, "role", "tablist");
      setProperty(bios_menu, "aria-label", "Setup menus");
      auto menu_title = createElement(NodeType.span);
      setProperty(menu_title, "id", "menu-title");
      setProperty(menu_title, "innerText", "SETUP");
      appendChild(bios_menu, menu_title);
      auto tab_main = createElement(NodeType.a);
      setProperty(tab_main, "id", "tab-main");
      setProperty(tab_main, "class", "bios-tab bios-tab-active");
      setProperty(tab_main, "href", "#menu-main");
      setProperty(tab_main, "data-menu-link", "main");
      setProperty(tab_main, "role", "tab");
      setProperty(tab_main, "tabindex", "0");
      setProperty(tab_main, "aria-selected", "true");
      setProperty(tab_main, "innerText", "Main");
      appendChild(bios_menu, tab_main);
      g6b_listen("tab-main", "click");
      auto tab_cpu = createElement(NodeType.a);
      setProperty(tab_cpu, "id", "tab-cpu");
      setProperty(tab_cpu, "class", "bios-tab");
      setProperty(tab_cpu, "href", "#menu-cpu");
      setProperty(tab_cpu, "data-menu-link", "cpu");
      setProperty(tab_cpu, "role", "tab");
      setProperty(tab_cpu, "tabindex", "-1");
      setProperty(tab_cpu, "aria-selected", "false");
      setProperty(tab_cpu, "innerText", "CPU");
      appendChild(bios_menu, tab_cpu);
      g6b_listen("tab-cpu", "click");
      auto tab_memory = createElement(NodeType.a);
      setProperty(tab_memory, "id", "tab-memory");
      setProperty(tab_memory, "class", "bios-tab");
      setProperty(tab_memory, "href", "#menu-memory");
      setProperty(tab_memory, "data-menu-link", "memory");
      setProperty(tab_memory, "role", "tab");
      setProperty(tab_memory, "tabindex", "-1");
      setProperty(tab_memory, "aria-selected", "false");
      setProperty(tab_memory, "innerText", "Memory");
      appendChild(bios_menu, tab_memory);
      g6b_listen("tab-memory", "click");
      auto tab_uncore = createElement(NodeType.a);
      setProperty(tab_uncore, "id", "tab-uncore");
      setProperty(tab_uncore, "class", "bios-tab");
      setProperty(tab_uncore, "href", "#menu-uncore");
      setProperty(tab_uncore, "data-menu-link", "uncore");
      setProperty(tab_uncore, "role", "tab");
      setProperty(tab_uncore, "tabindex", "-1");
      setProperty(tab_uncore, "aria-selected", "false");
      setProperty(tab_uncore, "innerText", "Uncore");
      appendChild(bios_menu, tab_uncore);
      g6b_listen("tab-uncore", "click");
      auto tab_devices = createElement(NodeType.a);
      setProperty(tab_devices, "id", "tab-devices");
      setProperty(tab_devices, "class", "bios-tab");
      setProperty(tab_devices, "href", "#menu-devices");
      setProperty(tab_devices, "data-menu-link", "devices");
      setProperty(tab_devices, "role", "tab");
      setProperty(tab_devices, "tabindex", "-1");
      setProperty(tab_devices, "aria-selected", "false");
      setProperty(tab_devices, "innerText", "Devices");
      appendChild(bios_menu, tab_devices);
      g6b_listen("tab-devices", "click");
      auto tab_boot = createElement(NodeType.a);
      setProperty(tab_boot, "id", "tab-boot");
      setProperty(tab_boot, "class", "bios-tab");
      setProperty(tab_boot, "href", "#menu-boot");
      setProperty(tab_boot, "data-menu-link", "boot");
      setProperty(tab_boot, "role", "tab");
      setProperty(tab_boot, "tabindex", "-1");
      setProperty(tab_boot, "aria-selected", "false");
      setProperty(tab_boot, "innerText", "Boot");
      appendChild(bios_menu, tab_boot);
      g6b_listen("tab-boot", "click");
      auto tab_settings = createElement(NodeType.a);
      setProperty(tab_settings, "id", "tab-settings");
      setProperty(tab_settings, "class", "bios-tab");
      setProperty(tab_settings, "href", "#menu-settings");
      setProperty(tab_settings, "data-menu-link", "settings");
      setProperty(tab_settings, "role", "tab");
      setProperty(tab_settings, "tabindex", "-1");
      setProperty(tab_settings, "aria-selected", "false");
      setProperty(tab_settings, "innerText", "Settings");
      appendChild(bios_menu, tab_settings);
      g6b_listen("tab-settings", "click");
      appendChild(root, bios_menu);
      auto bios_toolbar = createElement(NodeType.div);
      setProperty(bios_toolbar, "id", "bios-toolbar");
      auto refresh = createElement(NodeType.button);
      setProperty(refresh, "id", "refresh");
      setProperty(refresh, "type", "button");
      setProperty(refresh, "innerText", "Refresh / F10");
      appendChild(bios_toolbar, refresh);
      g6b_listen("refresh", "click");
      auto row_navigation_hint = createElement(NodeType.span);
      setProperty(row_navigation_hint, "id", "row-navigation-hint");
      setProperty(row_navigation_hint, "innerText", "Up/Down: field / Left/Right: tab");
      appendChild(bios_toolbar, row_navigation_hint);
      appendChild(root, bios_toolbar);
      auto status = createElement(NodeType.p);
      setProperty(status, "id", "status");
      setProperty(status, "role", "status");
      setProperty(status, "aria-live", "polite");
      setProperty(status, "innerText", "UI-BOOT: read-only setup");
      appendChild(root, status);
      auto bios_nav = createElement(NodeType.p);
      setProperty(bios_nav, "id", "bios-nav");
      setProperty(bios_nav, "hidden", "");
      appendChild(root, bios_nav);
      auto hw_nat_status = createElement(NodeType.p);
      setProperty(hw_nat_status, "id", "hw-nat-status");
      setProperty(hw_nat_status, "role", "status");
      appendChild(root, hw_nat_status);
      auto menu_main = createElement(NodeType.section);
      setProperty(menu_main, "id", "menu-main");
      setProperty(menu_main, "data-menu", "main");
      setProperty(menu_main, "aria-labelledby", "main-title");
      auto main_title = createElement(NodeType.h2);
      setProperty(main_title, "id", "main-title");
      setProperty(main_title, "innerText", "Main");
      appendChild(menu_main, main_title);
      auto n0 = createElement(NodeType.table);
      menu_main_body = createElement(NodeType.tbody);
      setProperty(menu_main_body, "id", "menu-main-body");
      appendChild(n0, menu_main_body);
      appendChild(menu_main, n0);
      appendChild(root, menu_main);
      auto menu_cpu = createElement(NodeType.section);
      setProperty(menu_cpu, "id", "menu-cpu");
      setProperty(menu_cpu, "data-menu", "cpu");
      setProperty(menu_cpu, "aria-labelledby", "cpu-title");
      setProperty(menu_cpu, "hidden", "");
      auto cpu_title = createElement(NodeType.h2);
      setProperty(cpu_title, "id", "cpu-title");
      setProperty(cpu_title, "innerText", "CPU");
      appendChild(menu_cpu, cpu_title);
      auto n1 = createElement(NodeType.table);
      menu_cpu_body = createElement(NodeType.tbody);
      setProperty(menu_cpu_body, "id", "menu-cpu-body");
      appendChild(n1, menu_cpu_body);
      appendChild(menu_cpu, n1);
      appendChild(root, menu_cpu);
      auto menu_memory = createElement(NodeType.section);
      setProperty(menu_memory, "id", "menu-memory");
      setProperty(menu_memory, "data-menu", "memory");
      setProperty(menu_memory, "aria-labelledby", "memory-title");
      setProperty(menu_memory, "hidden", "");
      auto memory_title = createElement(NodeType.h2);
      setProperty(memory_title, "id", "memory-title");
      setProperty(memory_title, "innerText", "Memory");
      appendChild(menu_memory, memory_title);
      auto n2 = createElement(NodeType.table);
      menu_memory_body = createElement(NodeType.tbody);
      setProperty(menu_memory_body, "id", "menu-memory-body");
      appendChild(n2, menu_memory_body);
      appendChild(menu_memory, n2);
      appendChild(root, menu_memory);
      auto menu_uncore = createElement(NodeType.section);
      setProperty(menu_uncore, "id", "menu-uncore");
      setProperty(menu_uncore, "data-menu", "uncore");
      setProperty(menu_uncore, "aria-labelledby", "uncore-title");
      setProperty(menu_uncore, "hidden", "");
      auto uncore_title = createElement(NodeType.h2);
      setProperty(uncore_title, "id", "uncore-title");
      setProperty(uncore_title, "innerText", "Uncore");
      appendChild(menu_uncore, uncore_title);
      auto n3 = createElement(NodeType.table);
      menu_uncore_body = createElement(NodeType.tbody);
      setProperty(menu_uncore_body, "id", "menu-uncore-body");
      appendChild(n3, menu_uncore_body);
      appendChild(menu_uncore, n3);
      appendChild(root, menu_uncore);
      auto menu_devices = createElement(NodeType.section);
      setProperty(menu_devices, "id", "menu-devices");
      setProperty(menu_devices, "data-menu", "devices");
      setProperty(menu_devices, "aria-labelledby", "devices-title");
      setProperty(menu_devices, "hidden", "");
      auto devices_title = createElement(NodeType.h2);
      setProperty(devices_title, "id", "devices-title");
      setProperty(devices_title, "innerText", "Devices");
      appendChild(menu_devices, devices_title);
      auto n4 = createElement(NodeType.table);
      menu_devices_body = createElement(NodeType.tbody);
      setProperty(menu_devices_body, "id", "menu-devices-body");
      appendChild(n4, menu_devices_body);
      appendChild(menu_devices, n4);
      appendChild(root, menu_devices);
      auto menu_boot = createElement(NodeType.section);
      setProperty(menu_boot, "id", "menu-boot");
      setProperty(menu_boot, "data-menu", "boot");
      setProperty(menu_boot, "aria-labelledby", "boot-title");
      setProperty(menu_boot, "hidden", "");
      auto boot_title = createElement(NodeType.h2);
      setProperty(boot_title, "id", "boot-title");
      setProperty(boot_title, "innerText", "Boot");
      appendChild(menu_boot, boot_title);
      auto n5 = createElement(NodeType.table);
      menu_boot_body = createElement(NodeType.tbody);
      setProperty(menu_boot_body, "id", "menu-boot-body");
      appendChild(n5, menu_boot_body);
      appendChild(menu_boot, n5);
      appendChild(root, menu_boot);
      auto menu_settings = createElement(NodeType.section);
      setProperty(menu_settings, "id", "menu-settings");
      setProperty(menu_settings, "data-menu", "settings");
      setProperty(menu_settings, "aria-labelledby", "settings-title");
      setProperty(menu_settings, "hidden", "");
      auto settings_title = createElement(NodeType.h2);
      setProperty(settings_title, "id", "settings-title");
      setProperty(settings_title, "innerText", "Settings");
      appendChild(menu_settings, settings_title);
      auto n6 = createElement(NodeType.table);
      menu_settings_body = createElement(NodeType.tbody);
      setProperty(menu_settings_body, "id", "menu-settings-body");
      appendChild(n6, menu_settings_body);
      appendChild(menu_settings, n6);
      appendChild(root, menu_settings);
      auto g6b_ui_conditional = createElement(NodeType.div);
      setProperty(g6b_ui_conditional, "id", "g6b-ui-conditional");
      appendChild(root, g6b_ui_conditional);
      auto n7 = createElement(NodeType.footer);
      auto bios_hint = createElement(NodeType.p);
      setProperty(bios_hint, "id", "bios-hint");
      setProperty(bios_hint, "innerText", "ArrowLeft/ArrowRight Select tab Home/End First/Last F10 Refresh (not save) Esc stays in setup");
      appendChild(n7, bios_hint);
      appendChild(root, n7);
      auto store = createElement(NodeType.section);
      setProperty(store, "id", "store");
      setProperty(store, "data-menu", "settings");
      setProperty(store, "data-fetch", "/bios/store");
      setProperty(store, "aria-labelledby", "store-title");
      setProperty(store, "hidden", "");
      auto store_title = createElement(NodeType.h2);
      setProperty(store_title, "id", "store-title");
      setProperty(store_title, "innerText", "Session storage");
      appendChild(store, store_title);
      auto store_note = createElement(NodeType.p);
      setProperty(store_note, "id", "store-note");
      setProperty(store_note, "innerText", "The kernel owns storage access. Inspect the registry without creating a database or changing its contents.");
      appendChild(store, store_note);
      store_status = createElement(NodeType.pre);
      setProperty(store_status, "id", "store-status");
      setProperty(store_status, "data-fetch", "/bios/store");
      appendChild(store, store_status);
      appendChild(root, store);
    } catch (Exception e) {
      // bounded catch: DOM construct
    }
    auto p0 = g6b_fetch("/bios/menu/main");
    auto p1 = g6b_fetch("/bios/menu/cpu");
    auto p2 = g6b_fetch("/bios/menu/memory");
    auto p3 = g6b_fetch("/bios/menu/uncore");
    auto p4 = g6b_fetch("/bios/menu/devices");
    auto p5 = g6b_fetch("/bios/menu/boot");
    auto p6 = g6b_fetch("/bios/menu/settings");
    auto p7 = g6b_fetch("/bios/store");
    if (libwasm_await_supported()) {
      libwasm_await__void(p0);
      try {
        auto json_p0 = libwasm_await_value();
        auto j0 = parseJSON!ThreadMemAllocator(json_p0);
        foreach (_; j0) {
          string id = "", label = "", value = "";
          bool writable = false;
          foreach (key; j0.byKey) {
            if (key == "id") id = j0.read!string;
            else if (key == "label") label = j0.read!string;
            else if (key == "value") value = j0.read!string;
            else if (key == "writable") writable = j0.read!bool;
            else j0.skipValue();
          }
          auto tr = createElement(NodeType.tr);
          setProperty(tr, "id", "field-main-" ~ id);
          setProperty(tr, "class", "bios-field");
          setProperty(tr, "data-field", id);
          setProperty(tr, "data-item", id);
          setProperty(tr, "tabindex", "-1");
          auto td0 = createElement(NodeType.td);
          setProperty(td0, "id", "label-main-" ~ id);
          setProperty(td0, "innerText", label);
          appendChild(tr, td0);
          auto td1 = createElement(NodeType.td);
          setProperty(td1, "id", "row-main-" ~ id);
          setProperty(td1, "innerText", value);
          appendChild(tr, td1);
          setProperty(tr, "data-writable", writable ? "true" : "false");
          appendChild(menu_main_body, tr);
        }
      } catch (Exception e) {}
      libwasm_await__void(p1);
      try {
        auto json_p1 = libwasm_await_value();
        auto j1 = parseJSON!ThreadMemAllocator(json_p1);
        foreach (_; j1) {
          string id = "", label = "", value = "";
          bool writable = false;
          foreach (key; j1.byKey) {
            if (key == "id") id = j1.read!string;
            else if (key == "label") label = j1.read!string;
            else if (key == "value") value = j1.read!string;
            else if (key == "writable") writable = j1.read!bool;
            else j1.skipValue();
          }
          auto tr = createElement(NodeType.tr);
          setProperty(tr, "id", "field-cpu-" ~ id);
          setProperty(tr, "class", "bios-field");
          setProperty(tr, "data-field", id);
          setProperty(tr, "data-item", id);
          setProperty(tr, "tabindex", "-1");
          auto td0 = createElement(NodeType.td);
          setProperty(td0, "id", "label-cpu-" ~ id);
          setProperty(td0, "innerText", label);
          appendChild(tr, td0);
          auto td1 = createElement(NodeType.td);
          setProperty(td1, "id", "row-cpu-" ~ id);
          setProperty(td1, "innerText", value);
          appendChild(tr, td1);
          setProperty(tr, "data-writable", writable ? "true" : "false");
          appendChild(menu_cpu_body, tr);
        }
      } catch (Exception e) {}
      libwasm_await__void(p2);
      try {
        auto json_p2 = libwasm_await_value();
        auto j2 = parseJSON!ThreadMemAllocator(json_p2);
        foreach (_; j2) {
          string id = "", label = "", value = "";
          bool writable = false;
          foreach (key; j2.byKey) {
            if (key == "id") id = j2.read!string;
            else if (key == "label") label = j2.read!string;
            else if (key == "value") value = j2.read!string;
            else if (key == "writable") writable = j2.read!bool;
            else j2.skipValue();
          }
          auto tr = createElement(NodeType.tr);
          setProperty(tr, "id", "field-memory-" ~ id);
          setProperty(tr, "class", "bios-field");
          setProperty(tr, "data-field", id);
          setProperty(tr, "data-item", id);
          setProperty(tr, "tabindex", "-1");
          auto td0 = createElement(NodeType.td);
          setProperty(td0, "id", "label-memory-" ~ id);
          setProperty(td0, "innerText", label);
          appendChild(tr, td0);
          auto td1 = createElement(NodeType.td);
          setProperty(td1, "id", "row-memory-" ~ id);
          setProperty(td1, "innerText", value);
          appendChild(tr, td1);
          setProperty(tr, "data-writable", writable ? "true" : "false");
          appendChild(menu_memory_body, tr);
        }
      } catch (Exception e) {}
      libwasm_await__void(p3);
      try {
        auto json_p3 = libwasm_await_value();
        auto j3 = parseJSON!ThreadMemAllocator(json_p3);
        foreach (_; j3) {
          string id = "", label = "", value = "";
          bool writable = false;
          foreach (key; j3.byKey) {
            if (key == "id") id = j3.read!string;
            else if (key == "label") label = j3.read!string;
            else if (key == "value") value = j3.read!string;
            else if (key == "writable") writable = j3.read!bool;
            else j3.skipValue();
          }
          auto tr = createElement(NodeType.tr);
          setProperty(tr, "id", "field-uncore-" ~ id);
          setProperty(tr, "class", "bios-field");
          setProperty(tr, "data-field", id);
          setProperty(tr, "data-item", id);
          setProperty(tr, "tabindex", "-1");
          auto td0 = createElement(NodeType.td);
          setProperty(td0, "id", "label-uncore-" ~ id);
          setProperty(td0, "innerText", label);
          appendChild(tr, td0);
          auto td1 = createElement(NodeType.td);
          setProperty(td1, "id", "row-uncore-" ~ id);
          setProperty(td1, "innerText", value);
          appendChild(tr, td1);
          setProperty(tr, "data-writable", writable ? "true" : "false");
          appendChild(menu_uncore_body, tr);
        }
      } catch (Exception e) {}
      libwasm_await__void(p4);
      try {
        auto json_p4 = libwasm_await_value();
        auto j4 = parseJSON!ThreadMemAllocator(json_p4);
        foreach (_; j4) {
          string id = "", label = "", value = "";
          bool writable = false;
          foreach (key; j4.byKey) {
            if (key == "id") id = j4.read!string;
            else if (key == "label") label = j4.read!string;
            else if (key == "value") value = j4.read!string;
            else if (key == "writable") writable = j4.read!bool;
            else j4.skipValue();
          }
          auto tr = createElement(NodeType.tr);
          setProperty(tr, "id", "field-devices-" ~ id);
          setProperty(tr, "class", "bios-field");
          setProperty(tr, "data-field", id);
          setProperty(tr, "data-item", id);
          setProperty(tr, "tabindex", "-1");
          auto td0 = createElement(NodeType.td);
          setProperty(td0, "id", "label-devices-" ~ id);
          setProperty(td0, "innerText", label);
          appendChild(tr, td0);
          auto td1 = createElement(NodeType.td);
          setProperty(td1, "id", "row-devices-" ~ id);
          setProperty(td1, "innerText", value);
          appendChild(tr, td1);
          setProperty(tr, "data-writable", writable ? "true" : "false");
          appendChild(menu_devices_body, tr);
        }
      } catch (Exception e) {}
      libwasm_await__void(p5);
      try {
        auto json_p5 = libwasm_await_value();
        auto j5 = parseJSON!ThreadMemAllocator(json_p5);
        foreach (_; j5) {
          string id = "", label = "", value = "";
          bool writable = false;
          foreach (key; j5.byKey) {
            if (key == "id") id = j5.read!string;
            else if (key == "label") label = j5.read!string;
            else if (key == "value") value = j5.read!string;
            else if (key == "writable") writable = j5.read!bool;
            else j5.skipValue();
          }
          auto tr = createElement(NodeType.tr);
          setProperty(tr, "id", "field-boot-" ~ id);
          setProperty(tr, "class", "bios-field");
          setProperty(tr, "data-field", id);
          setProperty(tr, "data-item", id);
          setProperty(tr, "tabindex", "-1");
          auto td0 = createElement(NodeType.td);
          setProperty(td0, "id", "label-boot-" ~ id);
          setProperty(td0, "innerText", label);
          appendChild(tr, td0);
          auto td1 = createElement(NodeType.td);
          setProperty(td1, "id", "row-boot-" ~ id);
          setProperty(td1, "innerText", value);
          appendChild(tr, td1);
          setProperty(tr, "data-writable", writable ? "true" : "false");
          appendChild(menu_boot_body, tr);
        }
      } catch (Exception e) {}
      libwasm_await__void(p6);
      try {
        auto json_p6 = libwasm_await_value();
        auto j6 = parseJSON!ThreadMemAllocator(json_p6);
        foreach (_; j6) {
          string id = "", label = "", value = "";
          bool writable = false;
          foreach (key; j6.byKey) {
            if (key == "id") id = j6.read!string;
            else if (key == "label") label = j6.read!string;
            else if (key == "value") value = j6.read!string;
            else if (key == "writable") writable = j6.read!bool;
            else j6.skipValue();
          }
          auto tr = createElement(NodeType.tr);
          setProperty(tr, "id", "field-settings-" ~ id);
          setProperty(tr, "class", "bios-field");
          setProperty(tr, "data-field", id);
          setProperty(tr, "data-item", id);
          setProperty(tr, "tabindex", "-1");
          auto td0 = createElement(NodeType.td);
          setProperty(td0, "id", "label-settings-" ~ id);
          setProperty(td0, "innerText", label);
          appendChild(tr, td0);
          auto td1 = createElement(NodeType.td);
          setProperty(td1, "id", "row-settings-" ~ id);
          setProperty(td1, "innerText", value);
          appendChild(tr, td1);
          setProperty(tr, "data-writable", writable ? "true" : "false");
          appendChild(menu_settings_body, tr);
        }
      } catch (Exception e) {}
      libwasm_await__void(p7);
      setProperty(store_status, "innerText", libwasm_await_value());
    }
  }
  void onUnmount() { }
}
mixin Spa!App;

private struct G6bFxParticle { float x, y, intensity, size; }
static assert(G6bFxParticle.sizeof == 16);
private __gshared G6bFxParticle[256] g6bFxParticles;
private __gshared float[512] g6bFxVelocity;
private __gshared float[2] g6bFxLogo;
private __gshared float[2] g6bFxLogoVelocity = [0.17f, 0.12f];
private __gshared uint g6bFxSeed = 0x6C696272;
private __gshared bool g6bFxReady;

private float g6bFxRandom() @trusted @nogc
{
    g6bFxSeed ^= g6bFxSeed << 13;
    g6bFxSeed ^= g6bFxSeed >> 17;
    g6bFxSeed ^= g6bFxSeed << 5;
    return cast(float)(g6bFxSeed & 0xFFFFFF) / 16777216.0f;
}

private float g6bFxClamp(float value, float low, float high) @safe @nogc
{
    return value < low ? low : (value > high ? high : value);
}

extern(C) export uint g6b_fx_data() @trusted @nogc
{
    return cast(uint)g6bFxParticles.ptr;
}

extern(C) export uint g6b_fx_count() @safe @nogc
{
    return 256;
}

extern(C) export uint g6b_fx_logo() @trusted @nogc
{
    return cast(uint)g6bFxLogo.ptr;
}

extern(C) export void g6b_fx_step(float dt) @trusted @nogc
{
    if (!g6bFxReady)
    {
        foreach (i; 0 .. 256)
        {
            g6bFxParticles[i] = G6bFxParticle(g6bFxRandom() * 2.0f - 1.0f,
                g6bFxRandom() * 2.0f - 1.0f, 0.35f + 0.65f * g6bFxRandom(),
                2.0f + 8.0f * g6bFxRandom());
            g6bFxVelocity[i * 2] = (g6bFxRandom() - 0.5f) * 0.2f;
            g6bFxVelocity[i * 2 + 1] = (g6bFxRandom() - 0.5f) * 0.2f;
        }
        g6bFxLogo[] = 0.0f;
        g6bFxReady = true;
    }
    if (!(dt > 0.0f)) return;
    if (dt > 0.05f) dt = 0.05f;
    foreach (axis; 0 .. 2)
    {
        const limit = axis == 0 ? 0.76f : 0.78f;
        g6bFxLogo[axis] += g6bFxLogoVelocity[axis] * dt;
        if (g6bFxLogo[axis] > limit || g6bFxLogo[axis] < -limit)
        {
            g6bFxLogo[axis] = g6bFxClamp(g6bFxLogo[axis], -limit, limit);
            g6bFxLogoVelocity[axis] = -g6bFxLogoVelocity[axis];
        }
    }
    foreach (i; 0 .. 256)
    {
        auto p = &g6bFxParticles[i];
        const dx = g6bFxLogo[0] - p.x;
        const dy = g6bFxLogo[1] - p.y;
        const force = 0.12f / (0.08f + dx * dx + dy * dy);
        float vx = g6bFxVelocity[i * 2];
        float vy = g6bFxVelocity[i * 2 + 1];
        vx = (vx + (dx * 0.30f - dy * 0.80f) * force * dt) * (1.0f - 0.18f * dt);
        vy = (vy + ((dy * 0.30f + dx * 0.80f) * force - 0.10f) * dt) * (1.0f - 0.18f * dt);
        vx = g6bFxClamp(vx, -1.5f, 1.5f);
        vy = g6bFxClamp(vy, -1.5f, 1.5f);
        p.x += vx * dt;
        p.y += vy * dt;
        p.intensity -= 0.18f * dt;
        if (p.x < -1.0f || p.x > 1.0f || p.y < -1.0f || p.y > 1.0f || p.intensity < 0.1f)
        {
            p.x = g6bFxLogo[0] + (g6bFxRandom() - 0.5f) * 0.05f;
            p.y = g6bFxLogo[1] + (g6bFxRandom() - 0.5f) * 0.05f;
            p.intensity = 0.55f + 0.45f * g6bFxRandom();
            p.size = 2.0f + 8.0f * g6bFxRandom();
            vx = (g6bFxRandom() - 0.5f) * 1.4f;
            vy = 0.2f + 0.8f * g6bFxRandom();
        }
        g6bFxVelocity[i * 2] = vx;
        g6bFxVelocity[i * 2 + 1] = vy;
    }
}
