// Generated by browser-ui compiler from src/Boot.svelte
//# svelte-d-ir orig=src/Boot.svelte kind=file parse=first-party
module boot;
import libwasm;

nothrow:
@safe:

struct Boot
{
nothrow:
  @trusted:
  mixin NodeDef!"section";
  @prop!"id" enum id = "boot-title";
  @prop!"innerText" string title = "Boot";
  void construct() @trusted { }
  void onMount() { }
  void onUnmount() { }
}
