// Generated by browser-ui compiler from src/Cpu.svelte
//# svelte-d-ir orig=src/Cpu.svelte kind=file parse=first-party
module cpu;
import libwasm;

nothrow:
@safe:

struct Cpu
{
nothrow:
  @trusted:
  mixin NodeDef!"section";
  @prop!"id" enum id = "cpu-title";
  @prop!"innerText" string title = "CPU";
  void construct() @trusted { }
  void onMount() { }
  void onUnmount() { }
}
