// Generated by browser-ui compiler from src/Devices.svelte
//# svelte-d-ir orig=src/Devices.svelte kind=file parse=first-party
module devices;
import libwasm;

nothrow:
@safe:

struct Devices
{
nothrow:
  @trusted:
  mixin NodeDef!"section";
  @prop!"id" enum id = "devices-title";
  @prop!"innerText" string title = "Devices";
  void construct() @trusted { }
  void onMount() { }
  void onUnmount() { }
}
