// Generated by browser-ui compiler from src/FileMgr.svelte
//# svelte-d-ir orig=src/FileMgr.svelte kind=file parse=first-party
module filemgr;
import libwasm;

nothrow:
@safe:

struct FileMgr
{
nothrow:
  @trusted:
  mixin NodeDef!"section";
  @prop!"id" enum id = "fm-tabs";
  @prop!"innerText" string listing = "USB-FILES";
  void construct() @trusted { }
  void onMount() { }
  void onUnmount() { }
}
