// Generated by browser-ui compiler from src/Flash.svelte
//# svelte-d-ir orig=src/Flash.svelte kind=file parse=first-party
module flash;
import libwasm;

nothrow:
@safe:

struct Flash
{
nothrow:
  @trusted:
  mixin NodeDef!"section";
  @prop!"id" enum id = "usb-title";
  @prop!"innerText" string images = "Read-only USB image listing; not refreshed";
  void construct() @trusted { }
  void onMount() { }
  void onUnmount() { }
}
