// Generated by browser-ui compiler from src/Main.svelte
//# svelte-d-ir orig=src/Main.svelte kind=file parse=first-party
module main;
import libwasm;

nothrow:
@safe:

struct Main
{
nothrow:
  @trusted:
  mixin NodeDef!"section";
  @prop!"id" enum id = "main-title";
  @prop!"innerText" string title = "Main";
  void construct() @trusted { }
  void onMount() { }
  void onUnmount() { }
}
