// Generated by browser-ui compiler from src/Memory.svelte
//# svelte-d-ir orig=src/Memory.svelte kind=file parse=first-party
module memory;
import libwasm;

nothrow:
@safe:

struct Memory
{
nothrow:
  @trusted:
  mixin NodeDef!"section";
  @prop!"id" enum id = "memory-title";
  @prop!"innerText" string title = "Memory";
  void construct() @trusted { }
  void onMount() { }
  void onUnmount() { }
}
