// Generated by browser-ui compiler from src/Menu.svelte
//# svelte-d-ir orig=src/Menu.svelte kind=file parse=first-party
module menu;
import libwasm;

nothrow:
@safe:

struct Menu
{
nothrow:
  @trusted:
  mixin NodeDef!"nav";
  @prop!"id" enum id = "menu-title";
  @prop!"innerText" string title = "Main CPU Memory Uncore Devices Boot Settings";
  void construct() @trusted { }
  void onMount() { }
  void onUnmount() { }
}
