// Generated by browser-ui compiler from src/Settings.svelte
//# svelte-d-ir orig=src/Settings.svelte kind=file parse=first-party
module settings;
import libwasm;

nothrow:
@safe:

struct Settings
{
nothrow:
  @trusted:
  mixin NodeDef!"section";
  @prop!"id" enum id = "settings-title";
  @prop!"innerText" string title = "Settings";
  void construct() @trusted { }
  void onMount() { }
  void onUnmount() { }
}
