// Generated by browser-ui compiler from src/Store.svelte
//# svelte-d-ir orig=src/Store.svelte kind=file parse=first-party
module store;
import libwasm;

nothrow:
@safe:

struct Store
{
nothrow:
  @trusted:
  mixin NodeDef!"section";
  void construct() @trusted { }
  void onMount() { }
  void onUnmount() { }
}
