// Generated by browser-ui compiler from src/Uncore.svelte
//# svelte-d-ir orig=src/Uncore.svelte kind=file parse=first-party
module uncore;
import libwasm;

nothrow:
@safe:

struct Uncore
{
nothrow:
  @trusted:
  mixin NodeDef!"section";
  @prop!"id" enum id = "uncore-title";
  @prop!"innerText" string title = "Uncore";
  void construct() @trusted { }
  void onMount() { }
  void onUnmount() { }
}
