#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate venus_map.h (C) and vn_map.svh (SV) for the 3d-a bare-metal
Venus probe.  Every device constant is parsed out of the SystemVerilog
packages so the C program never carries a hand-typed copy of the map.
Layout constants (virtqueue addresses, cookie, mailbox) are the TB's
ABI: they are emitted here once and consumed by both sides."""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CFG = ROOT / "corev_apu/include/g6lc_apu_cfg_pkg.sv"
PKG = ROOT / "corev_apu/apu/include/g6lc_apu_pkg.sv"

LP = re.compile(
    r"localparam\s+(?:(?:logic\s*\[\d+:\d+\]|int\s+unsigned|bit|int)\s+)?"
    r"(\w+)\s*=\s*([^;]+);")
FLD = re.compile(r"^\s*(\w+):\s*([^,}]+?),?\s*$", re.M)


def parse_localparams(path):
    vals = {}
    for m in LP.finditer(path.read_text(encoding="utf-8")):
        vals[m.group(1)] = m.group(2).strip()
    return vals


def value(expr, vals):
    expr = expr.strip().rstrip(",")
    expr = re.sub(r"\w+'\((.*)\)", r"\1", expr)          # unsigned'(x) cast
    m = re.match(r"(\d+)'h([0-9a-fA-F_]+)", expr)
    if m:
        return int(m.group(2).replace("_", ""), 16)
    m = re.match(r"(\d+)'d([0-9_]+)", expr)
    if m:
        return int(m.group(2).replace("_", ""), 10)
    m = re.match(r"(\d+)'b([01_xz]+)", expr)
    if m:
        return int(m.group(2).replace("_", "").replace("x", "0"), 2)
    if re.match(r"[0-9_]+$", expr):
        return int(expr.replace("_", ""), 10)
    if expr in vals:                                     # alias localparam
        return value(vals[expr], vals)
    raise KeyError(f"cannot resolve {expr!r}")


def apu_cfg_literal(path, name):
    """Fields of `localparam apu_cfg_t <name> = '{ ... };`"""
    txt = path.read_text(encoding="utf-8")
    m = re.search(
        r"localparam\s+apu_cfg_t\s+" + name + r"\s*=\s*'\{(.*?)\};",
        txt, re.S)
    if not m:
        raise KeyError(name)
    out = {}
    for fm in FLD.finditer(m.group(1)):
        out[fm.group(1)] = fm.group(2).strip()
    return out


def main():
    cfg_pk = parse_localparams(CFG)
    pkg = parse_localparams(PKG)
    venus = apu_cfg_literal(CFG, "ApuVenus")
    vals = dict(cfg_pk)
    vals.update(pkg)

    def C(sym):
        return value(sym, vals)

    def F(sym):            # ApuVenus literal field, alias-resolved
        return value(venus[sym], vals)

    h = {
        "VN_MMIO_BASE":    F("MmioBase"),
        "VN_MMIO_LEN":     F("MmioLength"),
        "VN_CONTROL_BASE": F("ControlBase"),
        "VN_CONTROL_LEN":  F("ControlLength"),
        "VN_IRQ_SOURCE":   F("IrqSource"),
        "VN_DMA_BASE":     F("DmaWindowBase"),
        "VN_DMA_BYTES":    F("DmaWindowBytes"),
        "VN_QUEUE_DEPTH":  F("QueueDepth"),
        "VN_NUM_CAPSETS":  F("NumCapsets"),
        "VN_SHM_BASE":     C("APU_SHM_BASE"),
        "VN_SHM_BYTES":    C("APU_SHM_BYTES"),
        "VN_SHM_ID":       C("APU_SHM_ID_HOST_VISIBLE"),
        "VN_MAGIC":        C("VIRTIO_MMIO_MAGIC"),
        "VN_VERSION":      C("VIRTIO_MMIO_VERSION2"),
        "VN_DEVICE_ID":    C("VIRTIO_DEVICE_GPU"),
        "VN_VENDOR":       C("G6LC_VIRTIO_VENDOR"),
        "VN_ACKNOWLEDGE":  C("VSTATUS_ACKNOWLEDGE"),
        "VN_DRIVER":       C("VSTATUS_DRIVER"),
        "VN_DRIVER_OK":    C("VSTATUS_DRIVER_OK"),
        "VN_FEATURES_OK":  C("VSTATUS_FEATURES_OK"),
        "VN_FAILED":       C("VSTATUS_FAILED"),
        "VN_NEEDS_RESET":  C("VSTATUS_DEVICE_NEEDS_RESET"),
        # testharness ABI: cookie + mailbox + virtqueue placement.
        # The tape stages its buffers at guest offsets 0x4000..0x12000;
        # queues sit at 0x80000+, the program body at 0x20000+.
        "VN_COOKIE_ADDR":  0x80000F00,
        "VN_MBX_ADDR":     0x80000E00,
        "VN_MBX_ACK":      0x80000E80,
        "VN_Q0_NUM":       64,
        "VN_Q1_NUM":       16,
        "VN_Q0_DESC":      0x80000000 + 0x80000,
        "VN_Q0_AVAIL":     0x80000000 + 0x81000,
        "VN_Q0_USED":      0x80000000 + 0x82000,
        "VN_Q1_DESC":      0x80000000 + 0x83000,
        "VN_Q1_AVAIL":     0x80000000 + 0x84000,
        "VN_Q1_USED":      0x80000000 + 0x85000,
        # cbo stride: D$ line (bits) / 8. Parsed per-target by the caller.
        "VN_CBO_LINE":     None,
        "PASS_TRANSPORT":  0x600D0001,
        "PASS_COMPUTE":    0x600D0002,
        "FAIL_BASE":       0xBAD00000,
    }
    for name in sorted(pkg):
        if name.startswith("VREG_") or name.startswith("VCFG_"):
            h[name] = C(name)

    # cache line from the selected target config package
    ccfg = parse_localparams(Path(sys.argv[3]))
    line_bits = C("DUMMY") if False else value(
        ccfg["CVA6ConfigDcacheLineWidth"], ccfg)
    h["VN_CBO_LINE"] = max(16, line_bits // 8)

    outh, outsv = Path(sys.argv[1]), Path(sys.argv[2])
    hp = ["// generated by gen_venus_map.py -- do not edit\n",
          "#ifndef VENUS_MAP_H\n#define VENUS_MAP_H\n"]
    sp = ["// generated by gen_venus_map.py -- do not edit\n"]
    for k, v in h.items():
        hp.append(f"#define {k} 0x{v:X}ULL\n")
        sp.append(f"localparam logic [63:0] SV_{k} = 64'h{v:X};\n")
    hp.append("#endif\n")
    outh.write_text("".join(hp), encoding="utf-8")
    outsv.write_text("".join(sp), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
