#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Convert vn_golden guest-script tapes (verif/tb/apu/vn_vectors/*.hex/.exp)
into a C header for the 3d-a bare-metal probe.

Tape word stream (same encoding tb_g6lc_apu_vgtop/vgsys consume; op table
from the tb_g6lc_apu_vgtop header):
    0        TP_END
    1 n al ah TP_MEMW   n words -> guest window at byte offset al
    2 ...    TP_CHAIN   nd x {a0,a1,len,is_write} + flags,f_lo,f_hi,cx,ring
    3 n al ah TP_APW    n words -> aperture at byte offset al
    4 r a e t TP_WAIT_HEAD   poll aperture[a]==e
    5 r a m w t TP_WAIT_IDLE poll (aperture[a]&m)==w
    6 w a0 a1 TP_CHECK   CK_HEAD/STATUS/REPLY/LIVE/EXTRA/APR
    7 n      TP_DELAY    ~n cycles

.exp records are 8 words each, kinds: 1 EK_RESP, 2 EK_BODY, 3 EK_HEAD,
4 EK_STATUS, 5 EK_REPLY, 6 EK_LIVE, 7 EK_EXTRA, 8 EK_FENCE,
10 EK_APRCHK, 11 EK_PAGES; FF/FF marks end.

Also emitted per tape: a ring map giving each created ring's aperture
byte address of its head and status words, recovered by scanning the
tape's TP_WAIT_HEAD/TP_WAIT_IDLE ops (vn_ring layout: head@0, tail@64,
status@128, so head_ap = status_ap - 128 when only status was seen).
"""
import sys
from pathlib import Path

VNVEC = Path(__file__).resolve().parents[3] / "verif/tb/apu/vn_vectors"
TP_MEMW, TP_CHAIN, TP_APW = 1, 2, 3
TP_WAIT_HEAD, TP_WAIT_IDLE, TP_CHECK, TP_DELAY = 4, 5, 6, 7


def words(path):
    out = []
    for line in path.read_text().split():
        line = line.strip()
        if not line or line.startswith("//"):
            continue
        out.append(int(line, 16))
    return out


def ring_map(tape):
    head, status = {}, {}
    i = 0
    while i < len(tape):
        op = tape[i]
        i += 1
        if op == 0:
            break
        if op == TP_MEMW or op == TP_APW:
            i += 2 + tape[i]
        elif op == TP_CHAIN:
            i += 4 * tape[i] + 5
        elif op == TP_WAIT_HEAD:
            head[tape[i]] = tape[i + 1]
            i += 4
        elif op == TP_WAIT_IDLE:
            status[tape[i]] = tape[i + 1]
            i += 5
        elif op == TP_CHECK:
            i += 3
        elif op == TP_DELAY:
            i += 1
        else:
            raise ValueError(f"unknown tape op {op} at {i}")
    # head_ap derivable from status_ap (RING_STATUS_OFF - RING_HEAD_OFF)
    for s, ad in status.items():
        head.setdefault(s, ad - 128)
    for s, ad in head.items():
        status.setdefault(s, ad + 128)
    return head, status


def cname(name):
    return name.replace("ue_", "").replace(".", "_")


def main():
    out = Path(sys.argv[1])
    names = sys.argv[2:]
    lines = ["// generated by tape2c.py -- do not edit\n",
             "#ifndef VN_TAPE_H\n#define VN_TAPE_H\n",
             "#include <stdint.h>\n",
             "typedef struct {\n",
             "  const uint32_t *tape, *exp;\n",
             "  /* {slot, head_ap, status_ap} triples, slot=0xff ends */\n",
             "  const uint32_t *rmap;\n",
             "  const char *name;\n",
             "} vn_session_t;\n"]
    sess = []
    for name in names:
        tape = words(VNVEC / f"{name}.hex")
        exp = words(VNVEC / f"{name}.exp")
        head, status = ring_map(tape)
        n = cname(name)
        lines.append(f"static const uint32_t tape_{n}[] = {{\n")
        for i in range(0, len(tape), 8):
            lines.append("  " + ",".join(f"0x{w:08x}" for w in
                                         tape[i:i + 8]) + ",\n")
        lines.append("};\n")
        lines.append(f"static const uint32_t exp_{n}[] = {{\n")
        for i in range(0, len(exp), 8):
            lines.append("  " + ",".join(f"0x{w:08x}" for w in
                                         exp[i:i + 8]) + ",\n")
        lines.append("};\n")
        lines.append(f"static const uint32_t rmap_{n}[] = {{\n  ")
        for s in sorted(set(head) | set(status)):
            lines.append(f"{s},0x{head[s]:x},0x{status[s]:x},")
        lines.append("0xff,0,0\n};\n")
        sess.append(f"  {{tape_{n},exp_{n},rmap_{n},\"{name}\"}}")
    lines.append("static const vn_session_t vn_sessions[] = {\n")
    lines.append(",\n".join(sess) + "\n};\n")
    lines.append(f"#define VN_NUM_SESSIONS {len(sess)}\n#endif\n")
    out.write_text("".join(lines), encoding="utf-8")
    print("tape2c:", ", ".join(names))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
