// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
/** Print libwasm D IR (mixin NodeDef / @prop / @child). Not LDC. */

import type { SvelteFile } from "./parse.ts";

export function printModule(file: SvelteFile, children: string[] = []): string {
  const struct = structName(file);
  const lines: string[] = [];
  lines.push(`// Generated by browser-ui compiler from ${file.rel}`);
  lines.push(`//# svelte-d-ir orig=${file.rel} kind=file parse=first-party`);
  lines.push("module " + dModule(file.ident) + ";");
  lines.push("import libwasm;");
  for (const c of children) {
    lines.push(`import ${c.toLowerCase()};`);
  }
  lines.push("");
  lines.push("nothrow:");
  lines.push("@safe:");
  lines.push("");
  lines.push(`struct ${struct}`);
  lines.push("{");
  lines.push("nothrow:");
  lines.push("  @trusted:");
  lines.push(`  mixin NodeDef!"${file.tag}";`);
  const rootId = file.ops.find((o) => o.kind === "text" && o.value);
  if (rootId && rootId.kind === "text") {
    lines.push(`  @prop!"id" enum id = "${rootId.id}";`);
  }
  for (const b of file.lets) {
    lines.push(`  @prop!"innerText" string ${b.name} = "${escapeD(b.value)}";`);
  }
  for (const c of children) {
    lines.push(`  @child ${c} ${c.toLowerCase()};`);
  }
  lines.push("  void construct() @trusted { }");
  lines.push("  void onMount() { }");
  lines.push("  void onUnmount() { }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

export function printApp(files: SvelteFile[]): string {
  const kids = files.filter((f) => f.ident !== "App_svelte").map((f) => structName(f));
  const app = files.find((f) => f.ident === "App_svelte") ?? files[0];
  const body = printModule(app, kids);
  return body + "mixin Spa!App;\n";
}

export function structName(file: SvelteFile): string {
  const base = file.rel.replace(/\\/g, "/").split("/").pop() ?? file.ident;
  const n = base.replace(/\.svelte$/i, "");
  return n.charAt(0).toUpperCase() + n.slice(1);
}

function dModule(ident: string): string {
  return ident.replace(/_svelte$/, "").toLowerCase();
}

function escapeD(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}
