// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
/** Print libwasm D IR (mixin NodeDef / @prop / @child). Not LDC. */

import type { SvelteFile } from "./parse.ts";

// Member names that libwasm Spa!/NodeDef consult via __traits(hasMember) or
// mixin-defined symbols; a @child field may not reuse them.
const RESERVED_MEMBERS = new Set([
  "main", "ready", "g6bStaticDom", "construct", "onMount", "onUnmount", "compile",
  "registerRoutes", "update", "unmount", "remount", "dumpState", "loadState",
]);

export function childFieldName(struct: string): string {
  const base = struct.charAt(0).toLowerCase() + struct.slice(1);
  return RESERVED_MEMBERS.has(base) ? base + "Child" : base;
}

export function validateDProject(files: SvelteFile[]): void {
  const names = new Set<string>();
  for (const file of files) {
    const name = structName(file);
    if (!/^[A-Z][A-Za-z0-9_]*$/.test(name) || ["Spa", "NodeDef", "Empty", "Application"].includes(name)) {
      throw new Error(`reserved or invalid D component name: ${name}`);
    }
    if (names.has(name.toLowerCase())) throw new Error(`D module name collision: ${name}`);
    names.add(name.toLowerCase());
  }
  if (!files.some((file) => structName(file) === "App")) throw new Error("LDC generation requires App.svelte");
}

export function printModule(file: SvelteFile, children: string[] = []): string {
  const struct = structName(file);
  const members = new Set([...RESERVED_MEMBERS, "id"]);
  for (const name of [...file.lets.map((binding) => binding.name), ...children.map(childFieldName)]) {
    if (members.has(name)) throw new Error(`D member collision in ${struct}: ${name}`);
    members.add(name);
  }
  const lines: string[] = [];
  lines.push(`// Generated by browser-ui compiler from ${file.rel}`);
  lines.push(`//# svelte-d-ir orig=${file.rel} kind=file parse=first-party`);
  lines.push("module " + dModule(file.ident) + ";");
  lines.push("import libwasm;");
  for (const c of children) {
    lines.push(`import ${c.toLowerCase()};`);
  }
  lines.push("");
  lines.push("nothrow:");
  lines.push("@safe:");
  lines.push("");
  lines.push(`struct ${struct}`);
  lines.push("{");
  lines.push("nothrow:");
  lines.push("  @trusted:");
  lines.push(`  mixin NodeDef!"${file.tag}";`);
  const rootId = file.ops.find((o) => o.kind === "text" && o.value);
  if (rootId && rootId.kind === "text") {
    lines.push(`  @prop!"id" enum id = "${escapeD(rootId.id)}";`);
  }
  for (const b of file.lets) {
    lines.push(`  @prop!"innerText" string ${b.name} = "${escapeD(b.value)}";`);
  }
  for (const c of children) {
    lines.push(`  @child ${c} ${childFieldName(c)};`);
  }
  lines.push("  void construct() @trusted { }");
  lines.push("  void onMount() { }");
  lines.push("  void onUnmount() { }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

export function printApp(files: SvelteFile[]): string {
  validateDProject(files);
  const kids = files.filter((f) => structName(f) !== "App").map((f) => structName(f));
  const app = files.find((f) => structName(f) === "App")!;
  // `ready` keeps libwasm `Spa` off the JS router: without it _start calls
  // router().navigateTo(document().location()…), which needs browser-only
  // Object_Getter imports the g6b cell does not provide.
  const body = printModule(app, kids).replace(
    "  void onMount() { }",
    "  void onMount() { }\n  enum g6bStaticDom = true;\n  void ready() { }",
  );
  return body + "mixin Spa!App;\n" + printFxD();
}

export function printFxD(): string {
  return `
private struct G6bFxParticle { float x, y, intensity, size; }
static assert(G6bFxParticle.sizeof == 16);
private __gshared G6bFxParticle[256] g6bFxParticles;
private __gshared float[512] g6bFxVelocity;
private __gshared float[2] g6bFxLogo;
private __gshared float[2] g6bFxLogoVelocity = [0.17f, 0.12f];
private __gshared uint g6bFxSeed = 0x6C696272;
private __gshared bool g6bFxReady;

private float g6bFxRandom() @trusted @nogc
{
    g6bFxSeed ^= g6bFxSeed << 13;
    g6bFxSeed ^= g6bFxSeed >> 17;
    g6bFxSeed ^= g6bFxSeed << 5;
    return cast(float)(g6bFxSeed & 0xFFFFFF) / 16777216.0f;
}

private float g6bFxClamp(float value, float low, float high) @safe @nogc
{
    return value < low ? low : (value > high ? high : value);
}

extern(C) export uint g6b_fx_data() @trusted @nogc
{
    return cast(uint)g6bFxParticles.ptr;
}

extern(C) export uint g6b_fx_count() @safe @nogc
{
    return 256;
}

extern(C) export uint g6b_fx_logo() @trusted @nogc
{
    return cast(uint)g6bFxLogo.ptr;
}

extern(C) export void g6b_fx_step(float dt) @trusted @nogc
{
    if (!g6bFxReady)
    {
        foreach (i; 0 .. 256)
        {
            g6bFxParticles[i] = G6bFxParticle(g6bFxRandom() * 2.0f - 1.0f,
                g6bFxRandom() * 2.0f - 1.0f, 0.35f + 0.65f * g6bFxRandom(),
                2.0f + 8.0f * g6bFxRandom());
            g6bFxVelocity[i * 2] = (g6bFxRandom() - 0.5f) * 0.2f;
            g6bFxVelocity[i * 2 + 1] = (g6bFxRandom() - 0.5f) * 0.2f;
        }
        g6bFxLogo[] = 0.0f;
        g6bFxReady = true;
    }
    if (!(dt > 0.0f)) return;
    if (dt > 0.05f) dt = 0.05f;
    foreach (axis; 0 .. 2)
    {
        const limit = axis == 0 ? 0.76f : 0.78f;
        g6bFxLogo[axis] += g6bFxLogoVelocity[axis] * dt;
        if (g6bFxLogo[axis] > limit || g6bFxLogo[axis] < -limit)
        {
            g6bFxLogo[axis] = g6bFxClamp(g6bFxLogo[axis], -limit, limit);
            g6bFxLogoVelocity[axis] = -g6bFxLogoVelocity[axis];
        }
    }
    foreach (i; 0 .. 256)
    {
        auto p = &g6bFxParticles[i];
        const dx = g6bFxLogo[0] - p.x;
        const dy = g6bFxLogo[1] - p.y;
        const force = 0.12f / (0.08f + dx * dx + dy * dy);
        float vx = g6bFxVelocity[i * 2];
        float vy = g6bFxVelocity[i * 2 + 1];
        vx = (vx + (dx * 0.30f - dy * 0.80f) * force * dt) * (1.0f - 0.18f * dt);
        vy = (vy + ((dy * 0.30f + dx * 0.80f) * force - 0.10f) * dt) * (1.0f - 0.18f * dt);
        vx = g6bFxClamp(vx, -1.5f, 1.5f);
        vy = g6bFxClamp(vy, -1.5f, 1.5f);
        p.x += vx * dt;
        p.y += vy * dt;
        p.intensity -= 0.18f * dt;
        if (p.x < -1.0f || p.x > 1.0f || p.y < -1.0f || p.y > 1.0f || p.intensity < 0.1f)
        {
            p.x = g6bFxLogo[0] + (g6bFxRandom() - 0.5f) * 0.05f;
            p.y = g6bFxLogo[1] + (g6bFxRandom() - 0.5f) * 0.05f;
            p.intensity = 0.55f + 0.45f * g6bFxRandom();
            p.size = 2.0f + 8.0f * g6bFxRandom();
            vx = (g6bFxRandom() - 0.5f) * 1.4f;
            vy = 0.2f + 0.8f * g6bFxRandom();
        }
        g6bFxVelocity[i * 2] = vx;
        g6bFxVelocity[i * 2 + 1] = vy;
    }
}
`;
}

export function structName(file: SvelteFile): string {
  const base = file.rel.replace(/\\/g, "/").split("/").pop() ?? file.ident;
  const n = base.replace(/\.svelte$/i, "");
  return n.charAt(0).toUpperCase() + n.slice(1);
}

function dModule(ident: string): string {
  return ident.replace(/_svelte$/, "").toLowerCase();
}

function escapeD(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\r/g, "\\r").replace(/\n/g, "\\n").replace(/\t/g, "\\t").replace(/\0/g, "\\0");
}
