// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
/** Print libwasm D IR (mixin NodeDef / @prop / @child). Not LDC. */

import { type MarkupNode, parseMarkupTree, type PgliteOp, type SvelteFile, type UiOp } from "./parse.ts";

// Member names that libwasm Spa!/NodeDef consult via __traits(hasMember) or
// mixin-defined symbols; a @child field may not reuse them.
const RESERVED_MEMBERS = new Set([
  "main", "ready", "g6bStaticDom", "construct", "onMount", "onUnmount", "compile",
  "registerRoutes", "update", "unmount", "remount", "dumpState", "loadState",
]);

export function childFieldName(struct: string): string {
  const base = struct.charAt(0).toLowerCase() + struct.slice(1);
  return RESERVED_MEMBERS.has(base) ? base + "Child" : base;
}

export function validateDProject(files: SvelteFile[]): void {
  const names = new Set<string>();
  for (const file of files) {
    const name = structName(file);
    if (!/^[A-Z][A-Za-z0-9_]*$/.test(name) || ["Spa", "NodeDef", "Empty", "Application"].includes(name)) {
      throw new Error(`reserved or invalid D component name: ${name}`);
    }
    if (names.has(name.toLowerCase())) throw new Error(`D module name collision: ${name}`);
    names.add(name.toLowerCase());
  }
  if (!files.some((file) => structName(file) === "App")) throw new Error("LDC generation requires App.svelte");
}

export function printModule(file: SvelteFile, children: string[] = []): string {
  const struct = structName(file);
  const members = new Set([...RESERVED_MEMBERS, "id"]);
  for (const name of [...file.lets.map((binding) => binding.name), ...children.map(childFieldName)]) {
    if (members.has(name)) throw new Error(`D member collision in ${struct}: ${name}`);
    members.add(name);
  }
  const lines: string[] = [];
  lines.push(`// Generated by browser-ui compiler from ${file.rel}`);
  lines.push(`//# svelte-d-ir orig=${file.rel} kind=file parse=first-party`);
  lines.push("module " + dModule(file.ident) + ";");
  lines.push("import libwasm;");
  for (const c of children) {
    lines.push(`import ${c.toLowerCase()};`);
  }
  lines.push("");
  lines.push("nothrow:");
  lines.push("@safe:");
  lines.push("");
  lines.push(`struct ${struct}`);
  lines.push("{");
  lines.push("nothrow:");
  lines.push("  @trusted:");
  lines.push(`  mixin NodeDef!"${file.tag}";`);
  for (const b of file.lets) {
    lines.push(`  @prop!"innerText" string ${b.name} = "${escapeD(b.value)}";`);
  }
  for (const c of children) {
    lines.push(`  @child ${c} ${childFieldName(c)};`);
  }
  lines.push("  void construct() @trusted { }");
  lines.push("  void onMount() { }");
  lines.push("  void onUnmount() { }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

export function printApp(files: SvelteFile[]): string {
  validateDProject(files);
  const extras = files.filter((f) => structName(f) !== "App");
  // Store.svelte is flattened into App.ready (ops + markup), not a Spa @child.
  // Other extras stay @child — flattening them would duplicate markup.
  const storeExtras = extras.filter((f) => structName(f) === "Store");
  const kids = extras.filter((f) => structName(f) !== "Store").map((f) => structName(f));
  const app = files.find((f) => structName(f) === "App")!;
  // `ready` keeps libwasm `Spa` off the JS router: without it _start calls
  // router().navigateTo(document().location()…), which needs browser-only
  // Object_Getter imports the g6b cell does not provide.
  const readyBody = printReady(app, storeExtras);
  const body = printModule(app, kids).replace(
    "  void onMount() { }",
    "  void onMount() { }\n  enum g6bStaticDom = true;\n" + readyBody,
  );
  return body + "mixin Spa!App;\n" + printFxD();
}

export function printReady(file: SvelteFile, extras: SvelteFile[] = []): string {
  const lines: string[] = [];
  lines.push("  void ready() {");
  // DOM construct may throw; .await must not share that landing pad
  // (Flatten + wasm-eh: svelte-d/architecture/AGENTS-D-IR-asyncify-wasm-eh.md).
  lines.push("    auto root = this.getNamedNode.node;");
  const roots = parseMarkupTree(file.src);
  const extraRoots = extras.map((f) => parseMarkupTree(f.src));
  const allOps = [...file.ops, ...extras.flatMap((f) => f.ops)];
  // DOM element ids that a pglite bind (`{rows}` / `{rows.field}`) will
  // paint after the DOM try block. Like tbody handles, these must be
  // hoisted out of the try so they stay in scope for the bind text emit.
  const bindTargetIds = new Set(
    allOps.filter((o): o is TextOp => o.kind === "text" && !!o.bind).map((o) => o.id),
  );
  const ctx: DTreeContext = {
    vars: new Map(),
    next: 0,
    tbody: new Map(),
    binds: new Set(
      allOps.filter((o): o is PgliteOp => o.kind === "pglite" && !!o.bind).map((o) => o.bind!),
    ),
    bindTargetIds,
  };
  if (roots[0]) collectHoistedHandles(roots[0], ctx);
  for (const er of extraRoots) {
    if (er[0]) collectHoistedHandles(er[0], ctx);
  }
  for (const v of ctx.tbody.values()) {
    // Hoist tbody + pglite-bind-target handles out of the DOM try so
    // await/parseJSON can append rows after rewind (Flatten deletes a
    // catch that wraps .await) and pglite binds can paint the handle.
    lines.push(`    Handle ${v} = 0;`);
  }
  lines.push("    try {");
  const root = roots[0];
  if (root) {
    for (const [name, value] of Object.entries(root.attrs)) {
      lines.push(`      setProperty(root, "${escapeD(name)}", "${escapeD(value)}");`);
    }
    for (const c of root.children) {
      lines.push(...printDNode(c, "root", ctx, 6));
    }
  }
  for (const er of extraRoots) {
    for (const c of er) {
      if (typeof c === "string") continue;
      lines.push(...printDNode(c, "root", ctx, 6));
    }
  }
  lines.push("    } catch (Exception e) {");
  lines.push("      // bounded catch: DOM construct");
  lines.push("    }");
  const fetches: { index: number; url: string; opIndex: number }[] = [];
  for (let i = 0; i < allOps.length; i++) {
    const op = allOps[i];
    if (op.kind === "fetch") {
      const needsAwait = allOps[i + 1]?.kind === "await";
      const h = fetches.length;
      fetches.push({ index: h, url: op.url, opIndex: i });
      lines.push(`    auto p${h} = g6b_fetch("${escapeD(op.url)}");`);
      if (needsAwait) {
        lines.push(`    libwasm_await__void(p${h});`);
        i++; // skip the await op
      }
    } else if (op.kind === "holyc") {
      lines.push(`    g6b_holyc("${escapeD(op.line)}");`);
    } else if (op.kind === "register") {
      lines.push(`    g6b_register("${escapeD(op.path)}", "${escapeD(op.method)}");`);
    }
  }
  const rows = printRowFetches(fetches, ctx);
  if (rows.length) {
    lines.push("    if (libwasm_await_supported()) {");
    lines.push(...rows.map((l) => "      " + l));
    lines.push("    }");
  }
  lines.push(...printPgliteReady({ ...file, ops: allOps }, ctx));
  lines.push("  }");
  return lines.join("\n");
}

type DTreeContext = {
  vars: Map<string, string>;
  next: number;
  tbody: Map<string, string>;
  binds: Set<string>;
  bindTargetIds: Set<string>;
};

function dVar(id: string | undefined, ctx: DTreeContext): string {
  if (id) {
    const safe = id.replace(/[^A-Za-z0-9_]/g, "_");
    const existing = ctx.vars.get(safe);
    if (existing) return existing;
    ctx.vars.set(safe, safe);
    return safe;
  }
  return `n${ctx.next++}`;
}

function collectHoistedHandles(node: MarkupNode | string, ctx: DTreeContext): void {
  if (typeof node === "string") return;
  if (node.attrs.id) {
    const isTbody = node.tag === "tbody";
    const isBindTarget = ctx.bindTargetIds.has(node.attrs.id);
    if (isTbody || isBindTarget) {
      ctx.tbody.set(node.attrs.id, dVar(node.attrs.id, ctx));
    }
  }
  for (const c of node.children) collectHoistedHandles(c, ctx);
}

function nodeTypeTag(tag: string): string {
  // libwasm NodeType uses `body_` and `template_` for D reserved words.
  if (tag === "body") return "body_";
  if (tag === "template") return "template_";
  return tag;
}

function menuTbodyId(url: string): string | undefined {
  const m = url.match(/^\/bios\/menu\/([a-z0-9-]+)$/);
  return m ? `menu-${m[1]}-body` : undefined;
}

function printRowFetches(fetches: { index: number; url: string }[], ctx: DTreeContext): string[] {
  const lines: string[] = [];
  for (const { index, url } of fetches) {
    const tbodyId = menuTbodyId(url);
    if (!tbodyId || !ctx.tbody.has(tbodyId)) continue;
    const tbody = ctx.tbody.get(tbodyId)!;
    const h = `p${index}`;
    const j = `j${index}`;
    lines.push(`libwasm_await__void(${h});`);
    lines.push(`try {`);
    lines.push(`  auto json_${h} = libwasm_await_value();`);
    lines.push(`  auto ${j} = parseJSON!ThreadMemAllocator(json_${h});`);
    lines.push(`  foreach (_; ${j}) {`);
    lines.push(`    string id = "", label = "", value = "";`);
    lines.push(`    bool writable = false;`);
    lines.push(`    foreach (key; ${j}.byKey) {`);
    lines.push(`      if (key == "id") id = ${j}.read!string;`);
    lines.push(`      else if (key == "label") label = ${j}.read!string;`);
    lines.push(`      else if (key == "value") value = ${j}.read!string;`);
    lines.push(`      else if (key == "writable") writable = ${j}.read!bool;`);
    lines.push(`      else ${j}.skipValue();`);
    lines.push(`    }`);
    lines.push(`    auto tr = createElement(NodeType.tr);`);
    lines.push(`    auto td0 = createElement(NodeType.td);`);
    lines.push(`    setProperty(td0, "innerText", label);`);
    lines.push(`    appendChild(tr, td0);`);
    lines.push(`    auto td1 = createElement(NodeType.td);`);
    lines.push(`    setProperty(td1, "innerText", value);`);
    lines.push(`    appendChild(tr, td1);`);
    lines.push(`    auto td2 = createElement(NodeType.td);`);
    lines.push(`    setProperty(td2, "innerText", writable ? "RW" : "R");`);
    lines.push(`    appendChild(tr, td2);`);
    lines.push(`    appendChild(${tbody}, tr);`);
    lines.push(`  }`);
    lines.push(`} catch (Exception e) {}`);
  }
  return lines;
}

function bindInterp(text: string, binds: Set<string>): { bind: string; field?: string } | undefined {
  const m = text.trim().match(/^\{([A-Za-z_][A-Za-z0-9_]*)(?:\.([A-Za-z_][A-Za-z0-9_]*))?\}$/);
  if (!m || !binds.has(m[1])) return undefined;
  return m[2] ? { bind: m[1], field: m[2] } : { bind: m[1] };
}

function printDNode(node: MarkupNode | string, parent: string, ctx: DTreeContext, indent: number): string[] {
  const pad = " ".repeat(indent);
  if (typeof node === "string") {
    if (bindInterp(node, ctx.binds)) return [];
    return [`${pad}setProperty(${parent}, "innerText", "${escapeD(node)}");`];
  }
  const id = node.attrs.id;
  const varName = dVar(id, ctx);
  const out: string[] = [];
  const hoisted = id !== undefined && ctx.tbody.has(id);
  out.push(
    `${pad}${hoisted ? "" : "auto "}${varName} = createElement(NodeType.${nodeTypeTag(node.tag)});`,
  );
  for (const [name, value] of Object.entries(node.attrs)) {
    if (name.startsWith("on:")) continue;
    out.push(`${pad}setProperty(${varName}, "${escapeD(name)}", "${escapeD(value)}");`);
  }
  for (const c of node.children) {
    out.push(...printDNode(c, varName, ctx, indent));
  }
  if (node.tag === "tbody" && id) ctx.tbody.set(id, varName);
  out.push(`${pad}appendChild(${parent}, ${varName});`);
  // Cell-owned clicks (B87/B92): setup tabs, `#refresh`, window/tab chrome.
  if (
    id &&
    (node.attrs["data-menu-link"] !== undefined ||
      node.attrs["data-window-action"] !== undefined ||
      node.attrs["data-tab-action"] !== undefined ||
      id === "refresh")
  ) {
    out.push(`${pad}g6b_listen("${escapeD(id)}", "click");`);
  }
  return out;
}

export function printFxD(): string {
  return `
private struct G6bFxParticle { float x, y, intensity, size; }
static assert(G6bFxParticle.sizeof == 16);
private __gshared G6bFxParticle[256] g6bFxParticles;
private __gshared float[512] g6bFxVelocity;
private __gshared float[2] g6bFxLogo;
private __gshared float[2] g6bFxLogoVelocity = [0.17f, 0.12f];
private __gshared uint g6bFxSeed = 0x6C696272;
private __gshared bool g6bFxReady;

private float g6bFxRandom() @trusted @nogc
{
    g6bFxSeed ^= g6bFxSeed << 13;
    g6bFxSeed ^= g6bFxSeed >> 17;
    g6bFxSeed ^= g6bFxSeed << 5;
    return cast(float)(g6bFxSeed & 0xFFFFFF) / 16777216.0f;
}

private float g6bFxClamp(float value, float low, float high) @safe @nogc
{
    return value < low ? low : (value > high ? high : value);
}

extern(C) export uint g6b_fx_data() @trusted @nogc
{
    return cast(uint)g6bFxParticles.ptr;
}

extern(C) export uint g6b_fx_count() @safe @nogc
{
    return 256;
}

extern(C) export uint g6b_fx_logo() @trusted @nogc
{
    return cast(uint)g6bFxLogo.ptr;
}

extern(C) export void g6b_fx_step(float dt) @trusted @nogc
{
    if (!g6bFxReady)
    {
        foreach (i; 0 .. 256)
        {
            g6bFxParticles[i] = G6bFxParticle(g6bFxRandom() * 2.0f - 1.0f,
                g6bFxRandom() * 2.0f - 1.0f, 0.35f + 0.65f * g6bFxRandom(),
                2.0f + 8.0f * g6bFxRandom());
            g6bFxVelocity[i * 2] = (g6bFxRandom() - 0.5f) * 0.2f;
            g6bFxVelocity[i * 2 + 1] = (g6bFxRandom() - 0.5f) * 0.2f;
        }
        g6bFxLogo[] = 0.0f;
        g6bFxReady = true;
    }
    if (!(dt > 0.0f)) return;
    if (dt > 0.05f) dt = 0.05f;
    foreach (axis; 0 .. 2)
    {
        const limit = axis == 0 ? 0.76f : 0.78f;
        g6bFxLogo[axis] += g6bFxLogoVelocity[axis] * dt;
        if (g6bFxLogo[axis] > limit || g6bFxLogo[axis] < -limit)
        {
            g6bFxLogo[axis] = g6bFxClamp(g6bFxLogo[axis], -limit, limit);
            g6bFxLogoVelocity[axis] = -g6bFxLogoVelocity[axis];
        }
    }
    foreach (i; 0 .. 256)
    {
        auto p = &g6bFxParticles[i];
        const dx = g6bFxLogo[0] - p.x;
        const dy = g6bFxLogo[1] - p.y;
        const force = 0.12f / (0.08f + dx * dx + dy * dy);
        float vx = g6bFxVelocity[i * 2];
        float vy = g6bFxVelocity[i * 2 + 1];
        vx = (vx + (dx * 0.30f - dy * 0.80f) * force * dt) * (1.0f - 0.18f * dt);
        vy = (vy + ((dy * 0.30f + dx * 0.80f) * force - 0.10f) * dt) * (1.0f - 0.18f * dt);
        vx = g6bFxClamp(vx, -1.5f, 1.5f);
        vy = g6bFxClamp(vy, -1.5f, 1.5f);
        p.x += vx * dt;
        p.y += vy * dt;
        p.intensity -= 0.18f * dt;
        if (p.x < -1.0f || p.x > 1.0f || p.y < -1.0f || p.y > 1.0f || p.intensity < 0.1f)
        {
            p.x = g6bFxLogo[0] + (g6bFxRandom() - 0.5f) * 0.05f;
            p.y = g6bFxLogo[1] + (g6bFxRandom() - 0.5f) * 0.05f;
            p.intensity = 0.55f + 0.45f * g6bFxRandom();
            p.size = 2.0f + 8.0f * g6bFxRandom();
            vx = (g6bFxRandom() - 0.5f) * 1.4f;
            vy = 0.2f + 0.8f * g6bFxRandom();
        }
        g6bFxVelocity[i * 2] = vx;
        g6bFxVelocity[i * 2 + 1] = vy;
    }
}
`;
}

export function structName(file: SvelteFile): string {
  const base = file.rel.replace(/\\/g, "/").split("/").pop() ?? file.ident;
  const n = base.replace(/\.svelte$/i, "");
  return n.charAt(0).toUpperCase() + n.slice(1);
}

function dModule(ident: string): string {
  return ident.replace(/_svelte$/, "").toLowerCase();
}

function printPgliteReady(file: SvelteFile, ctx: DTreeContext): string[] {
  const ops = file.ops.filter((o): o is PgliteOp => o.kind === "pglite");
  if (!ops.length) return [];
  const open = [...ops].reverse().find((o) => o.method === "open");
  const lines: string[] = [];
  if (open && open.arg1) {
    lines.push(`    auto db = PgLite("${escapeD(open.arg1)}");`);
  } else {
    lines.push("    auto db = PgLite();");
  }
  const emit = (op: PgliteOp, expr: string) => {
    if (op.bind) {
      if (ctx.vars.has(op.bind) || op.bind === "db" || op.bind === "root") {
        throw new Error(`pglite bind collides with DOM id or reserved name: ${op.bind}`);
      }
      lines.push(`    auto ${op.bind} = ${expr};`);
    } else {
      lines.push(`    ${expr};`);
    }
  };
  for (const op of ops) {
    switch (op.method) {
      case "open":
        break;
      case "exec":
        emit(op, `db.exec("${escapeD(op.arg1)}")`);
        break;
      case "queryAsync":
        emit(op, `db.queryAsync("${escapeD(op.arg1)}", "${escapeD(op.arg2 || "[]")}")`);
        break;
      case "query":
        if (op.awaited) {
          emit(op, `db.queryAsync("${escapeD(op.arg1)}", "${escapeD(op.arg2 || "[]")}")`);
        } else {
          emit(op, `db.query("${escapeD(op.arg1)}", "${escapeD(op.arg2 || "[]")}")`);
        }
        break;
      case "stat":
        emit(op, op.awaited ? "db.statAsync()" : "db.stat()");
        break;
      case "waitReady":
        emit(op, "db.waitReady()");
        break;
      case "listen":
        emit(op, `db.listen("${escapeD(op.arg1)}")`);
        break;
      case "unlisten":
        emit(op, `db.unlisten("${escapeD(op.arg1 || "*")}")`);
        break;
      case "notifies":
        emit(op, "db.notifies()");
        break;
      case "begin":
        emit(op, "db.begin()");
        break;
      case "commit":
        emit(op, "db.commit()");
        break;
      case "rollback":
        emit(op, "db.rollback()");
        break;
      case "dump":
        emit(op, "db.dump()");
        break;
      case "load":
        emit(op, `db.load("${escapeD(op.arg1)}")`);
        break;
      case "close":
        emit(op, "db.close()");
        break;
      case "export":
        emit(
          op,
          op.arg2
            ? `db.exportUsb("${escapeD(op.arg1)}", "${escapeD(op.arg2)}")`
            : `db.exportUsb("${escapeD(op.arg1)}")`,
        );
        break;
    }
  }
  lines.push(...printPgliteBindTexts(file.ops, ctx));
  return lines;
}

function printPgliteBindTexts(ops: UiOp[], ctx: DTreeContext): string[] {
  const lines: string[] = [];
  let n = 0;
  for (const op of ops) {
    if (op.kind !== "text" || !op.bind) continue;
    const handle = ctx.vars.get(op.id.replace(/[^A-Za-z0-9_]/g, "_"));
    if (!handle) throw new Error(`pglite bind {${op.bind}} needs a DOM id: ${op.id}`);
    if (op.field) {
      const tmp = `pglite_field_${n++}`;
      lines.push(`    auto ${tmp} = ${op.bind}["${escapeD(op.field)}"];`);
      lines.push(`    setProperty(${handle}, "innerText", JSON.stringify(${tmp}));`);
    } else {
      lines.push(`    setProperty(${handle}, "innerText", JSON.stringify(${op.bind}));`);
    }
  }
  return lines;
}

function escapeD(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\r/g, "\\r").replace(/\n/g, "\\n").replace(/\t/g, "\\t").replace(/\0/g, "\\0");
}
