# Copyright (c) 2026 Etienne Cimon
# SPDX-License-Identifier: MIT

[package]
name = "g6b-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "WASM MVP decoder + host JIT + RISC-V lower for BIOS UI"

[dependencies]
g6b-asm = { workspace = true }
g6b-dom = { workspace = true }

[lints]
workspace = true
