// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
//
// Emit SystemVerilog + origin comments + integrity reparse.

#![deny(missing_docs)]
#![forbid(unsafe_code)]

//! Synthesis of rewritten SystemVerilog trees and integrity checks.
//! See `architecture/AUTO-CORRECT-CORE-API.md` §3.7–3.9.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use sv_timing_core::{
    parse_paths, CoreError, CoreResult, ParseOptions, SourceLoc, TimingDesign,
};
use sv_timing_transform::{EditKind, EditRecord, EditTrace};

pub mod dense;
pub mod project;
pub mod rhs;
pub mod synth;

pub use dense::{
    dense_autocorrect_block, dense_autocorrect_block_with_cuts, dense_options_from_source,
    emit_blocks_for_trace, emit_blocks_for_trace_src, min_density_score_for_edits,
    min_density_score_for_trace, DenseEmitOptions, DensityReport, EmitBlocks,
};
pub use project::{
    edits_for_source, emit_project_autocorrect, emit_rel_for_source, infer_source_root,
    new_modules_from_trace, synthesize_project, write_project_emit, EmitManifestEntry,
    ProjectEmitOptions, ProjectEmitResult, ProjectLayout,
};
pub use rhs::{
    cut_assigns_from_source, has_free_gen_index, line_inside_generate, parse_assign_line,
    all_emit_extra_cuts, primary_feed_expr, remainder_sandwich_extra_cuts,
    rewrite_origin_assigns, rewrite_origin_rhs_replaces, sibling_span_extra_cuts,
    sink_assigns_sv, unresolved_insert_regs, CutAssign,
};
pub use synth::{synthesize_module, synthesize_module_with, SynthOptions};

/// Role of an emit file.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FileRole {
    /// Primary module source.
    Module,
    /// Package / header.
    Package,
    /// Testbench (integrity sim).
    Testbench,
    /// Other.
    Other,
}

/// One logical file to write.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmitFile {
    /// Relative path under emit root.
    pub rel_path: PathBuf,
    /// Role.
    pub role: FileRole,
    /// Full text.
    pub text: String,
}

/// Planned output tree.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EmitTree {
    /// Files keyed by relative path string.
    pub files: BTreeMap<String, EmitFile>,
    /// Insertion order of keys (preserve source flist order for joint reparse).
    /// BTreeMap alone would reparse packages alphabetically after modules.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub order: Vec<String>,
}

impl EmitTree {
    /// Empty tree.
    pub fn new() -> Self {
        Self::default()
    }

    /// Register / replace a file (order preserved for first insert).
    pub fn add_file(&mut self, rel_path: impl Into<PathBuf>, role: FileRole, text: String) {
        let rel_path = rel_path.into();
        let key = rel_path.to_string_lossy().replace('\\', "/");
        if !self.files.contains_key(&key) {
            self.order.push(key.clone());
        }
        self.files.insert(
            key,
            EmitFile {
                rel_path,
                role,
                text,
            },
        );
    }

    /// Paths in insertion order (falls back to BTreeMap order if `order` empty).
    pub fn ordered_keys(&self) -> Vec<String> {
        if !self.order.is_empty() {
            self.order
                .iter()
                .filter(|k| self.files.contains_key(k.as_str()))
                .cloned()
                .collect()
        } else {
            self.files.keys().cloned().collect()
        }
    }
}

/// Emit policy.
#[derive(Debug, Clone)]
pub struct EmitPolicy {
    /// Tool name in headers.
    pub tool: String,
    /// Run id.
    pub run_id: String,
    /// Inject origin comments.
    pub origin_comments: bool,
}

impl Default for EmitPolicy {
    fn default() -> Self {
        Self {
            tool: "sv-timing".into(),
            run_id: "local".into(),
            origin_comments: true,
        }
    }
}

/// Machine-generated file header.
pub fn machine_header(tool: &str, run_id: &str) -> String {
    format!(
        "// Generated by {tool} (run_id={run_id})\n\
         // DO NOT commit without human review.\n\
         // SPDX-FileCopyrightText: machine-generated\n"
    )
}

/// Format origin debug comment (original file:line).
pub fn origin_comment(loc: &SourceLoc, edit_id: Option<u32>) -> String {
    match edit_id {
        Some(id) => format!(
            "// sv-timing: origin {}:{}:{} edit={id}\n",
            loc.file, loc.start_line, loc.start_col
        ),
        None => format!(
            "// sv-timing: origin {}:{}:{}\n",
            loc.file, loc.start_line, loc.start_col
        ),
    }
}

/// Annotate emit tree texts with edit origins (prepend after header if missing).
pub fn annotate_origin_comments(tree: &mut EmitTree, trace: &EditTrace) {
    if trace.records.is_empty() {
        return;
    }
    let block: String = trace
        .records
        .iter()
        .map(|r| origin_comment(&r.origin, Some(r.id)))
        .collect();
    for f in tree.files.values_mut() {
        if !f.text.contains("sv-timing: origin") {
            // Insert after first header block if present
            if let Some(pos) = f.text.find('\n') {
                let (head, rest) = f.text.split_at(pos + 1);
                // Keep scanning header lines
                let mut idx = head.len();
                for line in rest.lines() {
                    if line.starts_with("//") {
                        idx += line.len() + 1;
                    } else {
                        break;
                    }
                }
                let mut new_text = String::new();
                new_text.push_str(&f.text[..idx]);
                new_text.push_str(&block);
                new_text.push_str(&f.text[idx..]);
                f.text = new_text;
            } else {
                f.text = format!("{block}{}", f.text);
            }
        }
    }
}

/// Build emit tree from design IR via [`synthesize_module`].
pub fn synthesize_design(design: &TimingDesign, policy: &EmitPolicy) -> EmitTree {
    let mut tree = EmitTree::new();
    for module in design.modules.values() {
        let stem = format!("{}{}", module.name, "__svt");
        let path = format!("{stem}.sv");
        tree.add_file(path, FileRole::Module, synthesize_module(module, policy));
    }
    tree
}

/// Apply auto-correct edits to original module source.
///
/// 1. **RHS rewrite** of origin assign lines → sample new pipe regs (sinks in dense block).
/// 2. **Early inject** (before first process): BalanceMux arm staging wires referenced by
///    origin RHS rewrites.
/// 3. **Late inject** (before `endmodule`): InsertReg dense pipe with real cut feeds
///    (`pipe_c = (origin_rhs)`), so feeds may use mid-module nets (R11 / Verilator order).
pub fn apply_edits_to_source(source: &str, trace: &EditTrace, policy: &EmitPolicy) -> String {
    let dense = dense_options_from_source(source);
    apply_edits_to_source_dense(source, trace, policy, &dense)
}

/// Same as [`apply_edits_to_source`] with explicit dense options (clk/rst names, width).
pub fn apply_edits_to_source_dense(
    source: &str,
    trace: &EditTrace,
    policy: &EmitPolicy,
    dense: &DenseEmitOptions,
) -> String {
    if trace.records.is_empty() {
        return source.to_string();
    }
    let cuts = cut_assigns_from_source(source, trace);
    // R12e lean default: do **not** rewrite origins or emit continuous sinks.
    // Pipe stages still emit with zero feeds (FO4 screening sidecar). Origin
    // rewrites and BalanceMux RTL remain opt-in for review fixtures.
    //
    // BalanceMux RHS rewrite **before** InsertReg: InsertReg injects a comment
    // line per cut and shifts later origin lines (`audit-remain-v22` rewrote
    // `stc_elem_q` instead of `dot_pending_q` at gemm :1859).
    let after_bm = if dense.emit_balance_mux_rtl {
        rewrite_origin_rhs_replaces(source, trace)
    } else {
        source.to_string()
    };
    let extras = if dense.real_cut_feeds {
        all_emit_extra_cuts(&after_bm, &cuts)
    } else {
        Vec::new()
    };
    let rewritten = if dense.real_cut_feeds {
        rewrite_origin_assigns(&after_bm, &cuts)
    } else {
        after_bm
    };
    // Without real feeds, still pass cuts for stage naming; sinks suppressed below.
    let mut cuts_for_dense: Vec<_> = if dense.real_cut_feeds {
        cuts
    } else {
        // Drop continuous flag so sink_assigns_sv emits nothing.
        cuts
            .into_iter()
            .map(|mut c| {
                c.continuous = false;
                c.line = 0; // no origin rewrite path
                c.lhs.clear();
                c
            })
            .collect()
    };
    // Sibling extras rewrite in-place inside named generate-if; do **not**
    // emit module-scope sinks for generate-locals. Feed-only dense cuts
    // (empty lhs) plus extra InsertReg records so the pipe decls exist.
    let mut emit_trace_owned: Option<EditTrace> = None;
    if !extras.is_empty() {
        let mut t = trace.clone();
        let seed_origin = t
            .records
            .iter()
            .find(|r| r.kind == EditKind::InsertReg)
            .map(|r| r.origin.clone());
        for extra in &extras {
            let mut origin = seed_origin
                .clone()
                .unwrap_or_else(|| SourceLoc::file_start(extra.pipe_name.as_str()));
            origin.start_line = extra.line;
            origin.end_line = extra.end_line.max(extra.line);
            t.record_edit(EditRecord {
                id: 0,
                kind: EditKind::InsertReg,
                origin,
                path_id: None,
                node_id: None,
                new_name: Some(extra.pipe_name.clone()),
                fo4_before: None,
                fo4_after: None,
                rationale: format!("emit extra {}", extra.lhs),
                emit_rhs: None,
                emit_rhs_extras: Vec::new(),
                emit_snippet: None,
            });
            cuts_for_dense.push(CutAssign {
                line: 0,
                end_line: 0,
                lhs: String::new(),
                rhs: extra.rhs.clone(),
                nonblocking: false,
                pipe_name: extra.pipe_name.clone(),
                edit_id: extra.edit_id,
                continuous: false,
            });
        }
        emit_trace_owned = Some(t);
    }
    let emit_trace = emit_trace_owned.as_ref().unwrap_or(trace);
    let blocks =
        dense::emit_blocks_for_trace_src(emit_trace, dense, &cuts_for_dense, Some(source));
    let header = machine_header(&policy.tool, &policy.run_id);
    // Dual inject (R11):
    // - early: factorize comments / first-process-safe review
    // - origin process: BalanceMux RTL (after mid-module decls; gemm pe_float_en)
    // - late: dense pipe before endmodule (cut feeds may reference mid-module nets)
    let rewritten = inject_before_first_process(&rewritten, &blocks.early);
    let rewritten = inject_bm_snippets_at_origin(&rewritten, &blocks.bm_at_origin);
    let rewritten = inject_before_endmodule(&rewritten, &blocks.late);
    let mut out = String::new();
    out.push_str(&header);
    out.push_str(&rewritten);
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

fn masked_syntax(source: &str) -> String {
    let bytes = source.as_bytes();
    let mut masked = bytes.to_vec();
    let mut i = 0;
    while i < bytes.len() {
        let start = i;
        if bytes[i..].starts_with(b"//") {
            while i < bytes.len() && bytes[i] != b'\n' { i += 1; }
        } else if bytes[i..].starts_with(b"/*") {
            i += 2;
            while i < bytes.len() && !bytes[i..].starts_with(b"*/") { i += 1; }
            i = (i + 2).min(bytes.len());
        } else if bytes[i] == b'"' {
            i += 1;
            while i < bytes.len() {
                if bytes[i] == b'\\' {
                    i = (i + 2).min(bytes.len());
                } else if bytes[i] == b'"' {
                    i += 1;
                    break;
                } else {
                    i += 1;
                }
            }
        } else if bytes[i] == b'\\' {
            while i < bytes.len() && !bytes[i].is_ascii_whitespace() { i += 1; }
        } else {
            i += 1;
            continue;
        }
        for ch in &mut masked[start..i] {
            if *ch != b'\n' && *ch != b'\r' { *ch = b' '; }
        }
    }
    String::from_utf8(masked).expect("mask preserves source UTF-8")
}

fn keyword_positions<'a>(text: &'a str, key: &'a str) -> impl Iterator<Item = usize> + 'a {
    text.match_indices(key).filter_map(move |(i, _)| {
        let ident = |b: &u8| b.is_ascii_alphanumeric() || matches!(b, b'_' | b'$');
        let before = i.checked_sub(1).and_then(|j| text.as_bytes().get(j));
        let after = text.as_bytes().get(i + key.len());
        (!before.is_some_and(ident) && !after.is_some_and(ident)).then_some(i)
    })
}

/// Insert `block` before the first procedural/continuous process in the module body.
///
/// Used so BalanceMux intermediate wires are declared before origin RHS rewrites
/// that reference them. Falls back to pre-`endmodule` placement.
fn inject_before_first_process(source: &str, block: &str) -> String {
    if block.trim().is_empty() {
        return source.to_string();
    }
    // Prefer first always_* / assign after module header.
    let lower = masked_syntax(source);
    let mut best: Option<usize> = None;
    for key in [
        "always_comb",
        "always_ff",
        "always_latch",
        "always",
        "assign",
    ] {
        if let Some(i) = keyword_positions(&lower, key).next() {
            // Only consider hits after "module "
            if let Some(mod_i) = keyword_positions(&lower, "module").next() {
                if i > mod_i {
                    best = Some(best.map_or(i, |b| b.min(i)));
                }
            }
        }
    }
    if let Some(i) = best {
        let mut out = String::with_capacity(source.len() + block.len() + 8);
        out.push_str(&source[..i]);
        if !out.ends_with('\n') {
            out.push('\n');
        }
        out.push_str(block);
        if !block.ends_with('\n') {
            out.push('\n');
        }
        out.push_str(&source[i..]);
        return out;
    }
    inject_before_endmodule(source, block)
}

/// Insert each BalanceMux snippet immediately before the process that
/// references its marker ident (origin RHS rewrite).
fn inject_bm_snippets_at_origin(source: &str, jobs: &[(String, String)]) -> String {
    if jobs.is_empty() {
        return source.to_string();
    }
    let mut at: BTreeMap<usize, String> = BTreeMap::new();
    let mut fallback = String::new();
    for (marker, snippet) in jobs {
        if marker.is_empty() || snippet.trim().is_empty() {
            continue;
        }
        let Some(pos) = enclosing_process_byte_for_marker(source, marker) else {
            fallback.push_str(snippet);
            if !snippet.ends_with('\n') {
                fallback.push('\n');
            }
            continue;
        };
        let entry = at.entry(pos).or_default();
        if !snippet.ends_with('\n') {
            entry.push_str(snippet);
            entry.push('\n');
        } else {
            entry.push_str(snippet);
        }
    }
    if at.is_empty() {
        if fallback.is_empty() {
            return source.to_string();
        }
        let mut block = String::from("  // BEGIN sv-timing auto-correct (balance_mux rewrite)\n");
        block.push_str(&fallback);
        block.push_str("  // END sv-timing auto-correct (balance_mux rewrite)\n");
        return inject_before_first_process(source, &block);
    }
    let mut out = source.to_string();
    // Later byte offsets first so earlier inserts stay valid.
    let mut positions: Vec<(usize, String)> = at.into_iter().collect();
    positions.sort_by_key(|(p, _)| std::cmp::Reverse(*p));
    for (pos, body) in positions {
        let mut block = String::from("  // BEGIN sv-timing auto-correct (balance_mux rewrite)\n");
        block.push_str(&body);
        if !body.ends_with('\n') {
            block.push('\n');
        }
        block.push_str("  // END sv-timing auto-correct (balance_mux rewrite)\n");
        let mut next = String::with_capacity(out.len() + block.len() + 8);
        next.push_str(&out[..pos]);
        if !next.ends_with('\n') {
            next.push('\n');
        }
        next.push_str(&block);
        if !block.ends_with('\n') {
            next.push('\n');
        }
        next.push_str(&out[pos..]);
        out = next;
    }
    if !fallback.is_empty() {
        let mut block = String::from("  // BEGIN sv-timing auto-correct (balance_mux rewrite)\n");
        block.push_str(&fallback);
        block.push_str("  // END sv-timing auto-correct (balance_mux rewrite)\n");
        out = inject_before_first_process(&out, &block);
    }
    out
}

fn ident_boundary(b: u8) -> bool {
    !(b.is_ascii_alphanumeric() || b == b'_')
}

/// Byte offset of the `always_*` / `assign` line that contains `marker`.
fn enclosing_process_byte_for_marker(source: &str, marker: &str) -> Option<usize> {
    let bytes = source.as_bytes();
    let m = marker.as_bytes();
    if m.is_empty() {
        return None;
    }
    let mut i = 0usize;
    let mut hit = None;
    while i + m.len() <= bytes.len() {
        if &bytes[i..i + m.len()] == m {
            let before_ok = i == 0 || ident_boundary(bytes[i - 1]);
            let after_ok = i + m.len() == bytes.len() || ident_boundary(bytes[i + m.len()]);
            if before_ok && after_ok {
                hit = Some(i);
                break;
            }
        }
        i += 1;
    }
    let pos = hit?;
    let mut i = pos;
    loop {
        while i > 0 && bytes[i - 1] != b'\n' {
            i -= 1;
        }
        let rest = &source[i..];
        let t = rest.trim_start();
        let lower = t.to_ascii_lowercase();
        if lower.starts_with("always_comb")
            || lower.starts_with("always_ff")
            || lower.starts_with("always_latch")
            || lower.starts_with("always ")
            || lower.starts_with("always@")
            || lower.starts_with("always @")
            || lower.starts_with("assign ")
            || lower.starts_with("assign\t")
        {
            return Some(i);
        }
        if i == 0 {
            return Some(pos);
        }
        i -= 1;
        while i > 0 && bytes[i - 1] != b'\n' {
            i -= 1;
        }
    }
}

/// Insert `block` immediately before the last `endmodule` in `source`.
fn inject_before_endmodule(source: &str, block: &str) -> String {
    if block.trim().is_empty() {
        return source.to_string();
    }
    let masked = masked_syntax(source);
    if let Some(idx) = keyword_positions(&masked, "endmodule").last() {
        let mut out = String::with_capacity(source.len() + block.len() + 8);
        out.push_str(&source[..idx]);
        if !out.ends_with('\n') {
            out.push('\n');
        }
        out.push_str(block);
        if !block.ends_with('\n') {
            out.push('\n');
        }
        out.push_str(&source[idx..]);
        out
    } else {
        format!("{source}\n{block}")
    }
}

/// Build emit tree from original sources + edit trace (one file per source path).
pub fn synthesize_corrected_sources(
    sources: &[(PathBuf, String)],
    trace: &EditTrace,
    policy: &EmitPolicy,
) -> EmitTree {
    let mut tree = EmitTree::new();
    for (path, src) in sources {
        let stem = path
            .file_stem()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| "corrected".into());
        let rel = PathBuf::from(format!("{stem}__svt.sv"));
        let text = apply_edits_to_source(src, trace, policy);
        tree.add_file(rel, FileRole::Module, text);
    }
    tree
}

/// Passthrough: wrap original source with header + optional origin (integrity baseline).
pub fn synthesize_passthrough_file(
    rel_path: impl Into<PathBuf>,
    source: &str,
    policy: &EmitPolicy,
    origin: Option<&SourceLoc>,
) -> EmitFile {
    let rel_path = rel_path.into();
    let mut text = machine_header(&policy.tool, &policy.run_id);
    if let Some(loc) = origin {
        text.push_str(&origin_comment(loc, None));
    }
    text.push_str(source);
    if !source.ends_with('\n') {
        text.push('\n');
    }
    EmitFile {
        rel_path,
        role: FileRole::Module,
        text,
    }
}

/// Write emit tree under `root_dir`.
pub fn write_emit_tree(tree: &EmitTree, root_dir: impl AsRef<Path>) -> CoreResult<Vec<PathBuf>> {
    let root = root_dir.as_ref();
    let mut written = Vec::new();
    for f in tree.files.values() {
        let path = root.join(&f.rel_path);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|source| CoreError::Io {
                path: parent.to_path_buf(),
                source,
            })?;
        }
        std::fs::write(&path, &f.text).map_err(|source| CoreError::Io {
            path: path.clone(),
            source,
        })?;
        written.push(path);
    }
    Ok(written)
}

/// Integrity report after emit.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IntegrityReport {
    /// All files reparsed OK (joint **or** edited-only syntax clean).
    pub reparse_ok: bool,
    /// Per-file messages.
    pub messages: Vec<String>,
    /// Structural OK (stub always true until checks land).
    pub structural_ok: bool,
    /// Lint ran.
    pub lint_ran: bool,
    /// Lint ok (or skipped).
    pub lint_ok: bool,
    /// Sim ran.
    pub sim_ran: bool,
    /// Sim ok (or skipped).
    pub sim_ok: bool,
    /// Joint full-tree reparse succeeded.
    #[serde(default)]
    pub joint_ok: bool,
    /// Edited files had only define/include context gaps (not syntax damage).
    #[serde(default)]
    pub context_soft: bool,
}

/// True when the emit text carries an auto-correct region (edited, not pure passthrough).
fn is_edited_emit_text(text: &str) -> bool {
    text.contains("BEGIN sv-timing auto-correct")
        || text.contains("sv-timing auto-correct")
}

/// Classify solo reparse failure as host **context** (defines/includes) vs syntax.
fn is_context_only_parse_error(msg: &str) -> bool {
    let m = msg.to_ascii_lowercase();
    m.contains("definenotfound")
        || m.contains("define not found")
        || m.contains("incompletename")
        || m.contains("include")
        || m.contains("filenotfound")
        || m.contains("file not found")
}

/// Reparse every emit file with the same front end (mandatory integrity).
///
/// **Full-core monorepo trees:** joint reparse must use **source order** (not
/// BTreeMap alphabetical) so packages define macros before modules. When joint
/// still fails (host macros / passthrough noise), integrity is judged on
/// **edited** files only: syntax damage fails hard; `DefineNotFound` alone is
/// recorded as `context_soft` and does **not** clear `reparse_ok` if no edited
/// file has a non-context parse error.
pub fn integrity_reparse(tree: &EmitTree, opts: &ParseOptions) -> IntegrityReport {
    integrity_reparse_ex(tree, opts, None)
}

/// Like [`integrity_reparse`], with optional map of emit relative path → original
/// source path. When solo emit parse fails but the **original** file also fails
/// under the same options, the failure is treated as pre-existing parser limit
/// (context soft), not emit damage — common for vendor `.v` / huge CSR cases.
pub fn integrity_reparse_ex(
    tree: &EmitTree,
    opts: &ParseOptions,
    origin_sources: Option<&BTreeMap<String, PathBuf>>,
) -> IntegrityReport {
    let mut report = IntegrityReport {
        reparse_ok: true,
        structural_ok: true,
        lint_ok: true,
        sim_ok: true,
        joint_ok: false,
        context_soft: false,
        ..Default::default()
    };
    // Unique dir per call so parallel tests do not race on the same path.
    let tmp = std::env::temp_dir().join(format!(
        "sv-timing-integrity-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0)
    ));
    if let Err(e) = std::fs::create_dir_all(&tmp) {
        report.reparse_ok = false;
        report.messages.push(format!("tmpdir failed: {e}"));
        return report;
    }
    if let Err(e) = write_emit_tree(tree, &tmp) {
        report.reparse_ok = false;
        report.messages.push(format!("write failed: {e}"));
        let _ = std::fs::remove_dir_all(&tmp);
        return report;
    }

    // Preserve synthesize/source order for joint parse.
    let keys = tree.ordered_keys();
    let mut paths = Vec::new();
    let mut edited_paths: Vec<(String, PathBuf)> = Vec::new();
    for k in &keys {
        let Some(f) = tree.files.get(k) else {
            continue;
        };
        let p = tmp.join(&f.rel_path);
        if is_edited_emit_text(&f.text) {
            edited_paths.push((k.clone(), p.clone()));
        }
        paths.push(p);
    }

    // Joint parse first (packages + modules must see each other, in flist order).
    match parse_paths(&paths, opts) {
        Ok(unit) => {
            report.joint_ok = true;
            report.reparse_ok = true;
            report
                .messages
                .push(format!("joint reparse ok: {} file(s)", unit.files.len()));
            let _ = std::fs::remove_dir_all(&tmp);
            return report;
        }
        Err(e) => {
            report
                .messages
                .push(format!("joint reparse failed: {e}"));
        }
    }

    // Fallback: judge **edited** files for syntax damage. Passthrough copies of
    // host RTL often need macros from the full package graph; DefineNotFound on
    // solo is context, not emit corruption.
    let mut solo = opts.clone();
    solo.ignore_include_error = true;
    // Allow incomplete defines when probing solo — surface DefineNotFound cleanly.
    solo.allow_parse_errors = false;

    let probe_set: Vec<(String, PathBuf)> = if edited_paths.is_empty() {
        // No auto-correct markers — probe every file.
        keys.iter()
            .filter_map(|k| {
                tree.files
                    .get(k)
                    .map(|f| (k.clone(), tmp.join(&f.rel_path)))
            })
            .collect()
    } else {
        edited_paths
    };

    let mut hard_fail = 0usize;
    let mut context_only = 0usize;
    for (name, p) in &probe_set {
        match parse_paths(std::slice::from_ref(p), &solo) {
            Ok(_) => {}
            Err(e2) => {
                let msg = format!("{e2}");
                let fname = Path::new(name)
                    .file_name()
                    .and_then(|s| s.to_str())
                    .unwrap_or(name.as_str());
                if is_context_only_parse_error(&msg) {
                    context_only += 1;
                    report
                        .messages
                        .push(format!("solo context {fname}: {msg}"));
                    continue;
                }
                // Pre-existing: original source also fails solo → not emit damage.
                let mut preexisting = false;
                if let Some(map) = origin_sources {
                    if let Some(orig) = map.get(name).or_else(|| {
                        // Match by basename when keys differ slightly.
                        map.iter()
                            .find(|(k, _)| {
                                Path::new(k).file_name() == Path::new(name).file_name()
                            })
                            .map(|(_, v)| v)
                    }) {
                        if orig.is_file()
                            && parse_paths(std::slice::from_ref(orig), &solo).is_err()
                        {
                            preexisting = true;
                        }
                    }
                }
                if preexisting {
                    context_only += 1;
                    report.messages.push(format!(
                        "solo preexisting {fname}: {msg} (original also fails)"
                    ));
                } else {
                    hard_fail += 1;
                    report
                        .messages
                        .push(format!("solo syntax {fname}: {msg}"));
                }
            }
        }
    }

    if hard_fail == 0 {
        report.reparse_ok = true;
        report.context_soft = context_only > 0 || !report.messages.is_empty();
        report.messages.push(format!(
            "edited integrity ok (files={} hard=0 context={context_only}; joint failed)",
            probe_set.len()
        ));
    } else {
        report.reparse_ok = false;
        report.context_soft = context_only > 0;
        report.messages.push(format!(
            "edited integrity failed (hard={hard_fail} context={context_only})"
        ));
    }

    let _ = std::fs::remove_dir_all(&tmp);
    report
}

/// Optional external lint hook (no-op unless `SV_TIMING_LINT=1` and tool present — stub).
pub fn integrity_lint_external(tree: &EmitTree) -> IntegrityReport {
    let mut r = IntegrityReport {
        reparse_ok: true,
        structural_ok: true,
        lint_ok: true,
        sim_ok: true,
        ..Default::default()
    };
    if std::env::var_os("SV_TIMING_LINT").is_none() {
        r.messages.push("lint skipped (SV_TIMING_LINT not set)".into());
        return r;
    }
    r.lint_ran = true;
    // Real verilator/slang invocation later; keep soft-pass for independence.
    r.messages
        .push(format!("lint stub: {} file(s) queued", tree.files.len()));
    r
}

/// Optional sim hook (`SV_TIMING_SIM=1`) — stub.
pub fn integrity_sim_external(tree: &EmitTree) -> IntegrityReport {
    let mut r = IntegrityReport {
        reparse_ok: true,
        structural_ok: true,
        lint_ok: true,
        sim_ok: true,
        ..Default::default()
    };
    if std::env::var_os("SV_TIMING_SIM").is_none() {
        r.messages.push("sim skipped (SV_TIMING_SIM not set)".into());
        return r;
    }
    r.sim_ran = true;
    r.messages
        .push(format!("sim stub: {} file(s)", tree.files.len()));
    r
}

/// Fail if reparse/structural failed (lint/sim soft unless forced later).
pub fn assert_valid_sv_bundle(report: &IntegrityReport) -> Result<(), String> {
    if !report.reparse_ok {
        return Err(format!("reparse failed: {:?}", report.messages));
    }
    if !report.structural_ok {
        return Err(format!("structural failed: {:?}", report.messages));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use sv_timing_core::loc::{OriginKind, SourceLoc};
    use sv_timing_transform::{EditKind, EditRecord, EditTrace};
    // EditKind/EditRecord already imported via super for apply_edits test

    #[test]
    fn injection_preserves_commented_and_quoted_process_keywords() {
        for decoy in [
            "//always_ff @(posedge clk) begin\n//end\n",
            "/* always_comb begin\nendmodule\nend */\n",
            "localparam string TEXT = \"always_ff endmodule\";\n",
            "logic always_ff_shadow;\n",
            "wire \\always_comb ;\n",
        ] {
            let src = format!("module inject_test(input logic a, output logic y);\n{decoy}always_comb y = a;\nendmodule\n");
            let block = "wire injected_wire;\n";
            let emitted = inject_before_first_process(&src, block);
            assert!(emitted.contains(decoy), "decoy corrupted: {emitted}");
            assert!(emitted.contains("wire injected_wire;\nalways_comb"), "wrong insertion: {emitted}");
            assert_eq!(emitted.replacen(block, "", 1), src);
        }
    }

    #[test]
    fn late_injection_ignores_trailing_comment_endmodule() {
        let src = "module inject_test;\nendmodule\n// endmodule\n";
        let emitted = inject_before_endmodule(src, "wire injected_wire;\n");
        assert!(emitted.contains("wire injected_wire;\nendmodule\n// endmodule"));
    }

    #[test]
    fn noop_passthrough_reparse() {
        let src = include_str!("../../../fixtures/comb_adder_cloud.sv");
        let policy = EmitPolicy::default();
        let mut tree = EmitTree::new();
        let f = synthesize_passthrough_file(
            "comb_adder_cloud__svt.sv",
            src,
            &policy,
            Some(&SourceLoc {
                file: "fixtures/comb_adder_cloud.sv".into(),
                start_line: 1,
                start_col: 1,
                end_line: 1,
                end_col: 1,
                byte_start: 0,
                byte_end: 0,
                origin: OriginKind::UserFile,
            }),
        );
        tree.add_file(f.rel_path.clone(), f.role, f.text);
        let mut trace = EditTrace::new();
        trace.record_edit(EditRecord {
            id: 0,
            kind: EditKind::Annotate,
            origin: SourceLoc {
                file: "fixtures/comb_adder_cloud.sv".into(),
                start_line: 14,
                start_col: 1,
                end_line: 14,
                end_col: 1,
                byte_start: 0,
                byte_end: 0,
                origin: OriginKind::UserFile,
            },
            path_id: None,
            node_id: None,
            new_name: None,
            fo4_before: None,
            fo4_after: None,
            rationale: "annotate test".into(),
            emit_rhs: None,
            emit_rhs_extras: Vec::new(),
            emit_snippet: None,
        });
        annotate_origin_comments(&mut tree, &trace);
        let text = &tree.files.values().next().unwrap().text;
        assert!(text.contains("sv-timing: origin"));
        let report = integrity_reparse(&tree, &ParseOptions::default());
        assert_valid_sv_bundle(&report).expect("reparse");
        assert!(report.reparse_ok);
    }

    #[test]
    fn header_mentions_tool() {
        let h = machine_header("sv-timing", "test");
        assert!(h.contains("sv-timing"));
    }

    #[test]
    fn emit_tree_preserves_insertion_order() {
        let mut tree = EmitTree::new();
        tree.add_file("z_mod.sv", FileRole::Module, "module z; endmodule\n".into());
        tree.add_file("a_pkg.sv", FileRole::Package, "package a; endpackage\n".into());
        tree.add_file("m_mid.sv", FileRole::Module, "module m; endmodule\n".into());
        let keys = tree.ordered_keys();
        assert_eq!(
            keys,
            vec!["z_mod.sv", "a_pkg.sv", "m_mid.sv"],
            "must not alphabetize for joint reparse"
        );
    }

    #[test]
    fn context_only_error_classifier() {
        assert!(is_context_only_parse_error("DefineNotFound(\"FFLARNC\")"));
        assert!(is_context_only_parse_error("define not found: FF"));
        assert!(!is_context_only_parse_error("Parse(Some((\"x.sv\", 99)))"));
    }

    #[test]
    fn apply_edits_inserts_before_endmodule_and_reparses() {
        let src = include_str!("../../../fixtures/auto_correct/deep_add_chain.sv");
        let mut trace = EditTrace::new();
        // Line 17: t1 = t0 + c_i  — recoverable cut site
        trace.record_edit(EditRecord {
            id: 0,
            kind: EditKind::InsertReg,
            origin: SourceLoc {
                file: "deep_add_chain.sv".into(),
                start_line: 17,
                start_col: 1,
                end_line: 17,
                end_col: 1,
                byte_start: 0,
                byte_end: 0,
                origin: OriginKind::UserFile,
            },
            path_id: Some(0),
            node_id: Some(1),
            new_name: Some("pipe_svt_p1".into()),
            fo4_before: Some(30.0),
            fo4_after: Some(15.0),
            rationale: "test cut".into(),
            emit_rhs: None,
            emit_rhs_extras: Vec::new(),
            emit_snippet: None,
        });
        let policy = EmitPolicy::default();
        let text = apply_edits_to_source(src, &trace, &policy);
        assert!(text.contains("pipe_svt_p1"));
        assert!(text.contains("BEGIN sv-timing auto-correct"));
        assert!(text.contains("localparam"));
        assert!(text.contains("always_ff"));
        // Lean densify is always_ff-only when clk/rst present (no density_scaffold).
        assert!(text.contains("endmodule"));
        // Dense pipe is late: after original always_comb body, before endmodule.
        let dense_pos = text.find("// BEGIN sv-timing auto-correct (dense emit)").expect("dense");
        let end_pos = text.rfind("endmodule").expect("endmodule");
        assert!(dense_pos < end_pos, "dense must be before endmodule");
        let body_pos = text.find("always_comb begin").expect("original always_comb");
        assert!(
            dense_pos > body_pos,
            "InsertReg dense must inject after mid-module processes (R11)"
        );
        // Lean R12e: no origin rewrite; zero cut feed; pipe stages still emit.
        assert!(
            text.contains("pipe_svt_p1") && text.contains("t1 = t0 + c_i"),
            "lean leaves origin intact: {text}"
        );
        assert!(
            text.contains("assign pipe_svt_p1_c = svt_zero")
                || text.contains("assign pipe_svt_p1_c = svt_zero;"),
            "lean zero feed expected: {text}"
        );
        assert!(
            !text.contains("assign t1 = pipe_svt_p1"),
            "lean must not sink continuous/procedural origins"
        );
        // Opt-in real feeds for continuous mid-module fixture is covered by
        // cut_feed_references_mid_module_net_after_decl.
        let dens = DensityReport::from_sv_fragment(
            text.split("BEGIN sv-timing").nth(1).unwrap_or(&text),
        );
        assert!(dens.score() >= min_density_score_for_edits(1));
        let mut tree = EmitTree::new();
        tree.add_file("deep_add_chain__svt.sv", FileRole::Module, text);
        let report = integrity_reparse(&tree, &ParseOptions::default());
        assert_valid_sv_bundle(&report).expect("reparse corrected");
    }

    #[test]
    fn sibling_span_extra_pipes_emit_own_decls() {
        let src = include_str!("../../../fixtures/auto_correct/sibling_span.sv");
        let line = src
            .lines()
            .position(|l| l.contains("assign a_span"))
            .expect("a_span") as u32
            + 1;
        let mut trace = EditTrace::new();
        trace.record_edit(EditRecord {
            id: 0,
            kind: EditKind::InsertReg,
            origin: SourceLoc {
                file: "sibling_span.sv".into(),
                start_line: line,
                start_col: 1,
                end_line: line,
                end_col: 1,
                byte_start: 0,
                byte_end: 0,
                origin: OriginKind::UserFile,
            },
            path_id: Some(0),
            node_id: Some(1),
            new_name: Some("pipe_svt_p1".into()),
            fo4_before: Some(18.5),
            fo4_after: Some(10.0),
            rationale: "a_span cut".into(),
            emit_rhs: None,
            emit_rhs_extras: Vec::new(),
            emit_snippet: None,
        });
        let mut dense = dense_options_from_source(src);
        dense.real_cut_feeds = true;
        let text = apply_edits_to_source_dense(src, &trace, &EmitPolicy::default(), &dense);
        assert!(
            text.contains("sibling span moved"),
            "expected sibling origin rewrite:\n{text}"
        );
        assert!(
            text.contains("pipe_svt_sib_b_span"),
            "expected extra b_span pipe decl:\n{text}"
        );
        assert!(
            !text.contains("assign b_span = pipe_svt_p1"),
            "different-RHS sibling must not share the seed pipe:\n{text}"
        );
        let live_b = text.lines().any(|l| {
            let t = l.trim();
            t.starts_with("assign b_span") && t.contains("p_q") && !t.starts_with("//")
        });
        assert!(!live_b, "b_span combo left live:\n{text}");
        let mut tree = EmitTree::new();
        tree.add_file("sibling_span__svt.sv", FileRole::Module, text);
        let report = integrity_reparse(&tree, &ParseOptions::default());
        assert_valid_sv_bundle(&report).expect("reparse sibling extras");
    }

    /// Cut feed RHS uses a net declared *after* the first process — early inject
    /// would fail Verilator "used before its declaration"; late inject must win.
    #[test]
    fn cut_feed_references_mid_module_net_after_decl() {
        let src = r#"// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
module mid_decl (
    input  logic       clk_i,
    input  logic       rst_ni,
    input  logic [7:0] a_i,
    output logic [7:0] y_o
);
  logic [7:0] early;
  always_comb begin
    early = a_i;
  end
  logic [7:0] rounded_abs;
  assign rounded_abs = a_i + 8'd1;
  logic [7:0] cast_result;
  assign cast_result = rounded_abs ^ early;
  assign y_o = cast_result;
endmodule
"#;
        let mut trace = EditTrace::new();
        // Line 16: assign cast_result = rounded_abs ^ early;
        trace.record_edit(EditRecord {
            id: 0,
            kind: EditKind::InsertReg,
            origin: SourceLoc {
                file: "mid_decl.sv".into(),
                start_line: 16,
                start_col: 1,
                end_line: 16,
                end_col: 1,
                byte_start: 0,
                byte_end: 0,
                origin: OriginKind::UserFile,
            },
            path_id: Some(0),
            node_id: Some(1),
            new_name: Some("pipe_svt_p1".into()),
            fo4_before: Some(40.0),
            fo4_after: Some(16.0),
            rationale: "mid-module cut".into(),
            emit_rhs: None,
            emit_rhs_extras: Vec::new(),
            emit_snippet: None,
        });
        let mut dense = dense_options_from_source(src);
        dense.real_cut_feeds = true;
        let text = apply_edits_to_source_dense(src, &trace, &EmitPolicy::default(), &dense);
        let decl = text
            .find("logic [7:0] rounded_abs")
            .expect("rounded_abs decl");
        let feed = text
            .find("assign pipe_svt_p1_c = (rounded_abs ^ early)")
            .expect("cut feed with mid-module nets");
        assert!(
            feed > decl,
            "cut feed must appear after rounded_abs decl (R11); feed={feed} decl={decl}"
        );
        let mut tree = EmitTree::new();
        tree.add_file("mid_decl__svt.sv", FileRole::Module, text);
        let report = integrity_reparse(&tree, &ParseOptions::default());
        assert_valid_sv_bundle(&report).expect("reparse mid_decl");
    }

    /// BalanceMux snippets stay early so origin RHS rewrite can see staged wires.
    #[test]
    fn balance_mux_snippet_injects_before_first_process() {
        let src = r#"module bm_mod (
    input logic a, b, c,
    output logic y
);
  logic t;
  always_comb begin
    t = a | b;
    y = t;
  end
endmodule
"#;
        let snippet = "  // --- BalanceMux arm staging (latency-neutral) ---\n  logic [63:0] svt_bm_top_p1_n0;\n  always_comb begin : svt_bm_top_p1_n0_stage\n    svt_bm_top_p1_n0 = a | b;\n  end\n";
        let mut trace = EditTrace::new();
        trace.record_edit(EditRecord {
            id: 0,
            kind: EditKind::BalanceMux,
            origin: SourceLoc {
                file: "bm_mod.sv".into(),
                start_line: 7,
                start_col: 1,
                end_line: 7,
                end_col: 1,
                byte_start: 0,
                byte_end: 0,
                origin: OriginKind::UserFile,
            },
            path_id: Some(1),
            node_id: Some(0),
            new_name: Some("svt_bm_top_p1_n0".into()),
            fo4_before: Some(20.0),
            fo4_after: Some(10.0),
            rationale: "stage".into(),
            emit_rhs: Some("svt_bm_top_p1_n0".into()),
            emit_rhs_extras: Vec::new(),
            emit_snippet: Some(snippet.into()),
        });
        // Lean default: BalanceMux credit-only (no RTL).
        let lean = apply_edits_to_source(src, &trace, &EmitPolicy::default());
        assert!(
            lean.contains("review-only credit") || !lean.contains("svt_bm_top_p1_n0_stage"),
            "lean demotes BalanceMux RTL"
        );
        // Opt-in structural BalanceMux early inject.
        let mut dense = dense_options_from_source(src);
        dense.emit_balance_mux_rtl = true;
        let text = apply_edits_to_source_dense(src, &trace, &EmitPolicy::default(), &dense);
        assert!(
            text.contains("svt_bm_top_p1_n0_stage"),
            "unique block label expected with emit_balance_mux_rtl"
        );
        let early = text
            .find("BEGIN sv-timing auto-correct (balance_mux rewrite)")
            .expect("balance_mux early");
        let first_proc = text.find("always_comb begin").expect("first process");
        assert!(
            early < first_proc || text[..first_proc].contains("svt_bm_top_p1_n0"),
            "BalanceMux staging must be early"
        );
    }

    /// gemm: first `always_comb` then later `logic pe_float_en` then `always_ff`.
    /// Snippet must inject after the late decl, not at the first process.
    #[test]
    fn balance_mux_snippet_injects_after_mid_module_decls() {
        let src = r#"module gemm_late (
    input logic clk_i, rst_ni,
    input logic pe_float_en_i,
    output logic [3:0] dot_pending_q
);
  always_comb begin
    // early mux
  end
  logic pe_float_en;
  assign pe_float_en = pe_float_en_i;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) dot_pending_q <= '0;
    else begin
      dot_pending_q <= pe_float_en ? (dot_pending_q + 4'd1) : 4'd0;
    end
  end
endmodule
"#;
        let snippet = "  logic [64-1:0] svt_bm_top_p1_n0;\n  always_comb begin : svt_bm_top_p1_n0_stage\n    svt_bm_top_p1_n0 = pe_float_en ? (dot_pending_q + 4'd1) : 4'd0;\n  end\n";
        let origin_line = src
            .lines()
            .position(|l| l.contains("dot_pending_q <=") && l.contains("pe_float_en"))
            .expect("nba") as u32
            + 1;
        assert!(
            crate::rhs::balance_mux_snippet_safe(src, snippet, origin_line),
            "snippet should be safe at origin process {}",
            crate::rhs::enclosing_process_start_line(src, origin_line)
        );
        assert!(
            !crate::rhs::has_free_gen_index(snippet),
            "fixture snippet must not trip gen-index refuse"
        );
        let mut trace = EditTrace::new();
        trace.record_edit(EditRecord {
            id: 0,
            kind: EditKind::BalanceMux,
            origin: SourceLoc {
                file: "gemm_late.sv".into(),
                start_line: origin_line,
                start_col: 1,
                end_line: origin_line,
                end_col: 1,
                byte_start: 0,
                byte_end: 0,
                origin: OriginKind::UserFile,
            },
            path_id: Some(1),
            node_id: Some(0),
            new_name: Some("svt_bm_top_p1_n0".into()),
            fo4_before: Some(26.0),
            fo4_after: Some(10.0),
            rationale: "stage".into(),
            emit_rhs: Some("svt_bm_top_p1_n0".into()),
            emit_rhs_extras: Vec::new(),
            emit_snippet: Some(snippet.into()),
        });
        let mut dense = dense_options_from_source(src);
        dense.emit_balance_mux_rtl = true;
        dense.real_cut_feeds = true;
        let text = apply_edits_to_source_dense(src, &trace, &EmitPolicy::default(), &dense);
        let decl = text.find("logic pe_float_en;").expect("late decl");
        let snip = text
            .find("svt_bm_top_p1_n0_stage")
            .expect("snippet must emit, not demote");
        assert!(
            snip > decl,
            "BalanceMux must inject after pe_float_en decl; decl={decl} snip={snip}\n{text}"
        );
        assert!(
            text.contains("dot_pending_q <= svt_bm_top_p1_n0"),
            "origin NBA must sample staged top:\n{text}"
        );
        let mut tree = EmitTree::new();
        tree.add_file("gemm_late__svt.sv", FileRole::Module, text);
        let report = integrity_reparse(&tree, &ParseOptions::default());
        assert_valid_sv_bundle(&report).expect("reparse gemm_late");
    }

    /// InsertReg before a later BalanceMux origin must not steal the BM line.
    #[test]
    fn balance_mux_rewrite_not_shifted_by_insertreg_comments() {
        let src = r#"module m;
  logic clk_i, rst_ni, a, b;
  logic [7:0] early_q, later_q;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      early_q <= '0;
      later_q <= '0;
    end else begin
      early_q <= a * b;
      later_q <= a + b + a;
    end
  end
endmodule
"#;
        let later = src
            .lines()
            .position(|l| l.contains("later_q <=") && l.contains('+'))
            .expect("later") as u32
            + 1;
        let early = src
            .lines()
            .position(|l| l.contains("early_q <=") && l.contains('*'))
            .expect("early") as u32
            + 1;
        let snippet = "  logic [64-1:0] svt_bm_top;\n  always_comb begin : svt_bm_top_stage\n    svt_bm_top = a + b + a;\n  end\n";
        let mut trace = EditTrace::new();
        trace.record_edit(EditRecord {
            id: 0,
            kind: EditKind::InsertReg,
            origin: SourceLoc {
                file: "m.sv".into(),
                start_line: early,
                start_col: 1,
                end_line: early,
                end_col: 1,
                byte_start: 0,
                byte_end: 0,
                origin: OriginKind::UserFile,
            },
            path_id: Some(0),
            node_id: Some(1),
            new_name: Some("pipe_svt_p1".into()),
            fo4_before: Some(56.0),
            fo4_after: Some(10.0),
            rationale: "cut".into(),
            emit_rhs: None,
            emit_rhs_extras: Vec::new(),
            emit_snippet: None,
        });
        trace.records[0].id = 0;
        trace.records[0].new_name = Some("pipe_svt_p1".into());
        trace.record_edit(EditRecord {
            id: 1,
            kind: EditKind::BalanceMux,
            origin: SourceLoc {
                file: "m.sv".into(),
                start_line: later,
                start_col: 1,
                end_line: later,
                end_col: 1,
                byte_start: 0,
                byte_end: 0,
                origin: OriginKind::UserFile,
            },
            path_id: Some(1),
            node_id: Some(2),
            new_name: Some("svt_bm_top".into()),
            fo4_before: Some(26.0),
            fo4_after: Some(10.0),
            rationale: "stage".into(),
            emit_rhs: Some("svt_bm_top".into()),
            emit_rhs_extras: Vec::new(),
            emit_snippet: Some(snippet.into()),
        });
        let mut dense = dense_options_from_source(src);
        dense.emit_balance_mux_rtl = true;
        dense.real_cut_feeds = true;
        let text = apply_edits_to_source_dense(src, &trace, &EmitPolicy::default(), &dense);
        assert!(
            text.contains("later_q <= svt_bm_top"),
            "BM must rewrite later_q, not a shifted neighbor:\n{text}"
        );
        assert!(
            !text.contains("early_q <= svt_bm_top"),
            "InsertReg origin must not receive the BM top:\n{text}"
        );
    }

    /// PASS-STRATEGY: gemm `c_span` is a continuous assign. Lean emit must leave
    /// it byte-identical; `--real-cut-feeds` must comment it out and sink lhs
    /// from the pipe so post_analyze can see the cut.
    #[test]
    fn real_cut_feeds_rewrites_gemm_span_origin() {
        let src = include_str!("../../../fixtures/auto_correct/gemm_span.sv");
        let line = src
            .lines()
            .position(|l| l.contains("assign c_span"))
            .expect("c_span assign") as u32
            + 1;
        let mut trace = EditTrace::new();
        trace.record_edit(EditRecord {
            id: 0,
            kind: EditKind::InsertReg,
            origin: SourceLoc {
                file: "gemm_span.sv".into(),
                start_line: line,
                start_col: 1,
                end_line: line,
                end_col: 1,
                byte_start: 0,
                byte_end: 0,
                origin: OriginKind::UserFile,
            },
            path_id: Some(0),
            node_id: Some(1),
            new_name: Some("pipe_svt_p1".into()),
            fo4_before: Some(304.5),
            fo4_after: Some(96.5),
            rationale: "gemm c_span cut".into(),
            emit_rhs: None,
            emit_rhs_extras: Vec::new(),
            emit_snippet: None,
        });
        let policy = EmitPolicy::default();
        let lean = apply_edits_to_source(src, &trace, &policy);
        assert!(
            lean.lines().any(|l| {
                let t = l.trim();
                t.starts_with("assign c_span") && t.contains("<<") && !t.starts_with("//")
            }),
            "lean must keep live c_span origin: {lean}"
        );
        assert!(
            !lean.contains("assign c_span = pipe_svt_p1"),
            "lean must not sink c_span"
        );

        let mut dense = dense_options_from_source(src);
        dense.real_cut_feeds = true;
        let text = apply_edits_to_source_dense(src, &trace, &policy, &dense);
        assert!(
            text.contains("moved c_span"),
            "richer emit must comment-out origin: {text}"
        );
        let live_origin = text.lines().any(|l| {
            let t = l.trim();
            if t.starts_with("//") || !t.starts_with("assign c_span") {
                return false;
            }
            t.split("//").next().unwrap_or("").contains("<<")
        });
        assert!(!live_origin, "richer emit left live c_span origin: {text}");
        assert!(
            text.contains("assign c_span = pipe_svt_p1"),
            "richer emit must sink c_span from pipe: {text}"
        );
        assert!(
            text.contains("assign pipe_svt_p1_c =")
                && (text.contains("acc1") || text.contains("prod")),
            "richer emit must feed pipe from origin rhs: {text}"
        );
        let mut tree = EmitTree::new();
        tree.add_file("gemm_span__svt.sv", FileRole::Module, text);
        let report = integrity_reparse(&tree, &ParseOptions::default());
        assert_valid_sv_bundle(&report).expect("reparse gemm_span richer emit");
    }

    /// `--real-cut-feeds` must rewrite a simple always_ff NBA (path 3131 shape).
    #[test]
    fn real_cut_feeds_rewrites_proc_nba_origin() {
        let src = include_str!("../../../fixtures/auto_correct/proc_nba_span.sv");
        let line = src
            .lines()
            .position(|l| l.contains("y_o <=") && l.contains("*"))
            .or_else(|| src.lines().position(|l| l.contains("y_o <=")))
            .expect("y_o nba") as u32
            + 1;
        let mut trace = EditTrace::new();
        trace.record_edit(EditRecord {
            id: 0,
            kind: EditKind::InsertReg,
            origin: SourceLoc {
                file: "proc_nba_span.sv".into(),
                start_line: line,
                start_col: 1,
                end_line: line,
                end_col: 1,
                byte_start: 0,
                byte_end: 0,
                origin: OriginKind::UserFile,
            },
            path_id: Some(0),
            node_id: Some(1),
            new_name: Some("pipe_svt_p1".into()),
            fo4_before: Some(68.0),
            fo4_after: Some(10.0),
            rationale: "proc nba cut".into(),
            emit_rhs: None,
            emit_rhs_extras: Vec::new(),
            emit_snippet: None,
        });
        let policy = EmitPolicy::default();
        let lean = apply_edits_to_source(src, &trace, &policy);
        assert!(
            lean.lines().any(|l| {
                let t = l.trim();
                t.contains("y_o <=") && t.contains("*") && !t.starts_with("//")
            }),
            "lean must keep live NBA origin: {lean}"
        );

        let mut dense = dense_options_from_source(src);
        dense.real_cut_feeds = true;
        let text = apply_edits_to_source_dense(src, &trace, &policy, &dense);
        assert!(
            text.contains("moved y_o") && text.contains("y_o <= pipe_svt_p1"),
            "richer emit must rewrite NBA: {text}"
        );
        let live_mul = text.lines().any(|l| {
            let t = l.trim();
            t.contains("y_o <=") && t.contains("*") && !t.starts_with("//")
        });
        assert!(!live_mul, "richer emit left live mul NBA: {text}");
        let mut tree = EmitTree::new();
        tree.add_file("proc_nba_span__svt.sv", FileRole::Module, text);
        let report = integrity_reparse(&tree, &ParseOptions::default());
        assert_valid_sv_bundle(&report).expect("reparse proc_nba richer emit");
    }

    /// Analyze → correct (`emit_structural`) → `--real-cut-feeds` emit → re-analyze.
    /// The IR cut must land in emitted SV as a FO4 drop, not only as a sidecar.
    #[test]
    fn gemm_span_correct_emit_reanalyze_drops_fo4() {
        use sv_timing_core::{
            analyze_files, default_fo4_v1_embedded, frequency_closure, LowerOptions,
            TimingTarget,
        };
        use sv_timing_transform::{run_correct_passes, PassContext, PassPolicy};
        use std::path::PathBuf;

        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures/auto_correct/gemm_span.sv");
        if !path.exists() {
            panic!("missing fixture {}", path.display());
        }
        let src = std::fs::read_to_string(&path).expect("read gemm_span");
        let mut lower = LowerOptions {
            target: TimingTarget::new(4000.0, 20.0, 0.2),
            cost_model: default_fo4_v1_embedded(),
            module_filter: vec!["gemm_span".into()],
            ..Default::default()
        };
        lower.cost_model.id = "fo4-v1".into();
        let out = analyze_files(&[path.clone()], &ParseOptions::default(), &lower)
            .expect("analyze gemm_span");
        let path_dump: Vec<String> = out
            .design
            .paths
            .iter()
            .map(|p| {
                format!(
                    "id={} fo4={:.1} nodes={} class={:?} kind={:?} mc={} loc={}:{}",
                    p.id,
                    p.total_fo4,
                    p.nodes.len(),
                    p.path_class,
                    p.path_kind,
                    p.multi_cycle,
                    p.primary_loc.file,
                    p.primary_loc.start_line
                )
            })
            .collect();
        let sol = out
            .design
            .module_cleanliness
            .get("gemm_span")
            .map(|s| format!("set={} C={:.3} pass={}", s.chosen.as_str(), s.cleanliness, s.timing_pass));
        let before = out
            .design
            .paths
            .iter()
            .filter(|p| !p.multi_cycle)
            .map(|p| p.total_fo4)
            .fold(0.0_f64, f64::max);
        assert!(
            before > 10.0,
            "fixture should miss 4 GHz budget 10 FO4; before={before} paths={path_dump:?} sol={sol:?}"
        );

        let mut policy = PassPolicy::default();
        policy.correct_enabled = true;
        policy.correct_allow_modules = vec!["gemm_span".into()];
        policy.allow_latency = true;
        policy.max_passes = 8;
        policy.emit_structural = true;
        let mut ctx = PassContext::new(out.design, out.names, policy);
        ctx.assume_clk = true;
        ctx.cost_model = default_fo4_v1_embedded();
        let ctx = run_correct_passes(ctx).expect("correct");
        let kinds: Vec<_> = ctx
            .trace
            .records
            .iter()
            .map(|r| format!("{:?}", r.kind))
            .collect();
        assert!(
            ctx.trace
                .records
                .iter()
                .any(|r| r.kind == EditKind::InsertReg),
            "expected InsertReg on gemm_span CombDatapath; edits={kinds:?} paths={path_dump:?} sol={sol:?}"
        );

        let mut dense = dense_options_from_source(&src);
        dense.real_cut_feeds = true;
        let text = apply_edits_to_source_dense(&src, &ctx.trace, &EmitPolicy::default(), &dense);
        let origin_moved = text.contains("moved ")
            && (text.contains("c_span")
                || text.contains("acc0")
                || text.contains("acc1")
                || text.contains("prod"));
        assert!(
            origin_moved,
            "richer emit must rewrite a continuous origin: {text}"
        );

        let dir = std::env::temp_dir().join(format!("svt-gemm-span-{}", std::process::id()));
        let _ = std::fs::create_dir_all(&dir);
        let outp = dir.join("gemm_span__svt.sv");
        std::fs::write(&outp, &text).expect("write emit");
        let post = analyze_files(&[outp.clone()], &ParseOptions::default(), &lower)
            .expect("re-analyze emit");
        let after = post
            .design
            .paths
            .iter()
            .filter(|p| !p.multi_cycle)
            .map(|p| p.total_fo4)
            .fold(0.0_f64, f64::max);
        let pc = frequency_closure(&post.design);
        let post_dump: Vec<String> = post
            .design
            .paths
            .iter()
            .map(|p| {
                format!(
                    "id={} fo4={:.1} nodes={} class={:?} mc={}",
                    p.id, p.total_fo4, p.nodes.len(), p.path_class, p.multi_cycle
                )
            })
            .collect();
        let _ = std::fs::remove_dir_all(&dir);
        assert!(
            after + 1.0 < before,
            "emitted re-analysis must drop FO4 (IR/emit contract); before={before:.1} after={after:.1} closes={} paths={post_dump:?} emit_head={}",
            pc.closes,
            text.lines().take(48).collect::<Vec<_>>().join("\n")
        );
    }

    /// Mixed exclusive leftover + gemm-shaped cone: cleanliness stays S3, the
    /// resilient exception still admits S4 InsertReg (audit-gemm-rcf hole).
    #[test]
    fn mixed_resilient_exception_admits_insert_reg() {
        use sv_timing_core::{
            analyze_files, default_fo4_v1_embedded, exception_policy, LowerOptions, TimingTarget,
        };
        use sv_timing_transform::{run_correct_passes, EditKind, PassContext, PassPolicy};
        use std::path::PathBuf;

        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures/auto_correct/mixed_resilient.sv");
        if !path.exists() {
            panic!("missing fixture {}", path.display());
        }
        let mut lower = LowerOptions {
            target: TimingTarget::new(4000.0, 20.0, 0.2),
            cost_model: default_fo4_v1_embedded(),
            module_filter: vec!["mixed_resilient".into()],
            ..Default::default()
        };
        lower.cost_model.id = "fo4-v1".into();
        let out = analyze_files(&[path.clone()], &ParseOptions::default(), &lower)
            .expect("analyze mixed_resilient");
        let dp = out
            .design
            .paths
            .iter()
            .filter(|p| {
                !p.multi_cycle
                    && p.path_class == sv_timing_core::PathClassKind::Plain
                    && p.path_kind == sv_timing_core::PathKind::RegToReg
            })
            .max_by(|a, b| a.total_fo4.partial_cmp(&b.total_fo4).unwrap())
            .expect("plain regtoreg cone");
        let ex = exception_policy(&out.design, dp).expect("resilient exception");
        assert!(
            ex.admit_insert_reg,
            "gemm-shaped cone must admit InsertReg; fo4={:.1} nodes={} kind={:?} note={}",
            dp.total_fo4,
            dp.nodes.len(),
            dp.path_kind,
            ex.note
        );
        let sol = out
            .design
            .module_cleanliness
            .get("mixed_resilient")
            .expect("cleanliness");
        let set_label = sol.chosen.as_str().to_string();
        let allows_ir = sol.allows_opportunity(sv_timing_core::OpportunityKind::InsertReg);
        let mut policy = PassPolicy::default();
        policy.correct_enabled = true;
        policy.correct_allow_modules = vec!["mixed_resilient".into()];
        policy.allow_latency = true;
        policy.max_passes = 8;
        policy.emit_structural = true;
        let mut ctx = PassContext::new(out.design, out.names, policy);
        ctx.assume_clk = true;
        ctx.cost_model = default_fo4_v1_embedded();
        let ctx = run_correct_passes(ctx).expect("correct");
        let kinds: Vec<_> = ctx
            .trace
            .records
            .iter()
            .map(|r| format!("{:?}", r.kind))
            .collect();
        assert!(
            ctx.trace
                .records
                .iter()
                .any(|r| r.kind == EditKind::InsertReg),
            "resilient exception must InsertReg even if cleanliness is {set_label}; edits={kinds:?} allows_ir={allows_ir}"
        );
    }
}
