// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
//
// Emit SystemVerilog + origin comments + integrity reparse.

#![deny(missing_docs)]
#![forbid(unsafe_code)]

//! Synthesis of rewritten SystemVerilog trees and integrity checks.
//! See `architecture/AUTO-CORRECT-CORE-API.md` §3.7–3.9.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use sv_timing_core::{
    parse_paths, CoreError, CoreResult, ParseOptions, SourceLoc, TimingDesign,
};
use sv_timing_transform::EditTrace;

pub mod dense;
pub mod project;
pub mod rhs;
pub mod synth;

pub use dense::{
    dense_autocorrect_block, dense_autocorrect_block_with_cuts, dense_options_from_source,
    emit_blocks_for_trace, emit_blocks_for_trace_src, min_density_score_for_edits,
    min_density_score_for_trace, DenseEmitOptions, DensityReport, EmitBlocks,
};
pub use project::{
    edits_for_source, emit_project_autocorrect, emit_rel_for_source, infer_source_root,
    new_modules_from_trace, synthesize_project, write_project_emit, EmitManifestEntry,
    ProjectEmitOptions, ProjectEmitResult, ProjectLayout,
};
pub use rhs::{
    cut_assigns_from_source, has_free_gen_index, line_inside_generate, parse_assign_line,
    primary_feed_expr, rewrite_origin_assigns, rewrite_origin_rhs_replaces, sink_assigns_sv,
    unresolved_insert_regs, CutAssign,
};
pub use synth::{synthesize_module, synthesize_module_with, SynthOptions};

/// Role of an emit file.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FileRole {
    /// Primary module source.
    Module,
    /// Package / header.
    Package,
    /// Testbench (integrity sim).
    Testbench,
    /// Other.
    Other,
}

/// One logical file to write.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmitFile {
    /// Relative path under emit root.
    pub rel_path: PathBuf,
    /// Role.
    pub role: FileRole,
    /// Full text.
    pub text: String,
}

/// Planned output tree.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EmitTree {
    /// Files keyed by relative path string.
    pub files: BTreeMap<String, EmitFile>,
    /// Insertion order of keys (preserve source flist order for joint reparse).
    /// BTreeMap alone would reparse packages alphabetically after modules.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub order: Vec<String>,
}

impl EmitTree {
    /// Empty tree.
    pub fn new() -> Self {
        Self::default()
    }

    /// Register / replace a file (order preserved for first insert).
    pub fn add_file(&mut self, rel_path: impl Into<PathBuf>, role: FileRole, text: String) {
        let rel_path = rel_path.into();
        let key = rel_path.to_string_lossy().replace('\\', "/");
        if !self.files.contains_key(&key) {
            self.order.push(key.clone());
        }
        self.files.insert(
            key,
            EmitFile {
                rel_path,
                role,
                text,
            },
        );
    }

    /// Paths in insertion order (falls back to BTreeMap order if `order` empty).
    pub fn ordered_keys(&self) -> Vec<String> {
        if !self.order.is_empty() {
            self.order
                .iter()
                .filter(|k| self.files.contains_key(k.as_str()))
                .cloned()
                .collect()
        } else {
            self.files.keys().cloned().collect()
        }
    }
}

/// Emit policy.
#[derive(Debug, Clone)]
pub struct EmitPolicy {
    /// Tool name in headers.
    pub tool: String,
    /// Run id.
    pub run_id: String,
    /// Inject origin comments.
    pub origin_comments: bool,
}

impl Default for EmitPolicy {
    fn default() -> Self {
        Self {
            tool: "sv-timing".into(),
            run_id: "local".into(),
            origin_comments: true,
        }
    }
}

/// Machine-generated file header.
pub fn machine_header(tool: &str, run_id: &str) -> String {
    format!(
        "// Generated by {tool} (run_id={run_id})\n\
         // DO NOT commit without human review.\n\
         // SPDX-FileCopyrightText: machine-generated\n"
    )
}

/// Format origin debug comment (original file:line).
pub fn origin_comment(loc: &SourceLoc, edit_id: Option<u32>) -> String {
    match edit_id {
        Some(id) => format!(
            "// sv-timing: origin {}:{}:{} edit={id}\n",
            loc.file, loc.start_line, loc.start_col
        ),
        None => format!(
            "// sv-timing: origin {}:{}:{}\n",
            loc.file, loc.start_line, loc.start_col
        ),
    }
}

/// Annotate emit tree texts with edit origins (prepend after header if missing).
pub fn annotate_origin_comments(tree: &mut EmitTree, trace: &EditTrace) {
    if trace.records.is_empty() {
        return;
    }
    let block: String = trace
        .records
        .iter()
        .map(|r| origin_comment(&r.origin, Some(r.id)))
        .collect();
    for f in tree.files.values_mut() {
        if !f.text.contains("sv-timing: origin") {
            // Insert after first header block if present
            if let Some(pos) = f.text.find('\n') {
                let (head, rest) = f.text.split_at(pos + 1);
                // Keep scanning header lines
                let mut idx = head.len();
                for line in rest.lines() {
                    if line.starts_with("//") {
                        idx += line.len() + 1;
                    } else {
                        break;
                    }
                }
                let mut new_text = String::new();
                new_text.push_str(&f.text[..idx]);
                new_text.push_str(&block);
                new_text.push_str(&f.text[idx..]);
                f.text = new_text;
            } else {
                f.text = format!("{block}{}", f.text);
            }
        }
    }
}

/// Build emit tree from design IR via [`synthesize_module`].
pub fn synthesize_design(design: &TimingDesign, policy: &EmitPolicy) -> EmitTree {
    let mut tree = EmitTree::new();
    for module in design.modules.values() {
        let stem = format!("{}{}", module.name, "__svt");
        let path = format!("{stem}.sv");
        tree.add_file(path, FileRole::Module, synthesize_module(module, policy));
    }
    tree
}

/// Apply auto-correct edits to original module source.
///
/// 1. **RHS rewrite** of origin assign lines → sample new pipe regs (sinks in dense block).
/// 2. **Early inject** (before first process): BalanceMux arm staging wires referenced by
///    origin RHS rewrites.
/// 3. **Late inject** (before `endmodule`): InsertReg dense pipe with real cut feeds
///    (`pipe_c = (origin_rhs)`), so feeds may use mid-module nets (R11 / Verilator order).
pub fn apply_edits_to_source(source: &str, trace: &EditTrace, policy: &EmitPolicy) -> String {
    let dense = dense_options_from_source(source);
    apply_edits_to_source_dense(source, trace, policy, &dense)
}

/// Same as [`apply_edits_to_source`] with explicit dense options (clk/rst names, width).
pub fn apply_edits_to_source_dense(
    source: &str,
    trace: &EditTrace,
    policy: &EmitPolicy,
    dense: &DenseEmitOptions,
) -> String {
    if trace.records.is_empty() {
        return source.to_string();
    }
    let cuts = cut_assigns_from_source(source, trace);
    // R12e lean default: do **not** rewrite origins or emit continuous sinks.
    // Pipe stages still emit with zero feeds (FO4 screening sidecar). Origin
    // rewrites and BalanceMux RTL remain opt-in for review fixtures.
    let rewritten = if dense.real_cut_feeds {
        let r = rewrite_origin_assigns(source, &cuts);
        if dense.emit_balance_mux_rtl {
            rewrite_origin_rhs_replaces(&r, trace)
        } else {
            r
        }
    } else if dense.emit_balance_mux_rtl {
        rewrite_origin_rhs_replaces(source, trace)
    } else {
        source.to_string()
    };
    // Without real feeds, still pass cuts for stage naming; sinks suppressed below.
    let cuts_for_dense: Vec<_> = if dense.real_cut_feeds {
        cuts
    } else {
        // Drop continuous flag so sink_assigns_sv emits nothing.
        cuts
            .into_iter()
            .map(|mut c| {
                c.continuous = false;
                c.line = 0; // no origin rewrite path
                c.lhs.clear();
                c
            })
            .collect()
    };
    let blocks =
        dense::emit_blocks_for_trace_src(trace, dense, &cuts_for_dense, Some(source));
    let header = machine_header(&policy.tool, &policy.run_id);
    // Dual inject (R11):
    // - early: BalanceMux wires before first process (origin RHS rewrite legality)
    // - late: dense pipe before endmodule (cut feeds may reference mid-module nets)
    let rewritten = inject_before_first_process(&rewritten, &blocks.early);
    let rewritten = inject_before_endmodule(&rewritten, &blocks.late);
    let mut out = String::new();
    out.push_str(&header);
    out.push_str(&rewritten);
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Insert `block` before the first procedural/continuous process in the module body.
///
/// Used so BalanceMux intermediate wires are declared before origin RHS rewrites
/// that reference them. Falls back to pre-`endmodule` placement.
fn inject_before_first_process(source: &str, block: &str) -> String {
    if block.trim().is_empty() {
        return source.to_string();
    }
    // Prefer first always_* / assign after module header.
    let lower = source.to_ascii_lowercase();
    let mut best: Option<usize> = None;
    for key in [
        "always_comb",
        "always_ff",
        "always_latch",
        "always @",
        "always@",
        "  assign ",
        "\nassign ",
    ] {
        if let Some(i) = lower.find(key) {
            // Only consider hits after "module "
            if let Some(mod_i) = lower.find("module ") {
                if i > mod_i {
                    best = Some(best.map_or(i, |b| b.min(i)));
                }
            }
        }
    }
    if let Some(i) = best {
        let mut out = String::with_capacity(source.len() + block.len() + 8);
        out.push_str(&source[..i]);
        if !out.ends_with('\n') {
            out.push('\n');
        }
        out.push_str(block);
        if !block.ends_with('\n') {
            out.push('\n');
        }
        out.push_str(&source[i..]);
        return out;
    }
    inject_before_endmodule(source, block)
}

/// Insert `block` immediately before the last `endmodule` in `source`.
fn inject_before_endmodule(source: &str, block: &str) -> String {
    if block.trim().is_empty() {
        return source.to_string();
    }
    if let Some(idx) = source.rfind("endmodule") {
        let mut out = String::with_capacity(source.len() + block.len() + 8);
        out.push_str(&source[..idx]);
        if !out.ends_with('\n') {
            out.push('\n');
        }
        out.push_str(block);
        if !block.ends_with('\n') {
            out.push('\n');
        }
        out.push_str(&source[idx..]);
        out
    } else {
        format!("{source}\n{block}")
    }
}

/// Build emit tree from original sources + edit trace (one file per source path).
pub fn synthesize_corrected_sources(
    sources: &[(PathBuf, String)],
    trace: &EditTrace,
    policy: &EmitPolicy,
) -> EmitTree {
    let mut tree = EmitTree::new();
    for (path, src) in sources {
        let stem = path
            .file_stem()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| "corrected".into());
        let rel = PathBuf::from(format!("{stem}__svt.sv"));
        let text = apply_edits_to_source(src, trace, policy);
        tree.add_file(rel, FileRole::Module, text);
    }
    tree
}

/// Passthrough: wrap original source with header + optional origin (integrity baseline).
pub fn synthesize_passthrough_file(
    rel_path: impl Into<PathBuf>,
    source: &str,
    policy: &EmitPolicy,
    origin: Option<&SourceLoc>,
) -> EmitFile {
    let rel_path = rel_path.into();
    let mut text = machine_header(&policy.tool, &policy.run_id);
    if let Some(loc) = origin {
        text.push_str(&origin_comment(loc, None));
    }
    text.push_str(source);
    if !source.ends_with('\n') {
        text.push('\n');
    }
    EmitFile {
        rel_path,
        role: FileRole::Module,
        text,
    }
}

/// Write emit tree under `root_dir`.
pub fn write_emit_tree(tree: &EmitTree, root_dir: impl AsRef<Path>) -> CoreResult<Vec<PathBuf>> {
    let root = root_dir.as_ref();
    let mut written = Vec::new();
    for f in tree.files.values() {
        let path = root.join(&f.rel_path);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|source| CoreError::Io {
                path: parent.to_path_buf(),
                source,
            })?;
        }
        std::fs::write(&path, &f.text).map_err(|source| CoreError::Io {
            path: path.clone(),
            source,
        })?;
        written.push(path);
    }
    Ok(written)
}

/// Integrity report after emit.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IntegrityReport {
    /// All files reparsed OK (joint **or** edited-only syntax clean).
    pub reparse_ok: bool,
    /// Per-file messages.
    pub messages: Vec<String>,
    /// Structural OK (stub always true until checks land).
    pub structural_ok: bool,
    /// Lint ran.
    pub lint_ran: bool,
    /// Lint ok (or skipped).
    pub lint_ok: bool,
    /// Sim ran.
    pub sim_ran: bool,
    /// Sim ok (or skipped).
    pub sim_ok: bool,
    /// Joint full-tree reparse succeeded.
    #[serde(default)]
    pub joint_ok: bool,
    /// Edited files had only define/include context gaps (not syntax damage).
    #[serde(default)]
    pub context_soft: bool,
}

/// True when the emit text carries an auto-correct region (edited, not pure passthrough).
fn is_edited_emit_text(text: &str) -> bool {
    text.contains("BEGIN sv-timing auto-correct")
        || text.contains("sv-timing auto-correct")
}

/// Classify solo reparse failure as host **context** (defines/includes) vs syntax.
fn is_context_only_parse_error(msg: &str) -> bool {
    let m = msg.to_ascii_lowercase();
    m.contains("definenotfound")
        || m.contains("define not found")
        || m.contains("incompletename")
        || m.contains("include")
        || m.contains("filenotfound")
        || m.contains("file not found")
}

/// Reparse every emit file with the same front end (mandatory integrity).
///
/// **Full-core monorepo trees:** joint reparse must use **source order** (not
/// BTreeMap alphabetical) so packages define macros before modules. When joint
/// still fails (host macros / passthrough noise), integrity is judged on
/// **edited** files only: syntax damage fails hard; `DefineNotFound` alone is
/// recorded as `context_soft` and does **not** clear `reparse_ok` if no edited
/// file has a non-context parse error.
pub fn integrity_reparse(tree: &EmitTree, opts: &ParseOptions) -> IntegrityReport {
    integrity_reparse_ex(tree, opts, None)
}

/// Like [`integrity_reparse`], with optional map of emit relative path → original
/// source path. When solo emit parse fails but the **original** file also fails
/// under the same options, the failure is treated as pre-existing parser limit
/// (context soft), not emit damage — common for vendor `.v` / huge CSR cases.
pub fn integrity_reparse_ex(
    tree: &EmitTree,
    opts: &ParseOptions,
    origin_sources: Option<&BTreeMap<String, PathBuf>>,
) -> IntegrityReport {
    let mut report = IntegrityReport {
        reparse_ok: true,
        structural_ok: true,
        lint_ok: true,
        sim_ok: true,
        joint_ok: false,
        context_soft: false,
        ..Default::default()
    };
    // Unique dir per call so parallel tests do not race on the same path.
    let tmp = std::env::temp_dir().join(format!(
        "sv-timing-integrity-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0)
    ));
    if let Err(e) = std::fs::create_dir_all(&tmp) {
        report.reparse_ok = false;
        report.messages.push(format!("tmpdir failed: {e}"));
        return report;
    }
    if let Err(e) = write_emit_tree(tree, &tmp) {
        report.reparse_ok = false;
        report.messages.push(format!("write failed: {e}"));
        let _ = std::fs::remove_dir_all(&tmp);
        return report;
    }

    // Preserve synthesize/source order for joint parse.
    let keys = tree.ordered_keys();
    let mut paths = Vec::new();
    let mut edited_paths: Vec<(String, PathBuf)> = Vec::new();
    for k in &keys {
        let Some(f) = tree.files.get(k) else {
            continue;
        };
        let p = tmp.join(&f.rel_path);
        if is_edited_emit_text(&f.text) {
            edited_paths.push((k.clone(), p.clone()));
        }
        paths.push(p);
    }

    // Joint parse first (packages + modules must see each other, in flist order).
    match parse_paths(&paths, opts) {
        Ok(unit) => {
            report.joint_ok = true;
            report.reparse_ok = true;
            report
                .messages
                .push(format!("joint reparse ok: {} file(s)", unit.files.len()));
            let _ = std::fs::remove_dir_all(&tmp);
            return report;
        }
        Err(e) => {
            report
                .messages
                .push(format!("joint reparse failed: {e}"));
        }
    }

    // Fallback: judge **edited** files for syntax damage. Passthrough copies of
    // host RTL often need macros from the full package graph; DefineNotFound on
    // solo is context, not emit corruption.
    let mut solo = opts.clone();
    solo.ignore_include_error = true;
    // Allow incomplete defines when probing solo — surface DefineNotFound cleanly.
    solo.allow_parse_errors = false;

    let probe_set: Vec<(String, PathBuf)> = if edited_paths.is_empty() {
        // No auto-correct markers — probe every file.
        keys.iter()
            .filter_map(|k| {
                tree.files
                    .get(k)
                    .map(|f| (k.clone(), tmp.join(&f.rel_path)))
            })
            .collect()
    } else {
        edited_paths
    };

    let mut hard_fail = 0usize;
    let mut context_only = 0usize;
    for (name, p) in &probe_set {
        match parse_paths(std::slice::from_ref(p), &solo) {
            Ok(_) => {}
            Err(e2) => {
                let msg = format!("{e2}");
                let fname = Path::new(name)
                    .file_name()
                    .and_then(|s| s.to_str())
                    .unwrap_or(name.as_str());
                if is_context_only_parse_error(&msg) {
                    context_only += 1;
                    report
                        .messages
                        .push(format!("solo context {fname}: {msg}"));
                    continue;
                }
                // Pre-existing: original source also fails solo → not emit damage.
                let mut preexisting = false;
                if let Some(map) = origin_sources {
                    if let Some(orig) = map.get(name).or_else(|| {
                        // Match by basename when keys differ slightly.
                        map.iter()
                            .find(|(k, _)| {
                                Path::new(k).file_name() == Path::new(name).file_name()
                            })
                            .map(|(_, v)| v)
                    }) {
                        if orig.is_file()
                            && parse_paths(std::slice::from_ref(orig), &solo).is_err()
                        {
                            preexisting = true;
                        }
                    }
                }
                if preexisting {
                    context_only += 1;
                    report.messages.push(format!(
                        "solo preexisting {fname}: {msg} (original also fails)"
                    ));
                } else {
                    hard_fail += 1;
                    report
                        .messages
                        .push(format!("solo syntax {fname}: {msg}"));
                }
            }
        }
    }

    if hard_fail == 0 {
        report.reparse_ok = true;
        report.context_soft = context_only > 0 || !report.messages.is_empty();
        report.messages.push(format!(
            "edited integrity ok (files={} hard=0 context={context_only}; joint failed)",
            probe_set.len()
        ));
    } else {
        report.reparse_ok = false;
        report.context_soft = context_only > 0;
        report.messages.push(format!(
            "edited integrity failed (hard={hard_fail} context={context_only})"
        ));
    }

    let _ = std::fs::remove_dir_all(&tmp);
    report
}

/// Optional external lint hook (no-op unless `SV_TIMING_LINT=1` and tool present — stub).
pub fn integrity_lint_external(tree: &EmitTree) -> IntegrityReport {
    let mut r = IntegrityReport {
        reparse_ok: true,
        structural_ok: true,
        lint_ok: true,
        sim_ok: true,
        ..Default::default()
    };
    if std::env::var_os("SV_TIMING_LINT").is_none() {
        r.messages.push("lint skipped (SV_TIMING_LINT not set)".into());
        return r;
    }
    r.lint_ran = true;
    // Real verilator/slang invocation later; keep soft-pass for independence.
    r.messages
        .push(format!("lint stub: {} file(s) queued", tree.files.len()));
    r
}

/// Optional sim hook (`SV_TIMING_SIM=1`) — stub.
pub fn integrity_sim_external(tree: &EmitTree) -> IntegrityReport {
    let mut r = IntegrityReport {
        reparse_ok: true,
        structural_ok: true,
        lint_ok: true,
        sim_ok: true,
        ..Default::default()
    };
    if std::env::var_os("SV_TIMING_SIM").is_none() {
        r.messages.push("sim skipped (SV_TIMING_SIM not set)".into());
        return r;
    }
    r.sim_ran = true;
    r.messages
        .push(format!("sim stub: {} file(s)", tree.files.len()));
    r
}

/// Fail if reparse/structural failed (lint/sim soft unless forced later).
pub fn assert_valid_sv_bundle(report: &IntegrityReport) -> Result<(), String> {
    if !report.reparse_ok {
        return Err(format!("reparse failed: {:?}", report.messages));
    }
    if !report.structural_ok {
        return Err(format!("structural failed: {:?}", report.messages));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use sv_timing_core::loc::{OriginKind, SourceLoc};
    use sv_timing_transform::{EditKind, EditRecord, EditTrace};
    // EditKind/EditRecord already imported via super for apply_edits test

    #[test]
    fn noop_passthrough_reparse() {
        let src = include_str!("../../../fixtures/comb_adder_cloud.sv");
        let policy = EmitPolicy::default();
        let mut tree = EmitTree::new();
        let f = synthesize_passthrough_file(
            "comb_adder_cloud__svt.sv",
            src,
            &policy,
            Some(&SourceLoc {
                file: "fixtures/comb_adder_cloud.sv".into(),
                start_line: 1,
                start_col: 1,
                end_line: 1,
                end_col: 1,
                byte_start: 0,
                byte_end: 0,
                origin: OriginKind::UserFile,
            }),
        );
        tree.add_file(f.rel_path.clone(), f.role, f.text);
        let mut trace = EditTrace::new();
        trace.record_edit(EditRecord {
            id: 0,
            kind: EditKind::Annotate,
            origin: SourceLoc {
                file: "fixtures/comb_adder_cloud.sv".into(),
                start_line: 14,
                start_col: 1,
                end_line: 14,
                end_col: 1,
                byte_start: 0,
                byte_end: 0,
                origin: OriginKind::UserFile,
            },
            path_id: None,
            node_id: None,
            new_name: None,
            fo4_before: None,
            fo4_after: None,
            rationale: "annotate test".into(),
            emit_rhs: None,
            emit_rhs_extras: Vec::new(),
            emit_snippet: None,
        });
        annotate_origin_comments(&mut tree, &trace);
        let text = &tree.files.values().next().unwrap().text;
        assert!(text.contains("sv-timing: origin"));
        let report = integrity_reparse(&tree, &ParseOptions::default());
        assert_valid_sv_bundle(&report).expect("reparse");
        assert!(report.reparse_ok);
    }

    #[test]
    fn header_mentions_tool() {
        let h = machine_header("sv-timing", "test");
        assert!(h.contains("sv-timing"));
    }

    #[test]
    fn emit_tree_preserves_insertion_order() {
        let mut tree = EmitTree::new();
        tree.add_file("z_mod.sv", FileRole::Module, "module z; endmodule\n".into());
        tree.add_file("a_pkg.sv", FileRole::Package, "package a; endpackage\n".into());
        tree.add_file("m_mid.sv", FileRole::Module, "module m; endmodule\n".into());
        let keys = tree.ordered_keys();
        assert_eq!(
            keys,
            vec!["z_mod.sv", "a_pkg.sv", "m_mid.sv"],
            "must not alphabetize for joint reparse"
        );
    }

    #[test]
    fn context_only_error_classifier() {
        assert!(is_context_only_parse_error("DefineNotFound(\"FFLARNC\")"));
        assert!(is_context_only_parse_error("define not found: FF"));
        assert!(!is_context_only_parse_error("Parse(Some((\"x.sv\", 99)))"));
    }

    #[test]
    fn apply_edits_inserts_before_endmodule_and_reparses() {
        let src = include_str!("../../../fixtures/auto_correct/deep_add_chain.sv");
        let mut trace = EditTrace::new();
        // Line 17: t1 = t0 + c_i  — recoverable cut site
        trace.record_edit(EditRecord {
            id: 0,
            kind: EditKind::InsertReg,
            origin: SourceLoc {
                file: "deep_add_chain.sv".into(),
                start_line: 17,
                start_col: 1,
                end_line: 17,
                end_col: 1,
                byte_start: 0,
                byte_end: 0,
                origin: OriginKind::UserFile,
            },
            path_id: Some(0),
            node_id: Some(1),
            new_name: Some("pipe_svt_p1".into()),
            fo4_before: Some(30.0),
            fo4_after: Some(15.0),
            rationale: "test cut".into(),
            emit_rhs: None,
            emit_rhs_extras: Vec::new(),
            emit_snippet: None,
        });
        let policy = EmitPolicy::default();
        let text = apply_edits_to_source(src, &trace, &policy);
        assert!(text.contains("pipe_svt_p1"));
        assert!(text.contains("BEGIN sv-timing auto-correct"));
        assert!(text.contains("localparam"));
        assert!(text.contains("always_ff"));
        // Lean densify is always_ff-only when clk/rst present (no density_scaffold).
        assert!(text.contains("endmodule"));
        // Dense pipe is late: after original always_comb body, before endmodule.
        let dense_pos = text.find("// BEGIN sv-timing auto-correct (dense emit)").expect("dense");
        let end_pos = text.rfind("endmodule").expect("endmodule");
        assert!(dense_pos < end_pos, "dense must be before endmodule");
        let body_pos = text.find("always_comb begin").expect("original always_comb");
        assert!(
            dense_pos > body_pos,
            "InsertReg dense must inject after mid-module processes (R11)"
        );
        // Lean R12e: no origin rewrite; zero cut feed; pipe stages still emit.
        assert!(
            text.contains("pipe_svt_p1") && text.contains("t1 = t0 + c_i"),
            "lean leaves origin intact: {text}"
        );
        assert!(
            text.contains("assign pipe_svt_p1_c = svt_zero")
                || text.contains("assign pipe_svt_p1_c = svt_zero;"),
            "lean zero feed expected: {text}"
        );
        assert!(
            !text.contains("assign t1 = pipe_svt_p1"),
            "lean must not sink continuous/procedural origins"
        );
        // Opt-in real feeds for continuous mid-module fixture is covered by
        // cut_feed_references_mid_module_net_after_decl.
        let dens = DensityReport::from_sv_fragment(
            text.split("BEGIN sv-timing").nth(1).unwrap_or(&text),
        );
        assert!(dens.score() >= min_density_score_for_edits(1));
        let mut tree = EmitTree::new();
        tree.add_file("deep_add_chain__svt.sv", FileRole::Module, text);
        let report = integrity_reparse(&tree, &ParseOptions::default());
        assert_valid_sv_bundle(&report).expect("reparse corrected");
    }

    /// Cut feed RHS uses a net declared *after* the first process — early inject
    /// would fail Verilator "used before its declaration"; late inject must win.
    #[test]
    fn cut_feed_references_mid_module_net_after_decl() {
        let src = r#"// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
module mid_decl (
    input  logic       clk_i,
    input  logic       rst_ni,
    input  logic [7:0] a_i,
    output logic [7:0] y_o
);
  logic [7:0] early;
  always_comb begin
    early = a_i;
  end
  logic [7:0] rounded_abs;
  assign rounded_abs = a_i + 8'd1;
  logic [7:0] cast_result;
  assign cast_result = rounded_abs ^ early;
  assign y_o = cast_result;
endmodule
"#;
        let mut trace = EditTrace::new();
        // Line 16: assign cast_result = rounded_abs ^ early;
        trace.record_edit(EditRecord {
            id: 0,
            kind: EditKind::InsertReg,
            origin: SourceLoc {
                file: "mid_decl.sv".into(),
                start_line: 16,
                start_col: 1,
                end_line: 16,
                end_col: 1,
                byte_start: 0,
                byte_end: 0,
                origin: OriginKind::UserFile,
            },
            path_id: Some(0),
            node_id: Some(1),
            new_name: Some("pipe_svt_p1".into()),
            fo4_before: Some(40.0),
            fo4_after: Some(16.0),
            rationale: "mid-module cut".into(),
            emit_rhs: None,
            emit_rhs_extras: Vec::new(),
            emit_snippet: None,
        });
        let mut dense = dense_options_from_source(src);
        dense.real_cut_feeds = true;
        let text = apply_edits_to_source_dense(src, &trace, &EmitPolicy::default(), &dense);
        let decl = text
            .find("logic [7:0] rounded_abs")
            .expect("rounded_abs decl");
        let feed = text
            .find("assign pipe_svt_p1_c = (rounded_abs ^ early)")
            .expect("cut feed with mid-module nets");
        assert!(
            feed > decl,
            "cut feed must appear after rounded_abs decl (R11); feed={feed} decl={decl}"
        );
        let mut tree = EmitTree::new();
        tree.add_file("mid_decl__svt.sv", FileRole::Module, text);
        let report = integrity_reparse(&tree, &ParseOptions::default());
        assert_valid_sv_bundle(&report).expect("reparse mid_decl");
    }

    /// BalanceMux snippets stay early so origin RHS rewrite can see staged wires.
    #[test]
    fn balance_mux_snippet_injects_before_first_process() {
        let src = r#"module bm_mod (
    input logic a, b, c,
    output logic y
);
  logic t;
  always_comb begin
    t = a | b;
    y = t;
  end
endmodule
"#;
        let snippet = "  // --- BalanceMux arm staging (latency-neutral) ---\n  logic [63:0] svt_bm_top_p1_n0;\n  always_comb begin : svt_bm_top_p1_n0_stage\n    svt_bm_top_p1_n0 = a | b;\n  end\n";
        let mut trace = EditTrace::new();
        trace.record_edit(EditRecord {
            id: 0,
            kind: EditKind::BalanceMux,
            origin: SourceLoc {
                file: "bm_mod.sv".into(),
                start_line: 7,
                start_col: 1,
                end_line: 7,
                end_col: 1,
                byte_start: 0,
                byte_end: 0,
                origin: OriginKind::UserFile,
            },
            path_id: Some(1),
            node_id: Some(0),
            new_name: Some("svt_bm_top_p1_n0".into()),
            fo4_before: Some(20.0),
            fo4_after: Some(10.0),
            rationale: "stage".into(),
            emit_rhs: Some("svt_bm_top_p1_n0".into()),
            emit_rhs_extras: Vec::new(),
            emit_snippet: Some(snippet.into()),
        });
        // Lean default: BalanceMux credit-only (no RTL).
        let lean = apply_edits_to_source(src, &trace, &EmitPolicy::default());
        assert!(
            lean.contains("review-only credit") || !lean.contains("svt_bm_top_p1_n0_stage"),
            "lean demotes BalanceMux RTL"
        );
        // Opt-in structural BalanceMux early inject.
        let mut dense = dense_options_from_source(src);
        dense.emit_balance_mux_rtl = true;
        let text = apply_edits_to_source_dense(src, &trace, &EmitPolicy::default(), &dense);
        assert!(
            text.contains("svt_bm_top_p1_n0_stage"),
            "unique block label expected with emit_balance_mux_rtl"
        );
        let early = text
            .find("BEGIN sv-timing auto-correct (balance_mux rewrite)")
            .expect("balance_mux early");
        let first_proc = text.find("always_comb begin").expect("first process");
        assert!(
            early < first_proc || text[..first_proc].contains("svt_bm_top_p1_n0"),
            "BalanceMux staging must be early"
        );
    }
}
