# Full corev_apu structural FO4 soak (excl. tb/test/deprecated).
# Packages from core/include for config/types.
+incdir+${CVA6_REPO_DIR}/core/include
+incdir+${CVA6_REPO_DIR}/corev_apu/include
+incdir+${CVA6_REPO_DIR}/vendor/pulp-platform/common_cells/include/
+incdir+${CVA6_REPO_DIR}/vendor/pulp-platform/axi/include/
${CVA6_REPO_DIR}/core/include/config_pkg.sv
${CVA6_REPO_DIR}/core/include/riscv_pkg.sv
${CVA6_REPO_DIR}/core/include/ariane_pkg.sv
${CVA6_REPO_DIR}/core/include/cv64a6_imafdc_sv39_config_pkg.sv
${CVA6_REPO_DIR}/corev_apu/altera/src/cva6_altera.sv
${CVA6_REPO_DIR}/corev_apu/altera/src/cva6_altera_peripherals.sv
${CVA6_REPO_DIR}/corev_apu/altera/src/dmi_vjtag.sv
${CVA6_REPO_DIR}/corev_apu/altera/src/dmi_vjtag_tap.sv
${CVA6_REPO_DIR}/corev_apu/axi_mem_if/src/axi2mem.sv
${CVA6_REPO_DIR}/corev_apu/bootrom/bootrom.sv
${CVA6_REPO_DIR}/corev_apu/clint/axi_lite_interface.sv
${CVA6_REPO_DIR}/corev_apu/clint/clint.sv
${CVA6_REPO_DIR}/corev_apu/coherence/g6lc_coherence_hub.sv
${CVA6_REPO_DIR}/corev_apu/coherence/g6lc_coherence_pkg.sv
${CVA6_REPO_DIR}/corev_apu/coherence/g6lc_inval_bus.sv
${CVA6_REPO_DIR}/corev_apu/coherence/g6lc_l1_inv_adapter.sv
${CVA6_REPO_DIR}/corev_apu/coherence/g6lc_lr_sc_tracker.sv
${CVA6_REPO_DIR}/corev_apu/coherence/g6lc_snoop_filter.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb/src/apb_cdc.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb/src/apb_demux.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb/src/apb_err_slv.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb/src/apb_intf.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb/src/apb_pkg.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb/src/apb_regs.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb/src/apb_test.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_node/src/apb_node.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_node/src/apb_node_wrap.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_timer/apb_timer.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_timer/timer.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_uart/src/apb_uart.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_uart/src/apb_uart_wrap.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_uart/src/reg_uart_wrap.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_uart/src/slib_clock_div.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_uart/src/slib_counter.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_uart/src/slib_edge_detect.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_uart/src/slib_fifo.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_uart/src/slib_input_filter.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_uart/src/slib_input_sync.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_uart/src/slib_mv_filter.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_uart/src/uart_baudgen.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_uart/src/uart_interrupt.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_uart/src/uart_receiver.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/apb_uart/src/uart_transmitter.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane-ethernet/axis_gmii_rx.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane-ethernet/axis_gmii_tx.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane-ethernet/dualmem_widen.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane-ethernet/dualmem_widen8.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane-ethernet/eth_mac_1g.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane-ethernet/eth_mac_1g_rgmii.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane-ethernet/eth_mac_1g_rgmii_fifo.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane-ethernet/framing_top.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane-ethernet/iddr.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane-ethernet/oddr.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane-ethernet/rgmii_core.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane-ethernet/rgmii_lfsr.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane-ethernet/rgmii_phy_if.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane-ethernet/rgmii_soc.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane-ethernet/ssio_ddr_in.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane_peripherals_xilinx.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/ariane_xilinx.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/axi2apb/src/axi2apb.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/axi2apb/src/axi2apb_64_32.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/axi2apb/src/axi2apb_wrap.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/axi_slice/src/axi_ar_buffer.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/axi_slice/src/axi_aw_buffer.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/axi_slice/src/axi_b_buffer.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/axi_slice/src/axi_r_buffer.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/axi_slice/src/axi_single_slice.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/axi_slice/src/axi_slice.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/axi_slice/src/axi_slice_wrap.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/axi_slice/src/axi_w_buffer.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/fan_ctrl.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/gpio/src/gpio.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/gpio/src/gpio_apb_wrap.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/gpio/src/gpio_axi_lite_wrap.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/gpio/src/gpio_input_stage.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/gpio/src/gpio_input_stage_no_clk_gates.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/gpio/src/gpio_reg_pkg.sv
${CVA6_REPO_DIR}/corev_apu/fpga/src/gpio/src/gpio_reg_top.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/DPTI/slicer_DPTI.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/ITI/cva6_iti/block_retirement.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/ITI/cva6_iti/iti.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/ITI/cva6_iti/itype_detector.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/ITI/cva6_iti/single_retirement.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/ITI/include/iti_pkg.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/rv_encapsulator-main/src/include/encap_pkg.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/rv_encapsulator-main/src/rtl/encapsulator.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/rv_tracer-main/include/te_pkg.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/rv_tracer-main/rtl/lzc.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/rv_tracer-main/rtl/rv_tracer.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/rv_tracer-main/rtl/te_branch_map.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/rv_tracer-main/rtl/te_filter.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/rv_tracer-main/rtl/te_packet_emitter.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/rv_tracer-main/rtl/te_priority.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/rv_tracer-main/rtl/te_reg.sv
${CVA6_REPO_DIR}/corev_apu/instr_tracing/rv_tracer-main/rtl/te_resync_counter.sv
${CVA6_REPO_DIR}/corev_apu/l2_cache/g6lc_l2_data.sv
${CVA6_REPO_DIR}/corev_apu/l2_cache/g6lc_l2_mshr.sv
${CVA6_REPO_DIR}/corev_apu/l2_cache/g6lc_l2_pkg.sv
${CVA6_REPO_DIR}/corev_apu/l2_cache/g6lc_l2_tag.sv
${CVA6_REPO_DIR}/corev_apu/l2_cache/g6lc_l2_top.sv
${CVA6_REPO_DIR}/corev_apu/l3_cache/g6lc_l3_inclusive_inv.sv
${CVA6_REPO_DIR}/corev_apu/l3_cache/g6lc_l3_pkg.sv
${CVA6_REPO_DIR}/corev_apu/l3_cache/g6lc_l3_top.sv
${CVA6_REPO_DIR}/corev_apu/l3_cache/g6lc_server_prefetcher.sv
${CVA6_REPO_DIR}/corev_apu/openpiton/ariane_verilog_wrap.sv
${CVA6_REPO_DIR}/corev_apu/openpiton/riscv_peripherals.sv
${CVA6_REPO_DIR}/corev_apu/register_interface/src/apb_to_reg.sv
${CVA6_REPO_DIR}/corev_apu/register_interface/src/axi_lite_to_reg.sv
${CVA6_REPO_DIR}/corev_apu/register_interface/src/axi_to_reg.sv
${CVA6_REPO_DIR}/corev_apu/register_interface/src/periph_to_reg.sv
${CVA6_REPO_DIR}/corev_apu/register_interface/src/reg_cdc.sv
${CVA6_REPO_DIR}/corev_apu/register_interface/src/reg_demux.sv
${CVA6_REPO_DIR}/corev_apu/register_interface/src/reg_intf.sv
${CVA6_REPO_DIR}/corev_apu/register_interface/src/reg_mux.sv
${CVA6_REPO_DIR}/corev_apu/register_interface/src/reg_test.sv
${CVA6_REPO_DIR}/corev_apu/register_interface/src/reg_to_mem.sv
${CVA6_REPO_DIR}/corev_apu/register_interface/src/reg_uniform.sv
${CVA6_REPO_DIR}/corev_apu/register_interface/vendor/lowrisc_opentitan/src/prim_subreg.sv
${CVA6_REPO_DIR}/corev_apu/register_interface/vendor/lowrisc_opentitan/src/prim_subreg_arb.sv
${CVA6_REPO_DIR}/corev_apu/register_interface/vendor/lowrisc_opentitan/src/prim_subreg_ext.sv
${CVA6_REPO_DIR}/corev_apu/register_interface/vendor/lowrisc_opentitan/src/prim_subreg_shadow.sv
${CVA6_REPO_DIR}/corev_apu/riscv-dbg/debug_rom/debug_rom.sv
${CVA6_REPO_DIR}/corev_apu/riscv-dbg/debug_rom/debug_rom_one_scratch.sv
${CVA6_REPO_DIR}/corev_apu/riscv-dbg/src/dm_csrs.sv
${CVA6_REPO_DIR}/corev_apu/riscv-dbg/src/dm_mem.sv
${CVA6_REPO_DIR}/corev_apu/riscv-dbg/src/dm_obi_top.sv
${CVA6_REPO_DIR}/corev_apu/riscv-dbg/src/dm_pkg.sv
${CVA6_REPO_DIR}/corev_apu/riscv-dbg/src/dm_sba.sv
${CVA6_REPO_DIR}/corev_apu/riscv-dbg/src/dm_top.sv
${CVA6_REPO_DIR}/corev_apu/riscv-dbg/src/dmi_cdc.sv
${CVA6_REPO_DIR}/corev_apu/riscv-dbg/src/dmi_jtag.sv
${CVA6_REPO_DIR}/corev_apu/riscv-dbg/src/dmi_jtag_tap.sv
${CVA6_REPO_DIR}/corev_apu/riscv-dbg/sva/dm_csrs_sva.sv
${CVA6_REPO_DIR}/corev_apu/riscv-dbg/sva/dm_sba_sva.sv
${CVA6_REPO_DIR}/corev_apu/riscv-dbg/sva/dm_top_sva.sv
${CVA6_REPO_DIR}/corev_apu/rv_plic/rtl/plic_regmap.sv
${CVA6_REPO_DIR}/corev_apu/rv_plic/rtl/plic_top.sv
${CVA6_REPO_DIR}/corev_apu/rv_plic/rtl/prim_subreg.sv
${CVA6_REPO_DIR}/corev_apu/rv_plic/rtl/prim_subreg_ext.sv
${CVA6_REPO_DIR}/corev_apu/rv_plic/rtl/rv_plic.sv
${CVA6_REPO_DIR}/corev_apu/rv_plic/rtl/rv_plic_gateway.sv
${CVA6_REPO_DIR}/corev_apu/rv_plic/rtl/rv_plic_reg_pkg.sv
${CVA6_REPO_DIR}/corev_apu/rv_plic/rtl/rv_plic_reg_top.sv
${CVA6_REPO_DIR}/corev_apu/rv_plic/rtl/rv_plic_target.sv
${CVA6_REPO_DIR}/corev_apu/rv_plic/rtl/tlul_pkg.sv
${CVA6_REPO_DIR}/corev_apu/rv_plic/rtl/top_pkg.sv
${CVA6_REPO_DIR}/corev_apu/src/ariane.sv
${CVA6_REPO_DIR}/corev_apu/src/g6lc_ara_attach.sv
${CVA6_REPO_DIR}/corev_apu/src/g6lc_axi_2to1_mux.sv
${CVA6_REPO_DIR}/corev_apu/src/g6lc_cluster.sv
