// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT

//! `g6q-emit-qemu` — backends **B1** (machine, CPU, devices) and **B2** (TCG plugins).
//!
//! # The boundary this crate exists on
//!
//! QEMU is GPL-2.0 and this package is MIT. Both facts survive because of one structural
//! rule, enforced by `tools/check_independence.py` and restated here because this is the
//! crate where it would be violated:
//!
//! > **The generator writes text. It never links, includes, binds or vendors QEMU.**
//!
//! The C this crate produces *is* part of a GPL work and therefore carries GPL terms —
//! emitting an MIT header into a QEMU tree would be the actual mistake. Output goes to
//! gitignored directories and is never tracked here
//! ([`AGENTS-licensing.md`] §2).
//!
//! # Stage
//!
//! Q0 implements the file header contract — the part that is a licensing correctness
//! question rather than a code-generation question — plus the emitted-file model. Q4
//! adds the machine, CPU and device emitters; Q5/Q7 add the plugins.
//!
//! [`AGENTS-licensing.md`]: ../../../AGENTS-licensing.md

#![forbid(unsafe_code)]

pub mod build;
pub mod cpu;
pub mod dts;
pub mod machine;
pub mod plugin;
pub mod pmu;

/// SPDX identifier every emitted file carries.
///
/// Deliberately GPL: the emitted file becomes part of QEMU, a separate work.
pub const EMITTED_SPDX: &str = "GPL-2.0-or-later";

/// A file produced by an emitter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmittedFile {
    /// Path relative to the emission root.
    pub path: String,
    /// Complete file contents, header included.
    pub contents: String,
}

impl EmittedFile {
    /// Compose a file from its body, prepending the mandatory header.
    ///
    /// `model_digest` identifies the [`g6q_core::TargetModel`] the content was derived
    /// from. It is the file's identity: no timestamp is emitted, so that re-running the
    /// generator on unchanged inputs produces byte-identical output and `gen --check` is
    /// a usable CI gate.
    pub fn new(
        path: impl Into<String>,
        generator_version: &str,
        model_digest: &str,
        body: &str,
    ) -> Self {
        let mut contents = banner(generator_version, model_digest);
        contents.push('\n');
        contents.push_str(body);
        if !contents.ends_with('\n') {
            contents.push('\n');
        }
        EmittedFile {
            path: path.into(),
            contents,
        }
    }

    /// Whether the file carries a well-formed header.
    pub fn header_is_valid(&self) -> bool {
        self.contents.contains("DO NOT EDIT")
            && self.contents.contains(EMITTED_SPDX)
            && self.contents.contains("does not link against QEMU")
    }
}

/// The mandatory header for generated C.
pub fn banner(generator_version: &str, model_digest: &str) -> String {
    format!(
        "/* DO NOT EDIT — generated by g6lc_qemu {generator_version} from model {model_digest}\n\
         \x20* SPDX-License-Identifier: {EMITTED_SPDX}\n\
         \x20* This file is part of QEMU (a separate work). The generator that produced it\n\
         \x20* is MIT-licensed and does not link against QEMU.\n\
         \x20*/\n"
    )
}

/// An emission: a set of files plus the digest they were derived from.
#[derive(Debug, Clone, Default)]
pub struct Emission {
    /// Files, in canonical path order.
    pub files: Vec<EmittedFile>,
}

impl Emission {
    /// An empty emission.
    pub fn new() -> Self {
        Self::default()
    }

    /// Add a file, keeping the set canonically ordered so output is deterministic
    /// regardless of the order emitters run in.
    pub fn push(&mut self, file: EmittedFile) {
        match self.files.binary_search_by(|f| f.path.cmp(&file.path)) {
            Ok(i) => self.files[i] = file,
            Err(i) => self.files.insert(i, file),
        }
    }

    /// Every file that is missing a valid header. Empty is the only acceptable result.
    pub fn files_missing_header(&self) -> Vec<&str> {
        self.files
            .iter()
            .filter(|f| !f.header_is_valid())
            .map(|f| f.path.as_str())
            .collect()
    }

    /// Whether two emissions are identical, which is what `gen --check` asserts.
    pub fn matches(&self, other: &Emission) -> bool {
        self.files == other.files
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn file(path: &str) -> EmittedFile {
        EmittedFile::new(path, "0.1.0", "sha256:abc", "void placeholder(void) { }\n")
    }

    #[test]
    fn emitted_files_carry_gpl_terms_not_mit() {
        // The emitted file becomes part of a GPL work; an MIT header here would be wrong.
        let f = file("hw/riscv/machine.c");
        assert!(f.contents.contains("GPL-2.0-or-later"));
        assert!(!f.contents.contains("SPDX-License-Identifier: MIT"));
    }

    #[test]
    fn emitted_files_state_the_no_link_boundary() {
        let f = file("hw/riscv/machine.c");
        assert!(f.contents.contains("does not link against QEMU"));
        assert!(f.header_is_valid());
    }

    #[test]
    fn emitted_files_warn_against_hand_editing() {
        let f = file("hw/riscv/machine.c");
        assert!(f.contents.starts_with("/* DO NOT EDIT"));
    }

    #[test]
    fn the_model_digest_is_the_identity_and_no_timestamp_is_emitted() {
        let a = EmittedFile::new("x.c", "0.1.0", "sha256:aaa", "body\n");
        let b = EmittedFile::new("x.c", "0.1.0", "sha256:aaa", "body\n");
        assert_eq!(a, b, "same inputs must give byte-identical output");

        let c = EmittedFile::new("x.c", "0.1.0", "sha256:bbb", "body\n");
        assert_ne!(a, c, "a different model must be visible in the output");
    }

    #[test]
    fn emission_order_is_canonical_regardless_of_insertion_order() {
        let mut a = Emission::new();
        a.push(file("z.c"));
        a.push(file("a.c"));
        let mut b = Emission::new();
        b.push(file("a.c"));
        b.push(file("z.c"));
        assert!(a.matches(&b));
        assert_eq!(a.files[0].path, "a.c");
    }

    #[test]
    fn a_file_without_a_header_is_detected() {
        let mut e = Emission::new();
        e.push(EmittedFile {
            path: "raw.c".into(),
            contents: "int main(void){}".into(),
        });
        assert_eq!(e.files_missing_header(), vec!["raw.c"]);
    }

    #[test]
    fn a_well_formed_emission_has_no_header_violations() {
        let mut e = Emission::new();
        e.push(file("hw/riscv/machine.c"));
        e.push(file("target/riscv/cpu.c"));
        assert!(e.files_missing_header().is_empty());
    }
}
