// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT

//! B1 custom-2 queue-instruction decoder, translation, and helpers.
//!
//! This module emits:
//!
//! - `target/riscv/g6lc-<target>-ai.decode` — the `decodetree` source for the
//!   queue instructions;
//! - `target/riscv/insn_trans/trans_g6lc_<target>_ai.c.inc` — the `trans_`
//!   routines included by `target/riscv/translate.c`;
//! - `target/riscv/g6lc-<target>-ai-helpers.h` — `DEF_HELPER` declarations;
//! - `target/riscv/g6lc-<target>-ai-helpers.c` — helper implementations.
//!
//! The generated code is GPL-2.0-or-later; the generator itself does not link
//! QEMU.  Real execution still needs the generated AI-island device (a
//! follow-up pass) because the helpers at this stage read no queue state.

use crate::{Emission, EmittedFile};
use g6q_core::model::TargetModel;

/// The queue instructions and the device that backs them are emitted as one unit.
///
/// The helpers `#include` the device's header and call into its state, so emitting either
/// half alone leaves the QEMU tree unbuildable. Both sides therefore share
/// [`crate::ai_island::resolved`] rather than carrying their own condition.
fn emit_guard(model: &TargetModel) -> Option<(String, &g6q_core::model::AiIslandModel)> {
    crate::ai_island::resolved(model)
}

/// Emit the `g6lc-<target>-ai.decode` decoder table.
pub fn emit_decode(model: &TargetModel, version: &str, digest: &str) -> Option<EmittedFile> {
    let (safe_id, island) = emit_guard(model)?;
    let instr = &island.instr_set;

    let op_bits = format!("{:07b}", instr.opcode_custom2 & 0x7f);
    let enq_bits = format!("{:07b}", (instr.match_enq >> 25) & 0x7f);
    let poll_bits = format!("{:07b}", (instr.match_poll >> 25) & 0x7f);
    let qfence_bits = format!("{:07b}", (instr.match_qfence >> 25) & 0x7f);
    let funct3 = format!("{:03b}", (instr.match_enq >> 12) & 0x7);

    let mut body = format!(
        "#\n\
# Generated decoder for the {id} AI queue instructions.\n\
# SPDX-License-Identifier: GPL-2.0-or-later\n\
#\n\
# The patterns below are derived from the design's own AI instruction set;\n\
# the source of truth is the ingested `mask_f7f3op` and `match_*` values.\n\
#\n\
%rd   7:5\n\
%rs1  15:5\n\
%rs2  20:5\n\
\n\
&r    rd rs1 rs2    !extern\n\
&r2   rd rs1         !extern\n\
\n\
@r    ....... ..... ..... ... ..... ....... &r %rs2 %rs1 %rd\n\
\n\
g6lc_{id}_ai_enq    {enq} ..... ..... {funct3} ..... {op} @r\n\
g6lc_{id}_ai_poll   {poll} ..... ..... {funct3} ..... {op} @r\n\
g6lc_{id}_ai_qfence {qfence} ..... ..... {funct3} ..... {op} @r\n",
        id = safe_id,
        funct3 = funct3,
        op = op_bits,
        enq = enq_bits,
        poll = poll_bits,
        qfence = qfence_bits,
    );

    if !body.ends_with('\n') {
        body.push('\n');
    }

    Some(EmittedFile {
        path: format!("target/riscv/g6lc-{safe_id}-ai.decode"),
        contents: format!(
            "# DO NOT EDIT — generated by g6lc_qemu {version} from model {digest}\n\
             # SPDX-License-Identifier: GPL-2.0-or-later\n\
             # This file is part of QEMU (a separate work). The generator that produced it\n\
             # is MIT-licensed and does not link against QEMU.\n\
             {body}"
        ),
    })
}

/// Emit the `trans_g6lc_<target>_ai.c.inc` translation stubs.
pub fn emit_trans(model: &TargetModel, version: &str, digest: &str) -> Option<EmittedFile> {
    let (safe_id, _) = emit_guard(model)?;

    let body = format!(
        "/*\n\
 * Translation routines for the {id} AI queue instructions.\n\
 * SPDX-License-Identifier: GPL-2.0-or-later\n\
 *\n\
 * These routines wire to `helper_g6lc_ai_*`.  The helpers return stub values\n\
 * until the generated AI-island device is available.\n\
 */\n\
\n\
static bool trans_g6lc_{id}_ai_enq(DisasContext *ctx, arg_r *a)\n\
{{\n\
    TCGv desc    = get_gpr(ctx, a->rs1, EXT_NONE);\n\
    TCGv ticket  = dest_gpr(ctx, a->rd);\n\
    gen_helper_g6lc_{id}_ai_enq(ticket, tcg_env, desc);\n\
    gen_set_gpr(ctx, a->rd, ticket);\n\
    return true;\n\
}}\n\
\n\
static bool trans_g6lc_{id}_ai_qfence(DisasContext *ctx, arg_r *a)\n\
{{\n\
    (void)ctx;\n\
    (void)a;\n\
    gen_helper_g6lc_{id}_ai_qfence(tcg_env);\n\
    return true;\n\
}}\n\
\n\
static bool trans_g6lc_{id}_ai_poll(DisasContext *ctx, arg_r *a)\n\
{{\n\
    TCGv ticket = get_gpr(ctx, a->rs1, EXT_NONE);\n\
    TCGv status = dest_gpr(ctx, a->rd);\n\
    gen_helper_g6lc_{id}_ai_poll(status, tcg_env, ticket);\n\
    gen_set_gpr(ctx, a->rd, status);\n\
    return true;\n\
}}\n",
        id = safe_id,
    );

    Some(EmittedFile::new(
        format!("target/riscv/insn_trans/trans_g6lc_{safe_id}_ai.c.inc"),
        version,
        digest,
        &body,
    ))
}

/// Emit `g6lc-<target>-ai-helpers.h` with `DEF_HELPER` declarations.
pub fn emit_helpers_h(model: &TargetModel, version: &str, digest: &str) -> Option<EmittedFile> {
    let (safe_id, _) = emit_guard(model)?;

    let body = format!(
        "/*\n\
 * Generated helper declarations for the {id} AI queue instructions.\n\
 * This unguarded fragment is meant to be included from target/riscv/helper.h;\n\
 * QEMU's helper-proto, helper-gen and helper-info expansions each redefine\n\
 * DEF_HELPER and re-include this fragment.\n\
 */\n\
DEF_HELPER_2(g6lc_{id}_ai_enq, tl, env, tl)\n\
DEF_HELPER_1(g6lc_{id}_ai_qfence, void, env)\n\
DEF_HELPER_2(g6lc_{id}_ai_poll, tl, env, tl)\n\
",
        id = safe_id,
    );

    Some(EmittedFile::new(
        format!("target/riscv/g6lc-{safe_id}-ai-helpers.h"),
        version,
        digest,
        &body,
    ))
}

/// Emit `g6lc-<target>-ai-helpers.c` with functional helper implementations.
pub fn emit_helpers_c(model: &TargetModel, version: &str, digest: &str) -> Option<EmittedFile> {
    let (safe_id, _) = emit_guard(model)?;

    let body = format!(
        r###"
/*
 * Helper implementations for the {id} AI queue instructions.
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#include "qemu/osdep.h"
#include "cpu.h"
#include "exec/helper-proto.h"
#include "hw/riscv/g6lc-{id}-ai-island.h"

target_ulong helper_g6lc_{id}_ai_enq(CPURISCVState *env, target_ulong desc_ptr)
{{
    return g6lc_{id}_ai_island_enq(g6lc_{id}_ai_island, env, desc_ptr);
}}

void helper_g6lc_{id}_ai_qfence(CPURISCVState *env)
{{
    g6lc_{id}_ai_island_qfence(g6lc_{id}_ai_island, env);
}}

target_ulong helper_g6lc_{id}_ai_poll(CPURISCVState *env, target_ulong ticket)
{{
    return g6lc_{id}_ai_island_poll(g6lc_{id}_ai_island, env, ticket);
}}
"###,
        id = safe_id,
    );

    Some(EmittedFile::new(
        format!("target/riscv/g6lc-{safe_id}-ai-helpers.c"),
        version,
        digest,
        &body,
    ))
}

/// Add decode, translation, helper, and device files to an emission when an
/// AI instruction set is present.
pub fn emit(model: &TargetModel, version: &str, digest: &str, emission: &mut Emission) {
    // One guard for the whole set: decoder, translation, device and helpers are
    // interdependent, so a partially-emitted set cannot build.
    if emit_guard(model).is_none() {
        return;
    }
    for f in [
        emit_decode(model, version, digest),
        emit_trans(model, version, digest),
    ]
    .into_iter()
    .flatten()
    {
        emission.push(f);
    }
    crate::ai_island::emit(model, version, digest, emission);
    for f in [
        emit_helpers_h(model, version, digest),
        emit_helpers_c(model, version, digest),
    ]
    .into_iter()
    .flatten()
    {
        emission.push(f);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use g6q_core::model::{AiDescLayout, AiInstrSet, DescField};

    fn ai_model() -> TargetModel {
        // The shared guard requires resolved descriptor geometry as well as an encoding,
        // because the helpers read the descriptor's completion pointer.
        let mut desc_layout = AiDescLayout {
            desc_bytes: 64,
            ..AiDescLayout::default()
        };
        desc_layout.fields.insert(
            "ptr_done".into(),
            DescField {
                offset: 56,
                size: 8,
                bit_low: 0,
                bit_high: 0,
            },
        );
        let mut m = TargetModel::new("ai");
        m.soc.ai_island = Some(g6q_core::model::AiIslandModel {
            instr_set: AiInstrSet {
                opcode_custom2: 0x5b,
                mask_f7f3op: 0xfe00707f,
                match_enq: 0x0000_505b,
                match_poll: 0x0200_505b,
                match_qfence: 0x0400_505b,
                ..Default::default()
            },
            desc_layout,
            ..Default::default()
        });
        m
    }

    #[test]
    fn emits_decode_with_ingested_patterns() {
        let m = ai_model();
        let f = emit_decode(&m, "0.1.0", "sha256:abc").unwrap();
        assert!(f.contents.contains("ai_enq"));
        assert!(f.contents.contains("1011011"));
        assert!(f.contents.contains("0000000"));
        assert!(f.contents.contains("0000001"));
        assert!(f.contents.contains("0000010"));
    }

    #[test]
    fn emits_trans_for_each_queue_instruction() {
        let m = ai_model();
        let f = emit_trans(&m, "0.1.0", "sha256:abc").unwrap();
        // Every symbol carries the target id: two AI machines must coexist in one
        // QEMU tree (the fixture `ai` machine and the real `g6lc64_ai` collided on
        // `helper_g6lc_ai_poll` / `trans_ai_enq` / the `g6lc_ai_island` global).
        let id = crate::machine::machine_name(&m.target_id);
        assert!(f.contents.contains(&format!("trans_g6lc_{id}_ai_enq")));
        assert!(f.contents.contains(&format!("trans_g6lc_{id}_ai_qfence")));
        assert!(f.contents.contains(&format!("trans_g6lc_{id}_ai_poll")));
        assert!(f.contents.contains(&format!("gen_helper_g6lc_{id}_ai_enq")));
        assert!(
            !f.contents.contains("trans_ai_enq(")
                && !f.contents.contains("gen_helper_g6lc_ai_enq(")
        );
    }

    #[test]
    fn emits_helper_header_and_source() {
        let m = ai_model();
        let h = emit_helpers_h(&m, "0.1.0", "sha256:abc").unwrap();
        let c = emit_helpers_c(&m, "0.1.0", "sha256:abc").unwrap();
        let id = crate::machine::machine_name(&m.target_id);
        assert!(h
            .contents
            .contains(&format!("DEF_HELPER_2(g6lc_{id}_ai_enq")));
        assert!(c.contents.contains(&format!("helper_g6lc_{id}_ai_enq")));
        assert!(c
            .contents
            .contains(&format!("g6lc_{id}_ai_island_enq(g6lc_{id}_ai_island,")));
        assert!(!h.contents.contains("DEF_HELPER_2(g6lc_ai_enq"));
    }

    #[test]
    fn skips_emission_when_no_ai_island() {
        let m = TargetModel::default();
        assert!(emit_decode(&m, "0.1.0", "sha256:abc").is_none());
        assert!(emit_trans(&m, "0.1.0", "sha256:abc").is_none());
        assert!(emit_helpers_h(&m, "0.1.0", "sha256:abc").is_none());
        assert!(emit_helpers_c(&m, "0.1.0", "sha256:abc").is_none());
    }
}
