// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT

//! Emit generated ZealC and linker artefacts from a [`BoardSpec`].

#![allow(missing_docs)]

use g6b_spec::{BoardSpec, ExtStatus};

/// All files the design compiler writes for one spec.
#[derive(Debug, Clone)]
pub struct DesignOut {
    pub config_zc: String,
    pub connectors_zc: String,
    pub mem_zc: String,
    pub linker_ld: String,
    pub kmain_zc: String,
    pub adam_zc: String,
    pub postboot_zc: String,
    pub loopback_zc: String,
    pub kstart_s: String,
    pub kints_s: String,
    pub gr_zc: String,
    pub memcpy_s: String,
    pub timer_s: String,
    pub browser_zc: String,
    pub tls_zc: String,
    pub https_zc: String,
    pub gl_glsl: String,
    pub svelte_zc: String,
    pub wasm_jit_s: String,
    pub crypto_s: String,
    pub endpoints_zc: String,
    pub holyc_ui_zc: String,
    pub mbox_dtsi: String,
    pub mbox_h: String,
    pub mbox_c: String,
    pub requirements: String,
}

/// Compile a BoardSpec into generated sources. Never emits RVV unless `spec.rvv_live()`.
pub fn compile(spec: &BoardSpec) -> DesignOut {
    DesignOut {
        config_zc: emit_config(spec),
        connectors_zc: emit_connectors(spec),
        mem_zc: emit_mem(spec),
        linker_ld: emit_linker(spec),
        kmain_zc: emit_kmain(spec),
        adam_zc: emit_adam(spec),
        postboot_zc: emit_postboot(spec),
        loopback_zc: emit_loopback(spec),
        kstart_s: emit_kstart_s(spec),
        kints_s: emit_kints_s(spec),
        gr_zc: emit_gr_zc(spec),
        memcpy_s: emit_memcpy_s(spec),
        timer_s: emit_timer_s(spec),
        browser_zc: emit_browser_zc(spec),
        tls_zc: emit_tls_zc(spec),
        https_zc: emit_https_zc(spec),
        gl_glsl: emit_gl_glsl(spec),
        svelte_zc: emit_svelte_zc(spec),
        wasm_jit_s: emit_wasm_jit_s(spec),
        crypto_s: emit_crypto_s(spec),
        endpoints_zc: emit_endpoints_zc(spec),
        holyc_ui_zc: emit_holyc_ui_zc(spec),
        mbox_dtsi: emit_mbox_dtsi(spec),
        mbox_h: emit_mbox_h(spec),
        mbox_c: emit_mbox_c(spec),
        requirements: emit_requirements(spec),
    }
}

fn flag(st: ExtStatus) -> u32 {
    match st {
        ExtStatus::Live => 1,
        _ => 0,
    }
}

fn emit_config(spec: &BoardSpec) -> String {
    let rvv = if spec.rvv_live() { 1 } else { 0 };
    format!(
        "// Generated by g6b-design — do not edit\n\
         // BoardSpec product={} march={}\n\
         #define G6LC_XLEN {}\n\
         #define G6LC_RVV {}\n\
         #define G6LC_RVC {}\n\
         #define G6LC_ZBA {}\n\
         #define G6LC_ZBB {}\n\
         #define G6LC_ZICBOZ {}\n\
         #define G6LC_ZACAS {}\n\
         #define G6LC_F {}\n\
         #define G6LC_D {}\n\
         #define G6LC_HARTS {}\n\
         #define G6LC_DISPLAY_HTML_JS {}\n\
         #define G6LC_GR {}\n\
         #define G6LC_GR_W {}\n\
         #define G6LC_GR_H {}\n\
         #define G6LC_GR_COLORS {}\n\
         #define G6LC_HOLYC_FAST_INIT {}\n\
         #define G6LC_DUAL_BAND_UART {}\n\
         #define G6LC_DUAL_BAND_TCP {}\n\
         #define G6LC_HOLYC_TCP_PORT {}\n\
         #define G6LC_POSTBOOT_{}\n\
         #define G6LC_POSTBOOT_KVM {}\n\
         #define G6LC_LOOPBACK {}\n\
         #define G6LC_MBOX_IRQ {}\n\
         #define G6LC_NET_EXPOSE_{}\n\
         #define G6LC_KVM_HTML_JS {}\n\
         #define G6LC_KVM_SSH_HOLYC {}\n\
         #define G6LC_PROXY {}\n\
         #define G6LC_PROXY_DPI {}\n\
         #define G6LC_PROXY_FPS {}\n\
         #define G6LC_PROXY_W {}\n\
         #define G6LC_PROXY_H {}\n\
         #define G6LC_PROXY_SCALE {}\n\
         #define G6LC_TIMER {}\n\
         #define G6LC_GL {}\n\
         #define G6LC_PROXY_ACCEL_RVV {}\n\
         #define G6LC_PROXY_ACCEL_AI {}\n\
         #define G6LC_TLS {}\n\
         #define G6LC_HTTPS {}\n\
         #define G6LC_WASM {}\n\
         #define G6LC_WASM_JIT {}\n\
         #define G6LC_UI_BLOB {}\n\
         #define G6LC_UI_MAGIC 0x49553647\n\
         #define G6LC_FILE_SERVE {}\n\
         #define G6LC_UI_SVELTE {}\n\
         #define G6LC_HTTP {}\n\
         #define G6LC_HTTP_GET {}\n\
         #define G6LC_HTTP1 {}\n\
         #define G6LC_HTTP2 {}\n\
         #define G6LC_HTTP_PROXY_JS {}\n\
         #define G6LC_PARAM_CLOCKS {}\n\
         #define G6LC_PARAM_EDK2 {}\n\
         #define G6LC_PARAM_UBOOT {}\n\
         #define G6LC_PARAM_BOOTLOADER {}\n\
         #define G6LC_CPU_HZ {}\n\
         #define G6LC_UART_BAUD {}\n\
         #define G6LC_HTTP_SERVE {}\n\
         #define G6LC_HTTP_FILES {}\n\
         #define G6LC_HTTP_FILES_HTML {}\n\
         #define G6LC_HTTP_FILES_JS {}\n\
         #define G6LC_HTTP_FILES_WASM {}\n\
         #define G6LC_HTTPS_FILES {}\n\
         #define G6LC_FLASH {}\n\
         #define G6LC_FLASH_OPENWRT {}\n\
         #define G6LC_FLASH_SELF {}\n\
         #define G6LC_SETTINGS {}\n\
         #define G6LC_SETTINGS_USB {}\n\
         #define G6LC_USB {}\n\
         #define G6LC_USB_FAT32 {}\n\
         #define G6LC_USB_KEY {}\n\
         #define G6LC_FS_FAT32 {}\n\
         #define G6LC_FS_NTFS {}\n\
         #define G6LC_FS_EXT4 {}\n\
         #define G6LC_CORES {}\n\
         #define G6LC_THREADS {}\n\
         #define G6LC_ISSUE {}\n\
         #define G6LC_OOO {}\n\
         #define G6LC_STREAM {}\n\
         #define G6LC_HYPERVISOR {}\n\
         #define G6LC_UNCORE_CLINT {}\n\
         #define G6LC_UNCORE_PLIC {}\n\
         #define G6LC_UNCORE_DDR {}\n\
         #define G6LC_UNCORE_PCIE {}\n\
         #define G6LC_UNCORE_ETH {}\n\
         #define G6LC_UNCORE_STORAGE {}\n\
         #define G6LC_UNCORE_HDMI {}\n",
        spec.product,
        spec.isa.march,
        spec.isa.xlen,
        rvv,
        flag(spec.isa.c),
        flag(spec.isa.zba),
        flag(spec.isa.zbb),
        flag(spec.isa.zicboz),
        flag(spec.isa.zacas),
        flag(spec.isa.f),
        flag(spec.isa.d),
        spec.harts,
        if spec.kernel.display == "html-js" {
            1
        } else {
            0
        },
        if spec.kernel.gr.enable { 1 } else { 0 },
        spec.kernel.gr.w,
        spec.kernel.gr.h,
        spec.kernel.gr.colors,
        if spec.holyc.fast_init { 1 } else { 0 },
        if spec.holyc.dual_band.uart { 1 } else { 0 },
        if spec.holyc.dual_band.tcp.enable {
            1
        } else {
            0
        },
        spec.holyc.dual_band.tcp.host_port,
        spec.postboot
            .enable
            .as_str()
            .replace('-', "_")
            .to_ascii_uppercase(),
        if spec.postboot.access == "kvm" { 1 } else { 0 },
        if spec.loopback.enable { 1 } else { 0 },
        spec.loopback.irq,
        spec.net_expose
            .mode
            .as_str()
            .replace('-', "_")
            .to_ascii_uppercase(),
        if spec.postboot.backends.iter().any(|b| b == "html-js") {
            1
        } else {
            0
        },
        if spec.postboot.backends.iter().any(|b| b == "ssh-holyc") {
            1
        } else {
            0
        },
        if spec.kernel.proxy.enable { 1 } else { 0 },
        spec.kernel.proxy.dpi,
        spec.kernel.proxy.refresh_hz(),
        spec.kernel.proxy.high_w,
        spec.kernel.proxy.high_h,
        {
            let sx = spec.kernel.proxy.high_w / spec.kernel.gr.w.max(1);
            let sy = spec.kernel.proxy.high_h / spec.kernel.gr.h.max(1);
            sx.min(sy).max(1)
        },
        1,
        if spec.kernel.proxy.gl { 1 } else { 0 },
        if spec.proxy_accel() == g6b_spec::ProxyAccel::Rvv {
            1
        } else {
            0
        },
        if spec.proxy_accel() == g6b_spec::ProxyAccel::AiIsland {
            1
        } else {
            0
        },
        if spec.kernel.tls.enable { 1 } else { 0 },
        if spec.kernel.tls.https { 1 } else { 0 },
        if spec.kernel.wasm.enable { 1 } else { 0 },
        if spec.kernel.wasm.jit { 1 } else { 0 },
        if spec.kernel.wasm.enable || spec.kernel.http.files.enable {
            1
        } else {
            0
        },
        if spec.kernel.wasm.enable || spec.kernel.http.files.enable {
            1
        } else {
            0
        },
        if spec.kernel.ui == "svelte-d" { 1 } else { 0 },
        if spec.kernel.http.enable { 1 } else { 0 },
        if spec.kernel.wasm.enable || spec.kernel.http.files.enable || spec.kernel.http.enable {
            1
        } else {
            0
        },
        if spec.kernel.http.http1 { 1 } else { 0 },
        if spec.kernel.http.http2 { 1 } else { 0 },
        if spec.kernel.http.proxy_js { 1 } else { 0 },
        if spec.kernel.params.clocks { 1 } else { 0 },
        if spec.kernel.params.edk2 { 1 } else { 0 },
        if spec.kernel.params.uboot { 1 } else { 0 },
        if spec.kernel.params.bootloader { 1 } else { 0 },
        spec.kernel.params.cpu_hz,
        spec.kernel.params.uart_baud,
        if spec.kernel.http.serve { 1 } else { 0 },
        if spec.kernel.http.files.enable { 1 } else { 0 },
        if spec.kernel.http.files.html { 1 } else { 0 },
        if spec.kernel.http.files.js { 1 } else { 0 },
        if spec.kernel.http.files.wasm { 1 } else { 0 },
        if spec.kernel.http.files.https { 1 } else { 0 },
        if spec.kernel.flash.enable { 1 } else { 0 },
        if spec.kernel.flash.openwrt { 1 } else { 0 },
        if spec.kernel.flash.self_update { 1 } else { 0 },
        if spec.kernel.settings.enable { 1 } else { 0 },
        if spec.kernel.settings.usb_key { 1 } else { 0 },
        if spec.kernel.usb.enable { 1 } else { 0 },
        if spec.kernel.usb.flash_fat32 { 1 } else { 0 },
        if spec.kernel.usb.key { 1 } else { 0 },
        if spec.kernel.usb.fs_fat32 { 1 } else { 0 },
        if spec.kernel.usb.fs_ntfs { 1 } else { 0 },
        if spec.kernel.usb.fs_ext4 { 1 } else { 0 },
        spec.cores,
        spec.threads,
        spec.geo.issue_ports,
        if spec.geo.ooo { 1 } else { 0 },
        if spec.geo.stream { 1 } else { 0 },
        if spec.hypervisor_live() { 1 } else { 0 },
        if spec.uncore.clint { 1 } else { 0 },
        if spec.uncore.plic { 1 } else { 0 },
        if spec.uncore.ddr { 1 } else { 0 },
        if spec.uncore.pcie { 1 } else { 0 },
        if spec.uncore.ethernet { 1 } else { 0 },
        if spec.uncore.storage { 1 } else { 0 },
        if spec.uncore.hdmi { 1 } else { 0 },
    )
}

fn emit_connectors(spec: &BoardSpec) -> String {
    let mut out = String::from("// Generated connectors — symbols exist only when live\n");
    for name in spec
        .connectors
        .core
        .iter()
        .chain(spec.connectors.apu.iter())
        .chain(spec.connectors.uncore.iter())
    {
        match name.as_str() {
            "sbi" => out.push_str("extern INative SbiPutchar(INative ch);\n"),
            "pmu" => out.push_str("extern INative PmuRead(INative idx);\n"),
            "opp" => out.push_str("extern INative OppSet(U8 *id);\n"),
            "uart" => out.push_str("extern INative UartPut(U8 ch);\n"),
            "gpio" => out.push_str("extern INative GpioRead(INative pin);\n"),
            "spi" => out.push_str("extern INative SpiRead(INative off, U8 *dst, INative n);\n"),
            "net" => out.push_str("extern INative NetSend(U8 *buf, INative n);\n"),
            "clint" | "aclint" => out.push_str("extern INative ClintTime();\n"),
            "plic" => out.push_str("extern INative PlicClaim();\n"),
            "ddr" | "litedram" | "dram" => out.push_str("extern INative DramProbe();\n"),
            "pcie" | "pci" => {
                out.push_str("extern INative PciCfgRead(INative bdf, INative off);\n")
            }
            "eth" | "ethernet" => out.push_str("extern INative EthStatus();\n"),
            "sata" | "nvme" | "sd" | "storage" => {
                out.push_str("extern INative BlkRead(INative lba, U8 *dst, INative n);\n")
            }
            "hdmi" | "displayport" | "dp" => out.push_str("extern INative HdmiEdid(U8 *dst);\n"),
            _ => {
                out.push_str("// unknown connector `");
                out.push_str(name);
                out.push_str("`\n");
            }
        }
    }
    for p in &spec.peripherals {
        if p.class == "ai-island" {
            out.push_str("extern INative AiCapRead(INative off);\n");
        }
    }
    if spec.holyc.dual_band.tcp.enable {
        out.push_str("extern INative HolycReplPut(U8 *buf, INative n);\n");
        out.push_str("extern INative HolycReplGet(U8 *buf, INative n);\n");
    }
    if spec.loopback.enable {
        out.push_str("extern INative MboxDoorbell(INative op);\n");
        out.push_str("extern INative MboxPut(U8 *buf, INative n);\n");
        out.push_str("extern INative MboxGet(U8 *buf, INative n);\n");
    }
    if spec.postboot.enable != g6b_spec::PostbootMode::Never {
        out.push_str("extern INative SbiSrst(INative typ);\n");
    }
    if spec.uncore.clint && !out.contains("ClintTime") {
        out.push_str("extern INative ClintTime();\n");
    }
    if spec.uncore.plic && !out.contains("PlicClaim") {
        out.push_str("extern INative PlicClaim();\n");
    }
    if spec.uncore.ddr && !out.contains("DramProbe") {
        out.push_str("extern INative DramProbe();\n");
    }
    if spec.uncore.pcie && !out.contains("PciCfgRead") {
        out.push_str("extern INative PciCfgRead(INative bdf, INative off);\n");
    }
    if spec.uncore.ethernet && !out.contains("EthStatus") {
        out.push_str("extern INative EthStatus();\n");
    }
    if spec.uncore.storage && !out.contains("BlkRead") {
        out.push_str("extern INative BlkRead(INative lba, U8 *dst, INative n);\n");
    }
    if spec.uncore.hdmi && !out.contains("HdmiEdid") {
        out.push_str("extern INative HdmiEdid(U8 *dst);\n");
    }
    out
}

fn emit_mem(spec: &BoardSpec) -> String {
    if spec.rvv_live() {
        String::from(
            "// Generated MemCpy — HolyC; RISC-V in MemCpy.S (ISEL-RVV)\n\
             U0 MemCpy(U8 *dst, U8 *src, INative n)\n\
             {\n\
             \twhile (n) { *dst++ = *src++; n--; }\n\
             }\n",
        )
    } else {
        String::from(
            "// Generated MemCpy — HolyC; RISC-V in MemCpy.S (ISEL-SCALAR)\n\
             U0 MemCpy(U8 *dst, U8 *src, INative n)\n\
             {\n\
             \twhile (n) { *dst++ = *src++; n--; }\n\
             }\n",
        )
    }
}

fn emit_memcpy_s(spec: &BoardSpec) -> String {
    g6b_asm::analyze::libcalls(spec).to_asm()
}

fn emit_timer_s(spec: &BoardSpec) -> String {
    g6b_asm::analyze::timer(spec).to_asm()
}

fn emit_linker(spec: &BoardSpec) -> String {
    format!(
        "/* Generated linker script: DRAM {} len {} text_offset {} XLEN {} */\n\
         OUTPUT_ARCH(riscv)\n\
         ENTRY(_start)\n\
         SECTIONS {{\n\
         \t. = {};\n\
         \t.text : {{ *(.text.start) *(.text*) }}\n\
         \t.rodata : {{ *(.rodata*) }}\n\
         \t.data : {{ *(.data*) }}\n\
         \t.bss : {{ *(.bss*) }}\n\
         }}\n",
        spec.dram_base, spec.dram_len, spec.text_offset, spec.isa.xlen, spec.dram_base,
    )
}

fn emit_kmain(spec: &BoardSpec) -> String {
    let port = spec.holyc.dual_band.tcp.host_port;
    let dual = if spec.holyc.dual_band.tcp.enable && spec.holyc.dual_band.uart {
        format!("\tPrint(\"DUAL-BAND uart+tcp:{port}\\n\");\n")
    } else if spec.holyc.dual_band.tcp.enable {
        format!("\tPrint(\"DUAL-BAND tcp:{port}\\n\");\n")
    } else if spec.holyc.dual_band.uart {
        String::from("\tPrint(\"DUAL-BAND uart\\n\");\n")
    } else {
        String::new()
    };
    let init = if spec.holyc.fast_init {
        "\tHolycInit();\n"
    } else {
        ""
    };
    let gr = if spec.kernel.gr.enable {
        format!(
            "U0 SysGrInit()\n\
             {{\n\
             \tPrint(\"GR-INIT {}x{}x{} backend={}\\n\");\n\
             }}\n\
             \n",
            spec.kernel.gr.w, spec.kernel.gr.h, spec.kernel.gr.colors, spec.kernel.gr.backend
        )
    } else {
        String::from(
            "U0 SysGrInit()\n\
             {\n\
             \tPrint(\"GR-OFF\\n\");\n\
             }\n\
             \n",
        )
    };
    format!(
        "// Generated KMain.ZC — rust g6b-design, do not edit\n\
         // product={} march={} xlen={}\n\
         U0 HolycInit()\n\
         {{\n\
         \tPrint(\"HOLYC-READY\\n\");\n\
         }}\n\
         \n\
         U0 UiBoot()\n\
         {{\n\
         \tPrint(\"UI-BOOT\\n\");\n\
         }}\n\
         \n\
         {gr}\
         U0 TimerInit()\n\
         {{\n\
         \tPrint(\"TIMER-READY SBI-TIME\\n\");\n\
         }}\n\
         \n\
         U0 KMain()\n\
         {{\n\
         \tPrint(\"G6LC-BIOS\\n\");\n\
         {init}\
         {dual}\
         \tSysGrInit();\n\
         \tTimerInit();\n\
         \tUiBoot();\n\
         }}\n",
        spec.product, spec.isa.march, spec.isa.xlen
    )
}

fn emit_adam(spec: &BoardSpec) -> String {
    format!(
        "// Generated Adam.ZC — Temple/ZealOS first task (product={})\n\
         U0 Adam()\n\
         {{\n\
         \tKMain();\n\
         }}\n",
        spec.product
    )
}

fn emit_postboot(spec: &BoardSpec) -> String {
    let mut out = format!(
        "// Generated PostBoot.ZC — enable={} access={}\n\
         // Immutable after Linux handoff (viewable, writes disabled):\n",
        spec.postboot.enable.as_str(),
        spec.postboot.access
    );
    for name in &spec.postboot.immutable {
        out.push_str("//   ");
        out.push_str(name);
        out.push('\n');
    }
    out.push_str(
        "U0 LinuxHandoff()\n\
         {\n\
         \tPrint(\"POSTBOOT-LIVE\\n\");\n\
         }\n\
         \n\
         U0 SshHolyc()\n\
         {\n\
         \tPrint(\"SSH-HOLYC\\n\");\n\
         }\n\
         \n\
         U0 ViewSection(U8 *name)\n\
         {\n\
         \tPrint(\"VIEW %s\\n\", name);\n\
         }\n\
         \n\
         U0 WriteSection(U8 *name)\n\
         {\n\
         \tPrint(\"WRITE %s\\n\", name);\n\
         }\n",
    );
    for cmd in &spec.postboot.power {
        let tag = match cmd.as_str() {
            "reboot" => "POWER-REBOOT",
            "shutdown" => "POWER-SHUTDOWN",
            "wakeup" => "POWER-WAKEUP",
            other => other,
        };
        let ident = match cmd.as_str() {
            "reboot" => "Reboot",
            "shutdown" => "Shutdown",
            "wakeup" => "Wakeup",
            other => other,
        };
        out.push_str(&format!("\nU0 {ident}()\n{{\n\tPrint(\"{tag}\\n\");\n}}\n"));
    }
    out
}

fn emit_browser_zc(spec: &BoardSpec) -> String {
    let mut out = String::from(
        "// Generated Browser.ZC — lightweight BIOS browser (not Chromium, not goja runtime)\n",
    );
    out.push_str(&format!(
        "// js={} display={} gl={}\n",
        spec.kernel.js, spec.kernel.display, spec.kernel.proxy.gl as u8
    ));
    for name in g6b_webidl::LIVE.iter().take(8) {
        out.push_str("// ");
        out.push_str(&g6b_webidl::marker(name));
        out.push('\n');
    }
    out.push_str("// ");
    out.push_str(&g6b_webidl::marker("Fetch"));
    out.push('\n');
    out.push_str("// ");
    out.push_str(&g6b_webidl::marker("WebGLRenderingContext"));
    out.push('\n');
    if spec.kernel.ui == "svelte-d" {
        out.push_str("// ui=svelte-d (kernel-spec/svelte-d; not LDC, not SvelteKit)\n");
    }
    if spec.kernel.usb.enable {
        out.push_str("// USB-FAT32 flash picker (always); firmware .bin/.elf/.img only\n");
        if spec.kernel.usb.key {
            out.push_str("// USB-FILES FileMgr fat32/ntfs/ext4 (two-pane; fetch /bios/files)\n");
        }
    }
    out.push_str(
        "// browser-UI: fetch /bios/menu/{main,cpu,memory,uncore,devices,boot,settings}\n",
    );
    out.push_str("U0 BrowserInit()\n{\n");
    out.push_str("\tPrint(\"BROWSER-READY\\n\");\n");
    if spec.kernel.wasm.enable {
        out.push_str(&format!("\tPrint(\"{}\\n\");\n", g6b_wasm::MARKER));
    }
    if spec.kernel.ui == "svelte-d" {
        out.push_str("\tPrint(\"SVELTE-LIVE NodeDef\\n\");\n");
        if spec.kernel.usb.key {
            out.push_str("\tPrint(\"SVELTE-LIVE FileMgr\\n\");\n");
        }
    }
    if spec.kernel.usb.enable {
        out.push_str("\tPrint(\"USB-FAT32\\n\");\n");
        if spec.kernel.usb.key {
            out.push_str("\tPrint(\"USB-FILES fat32/ntfs/ext4\\n\");\n");
        }
    }
    out.push_str("}\n");
    out
}

fn emit_svelte_zc(spec: &BoardSpec) -> String {
    let mut out = format!(
        "// Generated Svelte.ZC — svelte-d NodeDef catalog (ui={})\n",
        spec.kernel.ui
    );
    for m in g6b_wasm::svelte_live_markers() {
        out.push_str("// ");
        out.push_str(&m);
        out.push('\n');
    }
    if let Some(a) = g6b_wasm::svelte_stub_markers()
        .iter()
        .find(|s| s.contains("await"))
    {
        out.push_str("// ");
        out.push_str(a);
        out.push('\n');
    }
    out.push_str(
        "U0 SvelteInit()\n\
         {\n\
         \tPrint(\"SVELTE-LIVE NodeDef\\n\");\n",
    );
    if spec.kernel.usb.key {
        out.push_str("\tPrint(\"SVELTE-LIVE FileMgr\\n\");\n");
    }
    out.push_str("}\n");
    out
}

fn emit_wasm_jit_s(spec: &BoardSpec) -> String {
    if spec.kernel.wasm.jit {
        g6b_wasm::jit_add_i32().to_asm()
    } else {
        String::from("/* WASM-JIT off */\n")
    }
}

fn emit_tls_zc(spec: &BoardSpec) -> String {
    format!(
        "// Generated Tls.ZC — Botan rewrite: RSA+ECDSA+X.509 (enable={})\n\
         U0 TlsHandshake()\n\
         {{\n\
         \tPrint(\"{}\\n\");\n\
         }}\n\
         U0 TlsClientHello(U8 *host)\n\
         {{\n\
         \tPrint(\"TLS-CLIENTHELLO\\n\");\n\
         }}\n\
         U0 RsaVerify()\n\
         {{\n\
         \tPrint(\"RSA-VERIFY PKCS1-SHA256\\n\");\n\
         }}\n\
         U0 EcdsaVerify()\n\
         {{\n\
         \tPrint(\"ECDSA-VERIFY P256-SHA256\\n\");\n\
         }}\n\
         U0 CertParse(U8 *pem)\n\
         {{\n\
         \tPrint(\"CERT-OK\\n\");\n\
         }}\n\
         U0 NetOpenPort(U8 *kind)\n\
         {{\n\
         \tPrint(\"NET-OPEN %s bios-https={} ssh-holyc={}\\n\", kind);\n\
         }}\n",
        spec.kernel.tls.enable as u8,
        g6b_tls::tls_hello(),
        spec.net_expose.bios_https_port,
        spec.net_expose.ssh_holyc_port
    )
}

fn emit_https_zc(spec: &BoardSpec) -> String {
    let mut out = format!(
        "// Generated Https.ZC — web-compatible ClientHello (https={}) ServerHello (serve={})\n\
         U0 HttpsGet(U8 *url)\n\
         {{\n\
         \tPrint(\"HTTPS-GET %s\\n\", url);\n\
         }}\n",
        spec.kernel.tls.https as u8, spec.kernel.tls.serve as u8
    );
    if spec.kernel.tls.serve || spec.kernel.http.files.https {
        out.push_str(
            "U0 TlsServerHello(U8 *host)\n{\n\tPrint(\"TLS-SERVERHELLO\\n\");\n}\n\
             U0 HttpsServe()\n{\n\tPrint(\"HTTPS-SERVE files\\n\");\n}\n",
        );
    }
    out
}

fn emit_crypto_s(spec: &BoardSpec) -> String {
    g6b_asm::crypto::lib(&spec.kernel.tls).to_asm()
}

fn emit_endpoints_zc(spec: &BoardSpec) -> String {
    let mut out = format!(
        "// Generated Endpoints.ZC — kernel HTTP (http1={} http2={}); not SvelteKit\n",
        spec.kernel.http.http1 as u8, spec.kernel.http.http2 as u8
    );
    out.push_str(
        "U0 RegisterEndpoint(U8 *path, U8 *method)\n\
         {\n\
         \tPrint(\"EP-REG %s %s\\n\", method, path);\n\
         }\n\
         U0 HttpHandle(U8 *raw)\n\
         {\n\
         \tPrint(\"HTTP-OK\\n\");\n\
         }\n\
         U0 KernelGet(U8 *path)\n\
         {\n\
         \tPrint(\"KERNEL-GET %s\\n\", path);\n\
         }\n",
    );
    if spec.kernel.params.clocks {
        out.push_str("U0 BiosClocks() { KernelGet(\"/bios/clocks\"); }\n");
    }
    if spec.kernel.flash.enable {
        out.push_str(
            "U0 FlashImage(U8 *img)\n{\n\tPrint(\"FLASH-IMAGE %s\\n\", img);\n}\n\
             U0 BiosUpdate()\n{\n\tPrint(\"BIOS-UPDATE self\\n\");\n}\n",
        );
    }
    if spec.kernel.settings.enable {
        out.push_str(
            "U0 SettingsExport(U8 *via)\n{\n\tPrint(\"SETTINGS-EXPORT via=%s\\n\", via);\n}\n\
             U0 SettingsImport(U8 *via)\n{\n\tPrint(\"SETTINGS-IMPORT via=%s\\n\", via);\n}\n",
        );
    }
    if spec.kernel.usb.enable {
        out.push_str(
            "U0 UsbLs(U8 *kind)\n{\n\tPrint(\"USB-LS %s\\n\", kind);\n}\n\
             U0 UsbFlash(U8 *name)\n{\n\tPrint(\"USB-FLASH fat32 %s\\n\", name);\n}\n",
        );
        if spec.kernel.usb.key {
            out.push_str("U0 UsbKey(U8 *op)\n{\n\tPrint(\"USB-KEY %s\\n\", op);\n}\n");
        }
    }
    out.push_str(
        "U0 Menu(U8 *id)\n{\n\tKernelGet(\"/bios/menu\");\n}\n\
         U0 MenuCpu()\n{\n\tKernelGet(\"/bios/menu/cpu\");\n}\n\
         U0 MenuUncore()\n{\n\tKernelGet(\"/bios/menu/uncore\");\n}\n",
    );
    if spec.kernel.http.files.enable {
        out.push_str(
            "U0 FileServe(U8 *path)\n{\n\tKernelGet(path);\n}\n\
             U0 HttpFile(U8 *path)\n{\n\tKernelGet(path);\n}\n",
        );
    }
    out
}

fn emit_holyc_ui_zc(spec: &BoardSpec) -> String {
    g6b_ui::holyc_print_src(spec)
}

fn emit_gl_glsl(spec: &BoardSpec) -> String {
    let p = g6b_gr::proxy::Proxy::from_spec(spec);
    g6b_gr::gl::listing(&p)
}

fn emit_gr_zc(spec: &BoardSpec) -> String {
    let g = &spec.kernel.gr;
    format!(
        "// Generated Gr.ZC — rewrite of kernel-spec SysGrInit (not VGA ports)\n\
         // backend={} {}x{}x{}\n\
         U0 SysGrInit();\n",
        g.backend, g.w, g.h, g.colors
    )
}

fn emit_kstart_s(spec: &BoardSpec) -> String {
    g6b_asm::analyze::kstart(spec).to_asm()
}

fn emit_kints_s(spec: &BoardSpec) -> String {
    g6b_asm::analyze::kints(spec).to_asm()
}

fn emit_loopback(spec: &BoardSpec) -> String {
    if !spec.loopback.enable {
        return String::from("// loopback disabled\n");
    }
    format!(
        "// Generated Loopback.ZC — mbox {} irq {} → {}\n\
         // not a netdev; Linux binds after NET-DELEGATE\n\
         U0 LoopbackInit()\n\
         {{\n\
         \tPrint(\"LOOPBACK-MBOX\\n\");\n\
         }}\n",
        spec.loopback.base, spec.loopback.irq, spec.loopback.chardev
    )
}

fn emit_mbox_dtsi(spec: &BoardSpec) -> String {
    if !spec.loopback.enable {
        return String::new();
    }
    format!(
        "/* Generated — not a netdev. UART irq=1 SPI irq=2; this mailbox uses irq {}. */\n\
         bios_mbox: bios-mbox@{} {{\n\
         \tcompatible = \"{}\";\n\
         \treg = <0x0 {} 0x0 {}>;\n\
         \tinterrupt-parent = <&PLIC0>;\n\
         \tinterrupts = <{}>;\n\
         }};\n",
        spec.loopback.irq,
        spec.loopback
            .base
            .trim_start_matches("0x")
            .trim_start_matches("0X"),
        spec.loopback.compatible,
        spec.loopback.base,
        spec.loopback.len,
        spec.loopback.irq
    )
}

fn emit_mbox_h(spec: &BoardSpec) -> String {
    format!(
        "/* Generated g6lc_bios_mbox.h — MEI/SMC/IPMI-BT shaped; not a netdev */\n\
         #ifndef G6LC_BIOS_MBOX_H\n\
         #define G6LC_BIOS_MBOX_H\n\
         #define G6LC_MBOX_DOORBELL 0x00u\n\
         #define G6LC_MBOX_LENGTH   0x04u\n\
         #define G6LC_MBOX_STATUS   0x08u\n\
         #define G6LC_MBOX_IRQ_EN   0x0cu\n\
         #define G6LC_MBOX_CMD      0x10u\n\
         #define G6LC_MBOX_RSP      0x110u\n\
         #define G6LC_MBOX_CMD_BYTES 0x100u\n\
         #define G6LC_MBOX_RSP_BYTES 0x100u\n\
         #define G6LC_MBOX_ST_BUSY  0x1u\n\
         #define G6LC_MBOX_ST_RSP   0x2u\n\
         #define G6LC_MBOX_ST_DELEG 0x4u\n\
         #define G6LC_MBOX_IRQ      {}u\n\
         #endif\n",
        spec.loopback.irq
    )
}

fn emit_mbox_c(spec: &BoardSpec) -> String {
    format!(
        "/* Generated g6lc_bios_mbox.c — Linux miscdriver for {chardev} */\n\
         /* Analog: mei / ipmi_si / AppleSMC. Never a network device. */\n\
         /* After NET-DELEGATE both KVM faces (SSH+HolyC, HTML+JS ToHtml) ride this mailbox. */\n\
         #include <linux/miscdevice.h>\n\
         #include <linux/interrupt.h>\n\
         #include <linux/io.h>\n\
         #include <linux/module.h>\n\
         #include <linux/of.h>\n\
         #include <linux/platform_device.h>\n\
         #include <linux/uaccess.h>\n\
         #include \"g6lc_bios_mbox.h\"\n\
         \n\
         struct g6lc_bios {{\n\
         \tvoid __iomem *base;\n\
         \tint irq;\n\
         \tstruct miscdevice misc;\n\
         }};\n\
         \n\
         static irqreturn_t g6lc_bios_irq(int irq, void *data)\n\
         {{\n\
         \tstruct g6lc_bios *p = data;\n\
         \tu32 st = readl(p->base + G6LC_MBOX_STATUS);\n\
         \tif (!(st & G6LC_MBOX_ST_RSP))\n\
         \t\treturn IRQ_NONE;\n\
         \treturn IRQ_HANDLED;\n\
         }}\n\
         \n\
         static ssize_t g6lc_bios_read(struct file *f, char __user *buf, size_t n, loff_t *off)\n\
         {{\n\
         \tstruct g6lc_bios *p = container_of(f->private_data, struct g6lc_bios, misc);\n\
         \tu8 tmp[G6LC_MBOX_RSP_BYTES];\n\
         \tu32 len;\n\
         \tu32 i;\n\
         \t(void)off;\n\
         \tlen = readl(p->base + G6LC_MBOX_LENGTH);\n\
         \tif (len > G6LC_MBOX_RSP_BYTES)\n\
         \t\tlen = G6LC_MBOX_RSP_BYTES;\n\
         \tif (n < len)\n\
         \t\tlen = (u32)n;\n\
         \tfor (i = 0; i < len; i++)\n\
         \t\ttmp[i] = readb(p->base + G6LC_MBOX_RSP + i);\n\
         \tif (copy_to_user(buf, tmp, len))\n\
         \t\treturn -EFAULT;\n\
         \twritel(0, p->base + G6LC_MBOX_STATUS);\n\
         \treturn (ssize_t)len;\n\
         }}\n\
         \n\
         static ssize_t g6lc_bios_write(struct file *f, const char __user *buf, size_t n, loff_t *off)\n\
         {{\n\
         \tstruct g6lc_bios *p = container_of(f->private_data, struct g6lc_bios, misc);\n\
         \tu8 tmp[G6LC_MBOX_CMD_BYTES];\n\
         \tu32 len = n > G6LC_MBOX_CMD_BYTES ? G6LC_MBOX_CMD_BYTES : (u32)n;\n\
         \tu32 i;\n\
         \t(void)off;\n\
         \tif (copy_from_user(tmp, buf, len))\n\
         \t\treturn -EFAULT;\n\
         \tfor (i = 0; i < len; i++)\n\
         \t\twriteb(tmp[i], p->base + G6LC_MBOX_CMD + i);\n\
         \twritel(len, p->base + G6LC_MBOX_LENGTH);\n\
         \twritel(1, p->base + G6LC_MBOX_DOORBELL);\n\
         \treturn (ssize_t)len;\n\
         }}\n\
         \n\
         static const struct file_operations g6lc_bios_fops = {{\n\
         \t.owner = THIS_MODULE,\n\
         \t.read = g6lc_bios_read,\n\
         \t.write = g6lc_bios_write,\n\
         }};\n\
         \n\
         static const struct of_device_id g6lc_bios_mbox_of[] = {{\n\
         \t{{ .compatible = \"{compat}\" }},\n\
         \t{{ }}\n\
         }};\n\
         MODULE_DEVICE_TABLE(of, g6lc_bios_mbox_of);\n\
         \n\
         static int g6lc_bios_probe(struct platform_device *pdev)\n\
         {{\n\
         \tstruct g6lc_bios *p;\n\
         \tstruct resource *res;\n\
         \tint ret;\n\
         \tp = devm_kzalloc(&pdev->dev, sizeof(*p), GFP_KERNEL);\n\
         \tif (!p)\n\
         \t\treturn -ENOMEM;\n\
         \tres = platform_get_resource(pdev, IORESOURCE_MEM, 0);\n\
         \tp->base = devm_ioremap_resource(&pdev->dev, res);\n\
         \tif (IS_ERR(p->base))\n\
         \t\treturn PTR_ERR(p->base);\n\
         \tp->irq = platform_get_irq(pdev, 0);\n\
         \tif (p->irq < 0)\n\
         \t\treturn p->irq;\n\
         \tret = devm_request_irq(&pdev->dev, p->irq, g6lc_bios_irq, 0, \"g6lc-bios\", p);\n\
         \tif (ret)\n\
         \t\treturn ret;\n\
         \twritel(1, p->base + G6LC_MBOX_IRQ_EN);\n\
         \tp->misc.minor = MISC_DYNAMIC_MINOR;\n\
         \tp->misc.name = \"g6lc-bios\";\n\
         \tp->misc.fops = &g6lc_bios_fops;\n\
         \tplatform_set_drvdata(pdev, p);\n\
         \treturn misc_register(&p->misc);\n\
         }}\n\
         \n\
         static void g6lc_bios_remove(struct platform_device *pdev)\n\
         {{\n\
         \tstruct g6lc_bios *p = platform_get_drvdata(pdev);\n\
         \tmisc_deregister(&p->misc);\n\
         }}\n\
         \n\
         static struct platform_driver g6lc_bios_drv = {{\n\
         \t.probe = g6lc_bios_probe,\n\
         \t.remove = g6lc_bios_remove,\n\
         \t.driver = {{\n\
         \t\t.name = \"g6lc-bios-mbox\",\n\
         \t\t.of_match_table = g6lc_bios_mbox_of,\n\
         \t}},\n\
         }};\n\
         \n\
         module_platform_driver(g6lc_bios_drv);\n\
         /* Dual MIT/GPL if built out-of-tree; this generated stub is MIT in-package. */\n\
         MODULE_LICENSE(\"Dual MIT/GPL\");\n\
         MODULE_DESCRIPTION(\"GSys LibreCore BIOS mailbox ({chardev}, irq {irq})\");\n",
        chardev = spec.loopback.chardev,
        compat = spec.loopback.compatible,
        irq = spec.loopback.irq
    )
}

fn emit_requirements(spec: &BoardSpec) -> String {
    let mut out = String::from("# Inferred architecture requirements (from BoardSpec)\n");
    for line in spec.inferred_arch() {
        out.push_str("- ");
        out.push_str(&line);
        out.push('\n');
    }
    if spec.inferred_arch().is_empty() {
        out.push_str("- none (postboot.enable=never)\n");
    }
    out
}

/// Write `DesignOut` under `dir`.
pub fn write_to_dir(out: &DesignOut, dir: &std::path::Path) -> Result<(), String> {
    std::fs::create_dir_all(dir.join("zeal")).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/Config.ZC"), &out.config_zc).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/Connectors.ZC"), &out.connectors_zc)
        .map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/Mem.ZC"), &out.mem_zc).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/KMain.ZC"), &out.kmain_zc).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/Adam.ZC"), &out.adam_zc).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/PostBoot.ZC"), &out.postboot_zc).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/Loopback.ZC"), &out.loopback_zc).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/KStart.S"), &out.kstart_s).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/KInts.S"), &out.kints_s).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/Gr.ZC"), &out.gr_zc).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/MemCpy.S"), &out.memcpy_s).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/Timer.S"), &out.timer_s).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/Browser.ZC"), &out.browser_zc).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/Tls.ZC"), &out.tls_zc).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/Https.ZC"), &out.https_zc).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/adapter.glsl"), &out.gl_glsl).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/Svelte.ZC"), &out.svelte_zc).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/WasmJit.S"), &out.wasm_jit_s).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/TlsCrypto.S"), &out.crypto_s).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/Endpoints.ZC"), &out.endpoints_zc).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("zeal/HolycUi.ZC"), &out.holyc_ui_zc).map_err(|e| e.to_string())?;
    std::fs::create_dir_all(dir.join("linux")).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("linux/g6lc-bios-mbox.dtsi"), &out.mbox_dtsi)
        .map_err(|e| e.to_string())?;
    std::fs::write(dir.join("linux/g6lc_bios_mbox.h"), &out.mbox_h).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("linux/g6lc_bios_mbox.c"), &out.mbox_c).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("REQUIREMENTS.md"), &out.requirements).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("linker.ld"), &out.linker_ld).map_err(|e| e.to_string())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use g6b_spec::BoardSpec;

    #[test]
    fn rv32_config_has_xlen_32_and_rvv_0() {
        let spec = BoardSpec::from_json_str(
            r#"{"schema_version":1,"isa":{"xlen":32,"march":"rv32imac","extensions":{"c":"live","v":"absent"}}}"#,
        )
        .unwrap();
        let out = compile(&spec);
        assert!(
            out.config_zc.contains("#define G6LC_XLEN 32"),
            "{}",
            out.config_zc
        );
        assert!(
            out.config_zc.contains("#define G6LC_RVV 0"),
            "{}",
            out.config_zc
        );
        assert!(out.mem_zc.contains("ISEL-SCALAR"), "{}", out.mem_zc);
        assert!(!out.memcpy_s.contains("vsetvli"), "{}", out.memcpy_s);
    }

    #[test]
    fn fixtures_compile() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures");
        for name in [
            "cv32-uart.json",
            "g6lc64-virt.json",
            "g6lc32-router.json",
            "g6lc64-smt2.json",
        ] {
            let s = std::fs::read_to_string(root.join(name)).expect(name);
            let spec = BoardSpec::from_json_str(&s).expect(name);
            let out = compile(&spec);
            if name.contains("32") {
                assert!(out.config_zc.contains("G6LC_XLEN 32"));
                assert!(out.config_zc.contains("G6LC_RVV 0"));
            } else {
                assert!(out.config_zc.contains("G6LC_XLEN 64"));
                assert!(out.config_zc.contains("G6LC_RVV 0"));
            }
            assert!(out.kmain_zc.contains("HolycInit"), "{}", out.kmain_zc);
            assert!(out.adam_zc.contains("KMain()"), "{}", out.adam_zc);
            assert!(out.kstart_s.contains("purpose=hart-id"), "{}", out.kstart_s);
            assert!(out.kstart_s.contains("csrw\tstvec"), "{}", out.kstart_s);
            assert!(out.kstart_s.contains("mv\ttp, a0"), "{}", out.kstart_s);
            assert!(!out.kstart_s.contains("EFER") && !out.kstart_s.contains("CR0"));
            assert!(out.kints_s.contains("scause"), "{}", out.kints_s);
            assert!(out.kints_s.contains("trap_timer"), "{}", out.kints_s);
            assert!(out.timer_s.contains("sie"), "{}", out.timer_s);
            assert!(out.timer_s.contains("sstatus"), "{}", out.timer_s);
            assert!(out.timer_s.contains("rdtime"), "{}", out.timer_s);
            assert!(
                out.kstart_s.contains("jal\tra, TimerInit"),
                "{}",
                out.kstart_s
            );
            assert!(!out.kints_s.contains("LAPIC") && !out.kints_s.contains("IRET"));
            assert!(
                out.memcpy_s.contains("ISEL-SCALAR") || out.memcpy_s.contains("ISEL-RVV"),
                "{}",
                out.memcpy_s
            );
            assert!(
                out.config_zc.contains("G6LC_USB_FAT32 1"),
                "{}",
                out.config_zc
            );
            assert!(out.holyc_ui_zc.contains("HOLYC-UI"), "{}", out.holyc_ui_zc);
            assert!(out.endpoints_zc.contains("MenuCpu"), "{}", out.endpoints_zc);
            assert!(
                out.endpoints_zc.contains("UsbFlash"),
                "{}",
                out.endpoints_zc
            );
            if name.starts_with("g6lc64") {
                assert!(out.mbox_c.contains("miscdevice"), "{}", out.mbox_c);
                assert!(out.mbox_c.contains("g6lc-bios"), "{}", out.mbox_c);
                assert!(out.mbox_c.contains("file_operations"), "{}", out.mbox_c);
                assert!(out.mbox_c.contains("g6lc_bios_irq"), "{}", out.mbox_c);
                assert!(out.mbox_c.contains("platform_driver"), "{}", out.mbox_c);
                assert!(!out.mbox_c.contains("alloc_netdev"));
                assert!(!out.mbox_c.contains("register_netdev"));
                assert!(
                    out.loopback_zc.contains("LOOPBACK-MBOX"),
                    "{}",
                    out.loopback_zc
                );
                assert!(out.postboot_zc.contains("SshHolyc"), "{}", out.postboot_zc);
                assert!(out.kmain_zc.contains("SysGrInit"), "{}", out.kmain_zc);
                assert!(out.config_zc.contains("G6LC_GR 1"), "{}", out.config_zc);
                assert!(out.config_zc.contains("G6LC_GR_W 640"), "{}", out.config_zc);
                assert!(out.config_zc.contains("G6LC_PROXY 1"), "{}", out.config_zc);
                assert!(
                    out.browser_zc.contains("BROWSER-READY"),
                    "{}",
                    out.browser_zc
                );
                assert!(out.tls_zc.contains("TLS-HELLO"), "{}", out.tls_zc);
                assert!(out.gl_glsl.contains("GL-ADAPTER"), "{}", out.gl_glsl);
                assert!(out.config_zc.contains("G6LC_WASM 1"), "{}", out.config_zc);
                assert!(
                    out.config_zc.contains("G6LC_UI_BLOB 1"),
                    "{}",
                    out.config_zc
                );
                assert!(
                    out.config_zc.contains("G6LC_UI_MAGIC 0x49553647"),
                    "{}",
                    out.config_zc
                );
                assert!(
                    out.config_zc.contains("G6LC_FILE_SERVE 1"),
                    "{}",
                    out.config_zc
                );
                assert!(out.svelte_zc.contains("SVELTE-LIVE"), "{}", out.svelte_zc);
                assert!(out.wasm_jit_s.contains("wasm-jit"), "{}", out.wasm_jit_s);
                assert!(out.crypto_s.contains("rsa_limb_mul"), "{}", out.crypto_s);
                assert!(out.tls_zc.contains("RsaVerify"), "{}", out.tls_zc);
                assert!(
                    out.endpoints_zc.contains("RegisterEndpoint"),
                    "{}",
                    out.endpoints_zc
                );
                assert!(out.config_zc.contains("G6LC_HTTP"), "{}", out.config_zc);
                assert!(
                    out.config_zc.contains("G6LC_HTTP_GET 1"),
                    "{}",
                    out.config_zc
                );
                assert!(out.config_zc.contains("G6LC_FLASH 1"), "{}", out.config_zc);
                assert!(
                    out.config_zc.contains("G6LC_THREADS 2"),
                    "{}",
                    out.config_zc
                );
                assert!(out.config_zc.contains("G6LC_ISSUE 2"), "{}", out.config_zc);
                assert!(
                    out.config_zc.contains("G6LC_HTTP_FILES 1"),
                    "{}",
                    out.config_zc
                );
                assert!(out.https_zc.contains("HttpsServe"), "{}", out.https_zc);
                assert!(
                    out.endpoints_zc.contains("FileServe"),
                    "{}",
                    out.endpoints_zc
                );
                assert!(
                    out.config_zc.contains("G6LC_USB_KEY 1"),
                    "{}",
                    out.config_zc
                );
                assert!(
                    out.config_zc.contains("G6LC_FS_NTFS 1"),
                    "{}",
                    out.config_zc
                );
                assert!(
                    out.config_zc.contains("G6LC_FS_EXT4 1"),
                    "{}",
                    out.config_zc
                );
                assert!(out.endpoints_zc.contains("UsbKey"), "{}", out.endpoints_zc);
                assert!(
                    out.svelte_zc.contains("SVELTE-LIVE FileMgr"),
                    "{}",
                    out.svelte_zc
                );
                assert!(out.browser_zc.contains("USB-FILES"), "{}", out.browser_zc);
            }
            if name.contains("router") {
                assert!(
                    out.config_zc.contains("G6LC_FLASH_OPENWRT 1"),
                    "{}",
                    out.config_zc
                );
                assert!(
                    out.endpoints_zc.contains("FlashImage"),
                    "{}",
                    out.endpoints_zc
                );
                assert!(
                    out.config_zc.contains("G6LC_USB_KEY 0"),
                    "{}",
                    out.config_zc
                );
                assert!(!out.endpoints_zc.contains("UsbKey"), "{}", out.endpoints_zc);
            }
        }
    }

    #[test]
    fn kmain_mentions_holyc_ready() {
        let spec = BoardSpec::default();
        let out = compile(&spec);
        assert!(out.kmain_zc.contains("HOLYC-READY"));
        assert!(out.kmain_zc.contains("UI-BOOT"));
        assert!(out.kmain_zc.contains("G6LC-BIOS"));
    }

    #[test]
    fn server_fixture_hypervisor_rvv_uncore() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures");
        let s = std::fs::read_to_string(root.join("g6lc64-server.json")).unwrap();
        let spec = BoardSpec::from_json_str(&s).unwrap();
        let out = compile(&spec);
        assert!(
            out.config_zc.contains("G6LC_HYPERVISOR 1"),
            "{}",
            out.config_zc
        );
        assert!(out.config_zc.contains("G6LC_RVV 1"), "{}", out.config_zc);
        assert!(out.config_zc.contains("G6LC_STREAM 1"), "{}", out.config_zc);
        assert!(out.config_zc.contains("G6LC_OOO 1"), "{}", out.config_zc);
        assert!(out.config_zc.contains("G6LC_CORES 2"), "{}", out.config_zc);
        assert!(
            out.config_zc.contains("G6LC_UNCORE_PCIE 1"),
            "{}",
            out.config_zc
        );
        assert!(out.memcpy_s.contains("ISEL-RVV"), "{}", out.memcpy_s);
        assert!(out.holyc_ui_zc.contains("MENU cpu"), "{}", out.holyc_ui_zc);
        assert!(
            out.connectors_zc.contains("PciCfgRead"),
            "{}",
            out.connectors_zc
        );
    }

    #[test]
    fn rv64_rvv_live_mentions_vsetvli() {
        let spec = BoardSpec::from_json_str(
            r#"{"schema_version":1,"isa":{"xlen":64,"march":"rv64imafdcv","extensions":{"v":"live"}}}"#,
        )
        .unwrap();
        let out = compile(&spec);
        assert!(out.config_zc.contains("#define G6LC_RVV 1"));
        assert!(out.memcpy_s.contains("vsetvli"), "{}", out.memcpy_s);
        assert!(out.memcpy_s.contains("ISEL-RVV"), "{}", out.memcpy_s);
        assert!(!out.memcpy_s.to_ascii_lowercase().contains("rax"));
    }
}
